### PR TITLE
Highcharts path fix

### PR DESCRIPTION
**Pull request by azizpunjani**
[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1347)

### CODE REVIEW

**Comment by notmessenger** [comment]
@azizpunjani Please commit this against the `master` branch, as per https://github.com/softlayer/sl-ember-components/issues/1340

**Comment by notmessenger** [comment]
We you able to determine what changed?  We are still referencing the same release version in the blueprint for installation yet the paths seemed to have shifted since https://github.com/softlayer/sl-ember-components/issues/1248 was merged, which was done because the library has begun using the `lib` path.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1347#-:-K6nLie_oWmJda_Zyd3x:977926697)*

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1347)*

**Comment by azizpunjani** [comment]
@notmessenger looking at their [repo](https://github.com/highcharts/highcharts-dist), I can't find any record of when they moved files to the `lib` directory. Looks like the files are now at the root and have been for the longest time.

**Pull request merged**
