### PR TITLE
Closes softlayer/sl-ember-components#1477

### PR DESCRIPTION
**Pull request by alxyuu**
[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1479)

### CODE REVIEW

**Comment by azizpunjani** [comment]
@alxyuu I believe we can do away with `highchartsOptions` being computed off `options`, `updateOptions()` can [directly observe](https://github.com/azizpunjani/sl-ember-components/commit/ce8857ef74f9dd7870c57dea2f7b7571b97e0b1f) `options`. Thoughts?

**Comment by alxyuu** [comment]
oh yeah that actually makes more sense. Should I be merging your changes into my branch? Haven't seen multiple user workflows in this project yet

**Comment by azizpunjani** [comment]
We don't have a concrete process, but yes, you could merge my changes into your branch. Also, There seems to be merge conflicts right now on your branch.

**Comment by notmessenger** [comment]
I have not had a chance to dig into this issue yet, but glancing at it haven't these modifications previously been in the code and were removed?

**Comment by alxyuu** [comment]
`highchartsOptions` was previous a computed property observing nothing, but was changed to a method in #1287. There was never an observer for `options`

**Comment by notmessenger** [comment]
@alxyuu Can you merge in the latest changes to make sure there won't be any merge conflicts?

**Comment by alxyuu** [comment]
I was able to merge v.11 with no problems earlier but I didn't push it because it looks like the conflicts disappeared. is there still a need to merge?

**Comment by notmessenger** [comment]
I don't know.  Several PRs have been merged in that touch the same files as this one and once a PR is created it isn't automatically rebuilt with the latest changes.  Just trying to avoid a problem that may or may not exist.

**Comment by notmessenger** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/unit/components/sl-chart-test.js, line 109 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1479#-KAgRruj5pCuSUySNeYw:-KAgRruj5pCuSUySNeYx:-2102121316) ([raw file](https://github.com/softlayer/sl-ember-components/blob/ed6cea7fcd4a186deb04061d73876be3e52c6086/tests/unit/components/sl-chart-test.js#L109)):*
Setting a `const` is not needed - can just pass in `{}`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1479)*

**Comment by azizpunjani** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1479)*

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1479)*

**Pull request merged**
