### PR TITLE
Create Unit test to assert mixin is mixed in #755

### PR DESCRIPTION
**Pull request by erangeles**
[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/896)

### CODE REVIEW

**Comment by azizpunjani** [comment]
<sup>**[tests/unit/components/sl-checkbox-test.js, line 39 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/896#-K-sNqaD9UBl6kwUZiXg)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/3948a31ca6d54c0007d58e704c07ceb7b2d5726c/tests/unit/components/sl-checkbox-test.js#L39)):</sup>
Change "name" to null. '"name" property is null by default'


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/896)

**Comment by azizpunjani** [comment]
<sup>**[tests/unit/components/sl-checkbox-test.js, line 33 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/896#-K-sO1k-TVD3C0UGq72I)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/3948a31ca6d54c0007d58e704c07ceb7b2d5726c/tests/unit/components/sl-checkbox-test.js#L33)):</sup>
Just to be consistent change to '"label" property is false by default'


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/896)

**Comment by azizpunjani** [comment]
<sup>**[tests/unit/components/sl-checkbox-test.js, line 33 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/896#-K-sO1k-TVD3C0UGq72I)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/3948a31ca6d54c0007d58e704c07ceb7b2d5726c/tests/unit/components/sl-checkbox-test.js#L33)):</sup>
Ignore above. Test needs to read '"label" property is null by default'


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/896)

**Comment by azizpunjani** [comment]
<sup>**[tests/unit/components/sl-checkbox-test.js, line 27 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/896#-K-sOIAxP1kTZGCZ0yF3)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/3948a31ca6d54c0007d58e704c07ceb7b2d5726c/tests/unit/components/sl-checkbox-test.js#L27)):</sup>
Test needs to read '"disabled" property is false by default'


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/896)

**Comment by azizpunjani** [comment]
<sup>**[tests/unit/components/sl-checkbox-test.js, line 21 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/896#-K-sOQDadarPf65C_X-I)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/3948a31ca6d54c0007d58e704c07ceb7b2d5726c/tests/unit/components/sl-checkbox-test.js#L21)):</sup>
For consistency, add "is false by default"


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/896)

**Comment by erangeles** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

<sup>**[tests/unit/components/sl-checkbox-test.js, line 21 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/896#-K-sOQDadarPf65C_X-I)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/3948a31ca6d54c0007d58e704c07ceb7b2d5726c/tests/unit/components/sl-checkbox-test.js#L21)):</sup>
Done.


---

<sup>**[tests/unit/components/sl-checkbox-test.js, line 27 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/896#-K-sOIAxP1kTZGCZ0yF3)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/3948a31ca6d54c0007d58e704c07ceb7b2d5726c/tests/unit/components/sl-checkbox-test.js#L27)):</sup>
Done.


---

<sup>**[tests/unit/components/sl-checkbox-test.js, line 33 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/896#-K-sO1k-TVD3C0UGq72I)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/3948a31ca6d54c0007d58e704c07ceb7b2d5726c/tests/unit/components/sl-checkbox-test.js#L33)):</sup>
Done.


---

<sup>**[tests/unit/components/sl-checkbox-test.js, line 39 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/896#-K-sNqaD9UBl6kwUZiXg)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/3948a31ca6d54c0007d58e704c07ceb7b2d5726c/tests/unit/components/sl-checkbox-test.js#L39)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/896)

**Comment by erangeles** [comment]
@azizpunjani ready to be reviewed again.


---

Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/896)

**Comment by azizpunjani** [comment]
Reviewed, looks good now.


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/896)

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/896)

**Pull request merged**
