### PR TITLE
The integration test may not be following the pattern of all the others #1145

### PR DESCRIPTION
**Pull request by erangeles**
[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1160)

### CODE REVIEW

**Comment by juwara0** [comment]
I am reviewing this


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1160)

**Comment by juwara0** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

<sup>**[tests/integration/components/sl-span-test.js, line 14 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1160#-K2wBPZ_CL-G_sAA0425)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/b9570299e2d65f32856dff2efe054fa9ffa448d6/tests/integration/components/sl-span-test.js#L14)):</sup>
We do not need to include this since we have decided to only test positive assertions.


---

<sup>**[tests/integration/components/sl-span-test.js, line 20 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1160#-K2wBQWnwED33pDK0TOT)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/b9570299e2d65f32856dff2efe054fa9ffa448d6/tests/integration/components/sl-span-test.js#L20)):</sup>
We do not need to include this since we have decided to only test positive assertions.


---

<sup>**[tests/integration/components/sl-span-test.js, line 26 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1160#-K2wBRKsrwfCk05-QWs4)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/b9570299e2d65f32856dff2efe054fa9ffa448d6/tests/integration/components/sl-span-test.js#L26)):</sup>
We do not need to include this since we have decided to only test positive assertions.


---

<sup>**[tests/integration/components/sl-span-test.js, line 34 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1160#-K2wFwCtjM-SpIpDZHnP)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/b9570299e2d65f32856dff2efe054fa9ffa448d6/tests/integration/components/sl-span-test.js#L34)):</sup>
Lets change this message to: '"value" defaults to null'


---

<sup>**[tests/integration/components/sl-span-test.js, line 40 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1160#-K2wGCuB9VfE3hrOeQnz)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/b9570299e2d65f32856dff2efe054fa9ffa448d6/tests/integration/components/sl-span-test.js#L40)):</sup>
Lets change this message to: '"tagName" property defaults to "span"'

Notice that the word "property" is misspelled above.


---

<sup>**[tests/integration/components/sl-span-test.js, line 51 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1160#-K2wBdiYwv3NQLN-c5qq)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/b9570299e2d65f32856dff2efe054fa9ffa448d6/tests/integration/components/sl-span-test.js#L51)):</sup>
Lets update this to a more descriptive message. Maybe, '"value' text is displayed'


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1160)

**Comment by erangeles** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

<sup>**[tests/integration/components/sl-span-test.js, line 14 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1160#-K2wBPZ_CL-G_sAA0425)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/b9570299e2d65f32856dff2efe054fa9ffa448d6/tests/integration/components/sl-span-test.js#L14)):</sup>
Done.


---

<sup>**[tests/integration/components/sl-span-test.js, line 20 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1160#-K2wBQWnwED33pDK0TOT)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/b9570299e2d65f32856dff2efe054fa9ffa448d6/tests/integration/components/sl-span-test.js#L20)):</sup>
Done.


---

<sup>**[tests/integration/components/sl-span-test.js, line 26 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1160#-K2wBRKsrwfCk05-QWs4)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/b9570299e2d65f32856dff2efe054fa9ffa448d6/tests/integration/components/sl-span-test.js#L26)):</sup>
Done.


---

<sup>**[tests/integration/components/sl-span-test.js, line 34 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1160#-K2wFwCtjM-SpIpDZHnP)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/b9570299e2d65f32856dff2efe054fa9ffa448d6/tests/integration/components/sl-span-test.js#L34)):</sup>
Done.


---

<sup>**[tests/integration/components/sl-span-test.js, line 40 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1160#-K2wGCuB9VfE3hrOeQnz)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/b9570299e2d65f32856dff2efe054fa9ffa448d6/tests/integration/components/sl-span-test.js#L40)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1160)

**Comment by erangeles** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

<sup>**[tests/integration/components/sl-span-test.js, line 51 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1160#-K2wBdiYwv3NQLN-c5qq)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/b9570299e2d65f32856dff2efe054fa9ffa448d6/tests/integration/components/sl-span-test.js#L51)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1160)

**Comment by juwara0** [comment]
@notmessenger: this is ready to merge


---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1160)

**Comment by notmessenger** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[tests/integration/components/sl-span-test.js, line 19 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1160#-K2xVK6YNKSnX7mTnNvT)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/b4ed8acf510c7b1b12688b13634f7829091001d6/tests/integration/components/sl-span-test.js#L19)):</sup>
This should be in the unit test case


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1160)

**Comment by erangeles** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[tests/integration/components/sl-span-test.js, line 19 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1160#-K2xVK6YNKSnX7mTnNvT)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/b4ed8acf510c7b1b12688b13634f7829091001d6/tests/integration/components/sl-span-test.js#L19)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1160)

**Comment by juwara0** [comment]
@notmessenger: work on this is completed.


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1160)

**Comment by juwara0** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1160)

**Comment by notmessenger** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1160)_

**Pull request merged**
