### PR TITLE
Responsive paging

### PR DESCRIPTION
**Pull request by SpikedKira**
depends on #1339

[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1364)

### CODE REVIEW

**Comment by azizpunjani** [comment]
I'm a little concerned about the UX on this pagination. Please see this video if user is clicking through the pagination quickly http://recordit.co/NB5SKqnXEc

**Comment by azizpunjani** [comment]
Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[addon/components/sl-pagination.js, line 75 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364#-K7WOXfqessOuriEKmK_:-K7WOXfqessOuriEKmKa:-1541387355) ([raw file](https://github.com/softlayer/sl-ember-components/blob/6a8a76c0a00b340e7c89e299070f3941032f4be9/addon/components/sl-pagination.js#L75)):*
Should we be using the concise method syntax to be consistent with the rest of the functions in the file, i.e `didInsertElement() {.....}`

---

*[addon/components/sl-pagination.js, line 160 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364#-K7WPE8vqGSk0tQ-ifmA:-K7WPE8vqGSk0tQ-ifmB:-31168883) ([raw file](https://github.com/softlayer/sl-ember-components/blob/6a8a76c0a00b340e7c89e299070f3941032f4be9/addon/components/sl-pagination.js#L160)):*
We can probably improve this code by finding the current active page, deactivating it and activating the next page.

```
const pages = this.get( 'range' );
const currentPage = this.get( 'currentPage' );

const previousPage = pages.find( ( page ) => page.active );

Ember.set( previousPage, 'active', false );
Ember.set( pages[ currentPage - 1 ], 'active', true );
```

---

*[addon/components/sl-pagination.js, line 175 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364#-K7WOkDoe7KNaYcout1q:-K7WOkDoe7KNaYcout1r:2122061318) ([raw file](https://github.com/softlayer/sl-ember-components/blob/6a8a76c0a00b340e7c89e299070f3941032f4be9/addon/components/sl-pagination.js#L175)):*
Do we really need this queued in the `afterRender`, seems like it should work without this code.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364)*

**Comment by azizpunjani** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364)*

**Comment by notmessenger** [comment]
I agree with @azizpunjani though also realize that while we might be able to address it via fixed-width for 2-digit displays do we even want to try and address 3+ digit?

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364#-:-K7X1tr59nU5XdHCCHNT:-1740279548)*

**Comment by SpikedKira** [comment]
Open to logical suggestions.  I was aware of this already.  The same thing would happen if a similar list was centered horizontally and updated on page load (static html). 

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[addon/components/sl-pagination.js, line 75 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364#-K7WOXfqessOuriEKmK_:-K7XCHCsg2hov1h25KbL:958386306) ([raw file](https://github.com/softlayer/sl-ember-components/blob/6a8a76c0a00b340e7c89e299070f3941032f4be9/addon/components/sl-pagination.js#L75)):*
Not sure what is being said here.  Please elaborate.

---

*[addon/components/sl-pagination.js, line 175 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364#-K7WOkDoe7KNaYcout1q:-K7XCCJJ_5Ur4Nq1QnBX:-1699214119) ([raw file](https://github.com/softlayer/sl-ember-components/blob/6a8a76c0a00b340e7c89e299070f3941032f4be9/addon/components/sl-pagination.js#L175)):*
The idea is to keep the active one centered.  Since the active changed, yes, this is needed.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364#-:-K7XCJpc9xfNPCz6jaBz:-1402193106)*

**Comment by notmessenger** [comment]
Build is failing (for a few reasons)

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364#-:-K7Xfj3Bzlyc4GXm234n:-1852693211)*

**Comment by azizpunjani** [comment]
*[addon/components/sl-pagination.js, line 75 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364#-K7WOXfqessOuriEKmK_:-K7XhaqKSEpVVa2AXStz:-896762280) ([raw file](https://github.com/softlayer/sl-ember-components/blob/6a8a76c0a00b340e7c89e299070f3941032f4be9/addon/components/sl-pagination.js#L75)):*
Basically should we do 

```
didInsertElement(){ ... }
```
Instead of 
```
didInsertElement: function() {...}
```

To be consistent with other functions in this file.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364)*

**Comment by azizpunjani** [comment]
*[addon/components/sl-pagination.js, line 175 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364#-K7WOkDoe7KNaYcout1q:-K7l8GiqQTvimrMVqNe-:-1234480132) ([raw file](https://github.com/softlayer/sl-ember-components/blob/6a8a76c0a00b340e7c89e299070f3941032f4be9/addon/components/sl-pagination.js#L175)):*
Please try without the `scheduleOnce` it seems to be working on my end. Trying to prevent extra code we may not need.

```
    updateResponsivePlugin: Ember.observer(
        'currentPage',
        function() {
            this.$().twbsResponsivePagination( 'update' );
        }
    )
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364)*

**Comment by azizpunjani** [comment]
*[index.js, line 76 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364#-K7lBdBLLTqb80rwpKCW:-K7lBdBLLTqb80rwpKCX:-953480106) ([raw file](https://github.com/softlayer/sl-ember-components/blob/6e5b3b3bf09197bff9a0c9d04e15ef22361880ac/index.js#L76)):*
Non minified version should be used here for debugging purposes. When a production build is done, all these files will get minified.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364)*

**Comment by SpikedKira** [comment]
Review status: 7 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[addon/components/sl-pagination.js, line 175 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364#-K7WOkDoe7KNaYcout1q:-K7lU7wDOYDDbH8kf9fv:1456149061) ([raw file](https://github.com/softlayer/sl-ember-components/blob/6a8a76c0a00b340e7c89e299070f3941032f4be9/addon/components/sl-pagination.js#L175)):*
Without the scheduleOnce it "works" in an unintended way.  This has now been double verified.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364)*

**Comment by azizpunjani** [comment]
Reviewed 2 of 2 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364)*

**Comment by notmessenger** [comment]
Failing test

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364#-:-K7v8uji7K69mkR4FeAI:-1269424941)*

**Comment by SpikedKira** [comment]
Not ready for merge!
Impending conflict... will update when ready.

---

Review status: 7 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364#-:-K7wr6SLcp1OmHCvin3g:1438460220)*

**Comment by SpikedKira** [comment]
Should now be ready :)

---

Review status: 3 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364#-:-K8KPKfCJDZlgUjXkdn_:1714609847)*

**Comment by notmessenger** [comment]
You also have to add the "jquery.fn.twbs-responsive-pagination" Bower package to the blueprint

---

Reviewed 1 of 9 files at r1, 1 of 2 files at r2, 1 of 2 files at r3, 2 of 2 files at r4, 3 of 4 files at r5.
Review status: 8 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[addon/components/sl-pagination.js, line 114 \[r5\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364#-K8_NACgWmkfOoTLjkZu:-K8_NACgWmkfOoTLjkZv:-1793643411) ([raw file](https://github.com/softlayer/sl-ember-components/blob/7da38454b98ac38ff8770ce9516c987cb6cc07a9/addon/components/sl-pagination.js#L114)):*
In the wrong section

---

*[addon/components/sl-pagination.js, line 127 \[r5\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364#-K8_NBbYAYQbEmfSTv3y:-K8_NBbYAYQbEmfSTv3z:-1793643411) ([raw file](https://github.com/softlayer/sl-ember-components/blob/7da38454b98ac38ff8770ce9516c987cb6cc07a9/addon/components/sl-pagination.js#L127)):*
In the wrong section

---

*[addon/components/sl-pagination.js, line 246 \[r5\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364#-K8_JZY_dH3wcsoIajML:-K8_JZYaQf4n3LcAAGoG:1594584935) ([raw file](https://github.com/softlayer/sl-ember-components/blob/7da38454b98ac38ff8770ce9516c987cb6cc07a9/addon/components/sl-pagination.js#L246)):*
@private ?

---

*[tests/integration/components/sl-pagination-test.js, line 187 \[r5\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364#-K8_JrhrJh9bpu3ThBkU:-K8_JrhrJh9bpu3ThBkV:1633348102) ([raw file](https://github.com/softlayer/sl-ember-components/blob/7da38454b98ac38ff8770ce9516c987cb6cc07a9/tests/integration/components/sl-pagination-test.js#L187)):*
Move this comment to the line above the `assert.ok()` call

---

*[tests/integration/components/sl-pagination-test.js, line 202 \[r5\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364#-K8_Jv3FlmKh15CC07Fm:-K8_Jv3G8rfcs8OyHaxQ:1633348102) ([raw file](https://github.com/softlayer/sl-ember-components/blob/7da38454b98ac38ff8770ce9516c987cb6cc07a9/tests/integration/components/sl-pagination-test.js#L202)):*
Move this comment to the line above the `assert.ok()` call

---

*[tests/unit/components/sl-pagination-test.js, line 40 \[r5\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364#-K8_KPFDPTWPZRjwCy76:-K8_KPFDPTWPZRjwCy77:952723441) ([raw file](https://github.com/softlayer/sl-ember-components/blob/7da38454b98ac38ff8770ce9516c987cb6cc07a9/tests/unit/components/sl-pagination-test.js#L40)):*
Why is the `render()` call needed?  https://github.com/softlayer/sl-ember-components/blob/7e6c655b485cdcfbd92014d80654a455a2acd675/tests/unit/components/sl-calendar-test.js#L71 and https://github.com/softlayer/sl-ember-components/blob/7e6c655b485cdcfbd92014d80654a455a2acd675/tests/unit/components/sl-grid-test.js#L181 are examples of sending actions without needing to render.

This question applies to every other addition of `this.render()` in this file as well.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364#-:-K8_MvOSmJ07bLH-42Fh:1939799396)*

**Comment by SpikedKira** [comment]
do you mean the README?

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364#-:-K8_ZlQxidCuxmwSCCrD:-1517920392)*

**Comment by notmessenger** [comment]
https://github.com/softlayer/sl-ember-components/blob/v0.11.0/blueprints/sl-ember-components/index.js#L3

---

Review status: 8 of 9 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364#-:-K8_drrhcQ8A0jdWeYpp:-613180906)*

**Comment by notmessenger** [comment]
But yes, an entry should also be added to README.md and to http://softlayer.github.io/sl-ember-components/#/browsers

---

Review status: 8 of 9 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364#-:-K8_e6uh6b4Iqu_B2NY6:-997548136)*

**Comment by notmessenger** [comment]
Per the conversation in Gitter, support the ability enabled/disabled the responsiveness feature.  I will update the issue as well.

---

Review status: 8 of 9 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364#-:-K8_ezRvH3XiOP_ykKfC:38185502)*

**Comment by notmessenger** [comment]
...or not.  There is not issue for this PR.  Follow the guidance of the conversation in Gitter.

---

Review status: 8 of 9 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364#-:-K8_fRYSLiRySlBVKBzE:265604211)*

**Comment by SpikedKira** [comment]
Review status: 5 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/unit/components/sl-pagination-test.js, line 40 \[r5\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364#-K8_KPFDPTWPZRjwCy76:-K8_fJ5OI8qGwrmdo8ds:130550894) ([raw file](https://github.com/softlayer/sl-ember-components/blob/7da38454b98ac38ff8770ce9516c987cb6cc07a9/tests/unit/components/sl-pagination-test.js#L40)):*
updateResponsivePlugin() was throwing undefined error on this.$() which is why the renders were there.  I have added a conditional guard to prevent it and removed the this.render()s.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364)*

**Comment by azizpunjani** [comment]
*[tests/unit/components/sl-pagination-test.js, line 40 \[r5\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364#-K8_KPFDPTWPZRjwCy76:-K8_n3ap1_C7HLEyNj6o:1452235074) ([raw file](https://github.com/softlayer/sl-ember-components/blob/7da38454b98ac38ff8770ce9516c987cb6cc07a9/tests/unit/components/sl-pagination-test.js#L40)):*
As much as possible, we should not pollute our component code to accommodate our tests. The better way to test this action is to mock the `updateResponsivePlugin` function i.e 

```    
const component = this.subject({
        totalPages: 2,
        updateResponsivePlugin: function(){ }
 });
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364)*

**Comment by SpikedKira** [comment]
Review status: 4 of 10 files reviewed at latest revision, 8 unresolved discussions.

---

*[addon/components/sl-pagination.js, line 160 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364#-K7WPE8vqGSk0tQ-ifmA:-K98w0VsXcbiY7gxs09w:-499146009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/6a8a76c0a00b340e7c89e299070f3941032f4be9/addon/components/sl-pagination.js#L160)):*
Done.

---

*[addon/components/sl-pagination.js, line 114 \[r5\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364#-K8_NACgWmkfOoTLjkZu:-K98wV9sWSbnM-9Oyzvz:-499146009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/7da38454b98ac38ff8770ce9516c987cb6cc07a9/addon/components/sl-pagination.js#L114)):*
Done.

---

*[addon/components/sl-pagination.js, line 127 \[r5\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364#-K8_NBbYAYQbEmfSTv3y:-K98wVTmF9EvEnWnHHzQ:-1399559660) ([raw file](https://github.com/softlayer/sl-ember-components/blob/7da38454b98ac38ff8770ce9516c987cb6cc07a9/addon/components/sl-pagination.js#L127)):*
Done. I think this was a double?

---

*[addon/components/sl-pagination.js, line 246 \[r5\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364#-K8_JZY_dH3wcsoIajML:-K98w-_V0E8qdeqbRdFW:-499146009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/7da38454b98ac38ff8770ce9516c987cb6cc07a9/addon/components/sl-pagination.js#L246)):*
Done.

---

*[index.js, line 76 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364#-K7lBdBLLTqb80rwpKCW:-K98vzeZZfqAFdBJVXX4:-499146009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/6e5b3b3bf09197bff9a0c9d04e15ef22361880ac/index.js#L76)):*
Done.

---

*[tests/integration/components/sl-pagination-test.js, line 187 \[r5\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364#-K8_JrhrJh9bpu3ThBkU:-K98vU-iDuQHn5k3vt6U:-499146009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/7da38454b98ac38ff8770ce9516c987cb6cc07a9/tests/integration/components/sl-pagination-test.js#L187)):*
Done.

---

*[tests/integration/components/sl-pagination-test.js, line 202 \[r5\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364#-K8_Jv3FlmKh15CC07Fm:-K98vSLHkrJGi9ptpj7a:-499146009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/7da38454b98ac38ff8770ce9516c987cb6cc07a9/tests/integration/components/sl-pagination-test.js#L202)):*
Done.

---

*[tests/unit/components/sl-pagination-test.js, line 40 \[r5\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364#-K8_KPFDPTWPZRjwCy76:-K98vtcfACjScq8XEMl5:-499146009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/7da38454b98ac38ff8770ce9516c987cb6cc07a9/tests/unit/components/sl-pagination-test.js#L40)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364)*

**Comment by notmessenger** [comment]
Reviewed 2 of 5 files at r6, 4 of 4 files at r7.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[tests/dummy/app/templates/demos/sl-pagination.hbs, line 41 \[r7\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364#-K99QIxjzcI_B-_WUDyn:-K99QIxjzcI_B-_WUDyo:121124246) ([raw file](https://github.com/softlayer/sl-ember-components/blob/a39a52661e0273926d6f68d42f6f1bfd7f813302/tests/dummy/app/templates/demos/sl-pagination.hbs#L41)):*
Make the "responsive jQuery plugin" text a link to https://github.com/SpikedKira/jQuery.fn.twbsResponsivePagination

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364)*

**Comment by SpikedKira** [comment]
Review status: 9 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[tests/dummy/app/templates/demos/sl-pagination.hbs, line 41 \[r7\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364#-K99QIxjzcI_B-_WUDyn:-K9DHQg4I10ve3n1iPMR:-499146009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/a39a52661e0273926d6f68d42f6f1bfd7f813302/tests/dummy/app/templates/demos/sl-pagination.hbs#L41)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364)*

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1364)*

**Pull request merged**
