### PR TITLE
Closes softlayer/sl-ember-components#1418

### PR DESCRIPTION
**Pull request by SpikedKira**
[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1425)

### CODE REVIEW

**Comment by notmessenger** [comment]
So I had just had a thought :-/  We need to leverage Font Awesome because we do in the other repos (such as http://softlayer.github.io/sl-ember-translate/) and should remain consistent across them.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1425#-:-K8Lasf8dtoanet_6Yb7:-607044069)*

**Comment by azizpunjani** [comment]
*[tests/dummy/app/index.html, line 17 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1425#-K8Qod1PNTtjRRnoAdGW:-K8Qod1PNTtjRRnoAdGX:1340563176) ([raw file](https://github.com/softlayer/sl-ember-components/blob/6fc07d901579450ae2662e4cd942c9f3ad383a41/tests/dummy/app/index.html#L17)):*
Why are we not using bower to install font-awesome instead of linking to it directly? We do so for all our other dependencies.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1425)*

**Comment by SpikedKira** [comment]
*[tests/dummy/app/index.html, line 17 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1425#-K8Qod1PNTtjRRnoAdGW:-K8QrTFviDNpSWGX_pDA:269839669) ([raw file](https://github.com/softlayer/sl-ember-components/blob/6fc07d901579450ae2662e4cd942c9f3ad383a41/tests/dummy/app/index.html#L17)):*
Because it's not a dependency of the library?  It's merely a dependency of the dummy app inside of it, whose sole purpose is documentation.  Also, this is consistent with our other libraries (sl-ember-behavior).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1425)*

**Comment by azizpunjani** [comment]
*[tests/dummy/app/index.html, line 17 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1425#-K8Qod1PNTtjRRnoAdGW:-K8Uxic8-MrseChcSjoh:662667044) ([raw file](https://github.com/softlayer/sl-ember-components/blob/6fc07d901579450ae2662e4cd942c9f3ad383a41/tests/dummy/app/index.html#L17)):*
Gotcha, makes sense.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1425)*

**Comment by azizpunjani** [comment]
Reviewed 1 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1425)*

**Comment by notmessenger** [comment]
Reviewed 1 of 4 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1425)*

**Pull request merged**
