### PR TITLE
Closes softlayer/sl-ember-components#864

### PR DESCRIPTION
**Pull request by SpikedKira**
[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1280)

### CODE REVIEW

**Comment by azizpunjani** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[addon/components/sl-grid-column-header.js, line 61 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1280#-K5aKIoOm538Bxws8HnT:-K5aKIoOm538Bxws8HnU:-236945822) ([raw file](https://github.com/softlayer/sl-ember-components/blob/9ae70730008e2c194f2c6c6fb63e4bea3f786391/addon/components/sl-grid-column-header.js#L61)):*
All these properties need doc blocks.

---

*[addon/components/sl-grid-column-header.js, line 61 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1280#-K5aQD6JhLVhgAeBWfto:-K5aQD6JhLVhgAeBWftp:346646305) ([raw file](https://github.com/softlayer/sl-ember-components/blob/9ae70730008e2c194f2c6c6fb63e4bea3f786391/addon/components/sl-grid-column-header.js#L61)):*
Ember provides a way for passing in class values via the component property `class` i.e {{sl-grid-column-header class="class1 class2"}}`. Do we still want to create our own `extraClass` property? Or use standard Ember provided functionality? Just something to think about, I can think of points for an against using the "Ember way".

---

*[tests/dummy/app/controllers/demos/sl-grid.js, line 17 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1280#-K5aMaIrkozyOayympgu:-K5aMaIrkozyOayympgv:-781290634) ([raw file](https://github.com/softlayer/sl-ember-components/blob/9ae70730008e2c194f2c6c6fb63e4bea3f786391/tests/dummy/app/controllers/demos/sl-grid.js#L17)):*
I feel these lines of code will get repeated within a consuming application multiple times i.e resetting the sorted columns and setting the sort direction on the column that was clicked on. 

We can probably abstract it out into a helper function or a mixin so that it doesn't need to be repeated for each grid component. Doesn't have to be part of this PR but can be an issue on its own.

---

*[tests/integration/components/sl-grid-column-header-test.js, line 21 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1280#-K5aTNyZn_g4DKA4uKgA:-K5aTNyZn_g4DKA4uKgB:-1837520846) ([raw file](https://github.com/softlayer/sl-ember-components/blob/9ae70730008e2c194f2c6c6fb63e4bea3f786391/tests/integration/components/sl-grid-column-header-test.js#L21)):*
I'd say we do away with these variables and set the value directly i.e

```
this.set( 'sortable', true );
this.set( 'sorted', null );
...

this.set( 'sorted', 'asc' );'

...
```

Unless we are using the variables for something other than the code above.

---

*[tests/integration/components/sl-grid-column-header-test.js, line 68 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1280#-K5aUcaTwp6Hfn27F02a:-K5aUcaTwp6Hfn27F02b:-1539589642) ([raw file](https://github.com/softlayer/sl-ember-components/blob/9ae70730008e2c194f2c6c6fb63e4bea3f786391/tests/integration/components/sl-grid-column-header-test.js#L68)):*
I'd say we do away with this variable and set the class directly i.e 

```
this.set( 'extraClass', 'testClass' );
```

It's less code to scan, unless the variable serves another purpose.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1280)*

**Comment by azizpunjani** [comment]
Need to add `extraClass` and `sorted` to documentation and remove any old properties still present in the docs.

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1280#-:-K5aZvOq8FPm3F-6CHo4:-162798669)*

**Comment by SpikedKira** [comment]
*[tests/dummy/app/controllers/demos/sl-grid.js, line 17 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1280#-K5aMaIrkozyOayympgu:-K5fSPAkPN6kJpkyrTDZ:1864174149) ([raw file](https://github.com/softlayer/sl-ember-components/blob/9ae70730008e2c194f2c6c6fb63e4bea3f786391/tests/dummy/app/controllers/demos/sl-grid.js#L17)):*
https://github.com/softlayer/sl-ember-components/issues/1261

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1280)*

**Comment by azizpunjani** [comment]
Reviewed 4 of 5 files at r2, 2 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1280)*

**Comment by notmessenger** [comment]
Reviewed 4 of 9 files at r1, 4 of 5 files at r2, 2 of 3 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[addon/components/sl-grid-column-header.js, line 108 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1280#-K7HD0dxTptQmvMWwP7u:-K7HD0dxTptQmvMWwP7v:-1783370324) ([raw file](https://github.com/softlayer/sl-ember-components/blob/eb532ce98f01ff8897c94d227187f56365c8dab5/addon/components/sl-grid-column-header.js#L108)):*
Isn't the value of `sorted` `'null'` and not `null`?

The comparisons against `sorted` can be combined into `Ember.isNone()`

---

*[addon/components/sl-grid-column-header.js, line 111 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1280#-K7HDWBlxiQK_Eu4k96Y:-K7HDWBlxiQK_Eu4k96Z:-539855069) ([raw file](https://github.com/softlayer/sl-ember-components/blob/eb532ce98f01ff8897c94d227187f56365c8dab5/addon/components/sl-grid-column-header.js#L111)):*
A class of `column-` is applied to this component when the sort value is `'null'`?

---

*[addon/components/sl-grid.js, line 237 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1280#-K7HDmbQB4wPoHl-zcJR:-K7HDmbQB4wPoHl-zcJS:613277991) ([raw file](https://github.com/softlayer/sl-ember-components/blob/eb532ce98f01ff8897c94d227187f56365c8dab5/addon/components/sl-grid.js#L237)):*
This doesn't match up with the enum values.

---

*[tests/dummy/app/controllers/demos/sl-grid.js, line 23 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1280#-K7HRlcjyB5Mn4GbIulL:-K7HRlcjyB5Mn4GbIulM:564205473) ([raw file](https://github.com/softlayer/sl-ember-components/blob/eb532ce98f01ff8897c94d227187f56365c8dab5/tests/dummy/app/controllers/demos/sl-grid.js#L23)):*
Can this code be rewritten as

```
if ( 'asc' === currentDir ) {
    sortDir = 'desc';
}
```

---

*[tests/dummy/app/templates/demos/sl-grid.hbs, line 104 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1280#-K7HSHKVh5oee702Y4cD:-K7HSHKVh5oee702Y4cE:613277991) ([raw file](https://github.com/softlayer/sl-ember-components/blob/eb532ce98f01ff8897c94d227187f56365c8dab5/tests/dummy/app/templates/demos/sl-grid.hbs#L104)):*
This doesn't match up with the enum values.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1280)*

**Comment by SpikedKira** [comment]
Review status: 8 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[addon/components/sl-grid-column-header.js, line 111 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1280#-K7HDWBlxiQK_Eu4k96Y:-K7NMTS9ngQY3I9I8v1s:1374506179) ([raw file](https://github.com/softlayer/sl-ember-components/blob/eb532ce98f01ff8897c94d227187f56365c8dab5/addon/components/sl-grid-column-header.js#L111)):*
No, the condition keeps that from happening

---

*[addon/components/sl-grid.js, line 237 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1280#-K7HDmbQB4wPoHl-zcJR:-K7NMYDpgKyKW4VteX1f:-1293343204) ([raw file](https://github.com/softlayer/sl-ember-components/blob/eb532ce98f01ff8897c94d227187f56365c8dab5/addon/components/sl-grid.js#L237)):*
Fixed the enum from 'null' to null

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1280)*

**Comment by notmessenger** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1280)*

**Comment by notmessenger** [comment]
Reviewed 1 of 5 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1280)*

**Pull request merged**
