### PR TITLE
Create error architecture for sl-ember-components

### PR DESCRIPTION
**Pull request by juwara0**
Closes softlayer/sl-ember-components#1350

Created the error architecture for sl-ember-components and updated:
  sl-chart
  sl-date-time
  sl-menu
  sl-radio-group
  sl-tooltip 
to use the new error architecture.

[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1351)

### CODE REVIEW

**Comment by notmessenger** [comment]
Please merge latest changes from v0.11.0 branch so that tests can run.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1351#-:-K7H0sglyQa_d1cjd7iv:-1598593342)*

**Comment by notmessenger** [comment]
* Add a section to the README.md describing that this occurs and examples/description of how it can be leveraged in an application.
* Create an issue to only export `setErrorTypeThrown()` in test mode

---

Reviewed 5 of 7 files at r1.
Review status: 5 of 7 files reviewed at latest revision, 11 unresolved discussions.

---

*[addon/utils/error.js, line 45 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1351#-K7NCrW9anL-xxGHO71F:-K7NCrW9anL-xxGHO71G:-36537748) ([raw file](https://github.com/softlayer/sl-ember-components/blob/4605b8067a781580206f73c3bf69dabade46b167/addon/utils/error.js#L45)):*
I'm not sure we need `@function`.  Only needed it on `Ember.computed()` and the like so that it knew it's type but since this is assigned a function we might be okay?

---

*[addon/utils/error.js, line 55 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1351#-K7ND0KmFEjc11X_dohc:-K7ND0KmFEjc11X_dohd:-36537748) ([raw file](https://github.com/softlayer/sl-ember-components/blob/4605b8067a781580206f73c3bf69dabade46b167/addon/utils/error.js#L55)):*
I'm not sure we need `@function`.  Only needed it on `Ember.computed()` and the like so that it knew it's type but since this is assigned a function we might be okay?

---

*[addon/utils/error.js, line 66 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1351#-K7ND1VgE5SRRbhYIllh:-K7ND1VgE5SRRbhYIlli:-36537748) ([raw file](https://github.com/softlayer/sl-ember-components/blob/4605b8067a781580206f73c3bf69dabade46b167/addon/utils/error.js#L66)):*
I'm not sure we need `@function`.  Only needed it on `Ember.computed()` and the like so that it knew it's type but since this is assigned a function we might be okay?

---

*[addon/utils/error.js, line 77 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1351#-K7ND3za4yzHJQ6qXkpr:-K7ND3za4yzHJQ6qXkps:-36537748) ([raw file](https://github.com/softlayer/sl-ember-components/blob/4605b8067a781580206f73c3bf69dabade46b167/addon/utils/error.js#L77)):*
I'm not sure we need `@function`.  Only needed it on `Ember.computed()` and the like so that it knew it's type but since this is assigned a function we might be okay?

---

*[addon/utils/error.js, line 88 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1351#-K7NDPl0bpasfgYgO3Fi:-K7NDPl0bpasfgYgO3Fj:-501481568) ([raw file](https://github.com/softlayer/sl-ember-components/blob/4605b8067a781580206f73c3bf69dabade46b167/addon/utils/error.js#L88)):*
Remove extra empty line.

---

*[addon/utils/error.js, line 99 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1351#-K7ND5xpzkilNTySLZE1:-K7ND5xqe_X7Nce5_Jzu:-36537748) ([raw file](https://github.com/softlayer/sl-ember-components/blob/4605b8067a781580206f73c3bf69dabade46b167/addon/utils/error.js#L99)):*
I'm not sure we need `@function`.  Only needed it on `Ember.computed()` and the like so that it knew it's type but since this is assigned a function we might be okay?

---

*[addon/utils/error.js, line 117 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1351#-K7ND6dIBzyA-VdE-V7E:-K7ND6dJ_qIgkBQJMoz5:-36537748) ([raw file](https://github.com/softlayer/sl-ember-components/blob/4605b8067a781580206f73c3bf69dabade46b167/addon/utils/error.js#L117)):*
I'm not sure we need `@function`.  Only needed it on `Ember.computed()` and the like so that it knew it's type but since this is assigned a function we might be okay?

---

*[addon/utils/error.js, line 135 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1351#-K7ND7B-5jS__M2Vh_GQ:-K7ND7B-5jS__M2Vh_GR:-36537748) ([raw file](https://github.com/softlayer/sl-ember-components/blob/4605b8067a781580206f73c3bf69dabade46b167/addon/utils/error.js#L135)):*
I'm not sure we need `@function`.  Only needed it on `Ember.computed()` and the like so that it knew it's type but since this is assigned a function we might be okay?

---

*[addon/utils/error.js, line 153 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1351#-K7ND7tVhJnBRugKs3ey:-K7ND7tVhJnBRugKs3ez:-36537748) ([raw file](https://github.com/softlayer/sl-ember-components/blob/4605b8067a781580206f73c3bf69dabade46b167/addon/utils/error.js#L153)):*
I'm not sure we need `@function`.  Only needed it on `Ember.computed()` and the like so that it knew it's type but since this is assigned a function we might be okay?

---

*[addon/utils/error.js, line 171 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1351#-K7NDA2Ic3OZYlj34OwS:-K7NDA2Ic3OZYlj34OwT:-36537748) ([raw file](https://github.com/softlayer/sl-ember-components/blob/4605b8067a781580206f73c3bf69dabade46b167/addon/utils/error.js#L171)):*
I'm not sure we need `@function`.  Only needed it on `Ember.computed()` and the like so that it knew it's type but since this is assigned a function we might be okay?

---

*[addon/utils/error.js, line 173 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1351#-K7NDG0aHeX8wv7-hUwu:-K7NDG0aHeX8wv7-hUwv:2000297140) ([raw file](https://github.com/softlayer/sl-ember-components/blob/4605b8067a781580206f73c3bf69dabade46b167/addon/utils/error.js#L173)):*
This `@returns` doesn't match the other ones for similar functions.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1351#-:-K7NC1xZMCosyqXUduEP:1385020832)*

**Comment by notmessenger** [comment]
Reviewed 2 of 7 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1351)*

**Comment by juwara0** [comment]
https://github.com/softlayer/sl-ember-components/issues/1359 has been created to track the improvement of exporting setErrorTypeThrown() in test mode

---

Review status: 6 of 8 files reviewed at latest revision, 11 unresolved discussions.

---

*[addon/utils/error.js, line 45 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1351#-K7NCrW9anL-xxGHO71F:-K7NMnhEoGPZJ1R_GVUQ:-499146009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/4605b8067a781580206f73c3bf69dabade46b167/addon/utils/error.js#L45)):*
Done.

---

*[addon/utils/error.js, line 55 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1351#-K7ND0KmFEjc11X_dohc:-K7NMq9YbxNQFwXDch1y:-499146009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/4605b8067a781580206f73c3bf69dabade46b167/addon/utils/error.js#L55)):*
Done.

---

*[addon/utils/error.js, line 66 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1351#-K7ND1VgE5SRRbhYIllh:-K7NMr_VoHau4iQEJSpX:-499146009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/4605b8067a781580206f73c3bf69dabade46b167/addon/utils/error.js#L66)):*
Done.

---

*[addon/utils/error.js, line 77 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1351#-K7ND3za4yzHJQ6qXkpr:-K7NMtAPDdPJwdW_ORwD:-499146009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/4605b8067a781580206f73c3bf69dabade46b167/addon/utils/error.js#L77)):*
Done.

---

*[addon/utils/error.js, line 88 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1351#-K7NDPl0bpasfgYgO3Fi:-K7NJZaJ5KRfpiWsNXkZ:-499146009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/4605b8067a781580206f73c3bf69dabade46b167/addon/utils/error.js#L88)):*
Done.

---

*[addon/utils/error.js, line 99 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1351#-K7ND5xpzkilNTySLZE1:-K7NMvkwX3Reh-0IpMM1:-499146009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/4605b8067a781580206f73c3bf69dabade46b167/addon/utils/error.js#L99)):*
Done.

---

*[addon/utils/error.js, line 117 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1351#-K7ND6dIBzyA-VdE-V7E:-K7NMxNBPuFaDVQLIqAs:-499146009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/4605b8067a781580206f73c3bf69dabade46b167/addon/utils/error.js#L117)):*
Done.

---

*[addon/utils/error.js, line 135 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1351#-K7ND7B-5jS__M2Vh_GQ:-K7NMyd_RC6Yux6GlzCZ:-499146009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/4605b8067a781580206f73c3bf69dabade46b167/addon/utils/error.js#L135)):*
Done.

---

*[addon/utils/error.js, line 153 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1351#-K7ND7tVhJnBRugKs3ey:-K7NMzxvgVYk5UfpSPHo:-499146009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/4605b8067a781580206f73c3bf69dabade46b167/addon/utils/error.js#L153)):*
Done.

---

*[addon/utils/error.js, line 171 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1351#-K7NDA2Ic3OZYlj34OwS:-K7NN0JziFUq7GSac5jz:-499146009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/4605b8067a781580206f73c3bf69dabade46b167/addon/utils/error.js#L171)):*
Done.

---

*[addon/utils/error.js, line 173 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1351#-K7NDG0aHeX8wv7-hUwu:-K7NK3WswehJmQO1uAHm:-499146009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/4605b8067a781580206f73c3bf69dabade46b167/addon/utils/error.js#L173)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1351#-:-K7NNnhzY6gKXt-Z0Gq5:927036400)*

**Comment by notmessenger** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[README.md, line 155 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1351#-K7SS-p0vP8XmdJJmA1O:-K7SS-p0vP8XmdJJmA1P:-1278334730) ([raw file](https://github.com/softlayer/sl-ember-components/blob/f6c3658150e7d7bda3a6defe9111776f946cf98c/README.md#L155)):*
Need to add the necessary import statement(s) to this example.

---

*[README.md, line 161 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1351#-K7SS79gSOp7g5s-snSf:-K7SS79gSOp7g5s-snSg:1146242946) ([raw file](https://github.com/softlayer/sl-ember-components/blob/f6c3658150e7d7bda3a6defe9111776f946cf98c/README.md#L161)):*
Add space after `//`

---

*[README.md, line 162 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1351#-K7SS9NEaFK0CL1jMWUR:-K7SS9NFa_ABgPLxeUMa:1146242946) ([raw file](https://github.com/softlayer/sl-ember-components/blob/f6c3658150e7d7bda3a6defe9111776f946cf98c/README.md#L162)):*
Add space after `//`

---

*[README.md, line 166 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1351#-K7SS9qT4Or7EFqIOBqJ:-K7SS9qT4Or7EFqIOBqK:1146242946) ([raw file](https://github.com/softlayer/sl-ember-components/blob/f6c3658150e7d7bda3a6defe9111776f946cf98c/README.md#L166)):*
Add space after `//`

---

*[README.md, line 167 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1351#-K7SSADZ_Dwh7j6ds6c3:-K7SSADZ_Dwh7j6ds6c4:1146242946) ([raw file](https://github.com/softlayer/sl-ember-components/blob/f6c3658150e7d7bda3a6defe9111776f946cf98c/README.md#L167)):*
Add space after `//`

---

*[README.md, line 172 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1351#-K7SSH5y8f6wGg9yIdtz:-K7SSH5y8f6wGg9yIdu-:870841310) ([raw file](https://github.com/softlayer/sl-ember-components/blob/f6c3658150e7d7bda3a6defe9111776f946cf98c/README.md#L172)):*
Maybe direct them to *utils/error.js* file for list of exported ones can use?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1351)*

**Comment by juwara0** [comment]
Review status: 7 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

*[README.md, line 155 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1351#-K7SS-p0vP8XmdJJmA1O:-K7SUZW8mbtZ8kIBXjCk:-499146009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/f6c3658150e7d7bda3a6defe9111776f946cf98c/README.md#L155)):*
Done.

---

*[README.md, line 161 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1351#-K7SS79gSOp7g5s-snSf:-K7SUeCUnR27H5Lef4LR:-499146009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/f6c3658150e7d7bda3a6defe9111776f946cf98c/README.md#L161)):*
Done.

---

*[README.md, line 162 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1351#-K7SS9NEaFK0CL1jMWUR:-K7SUf971rKsptd3OyCC:-499146009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/f6c3658150e7d7bda3a6defe9111776f946cf98c/README.md#L162)):*
Done.

---

*[README.md, line 166 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1351#-K7SS9qT4Or7EFqIOBqJ:-K7SUgcaZ2Ox6qXK9Q40:-499146009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/f6c3658150e7d7bda3a6defe9111776f946cf98c/README.md#L166)):*
Done.

---

*[README.md, line 167 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1351#-K7SSADZ_Dwh7j6ds6c3:-K7SUhewmjKh8USjlSUk:-499146009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/f6c3658150e7d7bda3a6defe9111776f946cf98c/README.md#L167)):*
Done.

---

*[README.md, line 172 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1351#-K7SSH5y8f6wGg9yIdtz:-K7SVifUsD6lCUvbqAu0:-499146009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/f6c3658150e7d7bda3a6defe9111776f946cf98c/README.md#L172)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1351)*

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1351)*

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 82 \[r5\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1351#-K7Sp0ykFkAT5PXBQTm0:-K7Sp0ykFkAT5PXBQTm1:-960410719) ([raw file](https://github.com/softlayer/sl-ember-components/blob/37e21c5b5cf618e9cc2c7cd889ceda7490fd7299/README.md#L82)):*
* Remove "sl-ember-components"
* spelling of "comsuming"
* "applications" should be possessive

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1351)*

**Comment by juwara0** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 82 \[r5\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1351#-K7Sp0ykFkAT5PXBQTm0:-K7SpsZLDjAlHEhJwdnh:-499146009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/37e21c5b5cf618e9cc2c7cd889ceda7490fd7299/README.md#L82)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1351)*

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1351)*

**Pull request merged**
