### PR TITLE
Closes softlayer/sl-ember-components#869

### PR DESCRIPTION
**Pull request by SpikedKira**
fixed issue; which lead to a requirement for new testing patterns.

[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1069)

### CODE REVIEW

**Comment by notmessenger** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[addon/components/sl-date-range-picker.js, line 108 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1069#-K28hYwzu2w-xz09buS3)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/da193aef7a1180baeda1b7762f1a002f2c6df533/addon/components/sl-date-range-picker.js#L108)):</sup>
Missing `@param`


---

<sup>**[tests/unit/components/sl-date-range-picker-test.js, line 148 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1069#-K28i1yedYICVKftPvMj)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/da193aef7a1180baeda1b7762f1a002f2c6df533/tests/unit/components/sl-date-range-picker-test.js#L148)):</sup>
Shouldn't your advice from https://github.com/softlayer/sl-ember-components/issues/917 be followed?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1069)

**Comment by SpikedKira** [comment]
<sup>**[tests/unit/components/sl-date-range-picker-test.js, line 148 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1069#-K28i1yedYICVKftPvMj)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/da193aef7a1180baeda1b7762f1a002f2c6df533/tests/unit/components/sl-date-range-picker-test.js#L148)):</sup>
yes, yes it should -.-.  Friday was a bad day.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1069)

**Comment by notmessenger** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[addon/components/sl-date-range-picker.js, line 109 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1069#-K299rysYampJmJ5BfCU)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/607c1f97249a45374d6fe5ee7515c833496f7949/addon/components/sl-date-range-picker.js#L109)):</sup>
is this not a jQuery event?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1069)

**Comment by notmessenger** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1069)

**Comment by SpikedKira** [comment]
<sup>**[addon/components/sl-date-range-picker.js, line 109 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1069#-K299rysYampJmJ5BfCU)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/607c1f97249a45374d6fe5ee7515c833496f7949/addon/components/sl-date-range-picker.js#L109)):</sup>
It is, but you could use jquery to fire the event and pass in your own event that is simply a regular DOM event.  Would work the same.  The function does not require the extensions on the object provided by jQuery.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1069)

**Pull request merged**
