### PR TITLE
Added autoprefixer support

### PR DESCRIPTION
**Pull request by juwara0**
Closes: https://github.com/softlayer/sl-ember-components/issues/315

Added autoprefixer support into the build process.
Updated the README documentation with the details regarding autoprefixer and the need in a consuming app.

[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1483)

### CODE REVIEW

**Comment by notmessenger** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 242 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1483#-KAfofTEvABt_ROzTZFM:-KAfofTFzwIkDz4feRYB:-683439063) ([raw file](https://github.com/softlayer/sl-ember-components/blob/411acdca56e0e3b215ea214defaccbd37043aa25/README.md#L242)):*
Change sentence to:

Finally, you will need to run [broccoli-autoprefixer](https://github.com/sindresorhus/broccoli-autoprefixer) against the updated Twitter Bootstrap and/or LESS files.

---

*[README.md, line 244 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1483#-KAfoqpmJ_bezJ_5wc6k:-KAfoqpmJ_bezJ_5wc6l:1355492323) ([raw file](https://github.com/softlayer/sl-ember-components/blob/411acdca56e0e3b215ea214defaccbd37043aa25/README.md#L244)):*
Check the rest of the file.  Don't believe are using indentation as the pattern for code display, but instead ticks.  Confirm consistency. 

---

*[README.md, line 246 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1483#-KAfp1wRr_kHabnTs5_j:-KAfp1wRr_kHabnTs5_k:-1387380607) ([raw file](https://github.com/softlayer/sl-ember-components/blob/411acdca56e0e3b215ea214defaccbd37043aa25/README.md#L246)):*
* "browers" should be spelled "browsers" and be in back-ticks
* "ember-cli-build.js" should be in asterisks instead of back-ticks

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1483)*

**Comment by juwara0** [comment]
*[README.md, line 244 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1483#-KAfoqpmJ_bezJ_5wc6k:-KAft5ZS4O9rFVfa_eP4:-179093419) ([raw file](https://github.com/softlayer/sl-ember-components/blob/411acdca56e0e3b215ea214defaccbd37043aa25/README.md#L244)):*
I took a look through the file and for an inline what we are doing is back-ticks. For commands on a separate line we are using the indentation to create the code block box. I tried both out and feel like the code block box is more legible so decided to go that route. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1483)*

**Comment by juwara0** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 242 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1483#-KAfofTEvABt_ROzTZFM:-KAfrccOIV0erwvmJ0U0:-499146009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/411acdca56e0e3b215ea214defaccbd37043aa25/README.md#L242)):*
Done.

---

*[README.md, line 246 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1483#-KAfp1wRr_kHabnTs5_j:-KAft4v61N3LSzzQBWbv:-499146009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/411acdca56e0e3b215ea214defaccbd37043aa25/README.md#L246)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1483)*

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1483)*

**Pull request merged**
