### PR TITLE
Remove alias to _parentView._controller

### PR DESCRIPTION
**Pull request by erangeles**
initial commit, wanted to get your input on it @notmessenger . I reference this source http://discuss.emberjs.com/t/sub-component-action-not-bubbling-up/6739 for this fix.

### CODE REVIEW

**Comment by erangeles** [comment]
initial commit, wanted to get your input on it @notmessenger . I reference this source http://discuss.emberjs.com/t/sub-component-action-not-bubbling-up/6739 for this fix.

**Comment by notmessenger** [comment]
Would like your input on this @joshforisha

**Comment by joshforisha** [comment]
Part of the reason for the alias initially was so that the object the rowActions were run on could be customized. I suppose the same thing can be done by setting the targetAction on the component, but that will also affect other states of the grid unrelated to the rowActions.

If you don't think that changing the rowActions context is necessary, then this change would be fine.

**Comment by notmessenger** [comment]
Does yielded context give us a way forward on this @erangeles, as mentioned in the issue?

**Comment by erangeles** [comment]
@notmessenger yes it does.

**Comment by notmessenger** [comment]
I would prefer this approach then as it is more "standard" and less likely to change on us.  Your thoughts @joshforisha?

**Comment by joshforisha** [comment]
Sounds good.

**Comment by notmessenger** [comment]
See notes on issue

**Pull request closed without merging**
