### PR TITLE
 Create Unit test to assert properties observed by computed property #812

### PR DESCRIPTION
**Pull request by erangeles**
[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/884)

### CODE REVIEW

**Comment by juwara0** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/884)

**Comment by juwara0** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[tests/unit/components/sl-chart-test.js, line 357 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/884#-K-cYIWGZplRNUh0NWb7)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/3ccfe4de79805262c95f9137d8773191c1648352/tests/unit/components/sl-chart-test.js#L357)):</sup>
Please add an extra space at the end of the file


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/884)

**Comment by juwara0** [comment]
Reviewed 1 of 1 files at r2.
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[tests/unit/components/sl-chart-test.js, line 357 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/884#-K-cYIWGZplRNUh0NWb7)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/3ccfe4de79805262c95f9137d8773191c1648352/tests/unit/components/sl-chart-test.js#L357)):</sup>
RESOLVED


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/884)

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/884)

**Pull request merged**
