### PR TITLE
Create integration test suite and migrate appropriate tests from unit test suite #590

### PR DESCRIPTION
**Pull request by erangeles**
[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/961)

### CODE REVIEW

**Comment by erangeles** [comment]
@notmessenger adding more to this pr, please re-frame from reviewing it for now.

**Comment by erangeles** [comment]
@juwara0 can you please review this? thanks :)

**Comment by juwara0** [comment]
I have started reviewing this.


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/961)

**Comment by juwara0** [comment]
Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 26 unresolved discussions.

---

_[tests/integration/components/sl-input-test.js, line 25 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/961#-K3M0g5h0RoEcbunqmuO:-K3M0g5i7Hrjv2q5dgSZ:1191613963) ([raw file](https://github.com/softlayer/sl-ember-components/blob/2b5c0a97324d96aebe25a91d521c91927f26bb8e/tests/integration/components/sl-input-test.js#L25)):_
We do not need this assertion since we are not passing this property. For now, we are only concerned with positive assertions in the default test.

---

_[tests/integration/components/sl-input-test.js, line 31 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/961#-K3LcIKW3P22E7lCTvbv:-K3LcIKW3P22E7lCTvbw:1191613963) ([raw file](https://github.com/softlayer/sl-ember-components/blob/2b5c0a97324d96aebe25a91d521c91927f26bb8e/tests/integration/components/sl-input-test.js#L31)):_
We do not need this assertion since we are not passing this property. For now, we are only concerned with positive assertions in the default test.

---

_[tests/integration/components/sl-input-test.js, line 37 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/961#-K3LcH-h1U4eQ2eGReUK:-K3LcH-ixW36BlLnpy9r:1191613963) ([raw file](https://github.com/softlayer/sl-ember-components/blob/2b5c0a97324d96aebe25a91d521c91927f26bb8e/tests/integration/components/sl-input-test.js#L37)):_
We do not need this assertion since we are not passing this property. For now, we are only concerned with positive assertions in the default test.

---

_[tests/integration/components/sl-input-test.js, line 43 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/961#-K3M0u1VccWR__CPOWIC:-K3M0u1VccWR__CPOWID:1191613963) ([raw file](https://github.com/softlayer/sl-ember-components/blob/2b5c0a97324d96aebe25a91d521c91927f26bb8e/tests/integration/components/sl-input-test.js#L43)):_
We do not need this assertion since we are not passing this property. For now, we are only concerned with positive assertions in the default test.

---

_[tests/integration/components/sl-input-test.js, line 49 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/961#-K3LbZjVNpB3Mjtfxj_r:-K3LbZjVNpB3Mjtfxj_s:1191613963) ([raw file](https://github.com/softlayer/sl-ember-components/blob/2b5c0a97324d96aebe25a91d521c91927f26bb8e/tests/integration/components/sl-input-test.js#L49)):_
We do not need this assertion since we are not passing this property. For now, we are only concerned with positive assertions in the default test.

---

_[tests/integration/components/sl-input-test.js, line 64 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/961#-K3La57NMFzUp6-TSYrM:-K3La57NMFzUp6-TSYrN:2042072911) ([raw file](https://github.com/softlayer/sl-ember-components/blob/2b5c0a97324d96aebe25a91d521c91927f26bb8e/tests/integration/components/sl-input-test.js#L64)):_
We need to add an assert for the form-control class https://github.com/softlayer/sl-ember-components/blob/EmberCli-1.13.8/addon/templates/components/sl-input.hbs#L18 and https://github.com/softlayer/sl-ember-components/blob/EmberCli-1.13.8/addon/components/sl-input.js#L218

---

_[tests/integration/components/sl-input-test.js, line 102 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/961#-K3MDkyDkLZrnrvJYHlQ:-K3MDkyDkLZrnrvJYHlR:-1196640311) ([raw file](https://github.com/softlayer/sl-ember-components/blob/2b5c0a97324d96aebe25a91d521c91927f26bb8e/tests/integration/components/sl-input-test.js#L102)):_
We do not need to do this render or the assert below to check that text-info is not set. Just render the template with the property being set and verify that the class gets applied.

---

_[tests/integration/components/sl-input-test.js, line 115 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/961#-K3MI0Q8F8pX_Bn-miKb:-K3MI0Q8F8pX_Bn-miKc:-1628022789) ([raw file](https://github.com/softlayer/sl-ember-components/blob/2b5c0a97324d96aebe25a91d521c91927f26bb8e/tests/integration/components/sl-input-test.js#L115)):_
Please break this into two assertions one verifying that there is a class .text-info and the other one can be this one.

---

_[tests/integration/components/sl-input-test.js, line 124 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/961#-K3MEEFrbGEZaTCnEaGZ:-K3MEEFrbGEZaTCnEaG_:-1167868812) ([raw file](https://github.com/softlayer/sl-ember-components/blob/2b5c0a97324d96aebe25a91d521c91927f26bb8e/tests/integration/components/sl-input-test.js#L124)):_
We do not need to do this render or the assert below to check that text-danger is not set. Just render the template with the property being set and verify that the class gets applied.

---

_[tests/integration/components/sl-input-test.js, line 137 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/961#-K3MHwSgvF6mDWxbklY0:-K3MHwSgvF6mDWxbklY1:-1750466586) ([raw file](https://github.com/softlayer/sl-ember-components/blob/2b5c0a97324d96aebe25a91d521c91927f26bb8e/tests/integration/components/sl-input-test.js#L137)):_
Please break this into two assertions one verifying that there is a class .text-danger and the other one can be this one.

---

_[tests/integration/components/sl-input-test.js, line 180 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/961#-K3MFYD8vYRERhU88sIO:-K3MFYD8vYRERhU88sIP:-201954454) ([raw file](https://github.com/softlayer/sl-ember-components/blob/2b5c0a97324d96aebe25a91d521c91927f26bb8e/tests/integration/components/sl-input-test.js#L180)):_
We do not need to do this render or the assert below to check that help-block is not set. Just render the template with the property being set and verify that the class gets applied.

---

_[tests/integration/components/sl-input-test.js, line 193 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/961#-K3MHQuBtjE3vmTjs5ll:-K3MHQuBtjE3vmTjs5lm:-825338576) ([raw file](https://github.com/softlayer/sl-ember-components/blob/2b5c0a97324d96aebe25a91d521c91927f26bb8e/tests/integration/components/sl-input-test.js#L193)):_
Please break this into two assertions one verifying that there is a class .help-text and the other one can be this one.

---

_[tests/integration/components/sl-input-test.js, line 207 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/961#-K3MFiR-bveJ0jtbLV_i:-K3MFiR0XIh_8j2GaARG:-478917167) ([raw file](https://github.com/softlayer/sl-ember-components/blob/2b5c0a97324d96aebe25a91d521c91927f26bb8e/tests/integration/components/sl-input-test.js#L207)):_
Lets change this text to be more descriptive.   Maybe say 'Placeholder text is rendered'

---

_[tests/integration/components/sl-input-test.js, line 230 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/961#-K3MKqiJ0rAp6Rw2brQv:-K3MKqiJ0rAp6Rw2brQw:382506385) ([raw file](https://github.com/softlayer/sl-ember-components/blob/2b5c0a97324d96aebe25a91d521c91927f26bb8e/tests/integration/components/sl-input-test.js#L230)):_
We also need to have a test for suggestionNamePath: https://github.com/softlayer/sl-ember-components/blob/EmberCli-1.13.8/tests/dummy/app/templates/demos/sl-input.hbs#L214

---

_[tests/integration/components/sl-input-test.js, line 234 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/961#-K3MGlhX4vF3h03t1KWr:-K3MGlhX4vF3h03t1KWs:725059276) ([raw file](https://github.com/softlayer/sl-ember-components/blob/2b5c0a97324d96aebe25a91d521c91927f26bb8e/tests/integration/components/sl-input-test.js#L234)):_
Need to change this to: this.$( '>:first-child' ).find( '.twitter...

---

_[tests/integration/components/sl-input-test.js, line 239 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/961#-K3MH1jy1a-HwUZC3zsd:-K3MH1jy1a-HwUZC3zse:1849240285) ([raw file](https://github.com/softlayer/sl-ember-components/blob/2b5c0a97324d96aebe25a91d521c91927f26bb8e/tests/integration/components/sl-input-test.js#L239)):_
Need to change this to: this.$( '>:first-child' ).find( '

---

_[tests/integration/components/sl-input-test.js, line 244 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/961#-K3MH49QRFpv9RGLrLKv:-K3MH49QRFpv9RGLrLKw:1849240285) ([raw file](https://github.com/softlayer/sl-ember-components/blob/2b5c0a97324d96aebe25a91d521c91927f26bb8e/tests/integration/components/sl-input-test.js#L244)):_
Need to change this to: this.$( '>:first-child' ).find( '

---

_[tests/integration/components/sl-input-test.js, line 249 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/961#-K3MHGpVBUaTI69COlca:-K3MHGpVBUaTI69COlcb:1849240285) ([raw file](https://github.com/softlayer/sl-ember-components/blob/2b5c0a97324d96aebe25a91d521c91927f26bb8e/tests/integration/components/sl-input-test.js#L249)):_
Need to change this to: this.$( '>:first-child' ).find( '

---

_[tests/integration/components/sl-input-test.js, line 254 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/961#-K3MHIVwFUUrDmG9RXml:-K3MHIVwFUUrDmG9RXmm:1849240285) ([raw file](https://github.com/softlayer/sl-ember-components/blob/2b5c0a97324d96aebe25a91d521c91927f26bb8e/tests/integration/components/sl-input-test.js#L254)):_
Need to change this to: this.$( '>:first-child' ).find( '

---

_[tests/unit/components/sl-input-test.js, line 42 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/961#-K3MBZ5PcuoPzz0W0Sk8:-K3MBZ5PcuoPzz0W0Sk9:1943646536) ([raw file](https://github.com/softlayer/sl-ember-components/blob/2b5c0a97324d96aebe25a91d521c91927f26bb8e/tests/unit/components/sl-input-test.js#L42)):_
This change should be reverted.

---

_[tests/unit/components/sl-input-test.js, line 44 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/961#-K3MB_2jZ3nYFoAHHjgF:-K3MB_2kiTxChkSLCfpC:1943646536) ([raw file](https://github.com/softlayer/sl-ember-components/blob/2b5c0a97324d96aebe25a91d521c91927f26bb8e/tests/unit/components/sl-input-test.js#L44)):_
This change should be reverted.

---

_[tests/unit/components/sl-input-test.js, line 56 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/961#-K31Zx5dPyu-mIiPdBjS:-K31Zx5esrdi3dc8Rjyw:1943646536) ([raw file](https://github.com/softlayer/sl-ember-components/blob/2b5c0a97324d96aebe25a91d521c91927f26bb8e/tests/unit/components/sl-input-test.js#L56)):_
This change should be reverted.

---

_[tests/unit/components/sl-input-test.js, line 57 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/961#-K31_Hh6XEaOqDBmwGrZ:-K31_Hh6XEaOqDBmwGr_:201245606) ([raw file](https://github.com/softlayer/sl-ember-components/blob/2b5c0a97324d96aebe25a91d521c91927f26bb8e/tests/unit/components/sl-input-test.js#L57)):_
This change should be reverted

---

_[tests/unit/components/sl-input-test.js, line 188 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/961#-K31YdQRI7ajASQfhOV6:-K31YdQRI7ajASQfhOV7:313819831) ([raw file](https://github.com/softlayer/sl-ember-components/blob/2b5c0a97324d96aebe25a91d521c91927f26bb8e/tests/unit/components/sl-input-test.js#L188)):_
please removed the extra space... this.subject({

---

_[tests/unit/components/sl-input-test.js, line 192 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/961#-K3MLB1SWfGUIsriqMI8:-K3MLB1SWfGUIsriqMI9:1943646536) ([raw file](https://github.com/softlayer/sl-ember-components/blob/2b5c0a97324d96aebe25a91d521c91927f26bb8e/tests/unit/components/sl-input-test.js#L192)):_
This change should be reverted.

---

_[tests/unit/components/sl-input-test.js, line 195 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/961#-K3MLBzM3Kpxlq-saao7:-K3MLBzM3Kpxlq-saao8:1943646536) ([raw file](https://github.com/softlayer/sl-ember-components/blob/2b5c0a97324d96aebe25a91d521c91927f26bb8e/tests/unit/components/sl-input-test.js#L195)):_
This change should be reverted.

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/961)_

**Pull request closed without merging**
