### PR TITLE
Issue 974

### PR DESCRIPTION
**Pull request by SpikedKira**
[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1217)

### CODE REVIEW

**Comment by azizpunjani** [comment]
*[addon/components/sl-grid.js, line 745 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1217#-K4OzrwCvhJ6jNtequ9g:-K4OzrwCvhJ6jNtequ9h:-1956576888) ([raw file](https://github.com/softlayer/sl-ember-components/blob/6c5e42f6e41582f746c0202b3330fef921061603/addon/components/sl-grid.js#L745)):*
Should reference `Ember.$` instead of global`$`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1217)*

**Comment by azizpunjani** [comment]
*[addon/components/sl-grid.js, line 745 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1217#-K4OzrwCvhJ6jNtequ9g:-K4OzrwCvhJ6jNtequ9h:2027012044) ([raw file](https://github.com/softlayer/sl-ember-components/blob/6c5e42f6e41582f746c0202b3330fef921061603/addon/components/sl-grid.js#L745)):*
Should reference `Ember.$` instead of global`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1217)*

**Comment by SpikedKira** [comment]
*[addon/components/sl-grid.js, line 745 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1217#-K4OzrwCvhJ6jNtequ9g:-K4P1Sipb5FV5hXFFUPO:795446739) ([raw file](https://github.com/softlayer/sl-ember-components/blob/6c5e42f6e41582f746c0202b3330fef921061603/addon/components/sl-grid.js#L745)):*
thanks!

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1217)*

**Comment by notmessenger** [comment]
Merge conflicts

---

Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1217#-:-K4dPCfjzpQdehwxFy99:-385906380)*

**Comment by notmessenger** [comment]
Assertions for observed and computed properties were not modified/added for the grid and grid-cell component changes.

---

Reviewed 9 of 12 files at r1, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[addon/components/sl-grid-row.js, line 48 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1217#-K4hdLbBU5yLhxyyk33X:-K4hdLbBU5yLhxyyk33Y:1487233245) ([raw file](https://github.com/softlayer/sl-ember-components/blob/e79ccbafd4b8d1b042ad07f3dc38ef18f7c14311/addon/components/sl-grid-row.js#L48)):*
Needs DocBlock

---

*[addon/components/sl-grid.js, line 98 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1217#-K4hduPaBgfsHoLEY__f:-K4hduPaBgfsHoLEY__g:-692599106) ([raw file](https://github.com/softlayer/sl-ember-components/blob/e79ccbafd4b8d1b042ad07f3dc38ef18f7c14311/addon/components/sl-grid.js#L98)):*
Add empty line before this one.

---

*[addon/components/sl-grid.js, line 113 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1217#-K4hdlWg7wwDJc556axt:-K4hdlWg7wwDJc556axu:-692599106) ([raw file](https://github.com/softlayer/sl-ember-components/blob/e79ccbafd4b8d1b042ad07f3dc38ef18f7c14311/addon/components/sl-grid.js#L113)):*
Add empty line before this one.

---

*[addon/components/sl-grid.js, line 134 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1217#-K4heEZEYI6mkg2OoeRX:-K4heEZEYI6mkg2OoeRY:-2059787890) ([raw file](https://github.com/softlayer/sl-ember-components/blob/e79ccbafd4b8d1b042ad07f3dc38ef18f7c14311/addon/components/sl-grid.js#L134)):*
not "with a specific row object" any more?

---

*[app/styles/sl-grid.less, line 44 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1217#-K4hh-1mZTNVXM9-KKUJ:-K4hh-1mZTNVXM9-KKUK:637678919) ([raw file](https://github.com/softlayer/sl-ember-components/blob/e79ccbafd4b8d1b042ad07f3dc38ef18f7c14311/app/styles/sl-grid.less#L44)):*
Why not delete these?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1217#-:-K4hiWwRsiwSQATxR6gX:-380326546)*

**Comment by SpikedKira** [comment]
I found the missed observe/compute on grid, but not grid-cell.... did I still miss something there?

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[addon/components/sl-grid.js, line 134 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1217#-K4heEZEYI6mkg2OoeRX:-K4iHKh19N6DrAOQ3vo2:213497784) ([raw file](https://github.com/softlayer/sl-ember-components/blob/e79ccbafd4b8d1b042ad07f3dc38ef18f7c14311/addon/components/sl-grid.js#L134)):*
no, see selectRow()

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1217#-:-K4iMN_o7WUMnLUbbUj9:-1768264913)*

**Comment by notmessenger** [comment]
grid-cell: `style()`

---

Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1217#-:-K4wgjHwBQfQ2y_jHi8_:1816255876)*

**Comment by notmessenger** [comment]
Reviewed 7 of 7 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1217)*

**Pull request merged**
