### PR TITLE
Remove sl-loading-icon component offering (Title used to be: "Evaluate loading mask implementation, as compared to desired implementation in sl-panel") 

### PR DESCRIPTION
**Pull request by erangeles**
[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1369)

### CODE REVIEW

**Comment by azizpunjani** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1369)*

**Comment by erangeles** [comment]
this addresses  #1197

**Comment by erangeles** [comment]
@juwara0 this is ready. @azizpunjani reviewed it

**Comment by juwara0** [comment]
There is also mentions of `sl-loading-icon` still in: 
- tests/dummy/app/controllers/browsers.js
- tests/dummy/app/templates/index.hbs

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1369#-:-K8yh9sY-NHbrRBKl6gB:-1927269294)*

**Comment by juwara0** [comment]
Reviewed 11 of 11 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1369)*

**Comment by erangeles** [comment]
addressed @juwara0 comments.

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1369#-:-K8yni8apuJKFoQxFL2_:-1961696750)*

**Comment by juwara0** [comment]
@notmessenger - This looks ready to merge

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1369#-:-K8ypD1w-Sjxj2nXMGhq:1816636518)*

**Comment by notmessenger** [comment]
Reviewed 9 of 11 files at r1, 4 of 4 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1369)*

**Pull request merged**
