### PR TITLE
Fixed deprecation + sorting bug

### PR DESCRIPTION
**Pull request by azizpunjani**
Closes https://github.com/softlayer/sl-ember-components/issues/793

Connects to #793

### CODE REVIEW

**Comment by notmessenger** [comment]
Grid sorting is still experiencing issues, captured in https://github.com/softlayer/sl-ember-components/issues/856.  Feel free to either resolve them in this PR or push to the separate issue.

**Comment by azizpunjani** [comment]
@notmessenger sorting should work now. I had a few mistakes in my template string.

**Comment by notmessenger** [comment]
Test comment - can ignore

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/846)

**Comment by juwara0** [comment]
Testing threaded comments

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/846)

**Comment by notmessenger** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/846)

**Pull request merged**
