### PR TITLE
Sl grid tests

### PR DESCRIPTION
**Pull request by azizpunjani**
closes# https://github.com/softlayer/sl-ember-components/issues/1033
closes# https://github.com/softlayer/sl-ember-components/issues/588
closes# https://github.com/softlayer/sl-ember-components/issues/426

[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1164)

### CODE REVIEW

**Comment by azizpunjani** [comment]
<sup>**[tests/integration/components/sl-grid-test.js, line 326 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1164#-K30sTLuqYLYZ_Xe5sQC)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/46a26517c1ae53d6aafe65573c0e4c0dde878125/tests/integration/components/sl-grid-test.js#L326)):</sup>
Be consistent with template string spacing.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1164)

**Comment by notmessenger** [comment]
Merge conflicts

---

Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1164#-:-K3L8uJv2I5YKmAE9KX6:-385906380)_

**Comment by notmessenger** [comment]
Reviewed 7 of 11 files at r1, 2 of 2 files at r2.
Review status: 9 of 11 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

_[addon/components/sl-grid.js, line 566 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1164#-K3MOFE0sUizizVYTEtT:-K3MOFE0sUizizVYTEtU:-440341265) ([raw file](https://github.com/softlayer/sl-ember-components/blob/64771802074792da60f1d19e030c084ce073254e/addon/components/sl-grid.js#L566)):_
Number, not Integer

---

_[tests/integration/components/sl-grid-cell-test.js, line 4 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1164#-K3MOXKO_dwkSJKFn4jP:-K3MOXKO_dwkSJKFn4jQ:852332823) ([raw file](https://github.com/softlayer/sl-ember-components/blob/64771802074792da60f1d19e030c084ce073254e/tests/integration/components/sl-grid-cell-test.js#L4)):_
Make the first import in the file

---

_[tests/integration/components/sl-grid-test.js, line 49 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1164#-K3MPHud9U2KPz71BO2d:-K3MPHud9U2KPz71BO2e:1382749991) ([raw file](https://github.com/softlayer/sl-ember-components/blob/64771802074792da60f1d19e030c084ce073254e/tests/integration/components/sl-grid-test.js#L49)):_
Should be first test case in test suite to be consistent with other integration tests in the codebase

---

_[tests/unit/components/sl-grid-cell-test.js, line 47 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1164#-K3MQLIj9nbL5xQzr_72:-K3MQLIj9nbL5xQzr_73:326336003) ([raw file](https://github.com/softlayer/sl-ember-components/blob/64771802074792da60f1d19e030c084ce073254e/tests/unit/components/sl-grid-cell-test.js#L47)):_
Should be last test case in the test suite to be consistent with all other unit tests in the codebase

---

_[tests/unit/components/sl-grid-cell-test.js, line 233 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1164#-K3MQgGbpwb6XXt1uIHP:-K3MQgGbpwb6XXt1uIHQ:-813328332) ([raw file](https://github.com/softlayer/sl-ember-components/blob/64771802074792da60f1d19e030c084ce073254e/tests/unit/components/sl-grid-cell-test.js#L233)):_
These assertions should be part of the default values test case.  See https://github.com/softlayer/sl-ember-components/blob/EmberCli-1.13.8/tests/unit/components/sl-button-test.js for guidance

---

_[tests/unit/components/sl-grid-column-header-test.js, line 24 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1164#-K3MQndGJ8a7ld_yc2zV:-K3MQndGJ8a7ld_yc2zW:669984173) ([raw file](https://github.com/softlayer/sl-ember-components/blob/64771802074792da60f1d19e030c084ce073254e/tests/unit/components/sl-grid-column-header-test.js#L24)):_
This test case should be the last one in the test suite to be consistent with other unit tests in the codebase 

---

_[tests/unit/components/sl-grid-test.js, line 166 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1164#-K3MR2XM41Ad6AEqRslO:-K3MR2XM41Ad6AEqRslP:-1000467838) ([raw file](https://github.com/softlayer/sl-ember-components/blob/64771802074792da60f1d19e030c084ce073254e/tests/unit/components/sl-grid-test.js#L166)):_
This test case should be at the bottom of the test suite, but before the "Observer keys are correct" one,  to be consistent with other unit tests in the codebase

---

_[tests/unit/components/sl-grid-test.js, line 433 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1164#-K3MRJWIpDmMV_pyhq9b:-K3MRJWIpDmMV_pyhq9c:-137793380) ([raw file](https://github.com/softlayer/sl-ember-components/blob/64771802074792da60f1d19e030c084ce073254e/tests/unit/components/sl-grid-test.js#L433)):_
This should be set to the value we expect it to be - not a derived one.  More correctly/purely testing what we desire.

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1164)_

**Comment by azizpunjani** [comment]
Resolved issues outlined during code review.

---

Review status: 3 of 11 files reviewed at latest revision, all discussions resolved.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1164#-:-K3PqFbo8b7wr1uL8nXA:-1941425017)_

**Comment by notmessenger** [comment]
Reviewed 2 of 11 files at r1, 6 of 6 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1164)_

**Comment by notmessenger** [comment]
Failing test

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1164#-:-K3Pur3C1-CHYvgAIFPS:-1269424941)_

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1164)_

**Pull request merged**
