### PR TITLE
Create integration test suite and migrate appropriate tests from unit test suite

### PR DESCRIPTION
**Pull request by erangeles**
[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1050)

### CODE REVIEW

**Comment by notmessenger** [comment]
* There should be an integration test case for label support
* There should be an integration test case for size support
* There should be an integration test case for align support
* There should be an integration test case testing `icon` is set properly on `{{sl-drop-option}}`
* There should be an integration test case testing `label` is set properly on `{{sl-drop-option}}`
* There should be an integration test case for tooltip support (see `{{sl-button}}` test
* There should be a unit test assertion for `dataTrigger` property
* There should be a unit test assertion for `title` property
* There should be a unit test case for the `rightAligned()` logic
* There should be a unit test case for the `themeClass()` logic


---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

<sup>**[tests/integration/components/sl-drop-button-test.js, line 8 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K1ndS0UE9cTs064psx_)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/a22fabbd9f93f65de6becf8fcb0d5049b71b3189/tests/integration/components/sl-drop-button-test.js#L8)):</sup>
https://github.com/softlayer/ember-style-guide/blob/master/ember-testing.md#naming-component-integration-tests


---

<sup>**[tests/integration/components/sl-drop-button-test.js, line 27 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K1nnTBwrYy7OmecLyCq)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/a22fabbd9f93f65de6becf8fcb0d5049b71b3189/tests/integration/components/sl-drop-button-test.js#L27)):</sup>
Additional needed assertions:

* that `{{sl-button}}` was rendered with the expected class
* there is a `<ul>` with the expected classes and roles

The point of the "Default rendered state" test case is to render the component in its default state, only passing any required properties, and to verify it.


---

<sup>**[tests/integration/components/sl-drop-button-test.js, line 34 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K1ni53F4A3iRbm7M6rV)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/a22fabbd9f93f65de6becf8fcb0d5049b71b3189/tests/integration/components/sl-drop-button-test.js#L34)):</sup>
This assertion belongs in the "Default rendered state" test case


---

<sup>**[tests/integration/components/sl-drop-button-test.js, line 39 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K1niE9X6xXHjzigNy5N)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/a22fabbd9f93f65de6becf8fcb0d5049b71b3189/tests/integration/components/sl-drop-button-test.js#L39)):</sup>
Can remove this line


---

<sup>**[tests/integration/components/sl-drop-button-test.js, line 41 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K1niF87dFOvdFbKaPoA)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/a22fabbd9f93f65de6becf8fcb0d5049b71b3189/tests/integration/components/sl-drop-button-test.js#L41)):</sup>
Can hard-code the theme value.

Recommend setting it to something that is not part of the value coded into the component, such as "testValue", "__themeName__", etc.  This provides absolute certainty that things are working correctly and we didn't happen to stumble across a bug that gives a false positive.


---

<sup>**[tests/integration/components/sl-drop-button-test.js, line 78 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K1nyroSi4VCpmjAido3)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/a22fabbd9f93f65de6becf8fcb0d5049b71b3189/tests/integration/components/sl-drop-button-test.js#L78)):</sup>
I don't think this is testing what you think it is testing.  Look at the documentation for this component, and its template - there should be several more assertions around the logic as it can used in block form or given content via the `content` property which then has different permutations of rendering and functionality based on other properties as well.


---

<sup>**[tests/integration/components/sl-drop-button-test.js, line 97 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K1o-NVtzAOwAG44jnuo)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/a22fabbd9f93f65de6becf8fcb0d5049b71b3189/tests/integration/components/sl-drop-button-test.js#L97)):</sup>
Does this need to be here?


---

<sup>**[tests/integration/components/sl-drop-button-test.js, line 105 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K1o1WHwX0MYb4l9l5XT)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/a22fabbd9f93f65de6becf8fcb0d5049b71b3189/tests/integration/components/sl-drop-button-test.js#L105)):</sup>
Missing 3rd argument


---

<sup>**[tests/integration/components/sl-drop-button-test.js, line 108 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K1o-Ka6y1hY-0bwuaOr)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/a22fabbd9f93f65de6becf8fcb0d5049b71b3189/tests/integration/components/sl-drop-button-test.js#L108)):</sup>
Spacing before after double-quoted string


---

<sup>**[tests/unit/components/sl-drop-button-test.js, line 17 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K1o1FjJX1QC2jm2QiID)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/a22fabbd9f93f65de6becf8fcb0d5049b71b3189/tests/unit/components/sl-drop-button-test.js#L17)):</sup>
This test case should be merged with the "Default property values are set correctly" one.  See the `{{sl-button}}` tests for examples


---

<sup>**[tests/unit/components/sl-drop-button-test.js, line 26 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K1o1TnCFIjsz6SPzxSP)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/a22fabbd9f93f65de6becf8fcb0d5049b71b3189/tests/unit/components/sl-drop-button-test.js#L26)):</sup>
Missing 3rd argument


---

<sup>**[tests/unit/components/sl-drop-button-test.js, line 35 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K1o1vOkqHdmWhKwuoy_)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/a22fabbd9f93f65de6becf8fcb0d5049b71b3189/tests/unit/components/sl-drop-button-test.js#L35)):</sup>
spelling


---

<sup>**[tests/unit/components/sl-drop-button-test.js, line 69 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K1o3R--C-_3lfquUCNo)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/a22fabbd9f93f65de6becf8fcb0d5049b71b3189/tests/unit/components/sl-drop-button-test.js#L69)):</sup>
Remove this test case


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050)

**Comment by erangeles** [comment]
There should be an integration test case testing icon is set properly on {{sl-drop-option}} 
  - we don't offer that functionality, only can set an icon on sl-drop-button via iconClass not on sl-drop-option)


---

Review status: 0 of 2 files reviewed at latest revision, 12 unresolved discussions.

---

<sup>**[tests/integration/components/sl-drop-button-test.js, line 8 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K1ndS0UE9cTs064psx_)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/a22fabbd9f93f65de6becf8fcb0d5049b71b3189/tests/integration/components/sl-drop-button-test.js#L8)):</sup>
Done.


---

<sup>**[tests/integration/components/sl-drop-button-test.js, line 27 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K1nnTBwrYy7OmecLyCq)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/a22fabbd9f93f65de6becf8fcb0d5049b71b3189/tests/integration/components/sl-drop-button-test.js#L27)):</sup>
Done.


---

<sup>**[tests/integration/components/sl-drop-button-test.js, line 34 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K1ni53F4A3iRbm7M6rV)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/a22fabbd9f93f65de6becf8fcb0d5049b71b3189/tests/integration/components/sl-drop-button-test.js#L34)):</sup>
Done.


---

<sup>**[tests/integration/components/sl-drop-button-test.js, line 39 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K1niE9X6xXHjzigNy5N)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/a22fabbd9f93f65de6becf8fcb0d5049b71b3189/tests/integration/components/sl-drop-button-test.js#L39)):</sup>
Done.


---

<sup>**[tests/integration/components/sl-drop-button-test.js, line 41 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K1niF87dFOvdFbKaPoA)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/a22fabbd9f93f65de6becf8fcb0d5049b71b3189/tests/integration/components/sl-drop-button-test.js#L41)):</sup>
Done.


---

<sup>**[tests/integration/components/sl-drop-button-test.js, line 97 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K1o-NVtzAOwAG44jnuo)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/a22fabbd9f93f65de6becf8fcb0d5049b71b3189/tests/integration/components/sl-drop-button-test.js#L97)):</sup>
Done.


---

<sup>**[tests/integration/components/sl-drop-button-test.js, line 105 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K1o1WHwX0MYb4l9l5XT)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/a22fabbd9f93f65de6becf8fcb0d5049b71b3189/tests/integration/components/sl-drop-button-test.js#L105)):</sup>
What 3rd argument? 

https://github.com/softlayer/sl-ember-components/blob/EmberCli-1.13.8/tests/integration/components/sl-calendar-test.js#L197  https://github.com/softlayer/sl-ember-components/blob/EmberCli-1.13.8/tests/integration/components/sl-pagination-test.js#L88  https://github.com/softlayer/sl-ember-components/blob/EmberCli-1.13.8/tests/integration/components/sl-date-picker-test.js#L184   

All these component tests don't have a third argument on `assert.ok`,  reverted to just one argument to follow convention.


---

<sup>**[tests/integration/components/sl-drop-button-test.js, line 108 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K1o-Ka6y1hY-0bwuaOr)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/a22fabbd9f93f65de6becf8fcb0d5049b71b3189/tests/integration/components/sl-drop-button-test.js#L108)):</sup>
Spacing breaks the test as jQuery disallows spaces in contains(). reverted to `find( 'a' )` instead. 


---

<sup>**[tests/unit/components/sl-drop-button-test.js, line 17 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K1o1FjJX1QC2jm2QiID)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/a22fabbd9f93f65de6becf8fcb0d5049b71b3189/tests/unit/components/sl-drop-button-test.js#L17)):</sup>
Done.


---

<sup>**[tests/unit/components/sl-drop-button-test.js, line 26 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K1o1TnCFIjsz6SPzxSP)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/a22fabbd9f93f65de6becf8fcb0d5049b71b3189/tests/unit/components/sl-drop-button-test.js#L26)):</sup>
Done.


---

<sup>**[tests/unit/components/sl-drop-button-test.js, line 35 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K1o1vOkqHdmWhKwuoy_)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/a22fabbd9f93f65de6becf8fcb0d5049b71b3189/tests/unit/components/sl-drop-button-test.js#L35)):</sup>
Done.


---

<sup>**[tests/unit/components/sl-drop-button-test.js, line 69 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K1o3R--C-_3lfquUCNo)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/a22fabbd9f93f65de6becf8fcb0d5049b71b3189/tests/unit/components/sl-drop-button-test.js#L69)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050)

**Comment by notmessenger** [comment]
What does https://github.com/softlayer/sl-ember-components/blob/EmberCli-1.13.8/addon/templates/components/sl-drop-button.hbs#L22 do then if not support an icon property?  Just like line 23 supports a label option, for which you have added a test.


---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

<sup>**[tests/integration/components/sl-drop-button-test.js, line 105 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K1o1WHwX0MYb4l9l5XT)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/a22fabbd9f93f65de6becf8fcb0d5049b71b3189/tests/integration/components/sl-drop-button-test.js#L105)):</sup>
You are correct that I misspoke.  But the pattern is to actually have both arguments (see https://github.com/softlayer/sl-ember-components/search?utf8=✓&q=ok) so the first one needs to be replaced.


---

<sup>**[tests/integration/components/sl-drop-button-test.js, line 108 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K1o-Ka6y1hY-0bwuaOr)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/a22fabbd9f93f65de6becf8fcb0d5049b71b3189/tests/integration/components/sl-drop-button-test.js#L108)):</sup>
If the contains portion is more correct for how we should be accessing the DOM then the spacing around the quotes is acceptable.  I didn't check - I'm assuming it passed linting that way as well.


---

<sup>**[tests/integration/components/sl-drop-button-test.js, line 30 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K27fLCqJm9XMJHzltZ0)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/1cba722bc3d18c2ae5578f1922a970a13cfb7d69/tests/integration/components/sl-drop-button-test.js#L30)):</sup>
lower case "Class"


---

<sup>**[tests/integration/components/sl-drop-button-test.js, line 33 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K27ers_YTYebpip7ODI)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/1cba722bc3d18c2ae5578f1922a970a13cfb7d69/tests/integration/components/sl-drop-button-test.js#L33)):</sup>
This assertion is not needed as the integration tests for the `sl-button` component address this.


---

<sup>**[tests/integration/components/sl-drop-button-test.js, line 35 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K27fN9tCDWNiwKRbM3N)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/1cba722bc3d18c2ae5578f1922a970a13cfb7d69/tests/integration/components/sl-drop-button-test.js#L35)):</sup>
lower case "Class"


---

<sup>**[tests/integration/components/sl-drop-button-test.js, line 38 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K27ewcIs_HuXPU__xRI)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/1cba722bc3d18c2ae5578f1922a970a13cfb7d69/tests/integration/components/sl-drop-button-test.js#L38)):</sup>
This assertion is not needed as the integration tests for the `sl-button` component address this.


---

<sup>**[tests/integration/components/sl-drop-button-test.js, line 40 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K27fNl24p0duX7iKQPN)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/1cba722bc3d18c2ae5578f1922a970a13cfb7d69/tests/integration/components/sl-drop-button-test.js#L40)):</sup>
lower case "Class"


---

<sup>**[tests/integration/components/sl-drop-button-test.js, line 43 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K27ex-wXKXNmGW2rX-i)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/1cba722bc3d18c2ae5578f1922a970a13cfb7d69/tests/integration/components/sl-drop-button-test.js#L43)):</sup>
This assertion is not needed as the integration tests for the `sl-button` component address this.


---

<sup>**[tests/integration/components/sl-drop-button-test.js, line 45 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K27fONg_cbBBa3Fp-2o)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/1cba722bc3d18c2ae5578f1922a970a13cfb7d69/tests/integration/components/sl-drop-button-test.js#L45)):</sup>
lower case "Class"


---

<sup>**[tests/integration/components/sl-drop-button-test.js, line 50 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K27fOlUwAGWsXkBHZn6)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/1cba722bc3d18c2ae5578f1922a970a13cfb7d69/tests/integration/components/sl-drop-button-test.js#L50)):</sup>
lower case "Class"


---

<sup>**[tests/unit/components/sl-drop-button-test.js, line 92 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K2809UQTooA3vw3dNRO)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/1cba722bc3d18c2ae5578f1922a970a13cfb7d69/tests/unit/components/sl-drop-button-test.js#L92)):</sup>
This should be in the default values test case, not whether it can be set


---

<sup>**[tests/unit/components/sl-drop-button-test.js, line 102 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K280ENw7oUglp7BUuu8)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/1cba722bc3d18c2ae5578f1922a970a13cfb7d69/tests/unit/components/sl-drop-button-test.js#L102)):</sup>
This should be in the default values test case, not whether it can be set


---

<sup>**[tests/unit/components/sl-drop-button-test.js, line 124 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K280RghmFrnpR_6cVUF)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/1cba722bc3d18c2ae5578f1922a970a13cfb7d69/tests/unit/components/sl-drop-button-test.js#L124)):</sup>
this should test that null is returned with an invalid value, not that it was passed a null.  passing a null technically does the same thing but is not as obvious of what is being tested


---

<sup>**[tests/unit/components/sl-drop-button-test.js, line 135 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K280ehVOyuRTiSALehK)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/1cba722bc3d18c2ae5578f1922a970a13cfb7d69/tests/unit/components/sl-drop-button-test.js#L135)):</sup>
test the `false` state as well


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050)

**Comment by erangeles** [comment]
Review status: 0 of 2 files reviewed at latest revision, 14 unresolved discussions.

---

<sup>**[tests/integration/components/sl-drop-button-test.js, line 108 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K1o-Ka6y1hY-0bwuaOr)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/a22fabbd9f93f65de6becf8fcb0d5049b71b3189/tests/integration/components/sl-drop-button-test.js#L108)):</sup>
the only reason I had contain in place was to correctly identify which of the multiple `sl-drop-option` I wanted to click at the time based on label value, since that case since been removed it is no longer needed. I did pass linting though. 


---

<sup>**[tests/integration/components/sl-drop-button-test.js, line 30 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K27fLCqJm9XMJHzltZ0)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/1cba722bc3d18c2ae5578f1922a970a13cfb7d69/tests/integration/components/sl-drop-button-test.js#L30)):</sup>
Done.


---

<sup>**[tests/integration/components/sl-drop-button-test.js, line 33 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K27ers_YTYebpip7ODI)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/1cba722bc3d18c2ae5578f1922a970a13cfb7d69/tests/integration/components/sl-drop-button-test.js#L33)):</sup>
Done.


---

<sup>**[tests/integration/components/sl-drop-button-test.js, line 35 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K27fN9tCDWNiwKRbM3N)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/1cba722bc3d18c2ae5578f1922a970a13cfb7d69/tests/integration/components/sl-drop-button-test.js#L35)):</sup>
Done.


---

<sup>**[tests/integration/components/sl-drop-button-test.js, line 38 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K27ewcIs_HuXPU__xRI)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/1cba722bc3d18c2ae5578f1922a970a13cfb7d69/tests/integration/components/sl-drop-button-test.js#L38)):</sup>
Done.


---

<sup>**[tests/integration/components/sl-drop-button-test.js, line 40 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K27fNl24p0duX7iKQPN)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/1cba722bc3d18c2ae5578f1922a970a13cfb7d69/tests/integration/components/sl-drop-button-test.js#L40)):</sup>
Done.


---

<sup>**[tests/integration/components/sl-drop-button-test.js, line 43 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K27ex-wXKXNmGW2rX-i)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/1cba722bc3d18c2ae5578f1922a970a13cfb7d69/tests/integration/components/sl-drop-button-test.js#L43)):</sup>
Done.


---

<sup>**[tests/integration/components/sl-drop-button-test.js, line 45 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K27fONg_cbBBa3Fp-2o)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/1cba722bc3d18c2ae5578f1922a970a13cfb7d69/tests/integration/components/sl-drop-button-test.js#L45)):</sup>
Done.


---

<sup>**[tests/integration/components/sl-drop-button-test.js, line 50 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K27fOlUwAGWsXkBHZn6)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/1cba722bc3d18c2ae5578f1922a970a13cfb7d69/tests/integration/components/sl-drop-button-test.js#L50)):</sup>
Done.


---

<sup>**[tests/unit/components/sl-drop-button-test.js, line 92 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K2809UQTooA3vw3dNRO)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/1cba722bc3d18c2ae5578f1922a970a13cfb7d69/tests/unit/components/sl-drop-button-test.js#L92)):</sup>
Done.


---

<sup>**[tests/unit/components/sl-drop-button-test.js, line 102 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K280ENw7oUglp7BUuu8)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/1cba722bc3d18c2ae5578f1922a970a13cfb7d69/tests/unit/components/sl-drop-button-test.js#L102)):</sup>
Done.


---

<sup>**[tests/unit/components/sl-drop-button-test.js, line 124 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K280RghmFrnpR_6cVUF)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/1cba722bc3d18c2ae5578f1922a970a13cfb7d69/tests/unit/components/sl-drop-button-test.js#L124)):</sup>
Done.


---

<sup>**[tests/unit/components/sl-drop-button-test.js, line 135 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050#-K280ehVOyuRTiSALehK)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/1cba722bc3d18c2ae5578f1922a970a13cfb7d69/tests/unit/components/sl-drop-button-test.js#L135)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050)

**Comment by notmessenger** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1050)

**Pull request merged**
