### PR TITLE
Sl modal test

### PR DESCRIPTION
**Pull request by SpikedKira**
should close issues: #731, #853, #903

[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/912)

### CODE REVIEW

**Comment by notmessenger** [comment]
Connected to #903

**Comment by azizpunjani** [comment]
<sup>**[tests/integration/components/sl-modal-test.js, line 144 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K0RUX2lW2H8xubBkgsh)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/0ca60995f20e34e3841d3b8e804964fe7c83215d/tests/integration/components/sl-modal-test.js#L144)):</sup>
I would create a separate test for the animated property, so that properties are tested in isolation.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912)

**Comment by SpikedKira** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[tests/integration/components/sl-modal-test.js, line 144 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K0RUX2lW2H8xubBkgsh)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/0ca60995f20e34e3841d3b8e804964fe7c83215d/tests/integration/components/sl-modal-test.js#L144)):</sup>
I'm pretty sure my logic here was sound in terms of testing fail points.  Let's get someone else to weigh in on this.  I'm having trouble understanding what the possible draw back is from the current approach.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912)

**Comment by azizpunjani** [comment]
<sup>**[tests/integration/components/sl-modal-test.js, line 144 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K0RUX2lW2H8xubBkgsh)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/0ca60995f20e34e3841d3b8e804964fe7c83215d/tests/integration/components/sl-modal-test.js#L144)):</sup>
Here's a bug in the code that would slip by. 

```javascript
            const modal = this.$().modal({
                keyboard: true,
                show: false,
                backdrop: this.get( 'animated' )
            });
```

Not only does testing individual properties help eliminate such cross property contamination bugs, but it also makes the test code more digestible.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912)

**Comment by azizpunjani** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

<sup>**[tests/integration/components/sl-modal-test.js, line 113 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K0RUrfMsY9v-Z12at_h)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/0ca60995f20e34e3841d3b8e804964fe7c83215d/tests/integration/components/sl-modal-test.js#L113)):</sup>
Just reading the description, it's hard to tell what specifically is being tested. The description should be specific to what is being tested. 


---

<sup>**[tests/integration/components/sl-modal-test.js, line 127 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K0RVL2oQ67ChH_N5jnE)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/0ca60995f20e34e3841d3b8e804964fe7c83215d/tests/integration/components/sl-modal-test.js#L127)):</sup>
Just reading the description, it's hard to tell what specifically is being tested. The description should be specific to what is being tested. 


---

<sup>**[tests/integration/components/sl-modal-test.js, line 141 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K0RVN34L5SZpEH2huRh)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/0ca60995f20e34e3841d3b8e804964fe7c83215d/tests/integration/components/sl-modal-test.js#L141)):</sup>
Just reading the description, it's hard to tell what specifically is being tested. The description should be specific to what is being tested. 


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912)

**Comment by SpikedKira** [comment]
<sup>**[tests/integration/components/sl-modal-test.js, line 144 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K0RUX2lW2H8xubBkgsh)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/0ca60995f20e34e3841d3b8e804964fe7c83215d/tests/integration/components/sl-modal-test.js#L144)):</sup>
you're correct.  Irritating as it is, I don't see a good way to reuse the template code.  The test is now bulkier but more correct and maybe easier to read.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912)

**Comment by azizpunjani** [comment]
Build is failing https://travis-ci.org/softlayer/sl-ember-components/jobs/84987395#L569

**Comment by notmessenger** [comment]
The first bullet item of https://github.com/softlayer/sl-ember-components/issues/903 is "is backdrop option set to true by default?" but I do not see any such unit test covering this condition.  I'm assuming that https://github.com/softlayer/sl-ember-components/issues/765 is the better issue to add this?


---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 25 unresolved discussions, all commit checks successful.

---

<sup>**[tests/integration/components/sl-modal-test.js, line 127 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K0RVL2oQ67ChH_N5jnE)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/0ca60995f20e34e3841d3b8e804964fe7c83215d/tests/integration/components/sl-modal-test.js#L127)):</sup>
This same comment applies equally to the other assert comments.


---

<sup>**[tests/integration/components/sl-modal-test.js, line 46 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K0gFBH7dfCovXw6VHNj)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/23f44a333a99abc10730d824f4407210bea8628c/tests/integration/components/sl-modal-test.js#L46)):</sup>
* Capitalize `b` in `backdrop`
* Replace `thru` with `through`
* Replace 'jquery' with 'jQuery'

The purpose of this test case if to ensure that the `backdrop` property is correctly associated via template and component syntax that it is being passed along to jQuery correctly.  From this description, and perspective, the value of the property does not matter.  Meaning that in the assertions below we test two different values.  Yes, they happen to be Boolean values which only have two possibilities, but why are we not also testing a string?  Which strings should we use?  How many different ones?  The point is that the value is irrelevant.  So...we can reduce this test case to a single assertion that confirms that a value is passed along as expected.  Since we know this property will be assigned a Boolean value I would use a string, such as "test", in order to completely isolate ourselves from any false positives that might arise within the logic surrounding Boolean values.

Having said all that, if we are also needing/wanting to test that Boolean values, when specifically passed in, are or are not having something done to them (type casting, etc), then testing the specific values has value, though there should be an additional test that covers non-Boolean values.  And I would recommend changing the description of the test at that point as well.


---

<sup>**[tests/integration/components/sl-modal-test.js, line 47 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K0gFNVz2B11daSk4kg7)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/23f44a333a99abc10730d824f4407210bea8628c/tests/integration/components/sl-modal-test.js#L47)):</sup>
Replace `thru` with `through`


---

<sup>**[tests/integration/components/sl-modal-test.js, line 51 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K0gFcJz0UxpSuYOYoOQ)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/23f44a333a99abc10730d824f4407210bea8628c/tests/integration/components/sl-modal-test.js#L51)):</sup>
Remove `'` from property names


---

<sup>**[tests/integration/components/sl-modal-test.js, line 56 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K0gfg2kh4Y_E9HnFDnm)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/23f44a333a99abc10730d824f4407210bea8628c/tests/integration/components/sl-modal-test.js#L56)):</sup>
This comment makes it seem that there is a difference in the manner in which the properties are being set, not the value to which they are


---

<sup>**[tests/integration/components/sl-modal-test.js, line 58 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K0gGOI3yzKTuUchqVjO)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/23f44a333a99abc10730d824f4407210bea8628c/tests/integration/components/sl-modal-test.js#L58)):</sup>
Collapse into a single line


---

<sup>**[tests/integration/components/sl-modal-test.js, line 65 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K0gfklGWbZwM6-ukOVE)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/23f44a333a99abc10730d824f4407210bea8628c/tests/integration/components/sl-modal-test.js#L65)):</sup>
This comment makes it seem that there is a difference in the manner in which the properties are being set, not the value to which they are


---

<sup>**[tests/integration/components/sl-modal-test.js, line 67 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K0gGPO9DjC_QIzij9vT)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/23f44a333a99abc10730d824f4407210bea8628c/tests/integration/components/sl-modal-test.js#L67)):</sup>
Collapse into a single line


---

<sup>**[tests/integration/components/sl-modal-test.js, line 76 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K0gGQRo2ZTd3vgU7_d3)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/23f44a333a99abc10730d824f4407210bea8628c/tests/integration/components/sl-modal-test.js#L76)):</sup>
Collapse into a single line


---

<sup>**[tests/integration/components/sl-modal-test.js, line 85 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K0gHNHwa4s1wxnUaG6w)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/23f44a333a99abc10730d824f4407210bea8628c/tests/integration/components/sl-modal-test.js#L85)):</sup>
This can be put on a single line.  Think I prefer that but leave it to your preference.


---

<sup>**[tests/integration/components/sl-modal-test.js, line 87 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K0hBA5F5S7J3VJtes3A)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/23f44a333a99abc10730d824f4407210bea8628c/tests/integration/components/sl-modal-test.js#L87)):</sup>
Remove `'` from property names


---

<sup>**[tests/integration/components/sl-modal-test.js, line 98 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K0hCF-uIYdbhIWIlSQ2)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/23f44a333a99abc10730d824f4407210bea8628c/tests/integration/components/sl-modal-test.js#L98)):</sup>
This can be put on a single line.  Think I prefer that but leave it to your preference.


---

<sup>**[tests/integration/components/sl-modal-test.js, line 100 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K0hCBBVIlUrj74L_Ear)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/23f44a333a99abc10730d824f4407210bea8628c/tests/integration/components/sl-modal-test.js#L100)):</sup>
Remove `'` from property names


---

<sup>**[tests/integration/components/sl-modal-test.js, line 109 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K0kc1OrRtIo21b4SNbR)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/23f44a333a99abc10730d824f4407210bea8628c/tests/integration/components/sl-modal-test.js#L109)):</sup>
I'm not sure we need to assert the default values.  There is a test case that is checking the default value of the property.  Unless the default behavior is a derived one, only based upon this property, then there is no need to assert it.


---

<sup>**[tests/integration/components/sl-modal-test.js, line 111 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K0hCFsuf_ibp_IRYnyq)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/23f44a333a99abc10730d824f4407210bea8628c/tests/integration/components/sl-modal-test.js#L111)):</sup>
This can be put on a single line.  Think I prefer that but leave it to your preference.


---

<sup>**[tests/integration/components/sl-modal-test.js, line 113 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K0hBFcdey3atdilWyVp)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/23f44a333a99abc10730d824f4407210bea8628c/tests/integration/components/sl-modal-test.js#L113)):</sup>
Remove `'` from property names


---

<sup>**[tests/integration/components/sl-modal-test.js, line 124 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K0kcn5jFiXj7zasunFg)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/23f44a333a99abc10730d824f4407210bea8628c/tests/integration/components/sl-modal-test.js#L124)):</sup>
This comment makes it seem that there is a difference in the manner in which the properties are being set, not the value to which they are


---

<sup>**[tests/integration/components/sl-modal-test.js, line 126 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K0kcWK7TQvBaQTYY0oc)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/23f44a333a99abc10730d824f4407210bea8628c/tests/integration/components/sl-modal-test.js#L126)):</sup>
Collapse into a single line


---

<sup>**[tests/integration/components/sl-modal-test.js, line 133 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K0kcnsVVEBEQpimixmb)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/23f44a333a99abc10730d824f4407210bea8628c/tests/integration/components/sl-modal-test.js#L133)):</sup>
This comment makes it seem that there is a difference in the manner in which the properties are being set, not the value to which they are


---

<sup>**[tests/integration/components/sl-modal-test.js, line 135 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K0kcWqtZktoc0QDAEQn)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/23f44a333a99abc10730d824f4407210bea8628c/tests/integration/components/sl-modal-test.js#L135)):</sup>
Collapse into a single line


---

<sup>**[tests/integration/components/sl-modal-test.js, line 144 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K0kcXP5cUtffLuw-glw)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/23f44a333a99abc10730d824f4407210bea8628c/tests/integration/components/sl-modal-test.js#L144)):</sup>
Collapse into a single line


---

<sup>**[tests/integration/components/sl-modal-test.js, line 159 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K0kd8QtJGDrZUh4qAik)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/23f44a333a99abc10730d824f4407210bea8628c/tests/integration/components/sl-modal-test.js#L159)):</sup>
This does not allow for future DOM changes (addition of new elements).  If instead looked for `.fade` and asserted it against a length of 0, or similar, that would.


---

<sup>**[tests/integration/components/sl-modal-test.js, line 170 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K0kcREkBpjkKOqH7KEz)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/23f44a333a99abc10730d824f4407210bea8628c/tests/integration/components/sl-modal-test.js#L170)):</sup>
I'm not sure we need to assert the default values.  There is a test case that is checking the default value of the property.  Unless the default behavior is a derived one, only based upon this property, then there is no need to assert it.


---

<sup>**[tests/integration/components/sl-modal-test.js, line 437 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K0kdkD4PFuwtB6-ErrO)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/23f44a333a99abc10730d824f4407210bea8628c/tests/integration/components/sl-modal-test.js#L437)):</sup>
Is this assertion relevant if no other modal has yet to be rendered?


---

<sup>**[tests/integration/components/sl-modal-test.js, line 443 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K0kdoiaTq10jhanhwc4)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/23f44a333a99abc10730d824f4407210bea8628c/tests/integration/components/sl-modal-test.js#L443)):</sup>
Is this assertion relevant if no other modal has yet to be rendered?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912)

**Comment by SpikedKira** [comment]
For now it is effectively covered by this test, as there is not a unit test currently (see comments regarding line 109 of this review)


---

Review status: 0 of 1 files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---

<sup>**[tests/integration/components/sl-modal-test.js, line 46 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K0gFBH7dfCovXw6VHNj)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/23f44a333a99abc10730d824f4407210bea8628c/tests/integration/components/sl-modal-test.js#L46)):</sup>
I was testing 2 variations, regardless of Boolean to ensure that Aziz' example was not happening.  That is, that a secondary value is improperly assigned to the property internally.  For instance, the default value of animated could be assigned to backdrop by mistake.  If this were the case, then it's possible a single test case could align perfectly and false-pass.  If animated is true by default and mis-assigned to backdrop, and the test for backdrop tests if true is passed along properly, this test will pass when it shouldn't.


---

<sup>**[tests/integration/components/sl-modal-test.js, line 109 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K0kc1OrRtIo21b4SNbR)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/23f44a333a99abc10730d824f4407210bea8628c/tests/integration/components/sl-modal-test.js#L109)):</sup>
"There is a test case that is checking the default value of the property"  No, currently there is not one.  This may need to be revised once the unit test suite is created.


---

<sup>**[tests/integration/components/sl-modal-test.js, line 159 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K0kd8QtJGDrZUh4qAik)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/23f44a333a99abc10730d824f4407210bea8628c/tests/integration/components/sl-modal-test.js#L159)):</sup>
this just says that the component itself does not have a class of "fade". no other elements can influence this in any way


---

<sup>**[tests/integration/components/sl-modal-test.js, line 170 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K0kcREkBpjkKOqH7KEz)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/23f44a333a99abc10730d824f4407210bea8628c/tests/integration/components/sl-modal-test.js#L170)):</sup>
I'll circle back around to this one.


---

<sup>**[tests/integration/components/sl-modal-test.js, line 437 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K0kdkD4PFuwtB6-ErrO)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/23f44a333a99abc10730d824f4407210bea8628c/tests/integration/components/sl-modal-test.js#L437)):</sup>
I believe so.  We must check that component1 binds to the expected dom, else checking component2's binding can not be based on anything.  The assert can not be moved lower due to the need to reset the spies.


---

<sup>**[tests/integration/components/sl-modal-test.js, line 443 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K0kdoiaTq10jhanhwc4)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/23f44a333a99abc10730d824f4407210bea8628c/tests/integration/components/sl-modal-test.js#L443)):</sup>
See above.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912)

**Comment by notmessenger** [comment]
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

<sup>**[tests/integration/components/sl-modal-test.js, line 109 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K0kc1OrRtIo21b4SNbR)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/23f44a333a99abc10730d824f4407210bea8628c/tests/integration/components/sl-modal-test.js#L109)):</sup>
Default rendered state of the component should be asserted in a test case in the integration test suite.  Default property values should be asserted in the unit test suite.  For those that should be in the unit tests please add any notes related to such to https://github.com/softlayer/sl-ember-components/issues/765.  For the others, create a default state test case.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912)

**Comment by azizpunjani** [comment]
<sup>**[tests/integration/components/sl-modal-test.js, line 437 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K0kdkD4PFuwtB6-ErrO)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/23f44a333a99abc10730d824f4407210bea8628c/tests/integration/components/sl-modal-test.js#L437)):</sup>
I'm not sure this is relevant, I think this test would always pass regardless since during the time of this assertion there is only one instance present. We should only need to check that component2's binding is correct.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912)

**Comment by azizpunjani** [comment]
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

<sup>**[tests/integration/components/sl-modal-test.js, line 443 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K0kdoiaTq10jhanhwc4)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/23f44a333a99abc10730d824f4407210bea8628c/tests/integration/components/sl-modal-test.js#L443)):</sup>
I'm not sure this is relevant, I think this test would always pass regardless since during the time of this assertion there is only one instance present. We should only need to check that component2's binding is correct.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912)

**Comment by azizpunjani** [comment]
Review status: 0 of 1 files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

<sup>**[tests/integration/components/sl-modal-test.js, line 437 \[r5\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K19gyxal28FumK3WKDV)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/93ad3395ddf4459624cbac1a245abad20ea94e93/tests/integration/components/sl-modal-test.js#L437)):</sup>
Are we not testing bootstrap functionality here? Is any of our code getting tested via this asserts?


---

<sup>**[tests/integration/components/sl-modal-test.js, line 447 \[r5\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K19hJCwImFomnL7sUmL)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/93ad3395ddf4459624cbac1a245abad20ea94e93/tests/integration/components/sl-modal-test.js#L447)):</sup>
Are we not testing bootstrap functionality here? Is any of our code getting tested via this asserts?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912)

**Comment by azizpunjani** [comment]
Review status: 0 of 1 files reviewed at latest revision, 17 unresolved discussions, all commit checks successful.

---

<sup>**[tests/integration/components/sl-modal-test.js, line 435 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K19hwO2Cvc2WILCSo2N)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/23f44a333a99abc10730d824f4407210bea8628c/tests/integration/components/sl-modal-test.js#L435)):</sup>
Remove `$` prefix, per styleguide.


---

<sup>**[tests/integration/components/sl-modal-test.js, line 439 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K19i0Cj5BzVi_1JCt3J)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/23f44a333a99abc10730d824f4407210bea8628c/tests/integration/components/sl-modal-test.js#L439)):</sup>
Remove `$` prefix, per styleguide.


---

<sup>**[tests/integration/components/sl-modal-test.js, line 468 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K19i2W20T_PPzjboeRz)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/23f44a333a99abc10730d824f4407210bea8628c/tests/integration/components/sl-modal-test.js#L468)):</sup>
Remove `$` prefix, per styleguide.


---

<sup>**[tests/integration/components/sl-modal-test.js, line 474 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K19iJw_32TB0MKvkVmu)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/23f44a333a99abc10730d824f4407210bea8628c/tests/integration/components/sl-modal-test.js#L474)):</sup>
Remove `$` prefix, per styleguide.


---

<sup>**[tests/integration/components/sl-modal-test.js, line 481 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K19iLYVxlco5lEes9PN)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/23f44a333a99abc10730d824f4407210bea8628c/tests/integration/components/sl-modal-test.js#L481)):</sup>
Remove `$` prefix, per styleguide.


---

<sup>**[tests/integration/components/sl-modal-test.js, line 485 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K19iMehQuqCjqY8uref)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/23f44a333a99abc10730d824f4407210bea8628c/tests/integration/components/sl-modal-test.js#L485)):</sup>
Remove `$` prefix, per styleguide.


---

<sup>**[tests/integration/components/sl-modal-test.js, line 491 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K19iUoPbX0tCHHF8Tbx)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/23f44a333a99abc10730d824f4407210bea8628c/tests/integration/components/sl-modal-test.js#L491)):</sup>
Remove `$` prefix, per styleguide.


---

<sup>**[tests/integration/components/sl-modal-test.js, line 495 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K19iQbfuvBTL5Id6gMj)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/23f44a333a99abc10730d824f4407210bea8628c/tests/integration/components/sl-modal-test.js#L495)):</sup>
Remove `$` prefix, per styleguide.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912)

**Comment by azizpunjani** [comment]
Reviewed 1 of 1 files at r4.
Review status: 0 of 1 files reviewed at latest revision, 17 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912)

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 17 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912)

**Comment by SpikedKira** [comment]
Last commit incidentally closes #951 


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912)

**Comment by notmessenger** [comment]
Have all outstanding changes been made and this PR an be (re)reviewed?


---

Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912)

**Comment by SpikedKira** [comment]
yes; happy reviewing


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912)

**Comment by notmessenger** [comment]
This test suite needs to align with the current practices we are following, including, but not limited to:

* https://github.com/softlayer/ember-style-guide/issues/67


---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912)

**Comment by notmessenger** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

<sup>**[tests/integration/components/sl-modal-test.js, line 75 \[r7\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K1dq3aq9OBdOeLF3UZt)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/c81ee32b92c1957ced3d4579d4beb130da6c776d/tests/integration/components/sl-modal-test.js#L75)):</sup>
Construct this test case by using `this.set()` blah blah - see note in https://reviewable.io/reviews/softlayer/sl-ember-components/1020


---

<sup>**[tests/integration/components/sl-modal-test.js, line 235 \[r7\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K1dqw88N5HjISjlBRQk)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/f98b8533bfb943dcaa280deca4a017aa5b268b76/tests/integration/components/sl-modal-test.js#L235)):</sup>
This needs to still exist, but merged with "Default rendered state" test case.  Discussed in https://reviewable.io/reviews/softlayer/sl-ember-components/1020


---

<sup>**[tests/integration/components/sl-modal-test.js, line 326 \[r7\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K1dnpFQ0ZsT7uADeVlU)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/c81ee32b92c1957ced3d4579d4beb130da6c776d/tests/integration/components/sl-modal-test.js#L326)):</sup>
This should be an integration test - https://github.com/softlayer/ember-style-guide/blob/master/ember-testing.md#naming-component-unit-tests


---

<sup>**[tests/integration/components/sl-modal-test.js, line 332 \[r7\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K1dqt3jVuv0zyoM2Rhk)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/f98b8533bfb943dcaa280deca4a017aa5b268b76/tests/integration/components/sl-modal-test.js#L332)):</sup>
Why was this test case removed?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912)

**Comment by SpikedKira** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

<sup>**[tests/integration/components/sl-modal-test.js, line 326 \[r7\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K1dnpFQ0ZsT7uADeVlU)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/c81ee32b92c1957ced3d4579d4beb130da6c776d/tests/integration/components/sl-modal-test.js#L326)):</sup>
removing from integration. there are issues open to put it into unit.


---

<sup>**[tests/integration/components/sl-modal-test.js, line 332 \[r7\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K1dqt3jVuv0zyoM2Rhk)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/f98b8533bfb943dcaa280deca4a017aa5b268b76/tests/integration/components/sl-modal-test.js#L332)):</sup>
I think it was temporarily in the unit test or something... I have re-added it.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912)

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

<sup>**[tests/integration/components/sl-modal-test.js, line 59 \[r8\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K1e2GAGsPkDh4UU2phf)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/9c308ee03cf5d55d21a04e6673082eda58235d6b/tests/integration/components/sl-modal-test.js#L59)):</sup>
Not `hasClass()`?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912)

**Comment by SpikedKira** [comment]
<sup>**[tests/integration/components/sl-modal-test.js, line 59 \[r8\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912#-K1e2GAGsPkDh4UU2phf)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/9c308ee03cf5d55d21a04e6673082eda58235d6b/tests/integration/components/sl-modal-test.js#L59)):</sup>
can't... this gets added at root dom, which is also why I am using Ember.$


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/912)

**Pull request merged**
