### PR TITLE
Issue 1156

### PR DESCRIPTION
**Pull request by SpikedKira**
[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1162)

### CODE REVIEW

**Comment by azizpunjani** [comment]
Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

<sup>**[addon/components/sl-checkbox.js, line 31 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1162#-K2x6NqliEtL7HVjh-Xi)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/69ad5993f339d16f262c67792fe266defb35cd1c/addon/components/sl-checkbox.js#L31)):</sup>
`/** @type {?String} */ `
Since it has a null value to begin with.


---

<sup>**[tests/dummy/app/templates/demos/sl-checkbox.hbs, line 68 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1162#-K2x7UWUygGD7XTPwZi1)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/69ad5993f339d16f262c67792fe266defb35cd1c/tests/dummy/app/templates/demos/sl-checkbox.hbs#L68)):</sup>
Not Boolean?


---

<sup>**[tests/unit/components/sl-checkbox-test.js, line 23 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1162#-K2x951VxjnAwPzVSl_N)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/69ad5993f339d16f262c67792fe266defb35cd1c/tests/unit/components/sl-checkbox-test.js#L23)):</sup>
Need to add test for tagName here.


---

<sup>**[tests/unit/components/sl-checkbox-test.js, line 46 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1162#-K2x7cG-6MvKZ-I_LqSv)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/69ad5993f339d16f262c67792fe266defb35cd1c/tests/unit/components/sl-checkbox-test.js#L46)):</sup>
Is this assert needed? The one before this seems sufficient. 

If `checkboxType` is `checkbox` it shouldn't be anything else at this point in the code right?


---

<sup>**[tests/unit/components/sl-checkbox-test.js, line 63 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1162#-K2x8RZEgaPM2Gz3PGc7)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/69ad5993f339d16f262c67792fe266defb35cd1c/tests/unit/components/sl-checkbox-test.js#L63)):</sup>
Is this assert needed? The one before this seems sufficient. 

If `checkboxType` is `checkbox-inline` it shouldn't be anything else at this point in the code right?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1162)

**Comment by azizpunjani** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1162)

**Comment by notmessenger** [comment]
Reviewed 2 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[addon/templates/components/sl-checkbox.hbs, line 1 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1162#-K3KscTX9MR-4pUH7USP)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/ea2f301ad4443815b629111161a10f63e45a962f/addon/templates/components/sl-checkbox.hbs#L1)):</sup>
Isn't this going to put a `label` around this when `inline` is true?  If so, how are these template segments any different from one another?


---

<sup>**[tests/integration/components/sl-checkbox-test.js, line 95 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1162#-K3Kt8An0dx24t9rF0lJ)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/ea2f301ad4443815b629111161a10f63e45a962f/tests/integration/components/sl-checkbox-test.js#L95)):</sup>
This assertion should be in the default state test case


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1162)

**Comment by SpikedKira** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[addon/templates/components/sl-checkbox.hbs, line 1 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1162#-K3KscTX9MR-4pUH7USP)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/ea2f301ad4443815b629111161a10f63e45a962f/addon/templates/components/sl-checkbox.hbs#L1)):</sup>
label wraps the input at all times. if not inline, it is also wrapped with a div with special classes on it.


---

<sup>**[tests/integration/components/sl-checkbox-test.js, line 95 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1162#-K3Kt8An0dx24t9rF0lJ)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/ea2f301ad4443815b629111161a10f63e45a962f/tests/integration/components/sl-checkbox-test.js#L95)):</sup>
look again, it's in both places.  Default is NOT inline and has assert.ok(), this test IS inline and has the same test but assert.notOk()


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1162)

**Pull request merged**
