### PR TITLE
Create Unit test to assert properties observed by Ember.observer()

### PR DESCRIPTION
**Pull request by erangeles**
[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1112)

### CODE REVIEW

**Comment by juwara0** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[tests/unit/components/sl-chart-test.js, line 402 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1112#-K2wJgzL50q0ZYHPEgWv)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/1af516b05da970ad5a8b856f04eb81302f0be17a/tests/unit/components/sl-chart-test.js#L402)):</sup>
should be lowercase "keys"


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1112)

**Comment by juwara0** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1112)

**Comment by juwara0** [comment]
<sup>**[tests/unit/components/sl-chart-test.js, line 417 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1112#-K2wSEiJqG1XM1-g4FNH)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/1af516b05da970ad5a8b856f04eb81302f0be17a/tests/unit/components/sl-chart-test.js#L417)):</sup>
You need to add a blank line at the end of the file to pass listing.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1112)

**Comment by erangeles** [comment]
@juwara0 github doesnt show the empty line by default, it is present and has passed linting in the build. ready to merge.

**Comment by juwara0** [comment]
@notmessenger: this is ready to merge


---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1112)

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1112)

**Pull request merged**
