### PR TITLE
Closes softlayer/sl-ember-components#1123, Closes softlayer/sl-ember-…

### PR DESCRIPTION
**Pull request by SpikedKira**
…components#1124, Closes softlayer/sl-ember-components#1132, Closes softlayer/sl-ember-components#1137, Closes softlayer/sl-ember-components#1173, Closes softlayer/sl-ember-components#1202

[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1373)

### CODE REVIEW

**Comment by azizpunjani** [comment]
Review status: 0 of 20 files reviewed at latest revision, 4 unresolved discussions.

---

*[app/styles/addon.less, line 46 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373#-K7resO1VcKVa_pOIuvO:-K7resO1VcKVa_pOIuvP:-1046032406) ([raw file](https://github.com/softlayer/sl-ember-components/blob/3900dec4693e76a4ae30236ae55a18dcd9671c4b/app/styles/addon.less#L46)):*
Probably better to remove this commented code. It will be in git if we ever need to look at the history.

---

*[app/styles/sl-date-picker.less, line 8 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373#-K7rfVVeWvt2TGsDVR8R:-K7rfVVeWvt2TGsDVR8S:-815620454) ([raw file](https://github.com/softlayer/sl-ember-components/blob/3900dec4693e76a4ae30236ae55a18dcd9671c4b/app/styles/sl-date-picker.less#L8)):*
Debating if this should be a variable that can be referenced here and within the icon styles.

---

*[app/styles/sl-select.less, line 110 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373#-K7rfvb0ZhkunlRn9ZZh:-K7rfvb0ZhkunlRn9ZZi:-2062020668) ([raw file](https://github.com/softlayer/sl-ember-components/blob/3900dec4693e76a4ae30236ae55a18dcd9671c4b/app/styles/sl-select.less#L110)):*
All these repeated styles should be in a mixin or variables.  

---

*[app/styles/sl-select.less, line 137 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373#-K7rg9pgaIXgzAhfM_lp:-K7rg9pgaIXgzAhfM_lq:-1086587484) ([raw file](https://github.com/softlayer/sl-ember-components/blob/3900dec4693e76a4ae30236ae55a18dcd9671c4b/app/styles/sl-select.less#L137)):*
Probably best to remove commented code.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373)*

**Comment by azizpunjani** [comment]
Reviewed 20 of 20 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373)*

**Comment by SpikedKira** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[app/styles/addon.less, line 46 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373#-K7resO1VcKVa_pOIuvO:-K7vgWvHVm4y2JCRgIZE:656817337) ([raw file](https://github.com/softlayer/sl-ember-components/blob/3900dec4693e76a4ae30236ae55a18dcd9671c4b/app/styles/addon.less#L46)):*
thanks, forgot about it

---

*[app/styles/sl-date-picker.less, line 8 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373#-K7rfVVeWvt2TGsDVR8R:-K7vhHcB9ErI9tKOoFsF:-1936267484) ([raw file](https://github.com/softlayer/sl-ember-components/blob/3900dec4693e76a4ae30236ae55a18dcd9671c4b/app/styles/sl-date-picker.less#L8)):*
We don't actually want it here at all.  Once calendar and date-picker are properly rearchitected, this will no longer be necessary.

---

*[app/styles/sl-select.less, line 110 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373#-K7rfvb0ZhkunlRn9ZZh:-K7vgx_eU8AqjpqyZIf1:-234710045) ([raw file](https://github.com/softlayer/sl-ember-components/blob/3900dec4693e76a4ae30236ae55a18dcd9671c4b/app/styles/sl-select.less#L110)):*
I disagree from the point of view that this should not have to be done from the very beginning.  We shouldn't even be including the  select2 styles as if they are our own.  I would hope that the very nature of this is cleaned up rather than streamlining the hacky solution.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373)*

**Comment by azizpunjani** [comment]
Review status: 18 of 20 files reviewed at latest revision, 1 unresolved discussion.

---

*[app/styles/sl-select.less, line 110 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373#-K7rfvb0ZhkunlRn9ZZh:-K7vqpUIACCmc_eKj84D:1215628168) ([raw file](https://github.com/softlayer/sl-ember-components/blob/3900dec4693e76a4ae30236ae55a18dcd9671c4b/app/styles/sl-select.less#L110)):*
I agree because that would mean we would have to move select icon properties into a mixin which we should't be doing. I am ok with leaving this here until this component is re-written.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373)*

**Comment by azizpunjani** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373)*

**Comment by notmessenger** [comment]
Is it possible to achieve the same vertical alignment of the drop down icon between `sl-drop-button` and `sl-select`?

---

Reviewed 18 of 20 files at r1, 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 22 unresolved discussions.

---

*[addon/templates/components/sl-alert.hbs, line 2 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373#-K7vgDPswMsRKcY2dvBl:-K7vgDPswMsRKcY2dvBm:-1609316194) ([raw file](https://github.com/softlayer/sl-ember-components/blob/3900dec4693e76a4ae30236ae55a18dcd9671c4b/addon/templates/components/sl-alert.hbs#L2)):*
Guessing not supposed to be "area-close"

---

*[addon/templates/components/sl-grid.hbs, line 106 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373#-K7vgqYDGmQ0UrOxRy1H:-K7vgqYDGmQ0UrOxRy1I:-1362213086) ([raw file](https://github.com/softlayer/sl-ember-components/blob/3900dec4693e76a4ae30236ae55a18dcd9671c4b/addon/templates/components/sl-grid.hbs#L106)):*
Guessing not supposed to be "area-label"

---

*[addon/templates/components/sl-modal-header.hbs, line 4 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373#-K7vh6lbKS9Tp3yUhTmp:-K7vh6lbKS9Tp3yUhTmq:-1362213086) ([raw file](https://github.com/softlayer/sl-ember-components/blob/3900dec4693e76a4ae30236ae55a18dcd9671c4b/addon/templates/components/sl-modal-header.hbs#L4)):*
Guessing not supposed to be "area-label"

---

*[app/styles/addon.less, line 38 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373#-K7vvBXyYttU1knM_Oub:-K7vvBXyYttU1knM_Ouc:-1130355116) ([raw file](https://github.com/softlayer/sl-ember-components/blob/3900dec4693e76a4ae30236ae55a18dcd9671c4b/app/styles/addon.less#L38)):*
vendor prefixes should not be added, as https://github.com/softlayer/sl-ember-components/issues/315 will address their absence

---

*[app/styles/addon.less, line 4 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373#-K7w1cfHFtB7MaDTPMXe:-K7w1cfHFtB7MaDTPMXf:-36639526) ([raw file](https://github.com/softlayer/sl-ember-components/blob/df446c3e546628c5319925f5b54d1dcc7cde3d9b/app/styles/addon.less#L4)):*
This pattern will still clobber any user-defined ones that match "sl-icon-my-coolStuff".  Avoiding clobbering user-land styles is a stated goal of this approach so need to address.

---

*[app/styles/addon.less, line 39 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373#-K7vzrX0adFjVy6EDu_Q:-K7vzrX0adFjVy6EDu_R:-1130355116) ([raw file](https://github.com/softlayer/sl-ember-components/blob/df446c3e546628c5319925f5b54d1dcc7cde3d9b/app/styles/addon.less#L39)):*
vendor prefixes should not be added, as https://github.com/softlayer/sl-ember-components/issues/315 will address their absence

---

*[app/styles/sl-alert.less, line 6 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373#-K7vy9rEPZtkauEk4UQn:-K7vy9rEPZtkauEk4UQo:-1071788764) ([raw file](https://github.com/softlayer/sl-ember-components/blob/3900dec4693e76a4ae30236ae55a18dcd9671c4b/app/styles/sl-alert.less#L6)):*
This value should be defined in a variable for easy (re)definition by ourselves in the future and consuming applications

---

*[app/styles/sl-alert.less, line 1 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373#-K7vzYdcgFDkUTB7QPKM:-K7vzYdcgFDkUTB7QPKN:1340196626) ([raw file](https://github.com/softlayer/sl-ember-components/blob/df446c3e546628c5319925f5b54d1dcc7cde3d9b/app/styles/sl-alert.less#L1)):*
This should be shared via mixin with modal

---

*[app/styles/sl-calendar.less, line 3 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373#-K7vyGpCRQ26sU6M2KZX:-K7vyGpCRQ26sU6M2KZY:-1385127510) ([raw file](https://github.com/softlayer/sl-ember-components/blob/3900dec4693e76a4ae30236ae55a18dcd9671c4b/app/styles/sl-calendar.less#L3)):*
* This value should be defined in a variable for easy (re)definition by ourselves in the future and consuming applications
* Why is this value in single quotes when the icon declaration had its font value changed to double quotes?

---

*[app/styles/sl-calendar.less, line 7 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373#-K7vyHGBnmDUVsFpI429:-K7vyHGCbwgr4J0lUtbY:-1385127510) ([raw file](https://github.com/softlayer/sl-ember-components/blob/3900dec4693e76a4ae30236ae55a18dcd9671c4b/app/styles/sl-calendar.less#L7)):*
* This value should be defined in a variable for easy (re)definition by ourselves in the future and consuming applications
* Why is this value in single quotes when the icon declaration had its font value changed to double quotes?

---

*[app/styles/sl-date-picker.less, line 1 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373#-K7vyg66_CZiJ9qyLuXg:-K7vyg66_CZiJ9qyLuXh:1043913799) ([raw file](https://github.com/softlayer/sl-ember-components/blob/3900dec4693e76a4ae30236ae55a18dcd9671c4b/app/styles/sl-date-picker.less#L1)):*
Can any of these declarations be shared with the sl-icon ones (in a logical, useful way) via a mixin, etc?

---

*[app/styles/sl-date-picker.less, line 18 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373#-K7vyqwBvn7WzxwQxdnk:-K7vyqwBvn7WzxwQxdnl:806114716) ([raw file](https://github.com/softlayer/sl-ember-components/blob/3900dec4693e76a4ae30236ae55a18dcd9671c4b/app/styles/sl-date-picker.less#L18)):*
* This value should be defined in a variable for easy (re)definition by ourselves in the future and consuming applications
* Why is this value in single quotes when the font value is in double quotes?

---

*[app/styles/sl-date-picker.less, line 24 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373#-K7vyulkvJ2GA4K15hnv:-K7vyulkvJ2GA4K15hnw:806114716) ([raw file](https://github.com/softlayer/sl-ember-components/blob/3900dec4693e76a4ae30236ae55a18dcd9671c4b/app/styles/sl-date-picker.less#L24)):*
* This value should be defined in a variable for easy (re)definition by ourselves in the future and consuming applications
* Why is this value in single quotes when the font value is in double quotes?

---

*[app/styles/sl-drop-button.less, line 2 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373#-K7vz9Zp8VEOylcavRP5:-K7vz9Zp8VEOylcavRP6:-1071788764) ([raw file](https://github.com/softlayer/sl-ember-components/blob/df446c3e546628c5319925f5b54d1dcc7cde3d9b/app/styles/sl-drop-button.less#L2)):*
This value should be defined in a variable for easy (re)definition by ourselves in the future and consuming applications

---

*[app/styles/sl-grid.less, line 130 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373#-K7vzIP0L_428rz5puxX:-K7vzIP0L_428rz5puxY:1938606494) ([raw file](https://github.com/softlayer/sl-ember-components/blob/df446c3e546628c5319925f5b54d1dcc7cde3d9b/app/styles/sl-grid.less#L130)):*
* This value should be defined in a variable for easy (re)definition by ourselves in the future and consuming applications
* Why is this value in single quotes when others in other files are in double quotes?

---

*[app/styles/sl-menu.less, line 27 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373#-K7vzOozMQ2Kh6jXPf55:-K7vzOozMQ2Kh6jXPf56:-1071788764) ([raw file](https://github.com/softlayer/sl-ember-components/blob/df446c3e546628c5319925f5b54d1dcc7cde3d9b/app/styles/sl-menu.less#L27)):*
This value should be defined in a variable for easy (re)definition by ourselves in the future and consuming applications

---

*[app/styles/sl-modal.less, line 1 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373#-K7vzchDgau-jjduxX3d:-K7vzchDgau-jjduxX3e:1329026497) ([raw file](https://github.com/softlayer/sl-ember-components/blob/df446c3e546628c5319925f5b54d1dcc7cde3d9b/app/styles/sl-modal.less#L1)):*
This should be shared via mixin with alert

---

*[app/styles/sl-modal.less, line 6 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373#-K7vzUlvPTAI7j7Ld3jo:-K7vzUlvPTAI7j7Ld3jp:1938606494) ([raw file](https://github.com/softlayer/sl-ember-components/blob/df446c3e546628c5319925f5b54d1dcc7cde3d9b/app/styles/sl-modal.less#L6)):*
* This value should be defined in a variable for easy (re)definition by ourselves in the future and consuming applications
* Why is this value in single quotes when others in other files are in double quotes?

---

*[app/styles/sl-select.less, line 131 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373#-K7vzpDQhuMOPevHUsND:-K7vzpDQhuMOPevHUsNE:-1130355116) ([raw file](https://github.com/softlayer/sl-ember-components/blob/df446c3e546628c5319925f5b54d1dcc7cde3d9b/app/styles/sl-select.less#L131)):*
vendor prefixes should not be added, as https://github.com/softlayer/sl-ember-components/issues/315 will address their absence

---

*[app/styles/sl-select.less, line 132 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373#-K7vzpisUO-51FjC5YDG:-K7vzpisUO-51FjC5YDH:-1130355116) ([raw file](https://github.com/softlayer/sl-ember-components/blob/df446c3e546628c5319925f5b54d1dcc7cde3d9b/app/styles/sl-select.less#L132)):*
vendor prefixes should not be added, as https://github.com/softlayer/sl-ember-components/issues/315 will address their absence

---

*[tests/integration/components/sl-calendar-test.js, line 68 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373#-K7w-0erbapBg6nfmaTB:-K7w-0esxtmlsWgCd4dE:111458747) ([raw file](https://github.com/softlayer/sl-ember-components/blob/aad057152598512b15372db4af8f8df56c43a013/tests/integration/components/sl-calendar-test.js#L68)):*
Regardless of what was being specifically tested for value-wise the overall need is still the same - ensure that the template is making correct use of the icon class which gives us the accessibility support we are looking for.  Only removing these tests and not replacing with those that assert this is not desired.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373#-:-K7w3LcRwi1P1XDexrVA:-1916912811)*

**Comment by SpikedKira** [comment]
We are currently incorrectly copying Select2 styles into our sl-select.less file.  Since that is currently the case, I have modified the file to have a consistent placement.

In terms of single vs double quotes. There is a small glitch when the font-family is not in double quotes.  The contents can all be single quotes.

---

Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[addon/templates/components/sl-alert.hbs, line 2 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373#-K7vgDPswMsRKcY2dvBl:-K7wADbQHk2ArX2E2sKQ:-545265305) ([raw file](https://github.com/softlayer/sl-ember-components/blob/3900dec4693e76a4ae30236ae55a18dcd9671c4b/addon/templates/components/sl-alert.hbs#L2)):*
good guess >.>

---

*[app/styles/addon.less, line 38 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373#-K7vvBXyYttU1knM_Oub:-K7wAXzYDwXGTz-gE4wg:1498828680) ([raw file](https://github.com/softlayer/sl-ember-components/blob/3900dec4693e76a4ae30236ae55a18dcd9671c4b/app/styles/addon.less#L38)):*
This is a vendor specific, not a vendor prefix... As I understand it, the vendor prefixing adds needed prefixes to a standard css declaration.  This one is non-standard.  There is no "font-smoothing".

---

*[app/styles/addon.less, line 4 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373#-K7w1cfHFtB7MaDTPMXe:-K7wbWXwfd00M9b2CAbi:-581674527) ([raw file](https://github.com/softlayer/sl-ember-components/blob/df446c3e546628c5319925f5b54d1dcc7cde3d9b/app/styles/addon.less#L4)):*
Need to come to consensus on how to move forward on that front.

---

*[app/styles/addon.less, line 39 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373#-K7vzrX0adFjVy6EDu_Q:-K7wAttAVBHbRhGA65pQ:1498828680) ([raw file](https://github.com/softlayer/sl-ember-components/blob/df446c3e546628c5319925f5b54d1dcc7cde3d9b/app/styles/addon.less#L39)):*
This is a vendor specific, not a vendor prefix... As I understand it, the vendor prefixing adds needed prefixes to a standard css declaration.  This one is non-standard.  There is no "font-smoothing".

---

*[app/styles/sl-date-picker.less, line 1 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373#-K7vyg66_CZiJ9qyLuXg:-K7wbfUiyHG_nvq1Eqja:-250484244) ([raw file](https://github.com/softlayer/sl-ember-components/blob/3900dec4693e76a4ae30236ae55a18dcd9671c4b/app/styles/sl-date-picker.less#L1)):*
Nope... it shouldn't even be here (as discussed with Aziz below, in relation to select... same applies here)

---

*[app/styles/sl-select.less, line 131 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373#-K7vzpDQhuMOPevHUsND:-K7wBUzr2IhxqSJvc-1a:1498828680) ([raw file](https://github.com/softlayer/sl-ember-components/blob/df446c3e546628c5319925f5b54d1dcc7cde3d9b/app/styles/sl-select.less#L131)):*
This is a vendor specific, not a vendor prefix... As I understand it, the vendor prefixing adds needed prefixes to a standard css declaration.  This one is non-standard.  There is no "font-smoothing".

---

*[app/styles/sl-select.less, line 132 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373#-K7vzpisUO-51FjC5YDG:-K7wBV_lwKCKY0bC3JJn:1498828680) ([raw file](https://github.com/softlayer/sl-ember-components/blob/df446c3e546628c5319925f5b54d1dcc7cde3d9b/app/styles/sl-select.less#L132)):*
This is a vendor specific, not a vendor prefix... As I understand it, the vendor prefixing adds needed prefixes to a standard css declaration.  This one is non-standard.  There is no "font-smoothing".

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373#-:-K7wYEivzrHcpnpp4Sc-:676812619)*

**Comment by azizpunjani** [comment]
Review status: 6 of 24 files reviewed at latest revision, 7 unresolved discussions.

---

*[app/styles/addon.less, line 4 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373#-K7w1cfHFtB7MaDTPMXe:-K8-JZfujqh62qJHwyXT:1299730258) ([raw file](https://github.com/softlayer/sl-ember-components/blob/df446c3e546628c5319925f5b54d1dcc7cde3d9b/app/styles/addon.less#L4)):*
@notmessenger can you elaborate on this one? Why would the user be using sl-icon-* if they don't want any of our icon styling? It's the same if this were a class `.sl-icon`, if the user uses the class on their element those styles will get applied.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373)*

**Comment by SpikedKira** [comment]
*[app/styles/addon.less, line 4 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373#-K7w1cfHFtB7MaDTPMXe:-K8-cRzHCKvBcOG4LoS6:-563521360) ([raw file](https://github.com/softlayer/sl-ember-components/blob/df446c3e546628c5319925f5b54d1dcc7cde3d9b/app/styles/addon.less#L4)):*
This is in relation to a conversation we had verbally about why I changed it from a single "starts with" selector to the hybrid.  The question was why we could not just use the "contains string" selector against "sl-icon" and the answer to that is we don't to interfere with other styles if the consuming app were to have something like "asl-icon".  So in regards to not interfering, his statement is that we do not currently protect against "sl-icon-x" but we do protect against "xsl-icon-".  Seems like you SHOULD do both or neither.  However, there's not really a good way to do protect the end of the string like there is the beginning.  The outcome is that we do what we can because it has a low cost (a dozen bytes).  Protecting the end of the string would mean literally listing out all of our icon names rather than using a catch-all selector and the cost of that is far greater.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373)*

**Comment by azizpunjani** [comment]
*[app/styles/addon.less, line 4 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373#-K7w1cfHFtB7MaDTPMXe:-K80NmO5jOezgy0ikW9f:-1601739168) ([raw file](https://github.com/softlayer/sl-ember-components/blob/df446c3e546628c5319925f5b54d1dcc7cde3d9b/app/styles/addon.less#L4)):*
I think a starts with selector should suffice? Not sure we need the contains selector unless you can point out a use case.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373)*

**Comment by SpikedKira** [comment]
*[app/styles/addon.less, line 4 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373#-K7w1cfHFtB7MaDTPMXe:-K80ZYkY00OXDGPre_ei:-1875861274) ([raw file](https://github.com/softlayer/sl-ember-components/blob/df446c3e546628c5319925f5b54d1dcc7cde3d9b/app/styles/addon.less#L4)):*
class="warning sl-icon-close"

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373)*

**Comment by azizpunjani** [comment]
*[app/styles/addon.less, line 4 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373#-K7w1cfHFtB7MaDTPMXe:-K84wsw0GsbmwS55SWuM:1611678654) ([raw file](https://github.com/softlayer/sl-ember-components/blob/df446c3e546628c5319925f5b54d1dcc7cde3d9b/app/styles/addon.less#L4)):*
Ah ok.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373)*

**Comment by azizpunjani** [comment]
Reviewed 18 of 18 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373)*

**Comment by notmessenger** [comment]
Reviewed 1 of 2 files at r2, 18 of 18 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[app/styles/addon.less, line 4 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373#-K7w1cfHFtB7MaDTPMXe:-K85D90HkFtiT8ctnQAe:-1123357877) ([raw file](https://github.com/softlayer/sl-ember-components/blob/df446c3e546628c5319925f5b54d1dcc7cde3d9b/app/styles/addon.less#L4)):*
The way to fully address this is to list each specific named occurrence of the class (selectors).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373)*

**Comment by notmessenger** [comment]
Reviewed 12 of 12 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1373)*

**Pull request merged**
