### PR TITLE
Issue 1147

### PR DESCRIPTION
**Pull request by SpikedKira**
[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1185)

### CODE REVIEW

**Comment by SpikedKira** [comment]
closes #1147

**Comment by notmessenger** [comment]
Providing an invalid `theme` value causes the button to appear a dark(er) gray with no hover state (the hover state makes sense - the gray does not)

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1185#-:-K3Lw6_J7GNXcNupSsOr:-1953425345)_

**Comment by SpikedKira** [comment]
Correct, just like button component (which this is using) you will get a warning thrown in the console about invalid theme.


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1185)

**Comment by notmessenger** [comment]
A warning is fine.  Getting a different color than what I thought was the default one is what I am questioning

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1185#-:-K3MKx82zKTrLEdzuaLm:-404151740)_

**Pull request merged**
