### PR TITLE
Can the check for LESS in index.js be handled more succintly?

### PR DESCRIPTION
**Pull request by erangeles**
[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1467)

### CODE REVIEW

**Comment by notmessenger** [comment]
You did not refactor all uses of `isLessAddonInstalled()`

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1467#-:-KA7Q024hY4hD6TmknqF:-294872064)*

**Comment by notmessenger** [comment]
@juwara0 I/we still need to test this hands-on before merging.  Let the other know if have done so.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1467#-:-KA7Q9go3tL9q6y0i-mi:-1997945516)*

**Comment by azizpunjani** [comment]
You might experience an error due to this issue https://github.com/softlayer/sl-ember-components/pull/1478 when trying to run the consuming app. Basically some missing bootstrap variables that are referenced. The newer version of bootstrap has these variables.

**Comment by azizpunjani** [comment]
*[index.js, line 119 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1467#-KABbw7b1Vvci3BeSLSP:-KABbw7b1Vvci3BeSLSQ:1166648995) ([raw file](https://github.com/softlayer/sl-ember-components/blob/0b28b26b0c60f4a7536e7c6ef43b50153b33555a/index.js#L119)):*
Can be shortened down to 

```
if ( !this.isAddon() && !( 'ember-cli-less' in app.registry.availablePlugins ) )
``` 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1467)*

**Comment by azizpunjani** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1467)*

**Comment by juwara0** [comment]
As discussed yesterday, we are going to follow the pattern set by @azizpunjani in: https://github.com/azizpunjani/sl-ember-components/blob/dynamic-component-class-prefix/index.js#L8 and define a variable at the top of the file, set it to a value inside the `included` hook that can be used for the conditionals here: https://github.com/azizpunjani/sl-ember-components/blob/dynamic-component-class-prefix/index.js#L138 and https://github.com/azizpunjani/sl-ember-components/blob/dynamic-component-class-prefix/index.js#L92. 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1467#-:-KAFidCfqpHJ_e_TNbwc:1828386901)*

**Comment by erangeles** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[index.js, line 119 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1467#-KABbw7b1Vvci3BeSLSP:-KAGnwPDNBO-T10vP2ZG:-499146009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/0b28b26b0c60f4a7536e7c6ef43b50153b33555a/index.js#L119)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1467)*

**Comment by juwara0** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1467)*

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1467)*

**Pull request merged**
