### PR TITLE
Sl tab panel tests

### LINKED ISSUE #613: Failing tests
not ok 363 PhantomJS 1.9 - Unit | Component | sl tab panel: setupTabs() does so correctly
    ---
        actual: >
            null
        message: >
            Test timed out
        Log: |
    ...
not ok 364 PhantomJS 1.9 - Unit | Component | sl tab panel: ARIA roles are implemented
    ---
        actual: >
            0
        expected: >
            3
        message: >
            Rendered component has three <a> with "tab" ARIA role
        Log: |
    ...
^@not ok 365 PhantomJS 1.9 - Unit | Component | sl tab panel: "initialTabName" property is respected
    ---
        actual: >
            null
        message: >
            Test timed out
        Log: |
    ...
not ok 367 PhantomJS 1.9 - Unit | Component | sl tab panel: Tabs display in expected order when "alignTabs" property is not specified
    ---
        actual: >

        expected: >
            Max depth.,Max depth.,Max depth.
        Log: |
    ...
^@not ok 368 PhantomJS 1.9 - Unit | Component | sl tab panel: Clicking tab changes active tab
    ---
        actual: >
            null
        message: >
            Test timed out
        Log: |
    ...
not ok 369 PhantomJS 1.9 - Unit | Component | sl tab panel: Tab content height is adjusted after new tab selection
    ---
        actual: >
            null
        message: >
            Test timed out
        Log: |
    ...
^@not ok 370 PhantomJS 1.9 - Unit | Component | sl tab panel: "activatePane" animates as expected
    ---
        actual: >
            null
        message: >
            Test timed out
        Log: |
    ...
^@not ok 371 PhantomJS 1.9 - Unit | Component | sl tab panel: "deactivatePane" animates as expected
    ---
        actual: >
            null
        message: >
            Test timed out
        Log: |
    ...
^@not ok 372 PhantomJS 1.9 - Unit | Component | sl tab panel: "deactivatePane" calls specified callback
    ---
        actual: >
            null
        message: >
            Test timed out
        Log: |
    ...

### PR DESCRIPTION
**Pull request by azizpunjani**
Closed #613

[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/872)

### CODE REVIEW

**Comment by azizpunjani** [comment]
@notmessenger @juwara0 this PR is ready for review.

**Comment by azizpunjani** [comment]
Looks like the test if failing, will look into why one of the test cases is failing in phantom.

**Comment by juwara0** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

<sup>**[tests/integration/components/sl-tab-panel-test.js, line 101 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K-Tp8-22lTF7_tnWTai)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/25844892949c3f2bc7a7adea3318a5d1d32d153e/tests/integration/components/sl-tab-panel-test.js#L101)):</sup>
Replace single quotes for double.  initialTabName="b"


---

<sup>**[tests/integration/components/sl-tab-panel-test.js, line 147 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K-TYZIvWv2wG5l7HKzT)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/25844892949c3f2bc7a7adea3318a5d1d32d153e/tests/integration/components/sl-tab-panel-test.js#L147)):</sup>
Change use of single quotes to double.    alignTabs="right"


---

<sup>**[tests/integration/components/sl-tab-panel-test.js, line 159 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K-Te3m5vt2cUrmA58iT)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/25844892949c3f2bc7a7adea3318a5d1d32d153e/tests/integration/components/sl-tab-panel-test.js#L159)):</sup>
Since using the alignTabs="right" also has the effect of flipping the display order of the tabs, lets add an assert to verify that the tab order is flipped. We have an issue to track fixing the flipping of the tabs:  https://github.com/softlayer/sl-ember-components/issues/17 but lets go ahead and write that extra assert that we can update and reuse once the issue is fixed.


---

<sup>**[tests/integration/components/sl-tab-panel-test.js, line 187 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K-TpcoZdqbizPqwMKC1)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/25844892949c3f2bc7a7adea3318a5d1d32d153e/tests/integration/components/sl-tab-panel-test.js#L187)):</sup>
Do we want to add an assert to verify the content .html() as well?


---

<sup>**[tests/integration/components/sl-tab-panel-test.js, line 220 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K-Tju7SpM8eHEssjn1A)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/25844892949c3f2bc7a7adea3318a5d1d32d153e/tests/integration/components/sl-tab-panel-test.js#L220)):</sup>
So for the .tab-content's height what we want to verify is that the value is getting updated. In my testing, with the demo app, I am seeing that the starting height value is: 142px and as I click the second tab the height value is updated to: 63px, clicking the third tab - height is updated to 55px. So, in this case the test would fail because we are asserting that the current height is greater than the initial height. What I would like to do is watch the height value and see that it is getting updated. 


---

<sup>**[tests/unit/components/sl-tab-panel-test.js, line 25 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K-Ttua3p3Q5oC_CRBbC)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/25844892949c3f2bc7a7adea3318a5d1d32d153e/tests/unit/components/sl-tab-panel-test.js#L25)):</sup>
We need to add a test to validate the change() code pathways


---

<sup>**[tests/unit/components/sl-tab-panel-test.js, line 25 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K-TuBfYgVI6Gcmos99B)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/25844892949c3f2bc7a7adea3318a5d1d32d153e/tests/unit/components/sl-tab-panel-test.js#L25)):</sup>
We need to add a test to validate the setupTabs() code pathways


---

<sup>**[tests/unit/components/sl-tab-panel-test.js, line 25 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K-TuSY-nlEd9zQ0z2cL)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/25844892949c3f2bc7a7adea3318a5d1d32d153e/tests/unit/components/sl-tab-panel-test.js#L25)):</sup>
We need to add a test to validate the activatePane() code pathways


---

<sup>**[tests/unit/components/sl-tab-panel-test.js, line 25 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K-TuZHFPJZrZqUB9vJL)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/25844892949c3f2bc7a7adea3318a5d1d32d153e/tests/unit/components/sl-tab-panel-test.js#L25)):</sup>
We need to add a test to validate the deactivatePane() code pathways


---

<sup>**[tests/unit/components/sl-tab-panel-test.js, line 25 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K-Tuh0ImMhW0QHMnxyl)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/25844892949c3f2bc7a7adea3318a5d1d32d153e/tests/unit/components/sl-tab-panel-test.js#L25)):</sup>
We need to add a test to validate the setActiveTab() code pathways?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872)

**Comment by azizpunjani** [comment]
<sup>**[tests/integration/components/sl-tab-panel-test.js, line 187 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K-TpcoZdqbizPqwMKC1)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/25844892949c3f2bc7a7adea3318a5d1d32d153e/tests/integration/components/sl-tab-panel-test.js#L187)):</sup>
Hmm, not sure a test for that is necessary, because the html is never changed, just an `active` class is applied or removed off the tab and tab-pane.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872)

**Comment by azizpunjani** [comment]
<sup>**[tests/integration/components/sl-tab-panel-test.js, line 220 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K-Tju7SpM8eHEssjn1A)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/25844892949c3f2bc7a7adea3318a5d1d32d153e/tests/integration/components/sl-tab-panel-test.js#L220)):</sup>
In this test we are placing more content in tab B than in tab A or tab C. Hence it's height will *always* be greater than tab A or C. Please look at the template we render. 

```javascript
 {{#sl-tab-panel}}
            {{#sl-tab-pane label="A" name="a"}}A content{{/sl-tab-pane}}
            {{#sl-tab-pane label="B" name="b"}}
                B content<br><br>Taller content
            {{/sl-tab-pane}}
            {{#sl-tab-pane label="C" name="c"}}C content{{/sl-tab-pane}}
        {{/sl-tab-panel}}
```


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872)

**Comment by juwara0** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

<sup>**[tests/integration/components/sl-tab-panel-test.js, line 187 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K-TpcoZdqbizPqwMKC1)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/25844892949c3f2bc7a7adea3318a5d1d32d153e/tests/integration/components/sl-tab-panel-test.js#L187)):</sup>
So what I was thinking was to verify that the content that was set for that template is the one that is displayed.


---

<sup>**[tests/integration/components/sl-tab-panel-test.js, line 220 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K-Tju7SpM8eHEssjn1A)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/25844892949c3f2bc7a7adea3318a5d1d32d153e/tests/integration/components/sl-tab-panel-test.js#L220)):</sup>
That is correct for this test but what we really want to verify is that height is getting updated.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872)

**Comment by azizpunjani** [comment]
<sup>**[tests/integration/components/sl-tab-panel-test.js, line 187 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K-TpcoZdqbizPqwMKC1)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/25844892949c3f2bc7a7adea3318a5d1d32d153e/tests/integration/components/sl-tab-panel-test.js#L187)):</sup>
Can you think of a scenario where the content would not be the same as expected? I mean, we are explicitly selecting a tab-pane, trying to understand why its content would change.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872)

**Comment by azizpunjani** [comment]
<sup>**[tests/integration/components/sl-tab-panel-test.js, line 220 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K-Tju7SpM8eHEssjn1A)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/25844892949c3f2bc7a7adea3318a5d1d32d153e/tests/integration/components/sl-tab-panel-test.js#L220)):</sup>
I feel this test does exactly that. For example what if we have two tab panes with the same content? The height would be the same, so checking if the height is updated will fail in that case. Do you get my point? We have to test against a scenario we know would cause the height to be different.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872)

**Comment by juwara0** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

<sup>**[tests/integration/components/sl-tab-panel-test.js, line 187 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K-TpcoZdqbizPqwMKC1)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/25844892949c3f2bc7a7adea3318a5d1d32d153e/tests/integration/components/sl-tab-panel-test.js#L187)):</sup>
I did not see where we ever verified that the content is what it is set to be in the template.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872)

**Comment by azizpunjani** [comment]
<sup>**[tests/integration/components/sl-tab-panel-test.js, line 187 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K-TpcoZdqbizPqwMKC1)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/25844892949c3f2bc7a7adea3318a5d1d32d153e/tests/integration/components/sl-tab-panel-test.js#L187)):</sup>
Ah, that sounds like a different test. I can add a test in to verify that content is yielded and what we provide is what is rendered as part of the content.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872)

**Comment by juwara0** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

<sup>**[tests/integration/components/sl-tab-panel-test.js, line 220 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K-Tju7SpM8eHEssjn1A)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/25844892949c3f2bc7a7adea3318a5d1d32d153e/tests/integration/components/sl-tab-panel-test.js#L220)):</sup>
Yeah, I follow you. What would be cool is if we could somehow use spy on the height to see if it gets updated. Not sure how to do that though.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872)

**Comment by notmessenger** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

<sup>**[tests/integration/components/sl-tab-panel-test.js, line 220 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K-Tju7SpM8eHEssjn1A)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/25844892949c3f2bc7a7adea3318a5d1d32d153e/tests/integration/components/sl-tab-panel-test.js#L220)):</sup>
In a Unit test.  I'm fine tackling this this way in an integration test but what we are describing wishing we could do and the hoops we are jumping through are all because this is being tested in an integration test and not a unit test.   Maybe what would make us feel better about this assertion is that if it was a not equal comparison rather than a greater than?  Still have the possible scenario of equal height values obviously.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872)

**Comment by azizpunjani** [comment]
<sup>**[tests/unit/components/sl-tab-panel-test.js, line 25 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K-Ttua3p3Q5oC_CRBbC)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/25844892949c3f2bc7a7adea3318a5d1d32d153e/tests/unit/components/sl-tab-panel-test.js#L25)):</sup>
As discussed, this is being tested in the integration test by triggering a tab change.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872)

**Comment by azizpunjani** [comment]
Need to make a few more style changes to this.

**Comment by azizpunjani** [comment]
This is ready for review.


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872)

**Comment by juwara0** [comment]
Reviewed 1 of 3 files at r5, 1 of 1 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

<sup>**[addon/components/sl-tab-panel.js, line 128 \[r7\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K01l9U0kf5xtDMyEVis)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/dfa22895c942eb8e8352636019ae54c140e784d7/addon/components/sl-tab-panel.js#L128)):</sup>
Need to set @params


---

<sup>**[addon/components/sl-tab-panel.js, line 129 \[r7\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K01m0IXF3Eu38lO1Z8C)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/dfa22895c942eb8e8352636019ae54c140e784d7/addon/components/sl-tab-panel.js#L129)):</sup>
Please follow the style guide for documenting types: https://github.com/softlayer/ember-style-guide#general-rules. I am thinking that in this case we should not just use "Array" but instead use @typedef to define what the Array consists of as well.


---

<sup>**[tests/integration/components/sl-tab-panel-test.js, line 101 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K-Tp8-22lTF7_tnWTai)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/25844892949c3f2bc7a7adea3318a5d1d32d153e/tests/integration/components/sl-tab-panel-test.js#L101)):</sup>
RESOLVED


---

<sup>**[tests/integration/components/sl-tab-panel-test.js, line 147 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K-TYZIvWv2wG5l7HKzT)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/25844892949c3f2bc7a7adea3318a5d1d32d153e/tests/integration/components/sl-tab-panel-test.js#L147)):</sup>
RESOLVED


---

<sup>**[tests/integration/components/sl-tab-panel-test.js, line 159 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K-Te3m5vt2cUrmA58iT)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/25844892949c3f2bc7a7adea3318a5d1d32d153e/tests/integration/components/sl-tab-panel-test.js#L159)):</sup>
RESOLVED


---

<sup>**[tests/integration/components/sl-tab-panel-test.js, line 187 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K-TpcoZdqbizPqwMKC1)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/25844892949c3f2bc7a7adea3318a5d1d32d153e/tests/integration/components/sl-tab-panel-test.js#L187)):</sup>
If there is not a test for this in the sl-tab-pane, please open an issue to create one.


---

<sup>**[tests/integration/components/sl-tab-panel-test.js, line 220 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K-Tju7SpM8eHEssjn1A)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/25844892949c3f2bc7a7adea3318a5d1d32d153e/tests/integration/components/sl-tab-panel-test.js#L220)):</sup>
RESOLVED


---

<sup>**[tests/unit/components/sl-tab-panel-test.js, line 25 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K-Ttua3p3Q5oC_CRBbC)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/25844892949c3f2bc7a7adea3318a5d1d32d153e/tests/unit/components/sl-tab-panel-test.js#L25)):</sup>
RESOLVED


---

<sup>**[tests/unit/components/sl-tab-panel-test.js, line 25 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K-TuBfYgVI6Gcmos99B)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/25844892949c3f2bc7a7adea3318a5d1d32d153e/tests/unit/components/sl-tab-panel-test.js#L25)):</sup>
RESOLVED


---

<sup>**[tests/unit/components/sl-tab-panel-test.js, line 25 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K-TuSY-nlEd9zQ0z2cL)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/25844892949c3f2bc7a7adea3318a5d1d32d153e/tests/unit/components/sl-tab-panel-test.js#L25)):</sup>
RESOLVED


---

<sup>**[tests/unit/components/sl-tab-panel-test.js, line 25 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K-TuZHFPJZrZqUB9vJL)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/25844892949c3f2bc7a7adea3318a5d1d32d153e/tests/unit/components/sl-tab-panel-test.js#L25)):</sup>
RESOLVED


---

<sup>**[tests/unit/components/sl-tab-panel-test.js, line 25 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K-Tuh0ImMhW0QHMnxyl)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/25844892949c3f2bc7a7adea3318a5d1d32d153e/tests/unit/components/sl-tab-panel-test.js#L25)):</sup>
RESOLVED


---

<sup>**[tests/unit/components/sl-tab-panel-test.js, line 150 \[r7\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K-yxctZXhbzDSmG2F7u)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/dfa22895c942eb8e8352636019ae54c140e784d7/tests/unit/components/sl-tab-panel-test.js#L150)):</sup>
Please change this to assert.notOk() 


---

<sup>**[tests/unit/components/sl-tab-panel-test.js, line 162 \[r7\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K-yxaVY9B4iSfzizWch)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/dfa22895c942eb8e8352636019ae54c140e784d7/tests/unit/components/sl-tab-panel-test.js#L162)):</sup>
Please change this to assert.notOk() 


---

<sup>**[tests/unit/components/sl-tab-panel-test.js, line 267 \[r7\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K-yxDI5EFPSIFaUxPMo)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/dfa22895c942eb8e8352636019ae54c140e784d7/tests/unit/components/sl-tab-panel-test.js#L267)):</sup>
Please change this to assert.notOk() 


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872)

**Comment by azizpunjani** [comment]
<sup>**[tests/integration/components/sl-tab-panel-test.js, line 187 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K-TpcoZdqbizPqwMKC1)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/25844892949c3f2bc7a7adea3318a5d1d32d153e/tests/integration/components/sl-tab-panel-test.js#L187)):</sup>
Opened an issue https://github.com/softlayer/sl-ember-components/issues/909


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872)

**Comment by azizpunjani** [comment]
PR is ready for review.


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872)

**Comment by juwara0** [comment]
Reviewed 2 of 2 files at r8.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[addon/components/sl-tab-panel.js, line 128 \[r7\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K01l9U0kf5xtDMyEVis)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/dfa22895c942eb8e8352636019ae54c140e784d7/addon/components/sl-tab-panel.js#L128)):</sup>
RESOLVED


---

<sup>**[addon/components/sl-tab-panel.js, line 129 \[r7\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K01m0IXF3Eu38lO1Z8C)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/dfa22895c942eb8e8352636019ae54c140e784d7/addon/components/sl-tab-panel.js#L129)):</sup>
RESOLVED


---

<sup>**[tests/unit/components/sl-tab-panel-test.js, line 150 \[r7\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K-yxctZXhbzDSmG2F7u)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/dfa22895c942eb8e8352636019ae54c140e784d7/tests/unit/components/sl-tab-panel-test.js#L150)):</sup>
RESOLVED


---

<sup>**[tests/unit/components/sl-tab-panel-test.js, line 162 \[r7\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K-yxaVY9B4iSfzizWch)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/dfa22895c942eb8e8352636019ae54c140e784d7/tests/unit/components/sl-tab-panel-test.js#L162)):</sup>
RESOLVED


---

<sup>**[tests/unit/components/sl-tab-panel-test.js, line 267 \[r7\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K-yxDI5EFPSIFaUxPMo)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/dfa22895c942eb8e8352636019ae54c140e784d7/tests/unit/components/sl-tab-panel-test.js#L267)):</sup>
RESOLVED


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872)

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r6, 1 of 2 files at r8.
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

<sup>**[addon/components/sl-tab-panel.js, line 128 \[r8\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K02quYtWE2PTp7SGHX9)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/36550b462c0c3e822de981f74dfb5facc3b395e9/addon/components/sl-tab-panel.js#L128)):</sup>
Not a `Boolean`?


---

<sup>**[addon/components/sl-tab-panel.js, line 136 \[r8\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K02qhU09nIANCcG9opp)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/36550b462c0c3e822de981f74dfb5facc3b395e9/addon/components/sl-tab-panel.js#L136)):</sup>
Place after `@function` line


---

<sup>**[addon/components/sl-tab-panel.js, line 140 \[r8\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K02dytcnnlqDcwE5Pn1)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/36550b462c0c3e822de981f74dfb5facc3b395e9/addon/components/sl-tab-panel.js#L140)):</sup>
If I am calling `getTabs()` I would expect to get back a list of tabs (which I do).  These tabs are also telling me some stuff about themselves, which includes their active state.  From a (conceptual) architecture perspective this value could just as easily be coming from the object itself as it is from database data or other.  The point is - this is a property of the tab.  Having to pass into `getTabs()` the current active tab so that  it can then tell me whether the tab is the active one or not does not seem like a good design to me, especially when the value that is passed is is retrieved via a call to `this.getInitialTabName()`.  Seems `getTabs()` should be making the call to  `this.getInitialTabName()` if it cares about the data and not accept any parameters.


---

<sup>**[addon/components/sl-tab-panel.js, line 140 \[r8\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K02k_pyJN0t3vjvfOQ3)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/36550b462c0c3e822de981f74dfb5facc3b395e9/addon/components/sl-tab-panel.js#L140)):</sup>
This method is in the wrong section of the document


---

<sup>**[addon/components/sl-tab-panel.js, line 163 \[r8\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K02kcTis9Js7PofYvVq)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/36550b462c0c3e822de981f74dfb5facc3b395e9/addon/components/sl-tab-panel.js#L163)):</sup>
This method is in the wrong section of the document


---

<sup>**[addon/components/sl-tab-panel.js, line 166 \[r8\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K02ifyW8zeZSnMgX7tn)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/36550b462c0c3e822de981f74dfb5facc3b395e9/addon/components/sl-tab-panel.js#L166)):</sup>
Replace the logic of this method with

```
    let tabName = this.get( 'initialTabName' );

    if ( Ember.isEmpty( tabName ) ) {
        tabName = this.$( '.tab-pane:first' ).attr( 'data-tab-name' );
    }

    return tabName;
```


---

<sup>**[tests/unit/components/sl-tab-panel-test.js, line 69 \[r8\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K06cgbY0CeL1xd0FbIp)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/36550b462c0c3e822de981f74dfb5facc3b395e9/tests/unit/components/sl-tab-panel-test.js#L69)):</sup>
Follow style guide - https://github.com/softlayer/ember-style-guide/blob/master/ember-testing.md#example-testing-dependent-keys


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872)

**Comment by azizpunjani** [comment]
<sup>**[addon/components/sl-tab-panel.js, line 140 \[r8\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K02dytcnnlqDcwE5Pn1)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/36550b462c0c3e822de981f74dfb5facc3b395e9/addon/components/sl-tab-panel.js#L140)):</sup>
I agree. Initially I thought I would inject any data it needs but that does not work out in this particular case.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872)

**Comment by notmessenger** [comment]
Reviewed 1 of 2 files at r9.
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[addon/components/sl-tab-panel.js, line 128 \[r9\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K0R7Ajr67h55mPAxILk)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/c89cc081696b322d85a39ae2545c4f1fd8553e5e/addon/components/sl-tab-panel.js#L128)):</sup>
The indented spacing of this DocBlock is incorrect


---

<sup>**[addon/components/sl-tab-panel.js, line 140 \[r9\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K0R7PN5q-CnPmYnNo5w)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/c89cc081696b322d85a39ae2545c4f1fd8553e5e/addon/components/sl-tab-panel.js#L140)):</sup>
This is no longer necessary


---

<sup>**[addon/components/sl-tab-panel.js, line 183 \[r9\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872#-K0R7F_RcJlZtfgUNN5w)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/c89cc081696b322d85a39ae2545c4f1fd8553e5e/addon/components/sl-tab-panel.js#L183)):</sup>
This method is in the incorrect section


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872)

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r10.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/872)

**Pull request merged**
