### PR TITLE
Closes softlayer/sl-ember-components#987

### PR DESCRIPTION
**Pull request by SpikedKira**
[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1020)

### CODE REVIEW

**Comment by SpikedKira** [comment]
this might be related to #980

**Comment by notmessenger** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 32 unresolved discussions, some commit checks failed.

---

<sup>**[tests/integration/components/sl-alert-test.js, line 32 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1020#-K1dXqRaEiEJJa23DEBd)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/f4576dea28c5db4e1d29ec8bf6c3f4648c90f855/tests/integration/components/sl-alert-test.js#L32)):</sup>
This assertion should be removed per https://github.com/softlayer/sl-ember-components/issues/980 and https://github.com/softlayer/ember-style-guide/issues/67


---

<sup>**[tests/integration/components/sl-button-test.js, line 33 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1020#-K1dYHjFfb3IQGHnC9eY)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/6cfb45951f204a5dcc0c6d99031b4136afc66b44/tests/integration/components/sl-button-test.js#L33)):</sup>
Move this test case to be the first one in the test suite.


---

<sup>**[tests/integration/components/sl-button-test.js, line 36 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1020#-K1dYMS1biNAkSYWGr90)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/6cfb45951f204a5dcc0c6d99031b4136afc66b44/tests/integration/components/sl-button-test.js#L36)):</sup>
Invalid const name per style guide


---

<sup>**[tests/integration/components/sl-button-test.js, line 55 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1020#-K1dZjQavkp5IzgKZpgT)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/6cfb45951f204a5dcc0c6d99031b4136afc66b44/tests/integration/components/sl-button-test.js#L55)):</sup>
This assertion should be removed per https://github.com/softlayer/sl-ember-components/issues/980 and https://github.com/softlayer/ember-style-guide/issues/67


---

<sup>**[tests/integration/components/sl-button-test.js, line 60 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1020#-K1dZkgQcTEzsYotsjML)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/6cfb45951f204a5dcc0c6d99031b4136afc66b44/tests/integration/components/sl-button-test.js#L60)):</sup>
This assertion should be removed per https://github.com/softlayer/sl-ember-components/issues/980 and https://github.com/softlayer/ember-style-guide/issues/67


---

<sup>**[tests/integration/components/sl-date-range-picker-test.js, line 21 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1020#-K1d_Zsp1RcGJcfRn90P)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/6cfb45951f204a5dcc0c6d99031b4136afc66b44/tests/integration/components/sl-date-range-picker-test.js#L21)):</sup>
This assertion should be removed per https://github.com/softlayer/sl-ember-components/issues/980 and https://github.com/softlayer/ember-style-guide/issues/67


---

<sup>**[tests/integration/components/sl-date-range-picker-test.js, line 33 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1020#-K1d_a56Wo5LzUOXvnkH)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/6cfb45951f204a5dcc0c6d99031b4136afc66b44/tests/integration/components/sl-date-range-picker-test.js#L33)):</sup>
This assertion should be removed per https://github.com/softlayer/sl-ember-components/issues/980 and https://github.com/softlayer/ember-style-guide/issues/67


---

<sup>**[tests/integration/components/sl-drop-option-test.js, line 18 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1020#-K1daXHvo-NGkQId_D7K)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/6cfb45951f204a5dcc0c6d99031b4136afc66b44/tests/integration/components/sl-drop-option-test.js#L18)):</sup>
This assertion should be removed per https://github.com/softlayer/ember-style-guide/blob/master/ember-testing.md#component-unit-tests


---

<sup>**[tests/integration/components/sl-drop-option-test.js, line 24 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1020#-K1d_mZfeiN2I-Mskcru)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/6cfb45951f204a5dcc0c6d99031b4136afc66b44/tests/integration/components/sl-drop-option-test.js#L24)):</sup>
This test case should be rolled into the "Default rendered state" one


---

<sup>**[tests/integration/components/sl-modal-footer-test.js, line 14 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1020#-K1dapnpKqLs4qj6cUan)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/6cfb45951f204a5dcc0c6d99031b4136afc66b44/tests/integration/components/sl-modal-footer-test.js#L14)):</sup>
Follow https://github.com/softlayer/ember-style-guide/issues/66


---

<sup>**[tests/integration/components/sl-modal-header-test.js, line 14 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1020#-K1dazTy0xU3uQLLNDNR)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/6cfb45951f204a5dcc0c6d99031b4136afc66b44/tests/integration/components/sl-modal-header-test.js#L14)):</sup>
Follow https://github.com/softlayer/ember-style-guide/issues/66


---

<sup>**[tests/integration/components/sl-modal-header-test.js, line 35 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1020#-K1dcQA27-7SXXhbp_HN)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/6cfb45951f204a5dcc0c6d99031b4136afc66b44/tests/integration/components/sl-modal-header-test.js#L35)):</sup>
Rename this test case


---

<sup>**[tests/integration/components/sl-modal-header-test.js, line 48 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1020#-K1dcOm1emEiJPRcgOhq)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/6cfb45951f204a5dcc0c6d99031b4136afc66b44/tests/integration/components/sl-modal-header-test.js#L48)):</sup>
Remove this call.


---

<sup>**[tests/integration/components/sl-modal-header-test.js, line 52 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1020#-K1dcHVa-0gDm4DI8LZD)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/6cfb45951f204a5dcc0c6d99031b4136afc66b44/tests/integration/components/sl-modal-header-test.js#L52)):</sup>
Move this assertion to to the "Default rendered state" test suite


---

<sup>**[tests/integration/components/sl-modal-test.js, line 61 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1020#-K1dflHAPWnKH4astqTT)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/6cfb45951f204a5dcc0c6d99031b4136afc66b44/tests/integration/components/sl-modal-test.js#L61)):</sup>
The template used for this test case should be the bare minimum of provided values.  Passing `ariaLabelledBy`, for example, should not be done.


---

<sup>**[tests/integration/components/sl-modal-test.js, line 235 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1020#-K1de9SMH_P8Pzrmyobq)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/6cfb45951f204a5dcc0c6d99031b4136afc66b44/tests/integration/components/sl-modal-test.js#L235)):</sup>
This test case needs to be rolled into "Default rendered state one


---

<sup>**[tests/integration/components/sl-modal-test.js, line 248 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1020#-K1deMdM0VAqpvgBeak4)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/6cfb45951f204a5dcc0c6d99031b4136afc66b44/tests/integration/components/sl-modal-test.js#L248)):</sup>
Combine this test case with the one below and use this.set() calls for the animated property.


---

<sup>**[tests/integration/components/sl-modal-test.js, line 313 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1020#-K1dfxtGMpNc5Y1v_3eB)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/6cfb45951f204a5dcc0c6d99031b4136afc66b44/tests/integration/components/sl-modal-test.js#L313)):</sup>
Rename this test case to more accurately reflect what property presence causes `aria-hidden` to be true.


---

<sup>**[tests/integration/components/sl-panel-test.js, line 29 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1020#-K1dgZJ8hFNTvkh9uXmq)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/6cfb45951f204a5dcc0c6d99031b4136afc66b44/tests/integration/components/sl-panel-test.js#L29)):</sup>
https://github.com/softlayer/ember-style-guide/issues/66


---

<sup>**[tests/integration/components/sl-panel-test.js, line 34 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1020#-K1dgZjZrvA0_rqdrebP)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/6cfb45951f204a5dcc0c6d99031b4136afc66b44/tests/integration/components/sl-panel-test.js#L34)):</sup>
https://github.com/softlayer/ember-style-guide/issues/66


---

<sup>**[tests/integration/components/sl-panel-test.js, line 39 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1020#-K1dg_7cJTlOdMSptXFQ)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/6cfb45951f204a5dcc0c6d99031b4136afc66b44/tests/integration/components/sl-panel-test.js#L39)):</sup>
https://github.com/softlayer/ember-style-guide/issues/66


---

<sup>**[tests/integration/components/sl-panel-test.js, line 44 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1020#-K1dge3nWYBznLEJbMDv)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/6cfb45951f204a5dcc0c6d99031b4136afc66b44/tests/integration/components/sl-panel-test.js#L44)):</sup>
Merge this test case into "Default rendered state" one


---

<sup>**[tests/integration/components/sl-panel-test.js, line 71 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1020#-K1dgoSLiT53k2xBYm3w)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/6cfb45951f204a5dcc0c6d99031b4136afc66b44/tests/integration/components/sl-panel-test.js#L71)):</sup>
This render can be removed


---

<sup>**[tests/integration/components/sl-panel-test.js, line 75 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1020#-K1dgmw1pvdywSh_D8SY)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/6cfb45951f204a5dcc0c6d99031b4136afc66b44/tests/integration/components/sl-panel-test.js#L75)):</sup>
This assertion can be removed


---

<sup>**[tests/integration/components/sl-panel-test.js, line 86 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1020#-K1dgxcu3lhv63kWl4id)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/6cfb45951f204a5dcc0c6d99031b4136afc66b44/tests/integration/components/sl-panel-test.js#L86)):</sup>
Do we want to use `hasClass()` here?  If not, do we want to create a single reference to `this.$( '>:first-child' ).find( '.panel-heading' )` to be used in both assertions?


---

<sup>**[tests/integration/components/sl-panel-test.js, line 99 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1020#-K1dhAElrA7ZOlry8hGd)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/6cfb45951f204a5dcc0c6d99031b4136afc66b44/tests/integration/components/sl-panel-test.js#L99)):</sup>
Remove this call


---

<sup>**[tests/integration/components/sl-panel-test.js, line 103 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1020#-K1dh92CsS06MVilGocH)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/6cfb45951f204a5dcc0c6d99031b4136afc66b44/tests/integration/components/sl-panel-test.js#L103)):</sup>
Remove this assertion


---

<sup>**[tests/integration/components/sl-panel-test.js, line 127 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1020#-K1dhJv7eiLk8LnbWzvL)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/6cfb45951f204a5dcc0c6d99031b4136afc66b44/tests/integration/components/sl-panel-test.js#L127)):</sup>
Use `hasClass()`?


---

<sup>**[tests/integration/components/sl-tab-panel-test.js, line 84 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1020#-K1dhshkTRGePZ0Bxo0r)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/6cfb45951f204a5dcc0c6d99031b4136afc66b44/tests/integration/components/sl-tab-panel-test.js#L84)):</sup>
Merge this test case with the "Default rendered state" one


---

<sup>**[tests/integration/components/sl-tab-panel-test.js, line 134 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1020#-K1dhiQpJLItJLx1trfN)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/6cfb45951f204a5dcc0c6d99031b4136afc66b44/tests/integration/components/sl-tab-panel-test.js#L134)):</sup>
Merge this test case with the "Default rendered state" one


---

<sup>**[tests/integration/components/sl-textarea-test.js, line 262 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1020#-K1djkB-779FLQKczoOo)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/6cfb45951f204a5dcc0c6d99031b4136afc66b44/tests/integration/components/sl-textarea-test.js#L262)):</sup>
Remove this test case


---

<sup>**[tests/integration/components/sl-textarea-test.js, line 403 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1020#-K1djvYk3vo309GbI-9_)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/6cfb45951f204a5dcc0c6d99031b4136afc66b44/tests/integration/components/sl-textarea-test.js#L403)):</sup>
Move this assertion to the "Default rendered state" test case


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1020)

**Comment by SpikedKira** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

<sup>**[tests/integration/components/sl-panel-test.js, line 44 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1020#-K1dge3nWYBznLEJbMDv)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/6cfb45951f204a5dcc0c6d99031b4136afc66b44/tests/integration/components/sl-panel-test.js#L44)):</sup>
no need; corrections to the default test make this one obsolete, as they test the same thing inherently


---

<sup>**[tests/integration/components/sl-panel-test.js, line 86 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1020#-K1dgxcu3lhv63kWl4id)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/6cfb45951f204a5dcc0c6d99031b4136afc66b44/tests/integration/components/sl-panel-test.js#L86)):</sup>
Can't since this is a child node.  We would have no reliable way of finding it.


---

<sup>**[tests/integration/components/sl-panel-test.js, line 127 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1020#-K1dhJv7eiLk8LnbWzvL)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/6cfb45951f204a5dcc0c6d99031b4136afc66b44/tests/integration/components/sl-panel-test.js#L127)):</sup>
can't


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1020)

**Comment by notmessenger** [comment]
Reviewed 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

<sup>**[tests/integration/components/sl-date-range-picker-test.js, line 33 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1020#-K1f0SASjU3tANCFnPxC)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/6cfb45951f204a5dcc0c6d99031b4136afc66b44/tests/integration/components/sl-date-range-picker-test.js#L33)):</sup>
A test case for this needs to be added to the test suite.


---

<sup>**[tests/integration/components/sl-date-range-picker-test.js, line 315 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1020#-K1f0IsmJSd1aRYgskVi)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/6cfb45951f204a5dcc0c6d99031b4136afc66b44/tests/integration/components/sl-date-range-picker-test.js#L315)):</sup>
Remove this test and associated comment


---

<sup>**[tests/integration/components/sl-date-range-picker-test.js, line 10 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1020#-K1f-rlOiIOOTD46DcgY)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/e387a95b7268368916a483195145bff78ea50ec0/tests/integration/components/sl-date-range-picker-test.js#L10)):</sup>
There should be an assertion that there are to instances of sl-date-picker components with the correct classes on them


---

<sup>**[tests/integration/components/sl-date-range-picker-test.js, line 22 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1020#-K1f-q1-Wn-TkNJ5RCd9)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/e387a95b7268368916a483195145bff78ea50ec0/tests/integration/components/sl-date-range-picker-test.js#L22)):</sup>
Remove this assertion.

A test case for this needs to be added to the test suite.


---

<sup>**[tests/integration/components/sl-panel-test.js, line 29 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1020#-K1f18ZkjePfsLmzmxHi)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/e387a95b7268368916a483195145bff78ea50ec0/tests/integration/components/sl-panel-test.js#L29)):</sup>
Replace with `panelBody.length`, after moving definition of `panelBody` before this assertion


---

<sup>**[tests/integration/components/sl-tab-panel-test.js, line 53 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1020#-K1f2CbrOE0tRI5W_ttD)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/e387a95b7268368916a483195145bff78ea50ec0/tests/integration/components/sl-tab-panel-test.js#L53)):</sup>
Replace with "Tabs display in expected order"


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1020)

**Comment by notmessenger** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1020)

**Comment by notmessenger** [comment]
There are merge conflicts


---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1020)

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1020)

**Pull request merged**
