### PR TITLE
Closes softlayer/sl-ember-components#1125 first run of base bootstrap…

### PR DESCRIPTION
**Pull request by SpikedKira**
… support for the grid.  Most of this should be replaced by something better later on.  It is not perfect, but it's decent.  Also added type=button to the close button of details pane.

[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1154)

### CODE REVIEW

**Comment by SpikedKira** [comment]
I have addressed the column header alignment, sort icons, and overall grid height.  You may still see column header mis-alignment after window resize.  I have opened issue #1182 and talked to Aziz about implementing his mixin for this as it is on branch 13.


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1154)

**Comment by notmessenger** [comment]
I'm still seeing column header mis-alignment on initial load, without any window resize.

Do we want to use the *glyphicon-sort-by-alphabet* (and related) instead of just up/down arrows?

---

Reviewed 6 of 7 files at r3.
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[tests/unit/components/sl-grid-column-header-test.js, line 81 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1154#-K3L0o1bnAboryGE3yT2:-K3L0o1bnAboryGE3yT3:1003177455) ([raw file](https://github.com/softlayer/sl-ember-components/blob/ad955cc424e4f3d8a10943ce7d857aa545892c91/tests/unit/components/sl-grid-column-header-test.js#L81)):_
We don't need/want to assert this is some manner?

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1154#-:-K3L0VNCIOlD3Qp9Ld3n:-972921993)_

**Comment by SpikedKira** [comment]
The halfling glyphs for specific sorts are sort of weird.  Take a look at them.  If you want to use them, let's discuss how to figure that out.  The column header mis-alignment is going to be due to you having scrollbars turned off and I'm uncertain there is a fix for that with this iteration.


---

Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[tests/unit/components/sl-grid-column-header-test.js, line 81 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1154#-K3L0o1bnAboryGE3yT2)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/ad955cc424e4f3d8a10943ce7d857aa545892c91/tests/unit/components/sl-grid-column-header-test.js#L81)):</sup>
assert what?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1154)

**Comment by SpikedKira** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[tests/unit/components/sl-grid-column-header-test.js, line 81 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1154#-K3L0o1bnAboryGE3yT2)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/ad955cc424e4f3d8a10943ce7d857aa545892c91/tests/unit/components/sl-grid-column-header-test.js#L81)):</sup>
So, the asserts for all three classes are here.  What the CSS does with it, from a purely visual point of view, should be tested another way.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1154)

**Comment by notmessenger** [comment]
Reviewed 1 of 7 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1154)_

**Pull request merged**
