### PR TITLE
Closes softlayer/sl-ember-components#903

### PR DESCRIPTION
**Pull request by SpikedKira**
the 3rd test from issue outline was dropped due to how bootstrap modal actually functions vs how it was perceived to function at time of issue creation :)

[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/908)

### CODE REVIEW

**Comment by azizpunjani** [comment]
Test is failing https://travis-ci.org/softlayer/sl-ember-components/jobs/83973311#L851

**Comment by azizpunjani** [comment]
<sup>**[tests/integration/components/sl-modal-test.js, line 224 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/908#-K01LoQ-7C3bIp8s3Um_)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/5eadb2c8d98afd9b77ca3fda3aebdb299ade047e/tests/integration/components/sl-modal-test.js#L224)):</sup>
As discussed, hook into `afterShow` action as an alternative to `setTimeout`.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/908)

**Comment by azizpunjani** [comment]
<sup>**[tests/integration/components/sl-modal-test.js, line 251 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/908#-K01M9uUS6m_53iNlVMW)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/5eadb2c8d98afd9b77ca3fda3aebdb299ade047e/tests/integration/components/sl-modal-test.js#L251)):</sup>
As discussed, hook into `afterShow` action as an alternative to `setTimeout`.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/908)

**Comment by SpikedKira** [comment]
closing PR as this was kind of the wrong route to take.
Reworking file to close multiple issues and will create new PR.

**Pull request closed without merging**
