### PR TITLE
Closes softlayer/sl-ember-components#1320

### PR DESCRIPTION
**Pull request by SpikedKira**
[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1461)

### CODE REVIEW

**Comment by notmessenger** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[addon/templates/components/sl-pagination.hbs, line 2 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1461#-K9nkgTrMdGIUBvR7TZ1:-K9nkgTrMdGIUBvR7TZ2:-1718193940) ([raw file](https://github.com/softlayer/sl-ember-components/blob/e0b8ed60ce76eb36d0965b72914565f5bde1192b/addon/templates/components/sl-pagination.hbs#L2)):*
Shouldn't this employ `bubbles="false"`? https://guides.emberjs.com/v1.10.0/templates/actions/#toc_stopping-event-propagation

---

*[addon/templates/components/sl-pagination.hbs, line 14 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1461#-K9nkmDrcjWfJtnYIsHR:-K9nkmDrcjWfJtnYIsHS:-1718193940) ([raw file](https://github.com/softlayer/sl-ember-components/blob/e0b8ed60ce76eb36d0965b72914565f5bde1192b/addon/templates/components/sl-pagination.hbs#L14)):*
Shouldn't this employ `bubbles="false"`? https://guides.emberjs.com/v1.10.0/templates/actions/#toc_stopping-event-propagation

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1461)*

**Comment by juwara0** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1461)*

**Comment by SpikedKira** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[addon/templates/components/sl-pagination.hbs, line 2 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1461#-K9nkgTrMdGIUBvR7TZ1:-KA1Smb0JzvAXYleKs0W:-14271777) ([raw file](https://github.com/softlayer/sl-ember-components/blob/e0b8ed60ce76eb36d0965b72914565f5bde1192b/addon/templates/components/sl-pagination.hbs#L2)):*
I don't think so.  Ember seems to handle the href="#" properly.

Unless there is something I am unaware of in terms of routing events being fired when no route was handled or something along those lines.  I am fairly sure that this is okay as is.

---

*[addon/templates/components/sl-pagination.hbs, line 14 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1461#-K9nkmDrcjWfJtnYIsHR:-KA1SsUAO8vvie7Z_vJC:1672360058) ([raw file](https://github.com/softlayer/sl-ember-components/blob/e0b8ed60ce76eb36d0965b72914565f5bde1192b/addon/templates/components/sl-pagination.hbs#L14)):*
I don't think so.  Ember seems to handle the href="#" properly.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1461)*

**Comment by SpikedKira** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[addon/templates/components/sl-pagination.hbs, line 2 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1461#-K9nkgTrMdGIUBvR7TZ1:-KA1bv_Xti8BaVE0JGSL:-2071175486) ([raw file](https://github.com/softlayer/sl-ember-components/blob/e0b8ed60ce76eb36d0965b72914565f5bde1192b/addon/templates/components/sl-pagination.hbs#L2)):*
I guess the question becomes, do we want to explicitly prevent parent components from knowing that an action named "previousPage" was called?  If not, I would say we might want to change our action names; example: "sl-pagination-previous-page".

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1461)*

**Comment by azizpunjani** [comment]
*[addon/templates/components/sl-pagination.hbs, line 2 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1461#-K9nkgTrMdGIUBvR7TZ1:-KA1bYnYnoeWG16RLmXq:566063447) ([raw file](https://github.com/softlayer/sl-ember-components/blob/e0b8ed60ce76eb36d0965b72914565f5bde1192b/addon/templates/components/sl-pagination.hbs#L2)):*
The `action` helper implicitly prevents the default action. We would only need `bubble=false` if we didn't want the click to propagate up the DOM tree, which is not an issue in this case.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1461)*

**Comment by azizpunjani** [comment]
*[addon/templates/components/sl-pagination.hbs, line 14 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1461#-K9nkmDrcjWfJtnYIsHR:-KA1cMkCe_8qBKfp8GKi:566063447) ([raw file](https://github.com/softlayer/sl-ember-components/blob/e0b8ed60ce76eb36d0965b72914565f5bde1192b/addon/templates/components/sl-pagination.hbs#L14)):*
The `action` helper implicitly prevents the default action. We would only need `bubble=false` if we didn't want the click to propagate up the DOM tree, which is not an issue in this case.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1461)*

**Comment by SpikedKira** [comment]
*[addon/templates/components/sl-pagination.hbs, line 2 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1461#-K9nkgTrMdGIUBvR7TZ1:-KA1kxMVQxUuCpAS5SMP:-997612581) ([raw file](https://github.com/softlayer/sl-ember-components/blob/e0b8ed60ce76eb36d0965b72914565f5bde1192b/addon/templates/components/sl-pagination.hbs#L2)):*
I retract last statement as it was based on confusion.  First statement stands.

The bubble=false would prevent the dom event from firing.  This is separate from the ACTION being fired.  Using the bubble=false would prevent jquery added live bindings at the application level among other things.  It is obtrusive and should only be used when absolutely needed to prevent a known event from firing.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1461)*

**Comment by notmessenger** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[addon/templates/components/sl-pagination.hbs, line 2 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1461#-K9nkgTrMdGIUBvR7TZ1:-KA7RhHDxsirRa6aIk3y:993434524) ([raw file](https://github.com/softlayer/sl-ember-components/blob/e0b8ed60ce76eb36d0965b72914565f5bde1192b/addon/templates/components/sl-pagination.hbs#L2)):*
The text in the https://guides.emberjs.com/v1.13.0/templates/actions/#toc_default-event section and the first sentence of the https://guides.emberjs.com/v1.13.0/templates/actions/#toc_stopping-event-propagation section seem to be in contradiction to each other.  *However* since we will soon be moving to Ember v2.3.x+ which make this a moot point - https://guides.emberjs.com/v2.3.0/templates/actions/#toc_allowing-default-browser-action - we can shelve this conversation.

---

*[addon/templates/components/sl-pagination.hbs, line 14 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1461#-K9nkmDrcjWfJtnYIsHR:-KA7R2MSWhyrcg6ynklA:993434524) ([raw file](https://github.com/softlayer/sl-ember-components/blob/e0b8ed60ce76eb36d0965b72914565f5bde1192b/addon/templates/components/sl-pagination.hbs#L14)):*
The text in the https://guides.emberjs.com/v1.13.0/templates/actions/#toc_default-event section and the first sentence of the https://guides.emberjs.com/v1.13.0/templates/actions/#toc_stopping-event-propagation section seem to be in contradiction to each other.  *However* since we will soon be moving to Ember v2.3.x+ which make this a moot point - https://guides.emberjs.com/v2.3.0/templates/actions/#toc_allowing-default-browser-action - we can shelve this conversation.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1461)*

**Comment by azizpunjani** [comment]
*[addon/templates/components/sl-pagination.hbs, line 2 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1461#-K9nkgTrMdGIUBvR7TZ1:-KA8GayA1HhWkcbB2vfy:-1183636538) ([raw file](https://github.com/softlayer/sl-ember-components/blob/e0b8ed60ce76eb36d0965b72914565f5bde1192b/addon/templates/components/sl-pagination.hbs#L2)):*
Actually, they are not contradictory. `event.preventDefault` will prevent the default action  e.g in the case of a link, preventing the default action will prevent navigating to the href of the link. `bubbles=false` will prevent the event from propagating up the DOM tree to the parent nodes, which is different from preventing the default behavior. `bubbles` should still work in Ember 2.3+ https://github.com/emberjs/ember.js/blob/90d51dc9b07226264b4792e22d92aea48d0ead2c/packages/ember-routing-htmlbars/lib/keywords/element-action.js#L87-L93

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1461)*

**Pull request merged**
