### PR TITLE
Create Unit test suite

### PR DESCRIPTION
**Pull request by erangeles**
@notmessenger had to create new PR, last one got ruined due to git problems.

[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1190)

### CODE REVIEW

**Comment by erangeles** [comment]
https://github.com/softlayer/sl-ember-components/pull/1084 was the last pr, @juwara0 already reviewed it so its ready to be merged.

**Comment by juwara0** [comment]
I have started reviewing this.

---







_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1190#-:-K3VGhpz5yJsics1yfbW:268077471)_

**Comment by juwara0** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

_[tests/unit/components/sl-radio-group-test.js, line 29 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1190#-K3VWzXSOlx_LVlPfReM:-K3VWzXXIExrPNVukhD8:965533367) ([raw file](https://github.com/softlayer/sl-ember-components/blob/4e1b41c227502eb7fa968b8ab774b971c00ee8b4/tests/unit/components/sl-radio-group-test.js#L29)):_
Need to also add an assertion to test that namespace is mixin is present: https://github.com/softlayer/sl-ember-components/blob/EmberCli-1.13.8/addon/components/sl-radio-group.js#L14

---

_[tests/unit/components/sl-radio-group-test.js, line 32 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1190#-K3VXEY60cdXzhO1Vp99:-K3VXEY60cdXzhO1Vp9A:1664017942) ([raw file](https://github.com/softlayer/sl-ember-components/blob/4e1b41c227502eb7fa968b8ab774b971c00ee8b4/tests/unit/components/sl-radio-group-test.js#L32)):_
Test name is incorrect: https://github.com/softlayer/ember-style-guide/blob/master/ember-testing.md#naming-unit-tests

---

_[tests/unit/components/sl-radio-group-test.js, line 103 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1190#-K3VcfgKbwfXqNZzKc6p:-K3VcfgKbwfXqNZzKc6q:942276841) ([raw file](https://github.com/softlayer/sl-ember-components/blob/4e1b41c227502eb7fa968b8ab774b971c00ee8b4/tests/unit/components/sl-radio-group-test.js#L103)):_
There also needs to be an assert checking for disabled property and class on the <fieldset> tag

---

_[tests/unit/components/sl-radio-group-test.js, line 140 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1190#-K3Ve1M70zeJL4GTGCLh:-K3Ve1M70zeJL4GTGCLi:-138768515) ([raw file](https://github.com/softlayer/sl-ember-components/blob/4e1b41c227502eb7fa968b8ab774b971c00ee8b4/tests/unit/components/sl-radio-group-test.js#L140)):_
This title is incorrect for what is being tested. It should read something like 'initialize() - "inline=false" property adds "radio" class to "sl-radio"'

---

_[tests/unit/components/sl-radio-group-test.js, line 161 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1190#-K3WLGUM_lw4UbkG4cT5:-K3WLGUM_lw4UbkG4cT6:-1453595013) ([raw file](https://github.com/softlayer/sl-ember-components/blob/4e1b41c227502eb7fa968b8ab774b971c00ee8b4/tests/unit/components/sl-radio-group-test.js#L161)):_
Do you need this test since the one below written by Aziz covers both the scenario of the event handlers being setup in didInsertElement and their removal in willClearRender?

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1190)_

**Comment by juwara0** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1190)_

**Comment by juwara0** [comment]
Can you also add a test that exercises this line: https://github.com/softlayer/sl-ember-components/blob/EmberCli-1.13.8/addon/components/sl-radio-group.js#L137-L139

---







_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1190#-:-K3WQ0WlPumy5opdVDvg:-1770965122)_

**Comment by erangeles** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[tests/unit/components/sl-radio-group-test.js, line 29 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1190#-K3VWzXSOlx_LVlPfReM:-K4NwLFBqOrmTW9Jbif7:-499146009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/4e1b41c227502eb7fa968b8ab774b971c00ee8b4/tests/unit/components/sl-radio-group-test.js#L29)):*
Done.

---

*[tests/unit/components/sl-radio-group-test.js, line 32 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1190#-K3VXEY60cdXzhO1Vp99:-K4O-oHHfs0VRpgQdjo-:-499146009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/4e1b41c227502eb7fa968b8ab774b971c00ee8b4/tests/unit/components/sl-radio-group-test.js#L32)):*
Done.

---

*[tests/unit/components/sl-radio-group-test.js, line 103 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1190#-K3VcfgKbwfXqNZzKc6p:-K4O2Efq1fJxUNaDPP1k:1866807440) ([raw file](https://github.com/softlayer/sl-ember-components/blob/4e1b41c227502eb7fa968b8ab774b971c00ee8b4/tests/unit/components/sl-radio-group-test.js#L103)):*
the 2 tests below do exactly that, checks disabled prop and the class 'disabled'. 

---

*[tests/unit/components/sl-radio-group-test.js, line 140 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1190#-K3Ve1M70zeJL4GTGCLh:-K4O4LmhwhduUInq6zbh:-499146009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/4e1b41c227502eb7fa968b8ab774b971c00ee8b4/tests/unit/components/sl-radio-group-test.js#L140)):*
Done.

---

*[tests/unit/components/sl-radio-group-test.js, line 161 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1190#-K3WLGUM_lw4UbkG4cT5:-K4O4eROcl6m7YXt-CfY:-499146009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/4e1b41c227502eb7fa968b8ab774b971c00ee8b4/tests/unit/components/sl-radio-group-test.js#L161)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1190)*

**Comment by azizpunjani** [comment]
Review status: 0 of 1 files reviewed at latest revision, 9 unresolved discussions.

---

*[tests/unit/components/sl-radio-group-test.js, line 76 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1190#-K4OMbiAfMdrWePMzLOz:-K4OMbiAfMdrWePMzLP-:-1371409223) ([raw file](https://github.com/softlayer/sl-ember-components/blob/b180c7f2eeb055b92c6d9bd57809363bc8ffddc8/tests/unit/components/sl-radio-group-test.js#L76)):*
I believe this should be an integration test. I don't see any isolated component methods being called.

---

*[tests/unit/components/sl-radio-group-test.js, line 97 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1190#-K4Op2DtVupbUTngrq20:-K4Op2DtVupbUTngrq21:-1371409223) ([raw file](https://github.com/softlayer/sl-ember-components/blob/b180c7f2eeb055b92c6d9bd57809363bc8ffddc8/tests/unit/components/sl-radio-group-test.js#L97)):*
I believe this should be an integration test. I don't see any isolated component methods being called.

---

*[tests/unit/components/sl-radio-group-test.js, line 124 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1190#-K4Op5xKZvtwYpfiLNtJ:-K4Op5xKZvtwYpfiLNtK:-1371409223) ([raw file](https://github.com/softlayer/sl-ember-components/blob/b180c7f2eeb055b92c6d9bd57809363bc8ffddc8/tests/unit/components/sl-radio-group-test.js#L124)):*
I believe this should be an integration test. I don't see any isolated component methods being called.

---

*[tests/unit/components/sl-radio-group-test.js, line 145 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1190#-K4Op8S7XAX3lzVkJjKe:-K4Op8S7XAX3lzVkJjKf:-1371409223) ([raw file](https://github.com/softlayer/sl-ember-components/blob/b180c7f2eeb055b92c6d9bd57809363bc8ffddc8/tests/unit/components/sl-radio-group-test.js#L145)):*
I believe this should be an integration test. I don't see any isolated component methods being called.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1190)*

**Comment by azizpunjani** [comment]
*[tests/unit/components/sl-radio-group-test.js, line 229 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1190#-K4OqGUoeLhn02VC3ZQL:-K4OqGUoeLhn02VC3ZQM:-1371409223) ([raw file](https://github.com/softlayer/sl-ember-components/blob/b180c7f2eeb055b92c6d9bd57809363bc8ffddc8/tests/unit/components/sl-radio-group-test.js#L229)):*
I believe this should be an integration test. I don't see any isolated component methods being called.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1190)*

**Comment by juwara0** [comment]
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions.

---

*[tests/unit/components/sl-radio-group-test.js, line 140 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1190#-K3Ve1M70zeJL4GTGCLh:-K4OsRqsj-IGs4VFCA2W:-439186846) ([raw file](https://github.com/softlayer/sl-ember-components/blob/4e1b41c227502eb7fa968b8ab774b971c00ee8b4/tests/unit/components/sl-radio-group-test.js#L140)):*
The title is still incorrect. Please note that the class "radio" is added to '.sl-radio' https://github.com/softlayer/sl-ember-components/blob/EmberCli-1.13.8/addon/components/sl-radio-group.js#L123

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1190)*

**Comment by juwara0** [comment]
Review status: 0 of 1 files reviewed at latest revision, 8 unresolved discussions.

---

*[tests/unit/components/sl-radio-group-test.js, line 229 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1190#-K4OsrCM-3ggZt9XSlmQ:-K4OsrCNFx06jXfiXAKO:132247444) ([raw file](https://github.com/softlayer/sl-ember-components/blob/b180c7f2eeb055b92c6d9bd57809363bc8ffddc8/tests/unit/components/sl-radio-group-test.js#L229)):*
The title has a spelling error 'listner'

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1190)*

**Comment by juwara0** [comment]
*[tests/unit/components/sl-radio-group-test.js, line 245 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1190#-K4Otdo-F7nM3fZUwrDs:-K4Otdo-F7nM3fZUwrDt:188736705) ([raw file](https://github.com/softlayer/sl-ember-components/blob/b180c7f2eeb055b92c6d9bd57809363bc8ffddc8/tests/unit/components/sl-radio-group-test.js#L245)):*
spelling error of 'listner'

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1190)*

**Comment by juwara0** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1190)*

**Comment by juwara0** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[tests/unit/components/sl-radio-group-test.js, line 240 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1190#-K4Ow4_NCqYChyrKWIqn:-K4Ow4_NCqYChyrKWIqo:-1291058317) ([raw file](https://github.com/softlayer/sl-ember-components/blob/b180c7f2eeb055b92c6d9bd57809363bc8ffddc8/tests/unit/components/sl-radio-group-test.js#L240)):*
shouldn't this be trigger(  'change' ) 

https://github.com/softlayer/sl-ember-components/blob/EmberCli-1.13.8/addon/components/sl-radio-group.js#L136-L139

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1190)*

**Comment by erangeles** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[tests/unit/components/sl-radio-group-test.js, line 140 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1190#-K3Ve1M70zeJL4GTGCLh:-K4Ow7GOGWLchaeSAGXQ:1972861258) ([raw file](https://github.com/softlayer/sl-ember-components/blob/4e1b41c227502eb7fa968b8ab774b971c00ee8b4/tests/unit/components/sl-radio-group-test.js#L140)):*
removed test, see comment above.

---

*[tests/unit/components/sl-radio-group-test.js, line 76 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1190#-K4OMbiAfMdrWePMzLOz:-K4Ov8yFoYbjkZPmgvcW:-1960510571) ([raw file](https://github.com/softlayer/sl-ember-components/blob/b180c7f2eeb055b92c6d9bd57809363bc8ffddc8/tests/unit/components/sl-radio-group-test.js#L76)):*
correct, removed since this test already exists: https://github.com/softlayer/sl-ember-components/blob/EmberCli-1.13.8/tests/integration/components/sl-radio-group-test.js#L227

---

*[tests/unit/components/sl-radio-group-test.js, line 97 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1190#-K4Op2DtVupbUTngrq20:-K4OvPSlgstCycYY6XAQ:213852451) ([raw file](https://github.com/softlayer/sl-ember-components/blob/b180c7f2eeb055b92c6d9bd57809363bc8ffddc8/tests/unit/components/sl-radio-group-test.js#L97)):*
correct, removed since this test already exists: https://github.com/softlayer/sl-ember-components/blob/EmberCli-1.13.8/tests/integration/components/sl-radio-group-test.js#L45

---

*[tests/unit/components/sl-radio-group-test.js, line 124 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1190#-K4Op5xKZvtwYpfiLNtJ:-K4OvY3ywpSc_u3baSot:-1960511437) ([raw file](https://github.com/softlayer/sl-ember-components/blob/b180c7f2eeb055b92c6d9bd57809363bc8ffddc8/tests/unit/components/sl-radio-group-test.js#L124)):*
correct, removed since this test already exists: https://github.com/softlayer/sl-ember-components/blob/EmberCli-1.13.8/tests/integration/components/sl-radio-group-test.js#L159

---

*[tests/unit/components/sl-radio-group-test.js, line 145 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1190#-K4Op8S7XAX3lzVkJjKe:-K4Ow4ufEYG4iWXh4Are:-1152523412) ([raw file](https://github.com/softlayer/sl-ember-components/blob/b180c7f2eeb055b92c6d9bd57809363bc8ffddc8/tests/unit/components/sl-radio-group-test.js#L145)):*
correct, removed since test already exists: https://github.com/softlayer/sl-ember-components/blob/EmberCli-1.13.8/tests/integration/components/sl-radio-group-test.js#L181

---

*[tests/unit/components/sl-radio-group-test.js, line 229 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1190#-K4OqGUoeLhn02VC3ZQL:-K4OvlnOXlXiHjAJJlhN:-1960510637) ([raw file](https://github.com/softlayer/sl-ember-components/blob/b180c7f2eeb055b92c6d9bd57809363bc8ffddc8/tests/unit/components/sl-radio-group-test.js#L229)):*
correct, removed since this test already exists: https://github.com/softlayer/sl-ember-components/blob/EmberCli-1.13.8/tests/integration/components/sl-radio-group-test.js#L203

---

*[tests/unit/components/sl-radio-group-test.js, line 229 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1190#-K4OsrCM-3ggZt9XSlmQ:-K4Ovrcs_d3QcNXJ-MF_:1233109907) ([raw file](https://github.com/softlayer/sl-ember-components/blob/b180c7f2eeb055b92c6d9bd57809363bc8ffddc8/tests/unit/components/sl-radio-group-test.js#L229)):*
test was removed, see comment above.

---

*[tests/unit/components/sl-radio-group-test.js, line 245 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1190#-K4Otdo-F7nM3fZUwrDs:-K4Ow-gQUmzAXeGDWzp2:1233109907) ([raw file](https://github.com/softlayer/sl-ember-components/blob/b180c7f2eeb055b92c6d9bd57809363bc8ffddc8/tests/unit/components/sl-radio-group-test.js#L245)):*
test was removed, see comment above.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1190)*

**Comment by erangeles** [comment]
Review status: 0 of 1 files reviewed at latest revision, 10 unresolved discussions.

---

*[tests/unit/components/sl-radio-group-test.js, line 240 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1190#-K4Ow4_NCqYChyrKWIqn:-K4OwvZHGL5g8SJbF7Tq:1233109907) ([raw file](https://github.com/softlayer/sl-ember-components/blob/b180c7f2eeb055b92c6d9bd57809363bc8ffddc8/tests/unit/components/sl-radio-group-test.js#L240)):*
test was removed, see comment above.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1190)*

**Comment by azizpunjani** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[tests/unit/components/sl-radio-group-test.js, line 62 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1190#-K4OxdYZDhxRAAo4sC5e:-K4OxdYZDhxRAAo4sC5f:-1387937623) ([raw file](https://github.com/softlayer/sl-ember-components/blob/d9955ab21e9ad9a7fd748a9c0087cdb9bdbfd314/tests/unit/components/sl-radio-group-test.js#L62)):*
Indentation needs to be fixed. Also, function declaration can be made less verbose.

```javascript
assert.throws(
    () => component.initialize(),
    '"name" property must be set on component'
);
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1190)*

**Comment by erangeles** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[tests/unit/components/sl-radio-group-test.js, line 62 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1190#-K4OxdYZDhxRAAo4sC5e:-K4P0npciRVmzD01ixXY:-499146009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/d9955ab21e9ad9a7fd748a9c0087cdb9bdbfd314/tests/unit/components/sl-radio-group-test.js#L62)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1190)*

**Comment by azizpunjani** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1190)*

**Comment by juwara0** [comment]
Reviewed 1 of 1 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1190)*

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1190)*

**Pull request merged**
