### PR TITLE
Closes softlayer/sl-ember-components#1295

### PR DESCRIPTION
**Pull request by SpikedKira**
[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1366)

### CODE REVIEW

**Comment by azizpunjani** [comment]
Review status: 0 of 1 files reviewed at latest revision, 9 unresolved discussions.

---

*[addon/components/sl-grid.js, line 442 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1366#-K7v9otyta3tTCUdzCZv:-K7v9otyta3tTCUdzCZw:90681817) ([raw file](https://github.com/softlayer/sl-ember-components/blob/b077037369b18f24e031424ee42aa8a8685e0879/addon/components/sl-grid.js#L442)):*
@function tag not needed.

---

*[addon/components/sl-grid.js, line 453 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1366#-K7v9u-d_hilHEr80pPG:-K7v9u-d_hilHEr80pPH:90681817) ([raw file](https://github.com/softlayer/sl-ember-components/blob/b077037369b18f24e031424ee42aa8a8685e0879/addon/components/sl-grid.js#L453)):*
@function tag not needed.

---

*[addon/components/sl-grid.js, line 463 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1366#-K7v9uviE9oM8suy3mge:-K7v9uviE9oM8suy3mgf:90681817) ([raw file](https://github.com/softlayer/sl-ember-components/blob/b077037369b18f24e031424ee42aa8a8685e0879/addon/components/sl-grid.js#L463)):*
@function tag not needed.

---

*[addon/components/sl-grid.js, line 477 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1366#-K7v9wZFfdWgqx70OhL-:-K7v9wZFfdWgqx70OhL0:90681817) ([raw file](https://github.com/softlayer/sl-ember-components/blob/b077037369b18f24e031424ee42aa8a8685e0879/addon/components/sl-grid.js#L477)):*
@function tag not needed.

---

*[addon/components/sl-grid.js, line 520 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1366#-K7v9K-KbqKTZumJcyA4:-K7v9K-LFkDVxG-vxC4p:-2056218246) ([raw file](https://github.com/softlayer/sl-ember-components/blob/b077037369b18f24e031424ee42aa8a8685e0879/addon/components/sl-grid.js#L520)):*
Not sure how this is still in here because I remember removing it at some point. Do you mind removing this method? We shouldn't need it anymore as we are mixing in Namespace which contains this function.

---

*[addon/components/sl-grid.js, line 527 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1366#-K7v9zsd38mJ4pjyTn4f:-K7v9zsd38mJ4pjyTn4g:90681817) ([raw file](https://github.com/softlayer/sl-ember-components/blob/b077037369b18f24e031424ee42aa8a8685e0879/addon/components/sl-grid.js#L527)):*
@function tag not needed.

---

*[addon/components/sl-grid.js, line 572 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1366#-K7vA-o4MeLibu0AR3nP:-K7vA-o4MeLibu0AR3nQ:90681817) ([raw file](https://github.com/softlayer/sl-ember-components/blob/b077037369b18f24e031424ee42aa8a8685e0879/addon/components/sl-grid.js#L572)):*
@function tag not needed.

---

*[addon/components/sl-grid.js, line 586 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1366#-K7vA0KIRUI4Nf9BfAXD:-K7vA0KIRUI4Nf9BfAXE:90681817) ([raw file](https://github.com/softlayer/sl-ember-components/blob/b077037369b18f24e031424ee42aa8a8685e0879/addon/components/sl-grid.js#L586)):*
@function tag not needed.

---

*[addon/components/sl-grid.js, line 600 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1366#-K7vA110o-NOwYGPzJbJ:-K7vA110o-NOwYGPzJbK:90681817) ([raw file](https://github.com/softlayer/sl-ember-components/blob/b077037369b18f24e031424ee42aa8a8685e0879/addon/components/sl-grid.js#L600)):*
@function tag not needed.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1366)*

**Comment by azizpunjani** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1366)*

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[addon/components/sl-grid.js, line 213 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1366#-K8KFM3BsxL5KIMyVhhd:-K8KFM3BsxL5KIMyVhhe:151914471) ([raw file](https://github.com/softlayer/sl-ember-components/blob/3eb45063b63cc557e6e82f111db7ed94c42c6e9c/addon/components/sl-grid.js#L213)):*
Missing DocBlock.  See examples from recent work @azizpunjani has done

---

*[addon/components/sl-grid.js, line 221 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1366#-K8KFQLn_eKqcwWq_hs5:-K8KFQLouJDAIX9Z1eYh:151914471) ([raw file](https://github.com/softlayer/sl-ember-components/blob/3eb45063b63cc557e6e82f111db7ed94c42c6e9c/addon/components/sl-grid.js#L221)):*
Missing DocBlock.  See examples from recent work @azizpunjani has done

---

*[addon/components/sl-grid.js, line 441 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1366#-K8KFwQdiJPvYxiqpHg4:-K8KFwQdiJPvYxiqpHg5:1042485017) ([raw file](https://github.com/softlayer/sl-ember-components/blob/3eb45063b63cc557e6e82f111db7ed94c42c6e9c/addon/components/sl-grid.js#L441)):*
Is `@private` appropriate?  See examples from recent work @azizpunjani has done

---

*[addon/components/sl-grid.js, line 451 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1366#-K8KFxNqVehufBffw_pN:-K8KFxNqVehufBffw_pO:1042485017) ([raw file](https://github.com/softlayer/sl-ember-components/blob/3eb45063b63cc557e6e82f111db7ed94c42c6e9c/addon/components/sl-grid.js#L451)):*
Is `@private` appropriate?  See examples from recent work @azizpunjani has done

---

*[addon/components/sl-grid.js, line 555 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1366#-K8KFnAcHtDsK82zqRG4:-K8KFnAcHtDsK82zqRG5:1042485017) ([raw file](https://github.com/softlayer/sl-ember-components/blob/3eb45063b63cc557e6e82f111db7ed94c42c6e9c/addon/components/sl-grid.js#L555)):*
Is `@private` appropriate?  See examples from recent work @azizpunjani has done

---

*[addon/components/sl-grid.js, line 568 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1366#-K8KFq0lGaa5df9QW8LM:-K8KFq0makrLuanx9iJi:1042485017) ([raw file](https://github.com/softlayer/sl-ember-components/blob/3eb45063b63cc557e6e82f111db7ed94c42c6e9c/addon/components/sl-grid.js#L568)):*
Is `@private` appropriate?  See examples from recent work @azizpunjani has done

---

*[addon/components/sl-grid.js, line 581 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1366#-K8KFbeOjvxKHCF7cpR7:-K8KFbeOjvxKHCF7cpR8:1042485017) ([raw file](https://github.com/softlayer/sl-ember-components/blob/3eb45063b63cc557e6e82f111db7ed94c42c6e9c/addon/components/sl-grid.js#L581)):*
Is `@private` appropriate?  See examples from recent work @azizpunjani has done

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1366)*

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1366)*

**Pull request merged**
