### PR TITLE
Only export setErrorTypeThrown() in test environment

### PR DESCRIPTION
**Pull request by juwara0**
Closes softlayer/sl-ember-components#1359

[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1394)

### CODE REVIEW

**Comment by azizpunjani** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1394)*

**Comment by notmessenger** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[addon/utils/error.js, line 5 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1394#-K7wesKIpOk465ay14sB:-K7wer05CDwu_v150fTu:-624111555) ([raw file](https://github.com/softlayer/sl-ember-components/blob/11d2ccab4c7f93b2a629c606145c82d5b9f70861/addon/utils/error.js#L5)):*
Add empty line after this one

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1394)*

**Comment by notmessenger** [comment]
Verify that this code works as expected in a stand-alone consuming app as well.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1394#-:-K7wfZiy_syjo-3JsScf:479822990)*

**Comment by juwara0** [comment]
I verified that this works as expected in a stand-alone consuming app.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1394#-:-K7wniDciJNVzyJqWqS4:-830911347)*

**Comment by juwara0** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[addon/utils/error.js, line 5 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1394#-K7wesKIpOk465ay14sB:-K85E09EMfiZ5w2k5x1o:-499146009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/11d2ccab4c7f93b2a629c606145c82d5b9f70861/addon/utils/error.js#L5)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1394)*

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1394)*

**Pull request merged**
