### PR TITLE
 Create integration test suite and migrate appropriate tests from unit test suite #591

### PR DESCRIPTION
**Pull request by erangeles**
Connects to #591

[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/840)

### CODE REVIEW

**Comment by erangeles** [comment]
@notmessenger trying to test for defaults values however this component does not seem to have a hbs template, its just an icon. so not sure if possible to test the default value, will add a check for tagname as well.

**Comment by erangeles** [comment]
@notmessenger this PR is ready to be reviewed.

**Comment by notmessenger** [comment]
Review status: 0 of 2 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

<sup>**[tests/integration/components/sl-loading-icon-test.js, line 10 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/840#-JzzX-twzd6w5-xWHgqD)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/110ae700bd71f624d187c82e3c878120a98ee27c/tests/integration/components/sl-loading-icon-test.js#L10)):</sup>
Only use `{{sl-loading-icon}}` in the template, as this component does not support yielded content.

---

<sup>**[tests/integration/components/sl-loading-icon-test.js, line 24 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/840#-JzzXhmzZzuxfzxScD4n)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/110ae700bd71f624d187c82e3c878120a98ee27c/tests/integration/components/sl-loading-icon-test.js#L24)):</sup>
This type of assertion should be addressed via a unit test

---

<sup>**[tests/integration/components/sl-loading-icon-test.js, line 32 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/840#-JzzXGWNpdTZO_UycBQo)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/110ae700bd71f624d187c82e3c878120a98ee27c/tests/integration/components/sl-loading-icon-test.js#L32)):</sup>
Only use `{{sl-loading-icon}}` in the template, as this component does not support yielded content.

---

<sup>**[tests/integration/components/sl-loading-icon-test.js, line 36 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/840#-JzzXvwdd55j65g-oz8-)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/110ae700bd71f624d187c82e3c878120a98ee27c/tests/integration/components/sl-loading-icon-test.js#L36)):</sup>
Similar to other integration test patterns, also assert that the unexpected class is not present as well.

---

<sup>**[tests/integration/components/sl-loading-icon-test.js, line 42 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/840#-JzzXI5PviOnVXQsiv8H)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/110ae700bd71f624d187c82e3c878120a98ee27c/tests/integration/components/sl-loading-icon-test.js#L42)):</sup>
Only use `{{sl-loading-icon}}` in the template, as this component does not support yielded content.

---

<sup>**[tests/integration/components/sl-loading-icon-test.js, line 46 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/840#-JzzY0fLDnLlfTfhVzki)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/110ae700bd71f624d187c82e3c878120a98ee27c/tests/integration/components/sl-loading-icon-test.js#L46)):</sup>
Similar to other integration test patterns, also assert that the unexpected class is not present as well.

---

<sup>**[tests/unit/components/sl-loading-icon-test.js, line 0 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/840#-JzzXPdOtcqbU1Jojsze)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/110ae700bd71f624d187c82e3c878120a98ee27c/tests/unit/components/sl-loading-icon-test.js#L0)):</sup>
A unit test needs to exist that asserts the values of:

* `tagName`
* `inverse`

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/840)

**Comment by notmessenger** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/840)

**Comment by notmessenger** [comment]
Connects to #591

**Comment by erangeles** [comment]
All comments addressed, ready to be reviewed.

---

Review status: 0 of 2 files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---

<sup>**[tests/integration/components/sl-loading-icon-test.js, line 10 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/840#-JzzX-twzd6w5-xWHgqD)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/110ae700bd71f624d187c82e3c878120a98ee27c/tests/integration/components/sl-loading-icon-test.js#L10)):</sup>
Done.

---

<sup>**[tests/integration/components/sl-loading-icon-test.js, line 21 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/840#-JzzXhmzZzuxfzxScD4n)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/110ae700bd71f624d187c82e3c878120a98ee27c/tests/integration/components/sl-loading-icon-test.js#L21)):</sup>
Done.

---

<sup>**[tests/integration/components/sl-loading-icon-test.js, line 26 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/840#-JzzXGWNpdTZO_UycBQo)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/110ae700bd71f624d187c82e3c878120a98ee27c/tests/integration/components/sl-loading-icon-test.js#L26)):</sup>
Done.

---

<sup>**[tests/integration/components/sl-loading-icon-test.js, line 29 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/840#-JzzXvwdd55j65g-oz8-)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/110ae700bd71f624d187c82e3c878120a98ee27c/tests/integration/components/sl-loading-icon-test.js#L29)):</sup>
Done.

---

<sup>**[tests/integration/components/sl-loading-icon-test.js, line 40 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/840#-JzzXI5PviOnVXQsiv8H)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/110ae700bd71f624d187c82e3c878120a98ee27c/tests/integration/components/sl-loading-icon-test.js#L40)):</sup>
Done.

---

<sup>**[tests/integration/components/sl-loading-icon-test.js, line 43 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/840#-JzzY0fLDnLlfTfhVzki)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/110ae700bd71f624d187c82e3c878120a98ee27c/tests/integration/components/sl-loading-icon-test.js#L43)):</sup>
Done.

---

<sup>**[tests/unit/components/sl-loading-icon-test.js, line 0 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/840#-JzzXPdOtcqbU1Jojsze)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/110ae700bd71f624d187c82e3c878120a98ee27c/tests/unit/components/sl-loading-icon-test.js#L0)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/840)

**Comment by notmessenger** [comment]
Reviewed 2 of 2 files at r2.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/840)

**Comment by notmessenger** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[tests/unit/components/sl-loading-icon-test.js, line 23 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/840#-K-3gPJLMb-9mFKAywoe)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/97ce354d6c79d199326f5c8ab84dc402100972b7/tests/unit/components/sl-loading-icon-test.js#L23)):</sup>
This test is not needed, as it is testing Ember functionality.  I believe there may have been a cross between the timing of the comment left to assert the value of this property and its intent.

---

<sup>**[tests/unit/components/sl-loading-icon-test.js, line 33 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/840#-K-3ga8Q_qgMFQs59-AU)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/97ce354d6c79d199326f5c8ab84dc402100972b7/tests/unit/components/sl-loading-icon-test.js#L33)):</sup>
This test is not needed, as it is testing Ember functionality.  I believe there may have been a cross between the timing of the comment left to assert the value of this property and its intent.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/840)

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/840)

**Comment by erangeles** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

<sup>**[tests/integration/components/sl-loading-icon-test.js, line 24 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/840#-K-2AGsxAhusKYQTLKVn)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/110ae700bd71f624d187c82e3c878120a98ee27c/tests/integration/components/sl-loading-icon-test.js#L24)):</sup>
deleted unneeded test. ready to be reviewed/merged.

---

<sup>**[tests/unit/components/sl-loading-icon-test.js, line 23 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/840#-K-3gPJLMb-9mFKAywoe)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/97ce354d6c79d199326f5c8ab84dc402100972b7/tests/unit/components/sl-loading-icon-test.js#L23)):</sup>
Done.

---

<sup>**[tests/unit/components/sl-loading-icon-test.js, line 33 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/840#-K-3ga8Q_qgMFQs59-AU)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/97ce354d6c79d199326f5c8ab84dc402100972b7/tests/unit/components/sl-loading-icon-test.js#L33)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/840)

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/840)

**Pull request merged**
