### PR TITLE
Unit | Component | sl tab panel: getActiveTabName returns the correct value after setActiveTab() is called

### PR DESCRIPTION
**Pull request by erangeles**
[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1637)

### CODE REVIEW

**Comment by erangeles** [comment]
@notmessenger same thing here, dead method left over from refactor.

**Comment by juwara0** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1637)*

**Comment by notmessenger** [comment]
Is it expected for the tests in the build to be failing?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1637#-:-KBttyhnSv-KuYlyOeGG:1413824134)*

**Comment by notmessenger** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1637)*

**Pull request merged**
