### PR TITLE
Duplicate test case

### PR DESCRIPTION
**Pull request by erangeles**
[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1552)

### CODE REVIEW

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tests/unit/components/sl-date-picker-test.js, line 508 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1552#-KBYbaSRS4SynTypJHUG:-KBYbaSRS4SynTypJHUH:-1952758553) ([raw file](https://github.com/softlayer/sl-ember-components/blob/032a960e0b45cd540a8f80012aa5038199a227e8/tests/unit/components/sl-date-picker-test.js#L508)):*
Don't need this, and related, logic from this test case in the one that was left in the file?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1552)*

**Comment by erangeles** [comment]
*[tests/unit/components/sl-date-picker-test.js, line 508 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1552#-KBYbaSRS4SynTypJHUG:-KBhjWWfo4UalBz1oQHk:1355806885) ([raw file](https://github.com/softlayer/sl-ember-components/blob/032a960e0b45cd540a8f80012aa5038199a227e8/tests/unit/components/sl-date-picker-test.js#L508)):*
@notmessenger can you please rephrase this comment, I don't understand it. Thanks!

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1552)*

**Comment by notmessenger** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tests/unit/components/sl-date-picker-test.js, line 508 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1552#-KBYbaSRS4SynTypJHUG:-KBi-YoTkuWB8o-RHade:-1374829549) ([raw file](https://github.com/softlayer/sl-ember-components/blob/032a960e0b45cd540a8f80012aa5038199a227e8/tests/unit/components/sl-date-picker-test.js#L508)):*
There were two "There are no references to Ember.$, $ or jQuery" test cases in this file but they were not identical.  I want to make sure you didn't just remove one of them so that there was only one and that the content of this one isn't actually needed.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1552)*

**Comment by erangeles** [comment]
*[tests/unit/components/sl-date-picker-test.js, line 508 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1552#-KBYbaSRS4SynTypJHUG:-KBiRi_azcusy1Z-QYjC:1681866292) ([raw file](https://github.com/softlayer/sl-ember-components/blob/032a960e0b45cd540a8f80012aa5038199a227e8/tests/unit/components/sl-date-picker-test.js#L508)):*
so I made the deletion decision based on this changeset here, https://github.com/softlayer/sl-ember-components/commit/ade37a3f41a06b36ed1ce06f1cba30dbe967492d we can infer that this is the 'standard' content for this type of test.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1552)*

**Comment by notmessenger** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tests/unit/components/sl-date-picker-test.js, line 508 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1552#-KBYbaSRS4SynTypJHUG:-KBj4688FcPq9sm18mP3:-981696869) ([raw file](https://github.com/softlayer/sl-ember-components/blob/a0b05fcfb481f10736eee148afbd4e53e73210e3/tests/unit/components/sl-date-picker-test.js#L508)):*
Right, but the setting of `startDate` and the triggering of `willClearRender` are no longer needed?  Seems they might be necessary to trigger additional events within the components, but maybe not.  I haven't gone digging.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1552)*

**Comment by erangeles** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tests/unit/components/sl-date-picker-test.js, line 508 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1552#-KBYbaSRS4SynTypJHUG:-KBo2MBSUeW6l1pwj8NP:-686049136) ([raw file](https://github.com/softlayer/sl-ember-components/blob/a0b05fcfb481f10736eee148afbd4e53e73210e3/tests/unit/components/sl-date-picker-test.js#L508)):*
Confirmed it with Aziz, you only set params "if the parameters are needed for the component instantiation to work". so any logic in the previous test is NOT needed.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1552)*

**Pull request merged**
