### PR TITLE
Unit | Component | sl tab panel: getInitialTabName() returns the correct tab name

### PR DESCRIPTION
**Pull request by erangeles**
[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1639)

### CODE REVIEW

**Comment by juwara0** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/integration/components/sl-tab-panel-test.js, line 42 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1639#-KBt41GS9lLYkPfTmocx:-KBt41GS9lLYkPfTmocy:-325992253) ([raw file](https://github.com/softlayer/sl-ember-components/blob/cc6b40c6458ace0024b5eaa3c5c372702a1717f2/tests/integration/components/sl-tab-panel-test.js#L42)):*
I think we should also add the check for the active class on the tab panel.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1639)*

**Comment by juwara0** [comment]
If this is the last of the tests using the template at the top: https://github.com/softlayer/sl-ember-components/blob/eb33a8027093cc0230b91c89c5dfa3d2a993be98/tests/integration/components/sl-tab-panel-test.js#L5-L11 then we can remove that code as well.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1639#-:-KBt4fc-O89DXHDB2SYw:-365297668)*

**Comment by juwara0** [comment]
This is the correct link: https://github.com/softlayer/sl-ember-components/blob/eb33a8027093cc0230b91c89c5dfa3d2a993be98/tests/unit/components/sl-tab-panel-test.js#L9-L21
The one above was to the integration test.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1639#-:-KBt5b0zC4wMhtevbG4A:-2093160899)*

**Comment by erangeles** [comment]
*[tests/integration/components/sl-tab-panel-test.js, line 42 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1639#-KBt41GS9lLYkPfTmocx:-KBtAlFIZ-i9uX67rrdo:-469593337) ([raw file](https://github.com/softlayer/sl-ember-components/blob/cc6b40c6458ace0024b5eaa3c5c372702a1717f2/tests/integration/components/sl-tab-panel-test.js#L42)):*
done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1639)*

**Comment by erangeles** [comment]
verifying the  template use and if it can be removed.

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1639#-:-KBtAujWhiSSr1x_ne_g:671065174)*

**Comment by juwara0** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/integration/components/sl-tab-panel-test.js, line 44 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1639#-KBtCWoj-gmFHSGP8HAw:-KBtCWokoMJTzHZrBHPG:332515501) ([raw file](https://github.com/softlayer/sl-ember-components/blob/9dec0211b1c2ff41195a126d16d45963c9870dd0/tests/integration/components/sl-tab-panel-test.js#L44)):*
do you need to add the .hasClass() 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1639)*

**Comment by juwara0** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1639)*

**Comment by erangeles** [comment]
the unit test for `setupTabs()` still uses the template. I think you grabbed that test issue if im not mistaken.

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1639#-:-KBtEPyW5EKkhzr0Rb08:-305444851)*

**Comment by erangeles** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/integration/components/sl-tab-panel-test.js, line 44 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1639#-KBtCWoj-gmFHSGP8HAw:-KBtEcruxNEhzzfKGcZ6:-499146009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/9dec0211b1c2ff41195a126d16d45963c9870dd0/tests/integration/components/sl-tab-panel-test.js#L44)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1639)*

**Comment by juwara0** [comment]
Yes, I removed that test from the unit tests.

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1639#-:-KBtFIdhmFjk4sUsNkbI:-323024314)*

**Comment by juwara0** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1639)*

**Comment by juwara0** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1639)*

**Comment by juwara0** [comment]
@notmessenger - This PR should be merged last (Of the sl-tab-panel test issues, there are four) since it removes the last piece of needed code (the template)

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1639#-:-KBtKBqS0HNQ0Id3jmS2:1103269817)*

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tests/unit/components/sl-tab-panel-test.js, line 153 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1639#-KC8hkw-BLyuCVYERTcQ:-KC8hkw-BLyuCVYERTcR:830950966) ([raw file](https://github.com/softlayer/sl-ember-components/blob/eb33a8027093cc0230b91c89c5dfa3d2a993be98/tests/unit/components/sl-tab-panel-test.js#L153)):*
Why is this test being removed?  The corresponding functionality in the component still remains.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1639)*

**Comment by erangeles** [comment]
*[tests/unit/components/sl-tab-panel-test.js, line 153 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1639#-KC8hkw-BLyuCVYERTcQ:-KCYEnP02z32-AYhuo0b:275023695) ([raw file](https://github.com/softlayer/sl-ember-components/blob/eb33a8027093cc0230b91c89c5dfa3d2a993be98/tests/unit/components/sl-tab-panel-test.js#L153)):*
@juwara0 and I decided 

- the removed unit tests were testing the dom(which is the integration tests job) including this one as it utilizes the `test-template`.

- this has been replaced with an integration test named "first tab/tab pane has class active" to test the dom properly.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1639)*

**Comment by notmessenger** [comment]
Test is failing with

```
/home/travis/build/softlayer/sl-ember-components/tests/unit/components/sl-tab-panel-test.js
error  "hbs" is defined but never used  no-unused-vars
```

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1639#-:-KCYnbsEty6oo_NvEzkW:-1678084085)*

**Comment by notmessenger** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1639)*

**Comment by erangeles** [comment]
ready to merge.

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1639#-:-KCwCh_CgoNBYmWyESvV:1606695513)*

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1639)*

**Pull request merged**
