### PR TITLE
sl-drop-option test error thrown

### PR DESCRIPTION
**Pull request by erangeles**
[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1442)

### CODE REVIEW

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/integration/components/sl-drop-option-test.js, line 84 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1442#-K9JGG-1n7V7YtA4XO1y:-K9JGG-1n7V7YtA4XO1z:779408590) ([raw file](https://github.com/softlayer/sl-ember-components/blob/a70c6eb2a574b08232d04c95cb9eaa5358ae336b/tests/integration/components/sl-drop-option-test.js#L84)):*
You can't just remove the test in order to get rid of the error.  *addon/templates/components/sl-drop-option.hbs* implements the functionality this test covers.  At the very least, the functionality should have also been removed from the component, but that is not desired.  Instead either find a path that can be used that leverages an image asset in this repo so a 404 error does not occur or add a comment to this code (and the issue) regarding that this is behavior is desired and that the 404 is an acceptable side-effect to the testing of it.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1442)*

**Comment by erangeles** [comment]
*[tests/integration/components/sl-drop-option-test.js, line 84 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1442#-K9JGG-1n7V7YtA4XO1y:-K9Six4AMXevTZyfMGrH:605966198) ([raw file](https://github.com/softlayer/sl-ember-components/blob/a70c6eb2a574b08232d04c95cb9eaa5358ae336b/tests/integration/components/sl-drop-option-test.js#L84)):*
https://github.com/softlayer/sl-ember-components/blob/v0.11.0/addon/components/sl-drop-button.js

https://github.com/softlayer/sl-ember-components/blob/v0.11.0/addon/components/sl-drop-option.js

where in this component does icon property still exist? Thats why I removed this test, due to the fact we got rid of that property and this very test is testing the property that doesnt exist. I may be wrong but thats how I'm assessing this issue. let me look further into this.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1442)*

**Comment by notmessenger** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/integration/components/sl-drop-option-test.js, line 84 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1442#-K9JGG-1n7V7YtA4XO1y:-K9Z8xazNADFMPGMATwK:-948259142) ([raw file](https://github.com/softlayer/sl-ember-components/blob/a70c6eb2a574b08232d04c95cb9eaa5358ae336b/tests/integration/components/sl-drop-option-test.js#L84)):*
Like I said in the original comment - https://github.com/softlayer/sl-ember-components/blob/v0.11.0/addon/templates/components/sl-drop-option.hbs#L3-L4

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1442)*

**Comment by erangeles** [comment]
closing as this is being addressed by @juwara0 in #1451

**Pull request closed without merging**
