### PR TITLE
Sl calendar icons

### PR DESCRIPTION
**Pull request by azizpunjani**
Was initially able to use bootstrap glyphicons for next and previous. The problem we run into is that sl-datepicker ends up looking different because it does not use glyphicons. I tried to override sl-datepicker to use glyphicons but it ended up being a lot of CSS. 

I opted to make sl-calendar consistent with sl-datepicker by simply using the same htmlentities that sl-datepicker uses, instead of applying over 30 lines of CSS to override the sl-datepicker styles.

Closes https://github.com/softlayer/sl-ember-components/issues/1122

[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1209)

### CODE REVIEW

**Comment by notmessenger** [comment]
For each of the spans that were replaced with HTML entities, replace instead with a span with a class of "sl-icon-prev" (and appropriate class name based on specific context for each).  Then add this (pseudo) CSS declaration:

```
.calendar .sl-icon-prev:prev { content: "&#171"; font-family: serif; }
```

@SpikedKira and myself know the reasoning behind this and will gladly share it "in person" if desired.  Too much to write here.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1209#-:-K4ZCLEarH89UQ26yrKu:848304177)*

**Comment by SpikedKira** [comment]
.sl-ember-components.calendar .sl-icon-prev:before { content: "&#171;"; font-family: serif; }

that would be the more preferred :) I typed it lazily in chat with @notmessenger

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1209#-:-K4ZM9VOi5_J8PZEOabU:1800216295)*

**Comment by notmessenger** [comment]
There should be assertions or test case added to the integration test suite for sr-only content.

---

Reviewed 5 of 5 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[addon/components/sl-calendar-day.js, line 16 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1209#-K4hL8Cb3408SOvkw-dP:-K4hL8Cb3408SOvkw-dQ:751400783) ([raw file](https://github.com/softlayer/sl-ember-components/blob/88bd9102a242a3b5b93cf597e08a3b9acbd2982c/addon/components/sl-calendar-day.js#L16)):*
Belongs in the "Properties" comment block and requires a DocBlock

---

*[addon/components/sl-calendar-day.js, line 18 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1209#-K4hLDpMqcie3T1H73ME:-K4hLDpMqcie3T1H73MF:-718837343) ([raw file](https://github.com/softlayer/sl-ember-components/blob/88bd9102a242a3b5b93cf597e08a3b9acbd2982c/addon/components/sl-calendar-day.js#L18)):*
Requires a DocBlock

---

*[addon/components/sl-calendar-day.js, line 26 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1209#-K4hLHf7EQu3ty0OTfTI:-K4hLHf7EQu3ty0OTfTJ:-880895768) ([raw file](https://github.com/softlayer/sl-ember-components/blob/88bd9102a242a3b5b93cf597e08a3b9acbd2982c/addon/components/sl-calendar-day.js#L26)):*
Remove trailing comma

---

*[addon/components/sl-calendar-day.js, line 37 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1209#-K4hLG_sQvIIrrYBF93T:-K4hLG_sQvIIrrYBF93U:101773398) ([raw file](https://github.com/softlayer/sl-ember-components/blob/88bd9102a242a3b5b93cf597e08a3b9acbd2982c/addon/components/sl-calendar-day.js#L37)):*
* Belongs in the "Properties" comment block and requires a DocBlock
* What purpose is this serving?

---

*[addon/templates/components/sl-calendar.hbs, line 48 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1209#-K4hLZitWLHH6LnAi7nU:-K4hLZitWLHH6LnAi7nV:-2130312955) ([raw file](https://github.com/softlayer/sl-ember-components/blob/88bd9102a242a3b5b93cf597e08a3b9acbd2982c/addon/templates/components/sl-calendar.hbs#L48)):*
Why the style declaration?  It's not present in the "viewing days" condition.  If needs to be present can we do it via css declaration rather than inline?

---

*[addon/templates/components/sl-calendar.hbs, line 51 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1209#-K4hLkugm8sih1T5Z2n0:-K4hLkuh7uzzIAm-c4EQ:1399985408) ([raw file](https://github.com/softlayer/sl-ember-components/blob/88bd9102a242a3b5b93cf597e08a3b9acbd2982c/addon/templates/components/sl-calendar.hbs#L51)):*
Nitpicky: be consistent in the order used for "class" and "collapse" - the "viewing days" condition has a different order for similar DOM structure.  Makes is easier to move through the file, compare, etc.

---

*[addon/templates/components/sl-calendar.hbs, line 54 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1209#-K4hLi9Q1IgtutkMHT3c:-K4hLi9Q1IgtutkMHT3d:-2130312955) ([raw file](https://github.com/softlayer/sl-ember-components/blob/88bd9102a242a3b5b93cf597e08a3b9acbd2982c/addon/templates/components/sl-calendar.hbs#L54)):*
Why the style declaration?  It's not present in the "viewing days" condition.  If needs to be present can we do it via css declaration rather than inline?

---

*[addon/templates/components/sl-calendar.hbs, line 82 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1209#-K4hLzy7QDIwp5JEgUgB:-K4hLzy7QDIwp5JEgUgC:-2130312955) ([raw file](https://github.com/softlayer/sl-ember-components/blob/88bd9102a242a3b5b93cf597e08a3b9acbd2982c/addon/templates/components/sl-calendar.hbs#L82)):*
Why the style declaration?  It's not present in the "viewing days" condition.  If needs to be present can we do it via css declaration rather than inline?

---

*[addon/templates/components/sl-calendar.hbs, line 88 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1209#-K4hM0KNG2B4v6ggN9pl:-K4hM0KNG2B4v6ggN9pm:-2130312955) ([raw file](https://github.com/softlayer/sl-ember-components/blob/88bd9102a242a3b5b93cf597e08a3b9acbd2982c/addon/templates/components/sl-calendar.hbs#L88)):*
Why the style declaration?  It's not present in the "viewing days" condition.  If needs to be present can we do it via css declaration rather than inline?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1209#-:-K4hOAu7xUjicMqmTDi2:-1668839031)*

**Comment by notmessenger** [comment]
Build is failing

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1209#-:-K4hTt_znrg7V7QQcXqu:618820389)*

**Comment by azizpunjani** [comment]
Review status: 3 of 6 files reviewed at latest revision, 7 unresolved discussions.

---

*[addon/templates/components/sl-calendar.hbs, line 48 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1209#-K4hLZitWLHH6LnAi7nU:-K4i2UOsMu1I3zoxRdCh:235735062) ([raw file](https://github.com/softlayer/sl-ember-components/blob/88bd9102a242a3b5b93cf597e08a3b9acbd2982c/addon/templates/components/sl-calendar.hbs#L48)):*
Was there from before. Looks like dead code. Removed it.

---

*[addon/templates/components/sl-calendar.hbs, line 54 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1209#-K4hLi9Q1IgtutkMHT3c:-K4i2_hbc94PpXU_Ez68:235735062) ([raw file](https://github.com/softlayer/sl-ember-components/blob/88bd9102a242a3b5b93cf597e08a3b9acbd2982c/addon/templates/components/sl-calendar.hbs#L54)):*
Was there from before. Looks like dead code. Removed it.

---

*[addon/templates/components/sl-calendar.hbs, line 82 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1209#-K4hLzy7QDIwp5JEgUgB:-K4i2bgvMVcHzEYRpa4l:235735062) ([raw file](https://github.com/softlayer/sl-ember-components/blob/88bd9102a242a3b5b93cf597e08a3b9acbd2982c/addon/templates/components/sl-calendar.hbs#L82)):*
Was there from before. Looks like dead code. Removed it.

---

*[addon/templates/components/sl-calendar.hbs, line 88 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1209#-K4hM0KNG2B4v6ggN9pl:-K4i2chwbxZuwa5dy2iY:235735062) ([raw file](https://github.com/softlayer/sl-ember-components/blob/88bd9102a242a3b5b93cf597e08a3b9acbd2982c/addon/templates/components/sl-calendar.hbs#L88)):*
Was there from before. Looks like dead code. Removed it.

---

*[addon/components/sl-calendar-day.js, line 16 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1209#-K4hL8Cb3408SOvkw-dP:-K4i2gwtR6KEN3kfanaZ:-1927419124) ([raw file](https://github.com/softlayer/sl-ember-components/blob/88bd9102a242a3b5b93cf597e08a3b9acbd2982c/addon/components/sl-calendar-day.js#L16)):*
Was experiment with making the calendar more accessible, seems like a bigger task, so reverted changes.

---

*[addon/components/sl-calendar-day.js, line 18 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1209#-K4hLDpMqcie3T1H73ME:-K4i2n4tKdrkdvPGDLVs:-1927419124) ([raw file](https://github.com/softlayer/sl-ember-components/blob/88bd9102a242a3b5b93cf597e08a3b9acbd2982c/addon/components/sl-calendar-day.js#L18)):*
Was experiment with making the calendar more accessible, seems like a bigger task, so reverted changes.

---

*[addon/components/sl-calendar-day.js, line 37 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1209#-K4hLG_sQvIIrrYBF93T:-K4i2tNbGUzQZJK_S0uD:-1927419124) ([raw file](https://github.com/softlayer/sl-ember-components/blob/88bd9102a242a3b5b93cf597e08a3b9acbd2982c/addon/components/sl-calendar-day.js#L37)):*
Was experiment with making the calendar more accessible, seems like a bigger task, so reverted changes.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1209)*

**Comment by notmessenger** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[addon/templates/components/sl-calendar.hbs, line 8 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1209#-K4i5xe5IrS7hPiM9WZl:-K4i5xe5IrS7hPiM9WZm:182081827) ([raw file](https://github.com/softlayer/sl-ember-components/blob/19e2fc53af765203c9433651e39155c77035a983/addon/templates/components/sl-calendar.hbs#L8)):*
Why do we need any content here is not going to give it the `sr-only` class?  Same question applies to other occurrences of this pattern as well.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1209)*

**Comment by azizpunjani** [comment]
*[addon/templates/components/sl-calendar.hbs, line 8 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1209#-K4i5xe5IrS7hPiM9WZl:-K4iaNkjcXHWgwF3funZ:-1303393325) ([raw file](https://github.com/softlayer/sl-ember-components/blob/19e2fc53af765203c9433651e39155c77035a983/addon/templates/components/sl-calendar.hbs#L8)):*
Content is necessary for screen readers to be able to read aloud. All the `.sr-only` class does is hide the element from plain view. We already [do that](https://github.com/softlayer/sl-ember-components/blob/v0.11.0/app/styles/addon.less#L16) via CSS applied to the icon. The `.sr-only` class is not necessary. The text should still be read aloud by the screen reader because it's present, just not in plain sight.

Of course there are other accessibility issues but that's a whole another task.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1209)*

**Comment by notmessenger** [comment]
*[addon/templates/components/sl-calendar.hbs, line 8 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1209#-K4i5xe5IrS7hPiM9WZl:-K4iceDrPLzDfMygjJet:-532623083) ([raw file](https://github.com/softlayer/sl-ember-components/blob/19e2fc53af765203c9433651e39155c77035a983/addon/templates/components/sl-calendar.hbs#L8)):*
Your link (https://github.com/softlayer/sl-ember-components/blob/v0.11.0/app/styles/addon.less#L16) is for a right margin.  Is that how it's being hidden?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1209)*

**Comment by azizpunjani** [comment]
*[addon/templates/components/sl-calendar.hbs, line 8 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1209#-K4i5xe5IrS7hPiM9WZl:-K4ihu1idBHBeVZKas5c:-625631389) ([raw file](https://github.com/softlayer/sl-ember-components/blob/19e2fc53af765203c9433651e39155c77035a983/addon/templates/components/sl-calendar.hbs#L8)):*
Yes, the text is pushed far to the right, then the width is set to 1em and overflow is hidden.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1209)*

**Comment by notmessenger** [comment]
*[addon/templates/components/sl-calendar.hbs, line 8 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1209#-K4i5xe5IrS7hPiM9WZl:-K4iihK2QjZ_aGfF2NV1:671043014) ([raw file](https://github.com/softlayer/sl-ember-components/blob/19e2fc53af765203c9433651e39155c77035a983/addon/templates/components/sl-calendar.hbs#L8)):*
Why wouldn't we use the Bootstrap-provided mechanism of the `sr-only` class rather than rolling our own approach, even if the CSS is the same (don't know whether it is or not)?  We need to leverage Bootstrap as much as possible.  This class is used in a variety of the other components (https://github.com/softlayer/sl-ember-components/search?utf8=✓&q=only)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1209)*

**Comment by SpikedKira** [comment]
*[addon/templates/components/sl-calendar.hbs, line 8 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1209#-K4i5xe5IrS7hPiM9WZl:-K4ilus99pefVPQRBkdo:934356620) ([raw file](https://github.com/softlayer/sl-ember-components/blob/19e2fc53af765203c9433651e39155c77035a983/addon/templates/components/sl-calendar.hbs#L8)):*
The sr-only class will remove the dom element from flow (position: absolute) and reduce the height and width to 1px, effectively removing the element entirely from the page as much as possible using CSS.  The idea here is that a screen reader would have CSS off b/c why would they need them at all?  However, our approach leaves the dom element in place so that we can show an icon while hiding relative text that the icon is meant to convey.  Our approach works across the scale instead of just for fully able clients or fully disabled clients.  Having a screen reader turned on while also having CSS turned on should also work, for instance those with limited sight or very poor vision but still not blind.  In this case, highlighting the icon should trigger the client to read aloud "next page" or what have you.  I think this is much preferable to just text or nothing (which would also hide our icon).  

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1209)*

**Comment by notmessenger** [comment]
*[addon/templates/components/sl-calendar.hbs, line 8 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1209#-K4i5xe5IrS7hPiM9WZl:-K4ipurbbxBGCcVyNCDU:1618581630) ([raw file](https://github.com/softlayer/sl-ember-components/blob/19e2fc53af765203c9433651e39155c77035a983/addon/templates/components/sl-calendar.hbs#L8)):*
Do you recommend I create issues to modify all the other uses of =`sl-only` as well?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1209)*

**Comment by SpikedKira** [comment]
*[addon/templates/components/sl-calendar.hbs, line 8 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1209#-K4i5xe5IrS7hPiM9WZl:-K4ir_fjDXdLq9_hs4Nq:-1265898386) ([raw file](https://github.com/softlayer/sl-ember-components/blob/19e2fc53af765203c9433651e39155c77035a983/addon/templates/components/sl-calendar.hbs#L8)):*
Possibly.  It's going to be case by case really.  sr-only can still be useful if we have some sort of detail text that explains something that would not be present w/o CSS.  Possibly something like a graph?  For icons/symbols, I think it's not the right solution.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1209)*

**Comment by azizpunjani** [comment]
*[addon/templates/components/sl-calendar.hbs, line 8 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1209#-K4i5xe5IrS7hPiM9WZl:-K4iwQJvQJbY5idzrqIB:1445153799) ([raw file](https://github.com/softlayer/sl-ember-components/blob/19e2fc53af765203c9433651e39155c77035a983/addon/templates/components/sl-calendar.hbs#L8)):*
I'd like to mention that the bootstrap class `sr-only` works just as well as our solution. If the screen reader is turned on while CSS is turned on, the screen reader will read aloud the text even though the element with the class `sr-only` is absolutely positioned.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1209)*

**Comment by SpikedKira** [comment]
*[addon/templates/components/sl-calendar.hbs, line 8 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1209#-K4i5xe5IrS7hPiM9WZl:-K4jAQ7abCO8u7sKmWrh:-265165650) ([raw file](https://github.com/softlayer/sl-ember-components/blob/19e2fc53af765203c9433651e39155c77035a983/addon/templates/components/sl-calendar.hbs#L8)):*
Correct, the screen reader will always read it.  The issue is that the content will not be there if CSS is enabled.  The sr-only class removes the element from flow for people that have CSS turned on so that they don't see it.  We want them to see something (the symbol) but not the text.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1209)*

**Comment by azizpunjani** [comment]
*[addon/templates/components/sl-calendar.hbs, line 8 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1209#-K4i5xe5IrS7hPiM9WZl:-K4wU0fH0GJXWntBRTec:585722568) ([raw file](https://github.com/softlayer/sl-ember-components/blob/19e2fc53af765203c9433651e39155c77035a983/addon/templates/components/sl-calendar.hbs#L8)):*
`sr-only` is meant for text e.g

```
 <span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>
  <span id="inputSuccess5Status" class="sr-only">(success)</span>
```

The glyph will still show because it does not have the `.sr-only` class. The text however will not be displayed because of the `sr-only` class. 

What it comes down to is, do we want to go with what bootstrap provides us out of the box, or with our own implementation. BS4 also has this class present, I don't see any mention of it being removed/modified, unless I missed something.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1209)*

**Comment by azizpunjani** [comment]
*[addon/templates/components/sl-calendar.hbs, line 8 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1209#-K4i5xe5IrS7hPiM9WZl:-K4wW-bxUBjwRAOhCmm0:1267900465) ([raw file](https://github.com/softlayer/sl-ember-components/blob/19e2fc53af765203c9433651e39155c77035a983/addon/templates/components/sl-calendar.hbs#L8)):*
I guess the other difference is that in order to use the `sr-only` class we have to wrap the text in another element. The Bootstrap way is a little more work than what we currently have to do.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1209)*

**Comment by notmessenger** [comment]
*[addon/templates/components/sl-calendar.hbs, line 8 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1209#-K4i5xe5IrS7hPiM9WZl:-K4wfdS0QiSFbU5uzXQ0:848386228) ([raw file](https://github.com/softlayer/sl-ember-components/blob/19e2fc53af765203c9433651e39155c77035a983/addon/templates/components/sl-calendar.hbs#L8)):*
My vote would be that we do it the Bootstrap way, otherwise why are we using it?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1209)*

**Comment by notmessenger** [comment]
Reviewed 3 of 4 files at r5.
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1209)*

**Pull request merged**
