### PR TITLE
Implemented fix for CSP warning

### PR DESCRIPTION
**Pull request by juwara0**
Closes softlayer/sl-ember-components#852

[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1186)

### CODE REVIEW

**Comment by notmessenger** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1186)_

**Comment by notmessenger** [comment]
Weren't you going to put the aria attribute bindings in this PR?  If not, create an issue to do so.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1186#-:-K3LzZN1bjNcTybDYGcp:2083550300)_

**Comment by azizpunjani** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1186)_

**Comment by juwara0** [comment]
@notmessenger: You are correct. I was going to but since the component is not being split into a subcomponent I cannot since those attributes live on the child div element which we create in the sl-progress-bar template

---







_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1186#-:-K3M-hDKzF9tZXpQhRa5:1582256663)_

**Pull request merged**
