### PR TITLE
update Ember.assert to Ember.Error, Close #500

### LINKED ISSUE #500: Evaluate use of Ember.assert()
and replace with either `throw new Ember.Error()` or `warn`

### PR DESCRIPTION
**Pull request by Yogeswar**
update Ember.assert to Ember.Error, Close #500 softlayer/sl-ember-components#500

[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1133)

### CODE REVIEW

**Comment by juwara0** [comment]
We need to add tests to validate the calls to Ember.Error() and that they are called with the messages that are listed.


---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[addon/components/sl-tooltip.js, line 44 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1133#-K2s89eGEe9HczbZ3IUS)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/057022bac619ec7cbeba2d16622f41f8177df6bc/addon/components/sl-tooltip.js#L44)):</sup>
Lets break this statement onto multiple lines

throw new Ember.Error(
    'enableTooltip() and enablePopover() expect the parameter' +
    ' "title" and for it to be a string'
);


---

<sup>**[addon/components/sl-tooltip.js, line 50 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1133#-K2s8ge18wWdJ9xLUBYy)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/057022bac619ec7cbeba2d16622f41f8177df6bc/addon/components/sl-tooltip.js#L50)):</sup>
Lets break this statement onto multiple lines

throw new Ember.Error(
    'enablePopover() expects the parameter "popover" and' +
    ' for it to be a string'
);


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1133)

**Comment by juwara0** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[addon/components/sl-tooltip.js, line 44 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1133#-K2s89eGEe9HczbZ3IUS)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/057022bac619ec7cbeba2d16622f41f8177df6bc/addon/components/sl-tooltip.js#L44)):</sup>
```
throw new Ember.Error(
    'enableTooltip() and enablePopover() expect the parameter' +
    ' "title" and for it to be a string'
);
```


---

<sup>**[addon/components/sl-tooltip.js, line 50 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1133#-K2s8ge18wWdJ9xLUBYy)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/057022bac619ec7cbeba2d16622f41f8177df6bc/addon/components/sl-tooltip.js#L50)):</sup>
```
throw new Ember.Error(
    'enablePopover() expects the parameter "popover" and' +
    ' for it to be a string'
);
```


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1133)

**Comment by juwara0** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1133)

**Comment by Yogeswar** [comment]
Tests are already present that test these scenarios


---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[addon/components/sl-tooltip.js, line 44 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1133#-K2s89eGEe9HczbZ3IUS)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/057022bac619ec7cbeba2d16622f41f8177df6bc/addon/components/sl-tooltip.js#L44)):</sup>
done


---

<sup>**[addon/components/sl-tooltip.js, line 50 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1133#-K2s8ge18wWdJ9xLUBYy)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/057022bac619ec7cbeba2d16622f41f8177df6bc/addon/components/sl-tooltip.js#L50)):</sup>
done


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1133)

**Comment by juwara0** [comment]
@notmessenger: This is ready to merge


---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1133)

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

<sup>**[addon/components/sl-tooltip.js, line 36 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1133#-K2xRmrpa_6ugQur_Mpx)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/2fe7a46854ce0e4d7ee95d15e1c4a82824e38992/addon/components/sl-tooltip.js#L36)):</sup>
* Incorrect type


---

<sup>**[addon/components/sl-tooltip.js, line 37 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1133#-K2xRvbWAPQXDp-axrN_)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/2fe7a46854ce0e4d7ee95d15e1c4a82824e38992/addon/components/sl-tooltip.js#L37)):</sup>
Combine into single `@throws`


---

<sup>**[addon/components/sl-tooltip.js, line 43 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1133#-K2xRiM27_uz8N-akauw)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/2fe7a46854ce0e4d7ee95d15e1c4a82824e38992/addon/components/sl-tooltip.js#L43)):</sup>
Should follow https://github.com/softlayer/ember-style-guide/blob/master/javascript.md#conditional-statements


---

<sup>**[addon/components/sl-tooltip.js, line 49 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1133#-K2xRk6_R4-vx6iYk-Pc)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/2fe7a46854ce0e4d7ee95d15e1c4a82824e38992/addon/components/sl-tooltip.js#L49)):</sup>
Should follow https://github.com/softlayer/ember-style-guide/blob/master/javascript.md#conditional-statements


---

<sup>**[addon/components/sl-tooltip.js, line 50 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1133#-K2xRkTHb6MB3322xfmF)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/2fe7a46854ce0e4d7ee95d15e1c4a82824e38992/addon/components/sl-tooltip.js#L50)):</sup>
Should follow https://github.com/softlayer/ember-style-guide/blob/master/javascript.md#conditional-statements


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1133)

**Comment by Yogeswar** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

<sup>**[addon/components/sl-tooltip.js, line 36 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1133#-K2xRmrpa_6ugQur_Mpx)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/2fe7a46854ce0e4d7ee95d15e1c4a82824e38992/addon/components/sl-tooltip.js#L36)):</sup>
Done.


---

<sup>**[addon/components/sl-tooltip.js, line 37 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1133#-K2xRvbWAPQXDp-axrN_)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/2fe7a46854ce0e4d7ee95d15e1c4a82824e38992/addon/components/sl-tooltip.js#L37)):</sup>
Done.


---

<sup>**[addon/components/sl-tooltip.js, line 43 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1133#-K2xRiM27_uz8N-akauw)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/2fe7a46854ce0e4d7ee95d15e1c4a82824e38992/addon/components/sl-tooltip.js#L43)):</sup>
Done.


---

<sup>**[addon/components/sl-tooltip.js, line 49 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1133#-K2xRk6_R4-vx6iYk-Pc)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/2fe7a46854ce0e4d7ee95d15e1c4a82824e38992/addon/components/sl-tooltip.js#L49)):</sup>
Done.


---

<sup>**[addon/components/sl-tooltip.js, line 50 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1133#-K2xRkTHb6MB3322xfmF)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/2fe7a46854ce0e4d7ee95d15e1c4a82824e38992/addon/components/sl-tooltip.js#L50)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1133)

**Comment by juwara0** [comment]
<sup>**[addon/components/sl-tooltip.js, line 36 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1133#-K30iCi6X1_nwC-KnOWc)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/e4ab4920111528f75011c88b8ac16fa7dacb27d5/addon/components/sl-tooltip.js#L36)):</sup>
This should be {ember/Error} 


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1133)

**Comment by juwara0** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1133)

**Comment by Yogeswar** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

<sup>**[addon/components/sl-tooltip.js, line 36 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1133#-K30iCi6X1_nwC-KnOWc)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/e4ab4920111528f75011c88b8ac16fa7dacb27d5/addon/components/sl-tooltip.js#L36)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1133)

**Comment by juwara0** [comment]
@notmessenger: work is completed on this.


---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1133)

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1133)

**Pull request merged**
