### PR TITLE
Closes softlayer/sl-ember-components#563

### PR DESCRIPTION
**Pull request by juwara0**
Fixed deprecation by updating usage to recommended approach of using yielded context
Updated demo app and documentation to reflect new usage

### CODE REVIEW

**Comment by notmessenger** [comment]
Integration tests don't need to be modified?

**Comment by notmessenger** [comment]
Is https://github.com/juwara0/sl-ember-components/blob/563/tests/integration/components/sl-modal-test.js#L291 needed?

**Comment by notmessenger** [comment]
Let's have a conversation about the integration test changes

**Comment by juwara0** [comment]
In response to:
Is https://github.com/juwara0/sl-ember-components/blob/563/tests/integration/components/sl-modal-test.js#L291 needed?

I am not sure? That was not part of my changeset. Let me take a look and I will let you know.

**Pull request merged**
