### PR TITLE
Added additional integration tests for sl-radio

### PR DESCRIPTION
**Pull request by juwara0**
Closes softlayer/sl-ember-components#769

Added additional tests for:
default rendered state
label property
value property

Also added the property inline: false to the component since it was missing.

No tests were written for:
readonly property, since it is no longer part of this component
id is set to inputId, since it is no longer set in the template
name property, since the test was already written

[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1087)

### CODE REVIEW

**Comment by azizpunjani** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

<sup>**[tests/integration/components/sl-radio-test.js, line 26 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1087#-K2lXcQeck1L-TtMNiHL)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/06f824c3d9d9fd4cd9e8ab0561f9aeafe49cbdd3/tests/integration/components/sl-radio-test.js#L26)):</sup>
This assert will always be true because find will always return a jQuery object either with or without a collection (always truthy). Instead, do a strictEqual to check that length is 1.

`assert.strictEqual(
    this.$( '>:first-child' ).find( 'input[type="radio"]' ).length,
    1
);`


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1087)

**Comment by juwara0** [comment]
<sup>**[tests/integration/components/sl-radio-test.js, line 26 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1087#-K2lXcQeck1L-TtMNiHL)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/06f824c3d9d9fd4cd9e8ab0561f9aeafe49cbdd3/tests/integration/components/sl-radio-test.js#L26)):</sup>
RESOLVED


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1087)

**Comment by azizpunjani** [comment]
Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1087)

**Comment by notmessenger** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

<sup>**[tests/integration/components/sl-radio-test.js, line 82 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1087#-K3FpPeZ1ktePezmGPDv)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/aa078fc009c89dbf8857551b7c991d4b9b522b58/tests/integration/components/sl-radio-test.js#L82)):</sup>
I'm not sure we need this assertion.


---

<sup>**[tests/integration/components/sl-radio-test.js, line 104 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1087#-K3FojC3vChFOZHv6deP)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/aa078fc009c89dbf8857551b7c991d4b9b522b58/tests/integration/components/sl-radio-test.js#L104)):</sup>
Is this assertion needed, as its absence is asserted (by not being asserted) in the default state test case?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1087)

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1087)

**Pull request merged**
