### PR TITLE
Deprecation thrown in testing suite console

### PR DESCRIPTION
**Pull request by erangeles**
[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1441)

### CODE REVIEW

**Comment by juwara0** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/integration/components/sl-grid-cell-test.js, line 19 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1441#-K98G-f26LmXBwtxS2qE:-K98G-f26LmXBwtxS2qF:1595405734) ([raw file](https://github.com/softlayer/sl-ember-components/blob/a70c6eb2a574b08232d04c95cb9eaa5358ae336b/tests/integration/components/sl-grid-cell-test.js#L19)):*
In https://github.com/softlayer/sl-ember-components/commit/5f51b6b47ac7e079fcccada36ba205e10e89224b the row property was changed to record but this test was never updated. Instead of the changes in this PR please make the change to the line above by changing row=row to record=record and update the variables row, defaultRow as well to cell and defaultCell.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1441)*

**Comment by juwara0** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1441)*

**Comment by SpikedKira** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tests/integration/components/sl-grid-cell-test.js, line 25 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1441#-K98dn0WvTpvx1Mu5vXk:-K98dn0WvTpvx1Mu5vXl:-315084433) ([raw file](https://github.com/softlayer/sl-ember-components/blob/a4db4b62c3404269f7057a5d2cc0ee6f03058e2c/tests/integration/components/sl-grid-cell-test.js#L25)):*
Instead of changing the names, why is row even here? Is this necessary?

---

*[tests/integration/components/sl-grid-cell-test.js, line 47 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1441#-K98dtuAq1XDLe6OSJif:-K98dtuAq1XDLe6OSJig:-1823334490) ([raw file](https://github.com/softlayer/sl-ember-components/blob/a4db4b62c3404269f7057a5d2cc0ee6f03058e2c/tests/integration/components/sl-grid-cell-test.js#L47)):*
Same as above.  Please check if this is even needed.  I think not.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1441)*

**Comment by erangeles** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[tests/integration/components/sl-grid-cell-test.js, line 19 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1441#-K98G-f26LmXBwtxS2qE:-K98r1rhcBMcDw9VfL_u:1465820938) ([raw file](https://github.com/softlayer/sl-ember-components/blob/a70c6eb2a574b08232d04c95cb9eaa5358ae336b/tests/integration/components/sl-grid-cell-test.js#L19)):*
updating the var names in this variable didn't resolve the deprecation. updated the var names and left the fix that resolved the deprecation. 

---

*[tests/integration/components/sl-grid-cell-test.js, line 25 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1441#-K98dn0WvTpvx1Mu5vXk:-K98rLR4ZyVaWh0GP9yd:1744915597) ([raw file](https://github.com/softlayer/sl-ember-components/blob/a4db4b62c3404269f7057a5d2cc0ee6f03058e2c/tests/integration/components/sl-grid-cell-test.js#L25)):*
necessary, removing causes deprecation to be thrown.

---

*[tests/integration/components/sl-grid-cell-test.js, line 47 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1441#-K98dtuAq1XDLe6OSJif:-K98rUC8Mtu4JKU3svL4:1744915597) ([raw file](https://github.com/softlayer/sl-ember-components/blob/a4db4b62c3404269f7057a5d2cc0ee6f03058e2c/tests/integration/components/sl-grid-cell-test.js#L47)):*
necessary, removing causes deprecation to be thrown.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1441)*

**Comment by erangeles** [comment]
*[tests/integration/components/sl-grid-cell-test.js, line 19 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1441#-K98G-f26LmXBwtxS2qE:-K98yTW5Tt1LrYtaTaKq:-881082877) ([raw file](https://github.com/softlayer/sl-ember-components/blob/a70c6eb2a574b08232d04c95cb9eaa5358ae336b/tests/integration/components/sl-grid-cell-test.js#L19)):*
disregard my last comment. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1441)*

**Comment by erangeles** [comment]
*[tests/integration/components/sl-grid-cell-test.js, line 25 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1441#-K98dn0WvTpvx1Mu5vXk:-K98yWj-vuFNCsz2S-uE:-1829537347) ([raw file](https://github.com/softlayer/sl-ember-components/blob/a4db4b62c3404269f7057a5d2cc0ee6f03058e2c/tests/integration/components/sl-grid-cell-test.js#L25)):*
disregard my last comment.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1441)*

**Comment by SpikedKira** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[addon/components/sl-grid-cell.js, line 122 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1441#-K992vFeKBhM7ZjTjZIK:-K992vFeKBhM7ZjTjZIL:1530880445) ([raw file](https://github.com/softlayer/sl-ember-components/blob/efa14f4fa70fc7156a130e0c1e315edf5b0e5e0d/addon/components/sl-grid-cell.js#L122)):*
Consider reusing record const from memory instead of getting again

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1441)*

**Comment by juwara0** [comment]
Reviewed 1 of 2 files at r3.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/integration/components/sl-grid-cell-test.js, line 26 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1441#-K9965N67Bn6lLc2NUI1:-K9965N67Bn6lLc2NUI2:-1208725835) ([raw file](https://github.com/softlayer/sl-ember-components/blob/efa14f4fa70fc7156a130e0c1e315edf5b0e5e0d/tests/integration/components/sl-grid-cell-test.js#L26)):*
Since this is used twice lets make this a columnTemplate, like defaultTemplate before, and use it here and in the next test as well.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1441)*

**Comment by juwara0** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[addon/components/sl-grid-cell.js, line 122 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1441#-K992vFeKBhM7ZjTjZIK:-K998HhHPkQr0PIjGees:2035277621) ([raw file](https://github.com/softlayer/sl-ember-components/blob/efa14f4fa70fc7156a130e0c1e315edf5b0e5e0d/addon/components/sl-grid-cell.js#L122)):*
You can remove this changeset. It is not necessary.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1441)*

**Comment by juwara0** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1441)*

**Comment by juwara0** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[addon/components/sl-grid-cell.js, line 122 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1441#-K992vFeKBhM7ZjTjZIK:-K99A3Hf-vBPFIoFDmkW:471484289) ([raw file](https://github.com/softlayer/sl-ember-components/blob/efa14f4fa70fc7156a130e0c1e315edf5b0e5e0d/addon/components/sl-grid-cell.js#L122)):*
.get( ' record' ) will return the value or null. Additionally, we have the default of record set to null.

http://emberjs.com/api/#method_get

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1441)*

**Comment by juwara0** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[addon/components/sl-grid-cell.js, line 122 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1441#-K992vFeKBhM7ZjTjZIK:-K99FUITjgWtOXgEDJmy:-103828315) ([raw file](https://github.com/softlayer/sl-ember-components/blob/efa14f4fa70fc7156a130e0c1e315edf5b0e5e0d/addon/components/sl-grid-cell.js#L122)):*
I am incorrect. Disregard my comments above. I understand what is going on. Ember.get( object, ... ) is being called with object being null since this.get( 'record' ) is returning a null.
 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1441)*

**Comment by erangeles** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[addon/components/sl-grid-cell.js, line 122 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1441#-K992vFeKBhM7ZjTjZIK:-K99NYd0nagDXxdeCaqV:-499146009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/efa14f4fa70fc7156a130e0c1e315edf5b0e5e0d/addon/components/sl-grid-cell.js#L122)):*
Done.

---

*[tests/integration/components/sl-grid-cell-test.js, line 26 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1441#-K9965N67Bn6lLc2NUI1:-K99NWSu_zJh7VKqhePf:-499146009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/efa14f4fa70fc7156a130e0c1e315edf5b0e5e0d/tests/integration/components/sl-grid-cell-test.js#L26)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1441)*

**Comment by juwara0** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/integration/components/sl-grid-cell-test.js, line 26 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1441#-K9965N67Bn6lLc2NUI1:-K9XLaGgQWkIJL_ylLhD:-1665209347) ([raw file](https://github.com/softlayer/sl-ember-components/blob/efa14f4fa70fc7156a130e0c1e315edf5b0e5e0d/tests/integration/components/sl-grid-cell-test.js#L26)):*
RESOLVED

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1441)*

**Comment by notmessenger** [comment]
No documentation in the demo app needs to be updated to reflect these changes?

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[addon/components/sl-grid-cell.js, line 63 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1441#-K9Z7SUAB04xkwfLET7z:-K9Z7SUAB04xkwfLET8-:2050900896) ([raw file](https://github.com/softlayer/sl-ember-components/blob/f65b4f6cdfc26fd64f8392cc9044ce454d349c4e/addon/components/sl-grid-cell.js#L63)):*
Can this still be null?

---

*[addon/components/sl-grid-cell.js, line 70 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1441#-K9Z7W0bsiNbj3Cm8rcP:-K9Z7W0bsiNbj3Cm8rcQ:2050900896) ([raw file](https://github.com/softlayer/sl-ember-components/blob/f65b4f6cdfc26fd64f8392cc9044ce454d349c4e/addon/components/sl-grid-cell.js#L70)):*
Can this still be null?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1441#-:-K9Z8UWejxwRjiiemPf_:1996195695)*

**Comment by erangeles** [comment]
@notmessenger the types did not change but we could be a bit more clear with the description text. Also regarding the type null comments. The deprecation of "Calling Ember.get without a target object has been deprecated, please specify a target object." is thrown due to the fact that we have a null type representing an object and in the contentValue computed method we call a this.get on it when it can be null. Jeff and Micheal and I agreed that setting an object as an empty object would make it easier to work with the properties of "column, record" as we would not get "non-object" errors in the future and prevent deprecations like the ones we fixed with this PR.

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1441#-:-K9hK7MVcyOnLkrkAFEp:63521983)*

**Comment by erangeles** [comment]
Review status: 2 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[addon/components/sl-grid-cell.js, line 63 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1441#-K9Z7SUAB04xkwfLET7z:-K9hLOfGSkw2K0o2yce1:-499146009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/f65b4f6cdfc26fd64f8392cc9044ce454d349c4e/addon/components/sl-grid-cell.js#L63)):*
Done.

---

*[addon/components/sl-grid-cell.js, line 70 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1441#-K9Z7W0bsiNbj3Cm8rcP:-K9hLP3iOrksANorznmB:-499146009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/f65b4f6cdfc26fd64f8392cc9044ce454d349c4e/addon/components/sl-grid-cell.js#L70)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1441)*

**Comment by juwara0** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1441)*

**Comment by notmessenger** [comment]
* Let's be more clear in the description text then
* My comments about nullable were to draw attention to the fact that the `@type`s were incorrect, which you have fixed

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1441#-:-K9igXSi47jTVFIujrjn:887073906)*

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tests/dummy/app/templates/demos/sl-grid.hbs, line 114 \[r6\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1441#-K9nb_1uCeBMnOb1JInf:-K9nb_1uCeBMnOb1JIng:-1553571171) ([raw file](https://github.com/softlayer/sl-ember-components/blob/4d078c5fceec9c99e72ed5b1bbfdf9bc9ff40d6f/tests/dummy/app/templates/demos/sl-grid.hbs#L114)):*
Didn't realize this is what you were meaning in regards to more descriptive text.  Let's revert this change.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1441)*

**Comment by juwara0** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1441)*

**Comment by erangeles** [comment]
*[tests/dummy/app/templates/demos/sl-grid.hbs, line 114 \[r6\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1441#-K9nb_1uCeBMnOb1JInf:-KA0TyDXbmQ4Zb0dfXY4:593451939) ([raw file](https://github.com/softlayer/sl-ember-components/blob/4d078c5fceec9c99e72ed5b1bbfdf9bc9ff40d6f/tests/dummy/app/templates/demos/sl-grid.hbs#L114)):*
reverting this change.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1441)*

**Comment by juwara0** [comment]
*[addon/components/sl-grid-cell.js, line 122 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1441#-K992vFeKBhM7ZjTjZIK:-KA0UgW3PUX-qnCkbY5E:-1665209347) ([raw file](https://github.com/softlayer/sl-ember-components/blob/efa14f4fa70fc7156a130e0c1e315edf5b0e5e0d/addon/components/sl-grid-cell.js#L122)):*
RESOLVED

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1441)*

**Comment by erangeles** [comment]
@juwara0 ready to be merged in.

**Comment by juwara0** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1441)*

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1441)*

**Pull request merged**
