### PR TITLE
Create Unit test to assert properties observed by Ember.observer()

### PR DESCRIPTION
**Pull request by erangeles**
[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1116)

### CODE REVIEW

**Comment by juwara0** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[tests/unit/components/sl-tab-panel-test.js, line 394 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1116#-K2wROch0jvp3hr2GrP_)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/4b53a6d05b8e33f21e552233f26272659aebf812/tests/unit/components/sl-tab-panel-test.js#L394)):</sup>
You need to add a blank line here to pass listing.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1116)

**Comment by erangeles** [comment]
@juwara0 github doesnt show the empty line by default, it is present and has passed linting in the build. ready to merge.

**Comment by juwara0** [comment]
@notmessenger: this is ready to merge


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1116)

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1116)

**Pull request merged**
