### PR TITLE
Issue 765

### PR DESCRIPTION
**Pull request by SpikedKira**
[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/952)

### CODE REVIEW

**Comment by SpikedKira** [comment]
Test for ariaLabelledBy omitted.  Please advise special case.

**Comment by notmessenger** [comment]
* The modal component as an entire set of functionality is comprised of the modal, modal-body, modal-header, and modal-footer components.  As such, unit tests need to created for them as well as part of this issue's development
* `setupStreamActions()` has not tests against it
* `setupModal()` has not tests against it
* `unbindHandlers()` has not tests against it

* The tests for `ariaLabelledBy` having been omitted - a PR is not when to raise this.  Since we all have access to one another in person assistance should have been sought out and then the PR represent the final proposed solution for the issue resolving.  The reason for this is to ensure the PR does not get accidentally merged in and this missing functionality is overlooked.  Regarding how to test it, in addition to the separate comment about asserting its default value, `setLabelledby()`is the method that needs to be exercised to test this.  Given the nature of the values it is using (i.e. `elementId`) it is more appropriate to assert this logic in the integration test.  Confirm that it is being done so.  If it is not then add that change to this change set.


---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[tests/unit/components/sl-modal-test.js, line 10 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/952#-K1AlsLyi1hV_RfgUxeS)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/3c3f3aabd27ab2e3339cefb1f37bacdacde5125c/tests/unit/components/sl-modal-test.js#L10)):</sup>
All other component tests label this test suite `Expected Mixins are present`


---

<sup>**[tests/unit/components/sl-modal-test.js, line 42 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/952#-K1An384_Gi-tNWCOH3o)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/3c3f3aabd27ab2e3339cefb1f37bacdacde5125c/tests/unit/components/sl-modal-test.js#L42)):</sup>
Missing assertion for `ariaLabelledBy` property


---

<sup>**[tests/unit/components/sl-modal-test.js, line 100 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/952#-K1AnZJHS8rnnBdBC9JY)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/3c3f3aabd27ab2e3339cefb1f37bacdacde5125c/tests/unit/components/sl-modal-test.js#L100)):</sup>
Is this necessary?  If so, also add to the "hide() calls bootstrap modal hide" test case.  If not, then remove it.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/952)

**Comment by SpikedKira** [comment]
sub-components: honestly forgot about them, will commit shortly
setupStreamActions: added
setupModal: events tested; rest of the function is inherently tested in integration
unbindHandlers: event unbinding test added
ariaLabelledBy: understood; test in integration


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/952)

**Comment by SpikedKira** [comment]
<sup>**[tests/unit/components/sl-modal-test.js, line 10 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/952#-K1AlsLyi1hV_RfgUxeS)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/3c3f3aabd27ab2e3339cefb1f37bacdacde5125c/tests/unit/components/sl-modal-test.js#L10)):</sup>
changed. for the record, this phrasing was lifted from sl-button-test.js


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/952)

**Comment by SpikedKira** [comment]
<sup>**[tests/unit/components/sl-modal-test.js, line 42 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/952#-K1An384_Gi-tNWCOH3o)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/3c3f3aabd27ab2e3339cefb1f37bacdacde5125c/tests/unit/components/sl-modal-test.js#L42)):</sup>
this one is in integration


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/952)

**Comment by SpikedKira** [comment]
<sup>**[tests/unit/components/sl-modal-test.js, line 100 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/952#-K1AnZJHS8rnnBdBC9JY)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/3c3f3aabd27ab2e3339cefb1f37bacdacde5125c/tests/unit/components/sl-modal-test.js#L100)):</sup>
necessary to cleanup tests run in browser (modal shroud)


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/952)

**Comment by SpikedKira** [comment]
not ready for review... will comment


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/952)

**Comment by SpikedKira** [comment]
now ready for review


---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/952)

**Comment by notmessenger** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[tests/unit/components/sl-modal-header-test.js, line 15 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/952#-K1K3ECkTqg0oeohtSWd)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/b0dd9e2230ac4c05d3ba6f49e39bde7e0da0505f/tests/unit/components/sl-modal-header-test.js#L15)):</sup>
The `tagName` property should be removed from the `addon/components/sl-modal-header.js` file, and then this file can be removed entirely.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/952)

**Comment by SpikedKira** [comment]
That last commit will also close #948 


---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/952)

**Comment by notmessenger** [comment]
Reviewed 1 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/952)

**Pull request merged**
