### PR TITLE
Events code refactor. Closes #1300

### LINKED ISSUE #1300: Refactor to align with updated style guide
https://github.com/softlayer/ember-style-guide#defining-functions-to-be-called-when-events-are-triggered 

* `didInsertElement()` - https://github.com/softlayer/sl-ember-components/blob/v0.11.0/addon/components/sl-tab-panel.js#L78

### PR DESCRIPTION
**Pull request by azizpunjani**
[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1345)

### CODE REVIEW

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[addon/components/sl-tab-panel.js, line 56 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1345#-K6nKhqam5mi9yjRj679:-K6nKhqam5mi9yjRj67A:-2074900241) ([raw file](https://github.com/softlayer/sl-ember-components/blob/78fa7816e9bd32e9c2b8d3a6cc4351026ee9d9b8/addon/components/sl-tab-panel.js#L56)):*
The reason for including this is to be pro-active against future use of mixins which may have logic defined for this same hook.  As such, would we want `this._super()` to be more likely to be called after our own logic has ran and before?  Should we change the execution order of this method's logic?

---

*[addon/components/sl-tab-panel.js, line 67 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1345#-K6nKcBmrLApxM47Xvsp:-K6nKcBnOCrsvVMzjkC4:-795624428) ([raw file](https://github.com/softlayer/sl-ember-components/blob/78fa7816e9bd32e9c2b8d3a6cc4351026ee9d9b8/addon/components/sl-tab-panel.js#L67)):*
This should be in the "Methods" section.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1345)*

**Comment by notmessenger** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[addon/components/sl-tab-panel.js, line 63 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1345#-K6nOG3mLp0-bGG0L1IQ:-K6nOG3mLp0-bGG0L1IR:-762944275) ([raw file](https://github.com/softlayer/sl-ember-components/blob/78fa7816e9bd32e9c2b8d3a6cc4351026ee9d9b8/addon/components/sl-tab-panel.js#L63)):*
Do we want to mark this method as `@private`?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1345)*

**Comment by notmessenger** [comment]
Please merge latest changes from v0.11.0 branch so that tests can run.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1345#-:-K7H0oo9p8iaktpkUuU0:-1598593342)*

**Comment by azizpunjani** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[addon/components/sl-tab-panel.js, line 56 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1345#-K6nKhqam5mi9yjRj679:-K7H2vJKmyfK4vR0_sBB:-1021942592) ([raw file](https://github.com/softlayer/sl-ember-components/blob/78fa7816e9bd32e9c2b8d3a6cc4351026ee9d9b8/addon/components/sl-tab-panel.js#L56)):*
As we decided, we will call super before other logic in this function, in the future a developer may want to change the order as they say see fit.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1345)*

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1345)*

**Pull request merged**
