### PR TITLE
Closes softlayer/sl-ember-components#1306

### PR DESCRIPTION
**Pull request by SpikedKira**
removed unnecessary class "presentation"

[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1421)

### CODE REVIEW

**Comment by notmessenger** [comment]
The role of the element with the "divider" class should be "separator" not "menuItem"

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1421#-:-K8LSLH91oxEVDps5Iyf:-1664591156)*

**Comment by notmessenger** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[addon/components/sl-drop-option.js, line 89 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1421#-K8_fz76rg5fqsf0BDwk:-K8_fz76rg5fqsf0BDwl:1901648882) ([raw file](https://github.com/softlayer/sl-ember-components/blob/0ff8359d5f96195f6f3d824bf82a3b43966e0cda/addon/components/sl-drop-option.js#L89)):*
@azizpunjani @juwara0 What are your thoughts on the use of the is `const` rather than just using the `get()` call directly in the ternary?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1421)*

**Comment by notmessenger** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1421)*

**Comment by azizpunjani** [comment]
*[addon/components/sl-drop-option.js, line 89 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1421#-K8_fz76rg5fqsf0BDwk:-K8_km54BeXdcXJNGc35:-1813581550) ([raw file](https://github.com/softlayer/sl-ember-components/blob/0ff8359d5f96195f6f3d824bf82a3b43966e0cda/addon/components/sl-drop-option.js#L89)):*
I'm fine with this, although my personal preference would be `this.get( 'isDivider' ) ? 'separator' : 'menuitem';` which is concise and just as readable.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1421)*

**Comment by juwara0** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[addon/components/sl-drop-option.js, line 89 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1421#-K8_fz76rg5fqsf0BDwk:-K8_kTPho69II4zNioIj:-36432375) ([raw file](https://github.com/softlayer/sl-ember-components/blob/0ff8359d5f96195f6f3d824bf82a3b43966e0cda/addon/components/sl-drop-option.js#L89)):*
I feel like `return this.get( 'isDivider' ) ? 'separator' : 'menu item';` is cleaner unless the result of the `this.get( 'isDivider' ) ` is needed elsewhere.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1421)*

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1421)*

**Pull request merged**
