### PR TITLE
Closes softlayer/sl-ember-components#1179

### PR DESCRIPTION
**Pull request by SpikedKira**
[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1180)

### CODE REVIEW

**Comment by notmessenger** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[addon/templates/components/sl-modal.hbs, line 1 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1180#-K3IYRQ_IXc6m4Opmv3n)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/1ab38ec20ac66883329988984264f034b409df23/addon/templates/components/sl-modal.hbs#L1)):</sup>
This can't be done via a class name binding?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1180)

**Comment by notmessenger** [comment]
Specifying the `size` does not change the size of the modal, but instead the size of the font used inside it.


---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1180)

**Comment by azizpunjani** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

_[tests/dummy/app/templates/demos/sl-modal.hbs, line 166 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1180#-K3LLXsWiAW4r1RS2j6a:-K3LLXsWiAW4r1RS2j6b:-1046065369) ([raw file](https://github.com/softlayer/sl-ember-components/blob/1ab38ec20ac66883329988984264f034b409df23/tests/dummy/app/templates/demos/sl-modal.hbs#L166)):_
"small", "medium" etc is not a class though right? It's a property value? So maybe, "..designated by a size value of "small", "medium" (default) or "large""

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1180)_

**Comment by SpikedKira** [comment]
Good catch; I messed up.


---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[addon/templates/components/sl-modal.hbs, line 1 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1180#-K3IYRQ_IXc6m4Opmv3n)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/1ab38ec20ac66883329988984264f034b409df23/addon/templates/components/sl-modal.hbs#L1)):</sup>
can you class bind to a child element?


---

<sup>**[tests/dummy/app/templates/demos/sl-modal.hbs, line 166 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1180#-K3LLXsWiAW4r1RS2j6a)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/1ab38ec20ac66883329988984264f034b409df23/tests/dummy/app/templates/demos/sl-modal.hbs#L166)):</sup>
yeah, I messed up this implementation.  I am fixing it.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1180)

**Comment by notmessenger** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

_[addon/components/sl-modal.js, line 12 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1180#-K3L_Scg-4nUNWlF-EBH:-K3L_Scg-4nUNWlF-EBI:863443626) ([raw file](https://github.com/softlayer/sl-ember-components/blob/504a698a04ae2a96047e335850f1345841e03423/addon/components/sl-modal.js#L12)):_
Do you want to move this to the theme file like did in other PR?

---

_[addon/templates/components/sl-modal.hbs, line 1 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1180#-K3IYRQ_IXc6m4Opmv3n:-K3LYgLmcDyiAnAehIv1:1364336709) ([raw file](https://github.com/softlayer/sl-ember-components/blob/1ab38ec20ac66883329988984264f034b409df23/addon/templates/components/sl-modal.hbs#L1)):_
oh yeah, forgot it's a much of nested divs and that class has to go on that one.  never mind then

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1180)_

**Comment by SpikedKira** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[addon/components/sl-modal.js, line 12 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1180#-K3L_Scg-4nUNWlF-EBH)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/504a698a04ae2a96047e335850f1345841e03423/addon/components/sl-modal.js#L12)):</sup>
Not sure yet.  Need to go through and see how often "small", "medium", "large" is used.  I think more often there is a 4th "extra small".


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1180)

**Comment by azizpunjani** [comment]
Need to add in tests for this new property. If it's not being done in this PR, is there an issue open for it?

---







_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1180#-:-K3LkwERKBXVVrLCBDwd:-2129643233)_

**Comment by azizpunjani** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1180)_

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1180)_

**Pull request merged**
