### PR TITLE
Fixed bubbling of click event in sl-menu-item-show-all

### PR DESCRIPTION
**Pull request by juwara0**
Closes softlayer/sl-ember-components#1486

[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1487)

### CODE REVIEW

**Comment by erangeles** [comment]
*[addon/components/sl-menu-item-show-all.js, line 28 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1487#-KAq2xtTgseNrfWrOL9R:-KAq2xtTgseNrfWrOL9S:-977216469) ([raw file](https://github.com/softlayer/sl-ember-components/blob/e3ed2c050cb6004c117c43268c898857489da848/addon/components/sl-menu-item-show-all.js#L28)):*
erroneous indention.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1487)*

**Comment by erangeles** [comment]
@juwara0 is there no testing required for this change set? 

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1487#-:-KAq3XPY7M-1a5zM85W6:2095325193)*

**Comment by erangeles** [comment]
https://github.com/softlayer/sl-ember-components/blob/7e6c655b485cdcfbd92014d80654a455a2acd675/tests/integration/components/sl-menu-test.js#L370

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1487#-:-KAq4Q2J2dUR71QcBlbq:794695096)*

**Comment by azizpunjani** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[addon/templates/components/sl-menu-item-show-all.hbs, line 1 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1487#-KAq5NLxJXkyoEgQXTDV:-KAq5NLxJXkyoEgQXTDW:-1069164647) ([raw file](https://github.com/softlayer/sl-ember-components/blob/e3ed2c050cb6004c117c43268c898857489da848/addon/templates/components/sl-menu-item-show-all.hbs#L1)):*
I don't see a reason to prevent the event from bubbling/propagating here. As much as possible, we should not stop the event
from propagating unless absolutely necessary. One concrete reason is that we do not know what events the consuming application, or 
end users who are extending our components want to wire up to.

E.g If when tracking all clicks on the page using a global event handler, or there's a third party script tracking clicks, with
code such as this:

```
	$(document).click(function( e ){
		console.log( 'Element was clicked', e.target );

		//ajax request to log click on page and what element was clicked
	});
```

In this case the click on the "Show All" link will not propagate and not get captured.

The specific usecase for preventing event propagation is if clicking the element has unwanted side effects, such as the scenario below outlined in the docs:

```
{{#link-to 'post'}}
  Post
  <button {{action 'close' bubbles=false}}>✗</button>
{{/link-to}}
```

In this scenario clicking on the button would also navigate to the `post` route, which is an unintended side effect, hence
using bubbles=false here is necessary.

If we still think we need `bubbles=false` please share code and scenarios that I may not have accounted for.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1487)*

**Comment by azizpunjani** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1487)*

**Comment by juwara0** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[addon/components/sl-menu-item-show-all.js, line 28 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1487#-KAq2xtTgseNrfWrOL9R:-KAttILJzAea07uoK7p4:-499146009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/e3ed2c050cb6004c117c43268c898857489da848/addon/components/sl-menu-item-show-all.js#L28)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1487)*

**Comment by notmessenger** [comment]
Until https://github.com/softlayer/sl-ember-components/issues/1488 is resolved this PR cannot be fully tested, as does this approach also capture selection of the link via `enter` press?

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[addon/templates/components/sl-menu-item-show-all.hbs, line 1 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1487#-KAq5NLxJXkyoEgQXTDV:-KBA2GDsMDwixzZ6jPmX:1712634868) ([raw file](https://github.com/softlayer/sl-ember-components/blob/e3ed2c050cb6004c117c43268c898857489da848/addon/templates/components/sl-menu-item-show-all.hbs#L1)):*
I understand what you are saying @azizpunjani but the other menu item's click event are already being suppressed because of `{{action}}` syntax, as well the only target information this link would provide is `#`.

If you have another way to resolve this we're open to suggestions.

---

*[addon/templates/components/sl-menu-item-show-all.hbs, line 1 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1487#-KBA20OmgB2vuu7rAmz3:-KBA20OmgB2vuu7rAmz4:-933714239) ([raw file](https://github.com/softlayer/sl-ember-components/blob/d10b674fb2730146c712d4cb75dd99b27d71fe7b/addon/templates/components/sl-menu-item-show-all.hbs#L1)):*
Use double quotes around "click"

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1487#-:-KBA2CazLUKB8pqm6Cl-:-1640120815)*

**Comment by azizpunjani** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[addon/templates/components/sl-menu-item-show-all.hbs, line 1 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1487#-KAq5NLxJXkyoEgQXTDV:-KBAwBiBxc8CKfDkHaSf:-371191685) ([raw file](https://github.com/softlayer/sl-ember-components/blob/e3ed2c050cb6004c117c43268c898857489da848/addon/templates/components/sl-menu-item-show-all.hbs#L1)):*
The way to resolve it is simply do 

```
<a href="#" {{action 'click'}} class="sl-icon-show-all">Show All</a>`
```
 that should prevent the link from navigating to `/#` when clicked, there's not a need for `bubbles=false`.

> "the other menu item's click event are already being suppressed because of {{action}} syntax"

Yes, whenever you use the {{action}} helper `preventDefault=true` is implied, hence clicking the link will *not* navigate to the href on the link. This is exactly what we want, we shouldn't need the additional `bubbles=false`. If you notice we don't use it on [sl-menu-item](https://github.com/softlayer/sl-ember-components/blob/v0.11.0/addon/templates/components/sl-menu-item.hbs)  links either.

If we are advocating for `bubbles=false` whenever using links within our components, why are we not putting it on all links we use an action helper on? Why only this one?

Again, a very subtle point I'm trying to get across, `event.preventDefault()` vs `event.stopPropagation()`. We need `event.preventDefault()` in our case which is already `true` whenever we use the `{{action}}` helper, that's not my issue. My issue is `bubbles=false` which is `event.stopPropagation()`, we don't need that in this particular case.

Please read https://css-tricks.com/dangers-stopping-event-propagation/ for further clarification on the differences and why we should not prevent the event form bubbling i.e `event.stopPropagation()`, unless absolutely necessary.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1487)*

**Comment by juwara0** [comment]
I tested this fix against the `enter` press as well.

---

Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[addon/templates/components/sl-menu-item-show-all.hbs, line 1 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1487#-KAq5NLxJXkyoEgQXTDV:-KBDTxYC2yRGqiDFmf1l:-499146009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/e3ed2c050cb6004c117c43268c898857489da848/addon/templates/components/sl-menu-item-show-all.hbs#L1)):*
Done.

---

*[addon/templates/components/sl-menu-item-show-all.hbs, line 1 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1487#-KBA20OmgB2vuu7rAmz3:-KBDTFEKMv-Jk-33pyKo:-499146009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/d10b674fb2730146c712d4cb75dd99b27d71fe7b/addon/templates/components/sl-menu-item-show-all.hbs#L1)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1487#-:-KBDT4dL8HsW0zkWtTtv:-381494289)*

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1487)*

**Comment by notmessenger** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1487)*

**Pull request merged**
