### PR TITLE
Updated demo app documentation with CSS namespacing information

### PR DESCRIPTION
**Pull request by juwara0**
Closes softlayer/sl-ember-components#1387

Added CSS namespacing information to the demo app documentation for each component

[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1484)

### CODE REVIEW

**Comment by azizpunjani** [comment]
@juwara0 @notmessenger I'm wondering if the term "CSS Namespacing" is clear. Really, it's just a class, with a base
prefix, I think before, when we had `.sl-ember-components.alert` it was probably applicable, but not anymore?

IMO, I think it might be more helpful and relevant to the end user if we change the section title to "Custom CSS styling" or "Styling".
Also in the description we should probably state that this is a class they can use to style the respective component. Thoughts?

**Comment by azizpunjani** [comment]
@juwara

---

Reviewed 23 of 23 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1484#-:-KApnrv7Keuh8tH1q-mH:1965882847)*

**Comment by erangeles** [comment]
I think "Custom CSS styling" makes more sense, here is what ionic does http://learn.ionicframework.com/formulas/working-with-sass/ . They are also a component library and allow for custom sass in their component library.

**Comment by erangeles** [comment]
better example http://ionicframework.com/docs/platform-customization/platform-classes.html

**Comment by notmessenger** [comment]
@azizpunjani @erangeles Do you suggest also changing https://github.com/softlayer/sl-ember-components/tree/v0.11.0#customizing-a-components-css-prefix then, since these changes are in sync with it?

---

Reviewed 23 of 23 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1484#-:-KB9nf99FQxgIdD3_Mkq:-614940852)*

**Comment by azizpunjani** [comment]
@notmessenger I'm not sure anything needs to be changed on https://github.com/softlayer/sl-ember-components/tree/v0.11.0#customizing-a-components-css-prefix, it has no mention of CSS namespaces, it talks about a CSS prefix which is accurate. If you think we need to change some of the verbiage please clarify as to which parts need to change.

**Comment by juwara0** [comment]
I have updated the heading to "Custom CSS Styling" and the description text to speak of classes instead of namespaces.

---

Review status: 0 of 23 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1484#-:-KBEIeG6Bw9ijO5RPY9a:458907751)*

**Comment by notmessenger** [comment]
Reviewed 23 of 23 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1484)*

**Pull request merged**
