### PR TITLE
Change Ember.assert to Ember.error, Close #507

### LINKED ISSUE #507: Evaluate use of Ember.assert()
and replace with either `throw new Ember.Error()` or `warn`

### PR DESCRIPTION
**Pull request by Yogeswar**
Change Ember.assert to Ember.error, Close #507 softlayer/sl-ember-components#507

[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1119)

### CODE REVIEW

**Comment by juwara0** [comment]
We need to add a test to validate the call to Ember.Error() and that it is called with the message that is listed.


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1119)

**Comment by juwara0** [comment]
<sup>**[addon/components/sl-radio-group.js, line 81 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1119#-K2s7ahXUzkS2JyFVfcj)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/2f08fe02f260ab253d058656e71f8bfcfe72e0f0/addon/components/sl-radio-group.js#L81)):</sup>
Lets break this statement onto multiple lines. For example:

if ( !name ) {
    throw new  Ember.Error(
        'The name property must be set on the sl-radio-group component'
    );
}


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1119)

**Comment by juwara0** [comment]
<sup>**[addon/components/sl-radio-group.js, line 81 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1119#-K2s7ahXUzkS2JyFVfcj)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/2f08fe02f260ab253d058656e71f8bfcfe72e0f0/addon/components/sl-radio-group.js#L81)):</sup>
Please use correct indenting. For some reason my indenting was not picked up correctly. 


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1119)

**Comment by juwara0** [comment]
<sup>**[addon/components/sl-radio-group.js, line 81 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1119#-K2s7ahXUzkS2JyFVfcj)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/2f08fe02f260ab253d058656e71f8bfcfe72e0f0/addon/components/sl-radio-group.js#L81)):</sup>
```
if ( !name ) {
    throw new Ember.Error(
        'The name property must be set on the sl-radio-group component'
    );
}
```


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1119)

**Comment by juwara0** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1119)

**Comment by Yogeswar** [comment]
Yes, as discussed the tests are being written. Those should have the scenario automatically included. if not. we'll add it later.


---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[addon/components/sl-radio-group.js, line 81 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1119#-K2s7ahXUzkS2JyFVfcj)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/2f08fe02f260ab253d058656e71f8bfcfe72e0f0/addon/components/sl-radio-group.js#L81)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1119)

**Comment by juwara0** [comment]
The test to validate the throwing of the Exception is being tracked here: https://reviewable.io/reviews/softlayer/sl-ember-components/1084#-K2wW4bQpWGUvCJGdMJ7


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1119)

**Comment by juwara0** [comment]
@notmessenger: This is ready to merge


---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1119)

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[addon/components/sl-radio-group.js, line 80 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1119#-K2xOzBJ8ZMOWhqe8ccx)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/577f4a92ad3eb33db01414fcac7ebb060e2707b2/addon/components/sl-radio-group.js#L80)):</sup>
Prefer to see this as `if ( Ember.isEmpty( this.get( 'name' ) ) {` or similar; don't need a `const` to just then use the value and `isEmpty()` (or the appropriate equivalents) are preferred approach to existence checking.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1119)

**Comment by Yogeswar** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[addon/components/sl-radio-group.js, line 80 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1119#-K2xOzBJ8ZMOWhqe8ccx)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/577f4a92ad3eb33db01414fcac7ebb060e2707b2/addon/components/sl-radio-group.js#L80)):</sup>
Changed to Ember.isEmpty(). The constant 'name'  is used below in the function.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1119)

**Comment by juwara0** [comment]
<sup>**[addon/components/sl-radio-group.js, line 72 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1119#-K30iq58p4UlGukVChxo)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/eeb8024041fc50da854a9fe87c5ee296c71de08a/addon/components/sl-radio-group.js#L72)):</sup>
This should be {ember/Error}


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1119)

**Comment by juwara0** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1119)

**Comment by Yogeswar** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[addon/components/sl-radio-group.js, line 72 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1119#-K30iq58p4UlGukVChxo)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/eeb8024041fc50da854a9fe87c5ee296c71de08a/addon/components/sl-radio-group.js#L72)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1119)

**Comment by juwara0** [comment]
@notmessenger: work is completed on this.


---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1119)

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1119)

**Pull request merged**
