### PR TITLE
initial pass at default bootstrap styles for menu

### PR DESCRIPTION
**Pull request by SpikedKira**
[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1135)

### CODE REVIEW

**Comment by notmessenger** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

<sup>**[addon/templates/components/sl-menu-item-show-all.hbs, line 1 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1135#-K2mv4e87D6tv0dX4UFv)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/7c1132f07a9ef987bc4ab5b5b362bb764b14e086/addon/templates/components/sl-menu-item-show-all.hbs#L1)):</sup>
double quotes


---

<sup>**[addon/templates/components/sl-menu-item.hbs, line 2 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1135#-K2mvHz9ZqIRl-5FU0C0)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/7c1132f07a9ef987bc4ab5b5b362bb764b14e086/addon/templates/components/sl-menu-item.hbs#L2)):</sup>
double quotes


---

<sup>**[addon/templates/components/sl-menu-item.hbs, line 4 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1135#-K2mvIuc2okxxJCvPk5D)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/7c1132f07a9ef987bc4ab5b5b362bb764b14e086/addon/templates/components/sl-menu-item.hbs#L4)):</sup>
double quotes


---

<sup>**[app/styles/sl-ember-components.less, line 4 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1135#-K2mxVdV96BHUnJClazr)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/7c1132f07a9ef987bc4ab5b5b362bb764b14e086/app/styles/sl-ember-components.less#L4)):</sup>
Let's rename this to "addon" and addon.less, respectively


---

<sup>**[app/styles/sl-ember-global.less, line 12 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1135#-K2mviUyoQ4Xq1cFsVX7)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/7c1132f07a9ef987bc4ab5b5b362bb764b14e086/app/styles/sl-ember-global.less#L12)):</sup>
empty line before


---

<sup>**[app/styles/sl-menu.less, line 4 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1135#-K2mvchrCpzfFo8KTRnE)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/7c1132f07a9ef987bc4ab5b5b362bb764b14e086/app/styles/sl-menu.less#L4)):</sup>
empty line before


---

<sup>**[app/styles/sl-menu.less, line 7 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1135#-K2mvecOmKdlIvtxaftJ)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/7c1132f07a9ef987bc4ab5b5b362bb764b14e086/app/styles/sl-menu.less#L7)):</sup>
empty line before


---

<sup>**[app/styles/sl-menu.less, line 10 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1135#-K2mvf8NqFIIcFoYpHOa)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/7c1132f07a9ef987bc4ab5b5b362bb764b14e086/app/styles/sl-menu.less#L10)):</sup>
empty line before


---

<sup>**[app/styles/sl-menu.less, line 13 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1135#-K2mvfphY9V66G1CGhbz)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/7c1132f07a9ef987bc4ab5b5b362bb764b14e086/app/styles/sl-menu.less#L13)):</sup>
empty line before


---

<sup>**[app/styles/sl-menu.less, line 17 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1135#-K2mvhL2fR_Bp0jTSv6E)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/7c1132f07a9ef987bc4ab5b5b362bb764b14e086/app/styles/sl-menu.less#L17)):</sup>
empty line before


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1135)

**Comment by SpikedKira** [comment]
this is tested and ready


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1135)

**Comment by notmessenger** [comment]
Reviewed 6 of 7 files at r2.
Review status: 9 of 10 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1135)

**Comment by notmessenger** [comment]
Reviewed 1 of 7 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1135)

**Comment by notmessenger** [comment]
Adhere to https://github.com/softlayer/ember-style-guide/blob/master/javascript.md#whitespace in:
* */sl-ember-components/app/styles/addon.less*
* */sl-ember-components/app/styles/sl-menu.less*

Alphabetize the `@import 'sl-menu';` entry in */sl-ember-components/app/styles/sl-ember-components.less*

When showing all the menu items their class are not their active states.


---

Reviewed 1 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1135)

**Comment by notmessenger** [comment]
The show all arrow seems stronger than it needs to be?


---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1135)

**Comment by SpikedKira** [comment]
Arrow strong b/c bootstrap is out of date; missing 50+ glyphs.

The show all is tricky.  Let's discuss


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1135)

**Comment by notmessenger** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1135)

**Comment by notmessenger** [comment]
The arrow is still emphasized.  What about using the one used in sl-drop-button, for consistency across the components?


---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1135)

**Comment by SpikedKira** [comment]
I was going to revisit the glyphs used on all components after an inital pass at each, and a bootstrap update to get the 50+ extra glyphs. :D


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1135)

**Comment by notmessenger** [comment]
Please create an issue for this.


---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1135)

**Pull request merged**
