### PR TITLE
Closes softlayer/sl-ember-components#785

### PR DESCRIPTION
**Pull request by SpikedKira**
[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/895)

### CODE REVIEW

**Comment by azizpunjani** [comment]
Reviewed. Looks good.


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/895)

**Comment by notmessenger** [comment]
* Shouldn't it also be removed from `click()` in `addon/components/sl-button.js`?
* Modify `@throws` for `initialize()` in `addon/components/sl-chart.js`
* `sizeClass()` was missed in `addon/components/sl-grid-cell.js`


---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/895)

**Comment by SpikedKira** [comment]
wow, not sure how i missed addon/components/sl-grid-cell.

I'm not sure I have handled addon/components/sl-chart.js correctly.  Please double-check for me.


---

Review status: 4 of 7 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/895)

**Comment by notmessenger** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

<sup>**[addon/components/sl-button.js, line 85 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/895#-K06j-jgQhQ-hf-_dUsI)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/9bd252ed00fe885d113ae0f8bf88bf28cae8d8e4/addon/components/sl-button.js#L85)):</sup>
Remove all of these spaces.  Recommend setting your editor settings to strip extra spaces at end of lines on file save.


---

<sup>**[addon/components/sl-chart.js, line 83 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/895#-K06jJ1LE-eadTMN76cJ)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/9bd252ed00fe885d113ae0f8bf88bf28cae8d8e4/addon/components/sl-chart.js#L83)):</sup>
Should be `ember/Error`


---

<sup>**[addon/components/sl-chart.js, line 84 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/895#-K06jKNHG-BVhytl9UpJ)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/9bd252ed00fe885d113ae0f8bf88bf28cae8d8e4/addon/components/sl-chart.js#L84)):</sup>
Should be `ember/Error`


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/895)

**Comment by SpikedKira** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[addon/components/sl-button.js, line 85 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/895#-K06j-jgQhQ-hf-_dUsI)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/9bd252ed00fe885d113ae0f8bf88bf28cae8d8e4/addon/components/sl-button.js#L85)):</sup>
lol, it does do that... neat bug involving "* @", I think (noted now)


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/895)

**Comment by notmessenger** [comment]
Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[addon/components/sl-button.js, line 263 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/895#-K06zWYWe50v5eWqbW2E)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/1a3b1b5f73f420a920f5497352433ab444550be8/addon/components/sl-button.js#L263)):</sup>
Remove this line


---

<sup>**[addon/components/sl-chart.js, line 251 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/895#-K06zXYwOFNFkjZldtbH)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/1a3b1b5f73f420a920f5497352433ab444550be8/addon/components/sl-chart.js#L251)):</sup>
Remove this line


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/895)

**Comment by notmessenger** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/895)

**Pull request merged**
