### PR TITLE
Create integration test suite and migrate appropriate tests from unit test suite #607

### PR DESCRIPTION
**Pull request by erangeles**
[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/882)

### CODE REVIEW

**Comment by erangeles** [comment]
Integration testing is only available for components at the moment not mixin's.  


---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/882)

**Comment by notmessenger** [comment]
Correct, though the `{{sl-tooltip}}` component mixes in the `sl-tooltip-enabled` mixin, the functionality of which should be tested in the Integration test.


---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[tests/integration/components/sl-tooltip-test.js, line 14 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/882#-K-s2cLm0nyIfg6JCJ7T)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/8078317f5633ab453afa92086202439713138958/tests/integration/components/sl-tooltip-test.js#L14)):</sup>
This should not be tested in an Integration test, per https://github.com/softlayer/ember-style-guide/issues/35


---

<sup>**[tests/unit/components/sl-tooltip-test.js, line 22 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/882#-K-s2WX8Q2qh__0rn7Q_)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/202e2732785ee6070066ace6c762cd4da2843f42/tests/unit/components/sl-tooltip-test.js#L22)):</sup>
This test should be re-implemented, asserting the default value of the `tagName` property, per https://github.com/softlayer/ember-style-guide/issues/35


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/882)

**Comment by notmessenger** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/882)

**Comment by notmessenger** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

<sup>**[tests/unit/components/sl-tooltip-test.js, line 11 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/882#-K-s4kD56LPC0xlMDCEC)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/8078317f5633ab453afa92086202439713138958/tests/unit/components/sl-tooltip-test.js#L11)):</sup>
Is it required to pass an object to `this.subject()` in order for this assertion to pass?  If not, please remove it.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/882)

**Comment by erangeles** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

<sup>**[tests/integration/components/sl-tooltip-test.js, line 14 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/882#-K-s2cLm0nyIfg6JCJ7T)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/8078317f5633ab453afa92086202439713138958/tests/integration/components/sl-tooltip-test.js#L14)):</sup>
Done.


---

<sup>**[tests/unit/components/sl-tooltip-test.js, line 11 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/882#-K-s4kD56LPC0xlMDCEC)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/8078317f5633ab453afa92086202439713138958/tests/unit/components/sl-tooltip-test.js#L11)):</sup>
It is required, errors out if title is not set and if its not a string.


---

<sup>**[tests/unit/components/sl-tooltip-test.js, line 22 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/882#-K-s2WX8Q2qh__0rn7Q_)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/202e2732785ee6070066ace6c762cd4da2843f42/tests/unit/components/sl-tooltip-test.js#L22)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/882)

**Comment by erangeles** [comment]
new tests added for `dataTrigger` (https://github.com/softlayer/sl-ember-components/blob/EmberCli-1.13.8/addon/mixins/sl-tooltip-enabled.js#L30-L38) since it's mixin functionality. 


---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/882)

**Comment by notmessenger** [comment]
Reviewed 1 of 2 files at r2.
Review status: 1 of 2 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

<sup>**[tests/integration/components/sl-tooltip-test.js, line 41 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/882#-K01vUl9JLLKq3R8zgxu)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/9e0a9da447da0d903f612c397434ed04e2e0f1ab/tests/integration/components/sl-tooltip-test.js#L41)):</sup>
Does this have any impact on the test?


---

<sup>**[tests/integration/components/sl-tooltip-test.js, line 64 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/882#-K01vZzN4BJhamF9uS00)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/9e0a9da447da0d903f612c397434ed04e2e0f1ab/tests/integration/components/sl-tooltip-test.js#L64)):</sup>
Does this have any impact on the test?


---

<sup>**[tests/integration/components/sl-tooltip-test.js, line 87 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/882#-K01vfLu92cMcDu2gzeN)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/9e0a9da447da0d903f612c397434ed04e2e0f1ab/tests/integration/components/sl-tooltip-test.js#L87)):</sup>
Does this have any impact on the test?


---

<sup>**[tests/integration/components/sl-tooltip-test.js, line 110 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/882#-K01vpZpExD2srvQ3-rj)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/9e0a9da447da0d903f612c397434ed04e2e0f1ab/tests/integration/components/sl-tooltip-test.js#L110)):</sup>
Does this have any impact on the test?


---

<sup>**[tests/integration/components/sl-tooltip-test.js, line 124 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/882#-K01xiRA2af_AAfPSN-N)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/9e0a9da447da0d903f612c397434ed04e2e0f1ab/tests/integration/components/sl-tooltip-test.js#L124)):</sup>
If the element was given focus, which caused the popover to appear, what is making it go away before the click is called on the element?  Same idea with the mouse enter event.  The point is that there is nothing ensuring that the reason the 2nd and 3rd assertions are passing is not because of the first assertions setup.

This has also gotten me thinking about not only this test, but the other individual tests for hover, click, etc.  Seems we are tying ourselves specifically to the rendered output of the implementation rather than just spying on the setup of the expected values.  For example, I'm assuming `aria-describedby` is coming from the popover element itself from Bootstrap's implementation?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/882)

**Comment by notmessenger** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/882)

**Comment by notmessenger** [comment]
Please merge the latest changes to EmberCLI-1.13.8 into this issue as you continue to work on it.


---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/882)

**Comment by erangeles** [comment]
Review status: 1 of 3 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

<sup>**[tests/integration/components/sl-tooltip-test.js, line 41 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/882#-K01vUl9JLLKq3R8zgxu)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/9e0a9da447da0d903f612c397434ed04e2e0f1ab/tests/integration/components/sl-tooltip-test.js#L41)):</sup>
no, removed.


---

<sup>**[tests/integration/components/sl-tooltip-test.js, line 64 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/882#-K01vZzN4BJhamF9uS00)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/9e0a9da447da0d903f612c397434ed04e2e0f1ab/tests/integration/components/sl-tooltip-test.js#L64)):</sup>
no, removed.


---

<sup>**[tests/integration/components/sl-tooltip-test.js, line 87 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/882#-K01vfLu92cMcDu2gzeN)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/9e0a9da447da0d903f612c397434ed04e2e0f1ab/tests/integration/components/sl-tooltip-test.js#L87)):</sup>
no, removed.


---

<sup>**[tests/integration/components/sl-tooltip-test.js, line 110 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/882#-K01vpZpExD2srvQ3-rj)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/9e0a9da447da0d903f612c397434ed04e2e0f1ab/tests/integration/components/sl-tooltip-test.js#L110)):</sup>
no, removed.


---

<sup>**[tests/integration/components/sl-tooltip-test.js, line 124 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/882#-K01xiRA2af_AAfPSN-N)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/9e0a9da447da0d903f612c397434ed04e2e0f1ab/tests/integration/components/sl-tooltip-test.js#L124)):</sup>
`aria-described` is the direct output of bootstrap's tool tip , aside from this test I believe the rest were pretty effective at testing the direct behavior of our ember wrapped bootstrap component. I've removed these tests and placed them in the mixin unit test file.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/882)

**Comment by notmessenger** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/882)

**Pull request merged**
