### PR TITLE
Create Unit test to assert properties observed by Ember.observer()

### PR DESCRIPTION
**Pull request by erangeles**
[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1107)

### CODE REVIEW

**Comment by juwara0** [comment]
@notmessenger: This is ready to merge


---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1107)

**Comment by juwara0** [comment]
@notmessenger: Hang on. I found something that needs to be updated.


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1107)

**Comment by juwara0** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[tests/unit/components/sl-date-picker-test.js, line 494 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1107#-K2wSiYiRnOFesS5tFb0)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/f95bdc734ff4bfb3b6005bdd832aa9bdf04a32e2/tests/unit/components/sl-date-picker-test.js#L494)):</sup>
You need to add a blank line at the end of the file to pass listing.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1107)

**Comment by erangeles** [comment]
@juwara0 github doesnt show the empty line by default, it is present and has passed linting in the build. ready to merge.

**Comment by juwara0** [comment]
@notmessenger: this is ready to merge


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1107)

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1107)

**Pull request merged**
