### PR TITLE
Issue 763

### PR DESCRIPTION
**Pull request by SpikedKira**
[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/930)

### CODE REVIEW

**Comment by azizpunjani** [comment]
<sup>**[tests/unit/components/sl-modal-header-test.js, line 13 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/930#-K0fY6sAYML12DZMtTdZ)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/26ede313c9d845fd98f0147157abd6b4ab341217/tests/unit/components/sl-modal-header-test.js#L13)):</sup>
Change tabName to tagName.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/930)

**Comment by azizpunjani** [comment]
sl-modal-header also accepts title as a parameter, but it is not currently set to a default value in the sl-modal-header component. I have opened an issue for it https://github.com/softlayer/sl-ember-components/issues/931


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/930)

**Comment by SpikedKira** [comment]
<sup>**[tests/unit/components/sl-modal-header-test.js, line 13 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/930#-K0fY6sAYML12DZMtTdZ)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/26ede313c9d845fd98f0147157abd6b4ab341217/tests/unit/components/sl-modal-header-test.js#L13)):</sup>
doh! thanks


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/930)

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/930)

**Pull request merged**
