### PR TITLE
Calendar revision

### LINKED ISSUE #454: Implement sl-date-picker functionality natively, removing Bootstrap-Datepicker dependency
* Evaluate current functionality and determine if any modifications are desired
* Consider leveraging `sl-calendar` component
* Create/modify tests
* Update http://softlayer.github.io/sl-ember-components/#/browsers

### LINKED ISSUE #455: Implement sl-date-range-picker functionality natively, removing Bootstrap-Datepicker dependency
* Evaluate current functionality and determine if any modifications are desired
* Likely leverage sl-date-picker component
* Create/modify tests
* Update http://softlayer.github.io/sl-ember-components/#/browsers

### PR DESCRIPTION
**Pull request by SpikedKira**
Reworked the calendar to support wai-aria and use inside of date-picker.
Removed reliance on 3rd party plugin for date picker.

Closes #454, Closes #455 

[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1458)

### CODE REVIEW

**Comment by juwara0** [comment]
I am seeing the following errors when I build:

Building...

integration/components/sl-calendar-test.js: line 7, col 20, 'moment' is not defined.
integration/components/sl-calendar-test.js: line 11, col 20, 'moment' is not defined.
integration/components/sl-calendar-test.js: line 15, col 20, 'moment' is not defined.
integration/components/sl-calendar-test.js: line 19, col 20, 'moment' is not defined.
integration/components/sl-calendar-test.js: line 697, col 21, 'jQuery' is not defined.
integration/components/sl-calendar-test.js: line 706, col 17, 'jQuery' is not defined.
integration/components/sl-calendar-test.js: line 715, col 17, 'jQuery' is not defined.
integration/components/sl-calendar-test.js: line 724, col 17, 'jQuery' is not defined.
integration/components/sl-calendar-test.js: line 733, col 17, 'jQuery' is not defined.
integration/components/sl-calendar-test.js: line 742, col 17, 'jQuery' is not defined.
integration/components/sl-calendar-test.js: line 751, col 17, 'jQuery' is not defined.
integration/components/sl-calendar-test.js: line 760, col 17, 'jQuery' is not defined.
integration/components/sl-calendar-test.js: line 769, col 17, 'jQuery' is not defined.
integration/components/sl-calendar-test.js: line 779, col 17, 'jQuery' is not defined.
integration/components/sl-calendar-test.js: line 789, col 17, 'jQuery' is not defined.
integration/components/sl-calendar-test.js: line 800, col 17, 'jQuery' is not defined.

16 errors

unit/components/sl-calendar-test.js: line 7, col 20, 'moment' is not defined.
unit/components/sl-calendar-test.js: line 11, col 20, 'moment' is not defined.
unit/components/sl-calendar-test.js: line 15, col 20, 'moment' is not defined.
unit/components/sl-calendar-test.js: line 19, col 20, 'moment' is not defined.

4 errors

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1458#-:-K9ltxBVu_Lq4d-lo_Nv:1390459051)*

**Comment by juwara0** [comment]
Upon running: `ember serve` and navigating to the dummy app's page for sl-calendar I see the following DEPRECATION message in the console: 

```
Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.
Error
    at Function.createFromInputFallback (http://localhost:4200/assets/vendor.js:96505:36)
    at configFromString (http://localhost:4200/assets/vendor.js:96585:32)
    at configFromInput (http://localhost:4200/assets/vendor.js:97112:13)
    at prepareConfig (http://localhost:4200/assets/vendor.js:97099:13)
    at createFromConfig (http://localhost:4200/assets/vendor.js:97066:44)
    at createLocalOrUTC (http://localhost:4200/assets/vendor.js:97144:16)
    at local__createLocal (http://localhost:4200/assets/vendor.js:97148:16)
    at Moment.isBefore (http://localhost:4200/assets/vendor.js:97618:47)
    at null.<anonymous> (http://localhost:4200/assets/vendor.js:125085:43)
    at Descriptor.ComputedPropertyPrototype.get (http://localhost:4200/assets/vendor.js:29050:26)
```

---

Reviewed 3 of 38 files at r1.
Review status: 3 of 38 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1458#-:-K9mBM6c8BY3PXHojSH5:-1678675045)*

**Comment by azizpunjani** [comment]
Review status: 3 of 38 files reviewed at latest revision, 2 unresolved discussions.

---

*[addon/components/sl-calendar.js, line 407 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1458#-K9mncB8dEVGmL7jupDM:-K9mncB94FdWsyHytyv5:-1902610384) ([raw file](https://github.com/softlayer/sl-ember-components/blob/954b323ed0b5c0206b79c4297ae7bf248d307ca8/addon/components/sl-calendar.js#L407)):*
This should be `currentEvent.startDate.isSame( eventsPerDay[ day ].date, 'day' )`. Currently if two events with the same day, different time are passed in, they will not be grouped properly.

---

*[addon/components/sl-calendar.js, line 419 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1458#-K9moA1vXFe4VZnuINdc:-K9moA1vXFe4VZnuINdd:-1942469853) ([raw file](https://github.com/softlayer/sl-ember-components/blob/954b323ed0b5c0206b79c4297ae7bf248d307ca8/addon/components/sl-calendar.js#L419)):*
I feel like we can avoid this double loop entirely by consolidating this method with the  `weeksInMonthView` method. I feel the `weeksInMonthView` can get eventsPerDay from a different method and then use those eventsPerDay to set the day events. This will avoid running this loop over again since we already run it in `weeksInMonthView`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1458)*

**Comment by azizpunjani** [comment]
Selecting a date on date picker by pressing the spacebar does select the date, but does not close the datepicker. Also escape does not work to close the datepicker when datepicker has focus. Shouldn't the datepicker close when escape is pressed even though the datepicker is focused?

---

Review status: 3 of 38 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1458#-:-K9muzELuLij5-2ryryy:-6614450)*

**Comment by notmessenger** [comment]
Which issues does this PR address?

---

Review status: 3 of 38 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1458#-:-K9rhc_xnbYKGbVxNCIm:-974930544)*

**Comment by azizpunjani** [comment]
@SpikedKira I was thinking. Can we not add a `isSeventh`property on the day object? That way in the view while looping over, we can check `{{#if day.isSeventh}}`? That will help us flatten the current arrays into one array, and be able to display the days without having to resort to a helper. I may be oversimplifying it and it may not work but thought I would put the idea out there.

---

Review status: 3 of 38 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1458#-:-KA08W6r2rfEy9GyOrLj:247259147)*

**Comment by erangeles** [comment]
*[addon/components/sl-calendar.js, line 182 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1458#-KA79wrNXftUx0WAbKC0:-KA79wrO0x3wRQoRS_Lq:-1546488640) ([raw file](https://github.com/softlayer/sl-ember-components/blob/06217dbceba06add9f66e66f2b2f7cd19380868b/addon/components/sl-calendar.js#L182)):*
what about keypad support? they have multiple keycodes according to this.  http://unixpapa.com/js/key.html

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1458)*

**Comment by notmessenger** [comment]
All of these questions are great ones - such as https://reviewable.io/reviews/softlayer/sl-ember-components/1458#-KA79wrNXftUx0WAbKC0:-KA79wrO0x3wRQoRS_Lq:-1546488640 - but are better suited for discussion on https://github.com/softlayer/sl-ember-components/issues/1253 which is where all of the work in this PR should have been discussed prior to being undertaken, especially since all of the issues it resolves are slated for the same milestone (though there may be a few that are not - still waiting on a list from @SpikedKira))

The point is, this PR will not be reviewed or considered for merging until work on the v0.13.0 milestone begins and https://github.com/softlayer/sl-ember-components/issues/1253 is completed.

---

Review status: 3 of 38 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1458#-:-KA7TLOZk1o7l4_eW1ng:-528840471)*

**Comment by SpikedKira** [comment]
@notmessenger I modified the top post to link 2 issues this intends to close.  All others, including #1253 I was intending to tackle in 0.13.0, using this PR as a new base-line.  I have a list of features to add to #1253 based on this PR (new features and such).

If it all needs to wait till 0.13.0, that's fine, it will just be larger

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1458#-:-KAAyOPMpIIGsnIEUwvD:787887216)*

**Comment by erangeles** [comment]
@notmessenger why was this issue closed? There was no explanation on why, maybe it retroactively happened via automation since v11 branch was released(just a guess). But this invalidates the code review as well...

**Comment by notmessenger** [comment]
@erangeles My guess is that it occurred automatically when I deleted the `v0.11.0` branch.  @SpikedKira will need to resubmit this PR at the appropriate time.

**Pull request closed without merging**
