### PR TITLE
Create Unit test to assert properties observed by Ember.observer()

### PR DESCRIPTION
**Pull request by erangeles**
[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1115)

### CODE REVIEW

**Comment by juwara0** [comment]
@notmessenger: This is ready to merge


---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1115)

**Comment by juwara0** [comment]
@notmessenger: Found something hang on...


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1115)

**Comment by juwara0** [comment]
<sup>**[tests/unit/components/sl-input-test.js, line 355 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1115#-K2wRvR7pu3eUjEPxqtZ)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/424cde57d7745dfbac56f9b25f37400c14058416/tests/unit/components/sl-input-test.js#L355)):</sup>
You need to add a blank line at the bottom of the file to pass linting.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1115)

**Comment by erangeles** [comment]
@juwara0 github doesnt show the empty line by default, it is present and has passed linting in the build. ready to merge.

**Comment by juwara0** [comment]
@notmessenger: this is ready to merge


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1115)

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1115)

**Pull request merged**
