### PR TITLE
Create Unit test to assert properties observed by computed property #809

### PR DESCRIPTION
**Pull request by erangeles**
[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/887)

### CODE REVIEW

**Comment by juwara0** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[tests/unit/components/sl-alert-test.js, line 19 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/887#-K-cesHOjNuJU_88SfC1)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/13066fd9f668248f6e1861984b7be95e337495e9/tests/unit/components/sl-alert-test.js#L19)):</sup>
Please insert a line (space) at the bottom of the file


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/887)

**Comment by erangeles** [comment]
this issue will address #748 since it's already creating a unit test file for sl-alert.

**Comment by juwara0** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[tests/unit/components/sl-alert-test.js, line 19 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/887#-K-cesHOjNuJU_88SfC1)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/13066fd9f668248f6e1861984b7be95e337495e9/tests/unit/components/sl-alert-test.js#L19)):</sup>
RESOLVED


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/887)

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/887)

**Pull request merged**
