### PR TITLE
Issue916

### PR DESCRIPTION
**Pull request by alxyuu**
[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/929)

### CODE REVIEW

**Comment by azizpunjani** [comment]
Reviewing this.

**Comment by azizpunjani** [comment]
`tests/integration/components/sl-select.js` needs to be renamed to `tests/integration/components/sl-select-test.js` otherwise the test runner will not pick it up https://github.com/ember-cli/ember-cli/blob/3c615aa55dfe6be1adf14ef67e74028b09560138/tests/runner.js#L23


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/929)

**Comment by azizpunjani** [comment]
Reviewed 18 of 19 files at r1, 1 of 1 files at r2.
Review status: 19 of 20 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

<sup>**[tests/integration/components/sl-checkbox-test.js, line 92 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/929#-K0gfpkPmo2mIHEtFN1Z)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/0d9aedc8ac969b4022314bf29d981b9153bf8663/tests/integration/components/sl-checkbox-test.js#L92)):</sup>
Please use, inline component syntax `{{sl-checkbox}}` as this is the correct usage. I have opened an issue to fix the other instances above in this file https://github.com/softlayer/sl-ember-components/issues/932


---

<sup>**[tests/integration/components/sl-checkbox-test.js, line 103 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/929#-K0ggCeFFJC9TJp5UmUL)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/0d9aedc8ac969b4022314bf29d981b9153bf8663/tests/integration/components/sl-checkbox-test.js#L103)):</sup>
Please use, inline component syntax `{{sl-checkbox}}` as this is the correct usage


---

<sup>**[tests/integration/components/sl-input-test.js, line 23 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/929#-K0ggHlnUId9LsaRAGq1)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/0d9aedc8ac969b4022314bf29d981b9153bf8663/tests/integration/components/sl-input-test.js#L23)):</sup>
Please use, inline component syntax `{{sl-input}}` as this is the correct usage.


---

<sup>**[tests/integration/components/sl-input-test.js, line 34 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/929#-K0ggL2UDlgOLigSEono)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/0d9aedc8ac969b4022314bf29d981b9153bf8663/tests/integration/components/sl-input-test.js#L34)):</sup>
Please use, inline component syntax `{{sl-input ....}}` as this is the correct usage.


---

<sup>**[tests/integration/components/sl-select.js, line 10 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/929#-K0ggNEb_vfHHwBBr7KK)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/0d9aedc8ac969b4022314bf29d981b9153bf8663/tests/integration/components/sl-select.js#L10)):</sup>
Please use, inline component syntax `{{sl-select}}` as this is the correct usage.


---

<sup>**[tests/integration/components/sl-select.js, line 21 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/929#-K0ggQJ2hdHqoFJNcMVy)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/0d9aedc8ac969b4022314bf29d981b9153bf8663/tests/integration/components/sl-select.js#L21)):</sup>
Please use, inline component syntax `{{sl-select}}` as this is the correct usage.


---

<sup>**[tests/integration/components/sl-textarea-test.js, line 458 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/929#-K0ggSnfIBdOgrUACSTI)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/0d9aedc8ac969b4022314bf29d981b9153bf8663/tests/integration/components/sl-textarea-test.js#L458)):</sup>
Please use, inline component syntax `{{sl-textarea}}` as this is the correct usage.


---

<sup>**[tests/integration/components/sl-textarea-test.js, line 469 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/929#-K0ggW9lI2gcti1uhj7A)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/0d9aedc8ac969b4022314bf29d981b9153bf8663/tests/integration/components/sl-textarea-test.js#L469)):</sup>
Please use, inline component syntax `{{sl-textarea}}` as this is the correct usage.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/929)

**Comment by azizpunjani** [comment]
Need to add a unit test to check for presence of InputEnabled mixin for sl-radio.


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/929)

**Comment by azizpunjani** [comment]
Do you mind adding an integration test to check if setting the name property on an sl-radio component also sets the name attribute on the DOM element? Otherwise please open an issue so this test can be added later.


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/929)

**Comment by azizpunjani** [comment]
Reviewed 1 of 19 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/929)

**Comment by azizpunjani** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---

<sup>**[addon/components/sl-checkbox.js, line 8 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/929#-K0gvgDOWGKN4cBSeJ3V)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/8b220443a70bed15fd9058143458cfdc4b567e23/addon/components/sl-checkbox.js#L8)):</sup>
Please add `@augments module:mixins/sl-input-based`


---

<sup>**[addon/components/sl-radio.js, line 7 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/929#-K0gvphAqIykWMlm-bCo)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/0d9aedc8ac969b4022314bf29d981b9153bf8663/addon/components/sl-radio.js#L7)):</sup>
Please add `@augments module:mixins/sl-input-based`


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/929)

**Comment by azizpunjani** [comment]
@notmessenger this is ready for review when you have a chance.

**Comment by azizpunjani** [comment]
Reviewed 9 of 9 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/929)

**Comment by notmessenger** [comment]
<sup>**[addon/components/sl-checkbox.js, line 20 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/929#-K1AXn62nN6Yu8pcc54O)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/3a8651e1193fe4d4e5d664690bfce085f77cb31a/addon/components/sl-checkbox.js#L20)):</sup>
Doesn't a `checkedString()` computed property need to be added to addon/mixins/sl-input-based.js?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/929)

**Comment by notmessenger** [comment]
<sup>**[tests/unit/components/sl-input-test.js, line 111 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/929#-K1APaqwCpXDpRJV1Qsg)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/c198d0bc8c271c33d0443c68a5fca613b8fa6192/tests/unit/components/sl-input-test.js#L111)):</sup>
Shouldn't the `name` property be tested like all the other test cases of the other properties?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/929)

**Comment by notmessenger** [comment]
<sup>**[tests/unit/components/sl-input-test.js, line 111 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/929#-K1AOeNrCn37v-3T_pid)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/c198d0bc8c271c33d0443c68a5fca613b8fa6192/tests/unit/components/sl-input-test.js#L111)):</sup>
`value` property should be tested


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/929)

**Comment by notmessenger** [comment]
<sup>**[tests/integration/components/sl-select-test.js, line 28 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/929#-K1ATzNFongC-lMJeibI)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/c198d0bc8c271c33d0443c68a5fca613b8fa6192/tests/integration/components/sl-select-test.js#L28)):</sup>
Remove this test suite as we currently do not implement any tests for the `{{sl-select}}` component and do not plan to until the v0.14.0 milestone.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/929)

**Comment by notmessenger** [comment]
<sup>**[tests/unit/components/sl-input-test.js, line 117 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/929#-K1APYGlT2GBJCjtHAkp)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/3a8651e1193fe4d4e5d664690bfce085f77cb31a/tests/unit/components/sl-input-test.js#L117)):</sup>
Shouldn't the "'Required property does not display required label'" test also be removed?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/929)

**Comment by notmessenger** [comment]
<sup>**[addon/components/sl-radio.js, line 17 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/929#-K1ASo4u5kRD7kb6GEX-)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/3a8651e1193fe4d4e5d664690bfce085f77cb31a/addon/components/sl-radio.js#L17)):</sup>
If removing this, doesn't the template need to be changed to bind to `readonlyString` like the other components?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/929)

**Comment by alxyuu** [comment]
Review status: 17 of 24 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

<sup>**[addon/components/sl-checkbox.js, line 20 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/929#-K1AXn62nN6Yu8pcc54O)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/3a8651e1193fe4d4e5d664690bfce085f77cb31a/addon/components/sl-checkbox.js#L20)):</sup>
no - these attributes are not necessary, as they're being placed on the parent div. The ember input helper simply takes a true or false value for checked. Not sure why there's a disabledString property, as disabled also accepts true and false - it's only readonly that has the odd behavior.


---

<sup>**[addon/components/sl-radio.js, line 17 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/929#-K1ASo4u5kRD7kb6GEX-)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/3a8651e1193fe4d4e5d664690bfce085f77cb31a/addon/components/sl-radio.js#L17)):</sup>
the attribute is bound to the parent div, so it is not applicable here. also, readonly is ignored on radios. From the MDN input docs:

readonly HTML5
This Boolean attribute indicates that the user cannot modify the value of the control. It is ignored if the value of the type attribute is hidden, range, color, checkbox, radio, file, or a button type (such as button or submit).

given this fact, I'll be removing readonly from sl-radio.


---

<sup>**[tests/unit/components/sl-input-test.js, line 111 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/929#-K1APaqwCpXDpRJV1Qsg)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/c198d0bc8c271c33d0443c68a5fca613b8fa6192/tests/unit/components/sl-input-test.js#L111)):</sup>
name is tested in integration. In my opinion, quite a few of these tests should be moved to integration (like labels when required). but it's outside the scope of this issue.


---

<sup>**[tests/unit/components/sl-input-test.js, line 117 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/929#-K1APYGlT2GBJCjtHAkp)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/3a8651e1193fe4d4e5d664690bfce085f77cb31a/tests/unit/components/sl-input-test.js#L117)):</sup>
no, because the label is part of this component. required was removed because it's part of the mixin, not this component.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/929)

**Comment by azizpunjani** [comment]
Review status: 17 of 24 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

<sup>**[addon/components/sl-checkbox.js, line 20 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/929#-K1AXn62nN6Yu8pcc54O)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/3a8651e1193fe4d4e5d664690bfce085f77cb31a/addon/components/sl-checkbox.js#L20)):</sup>
I have confirmed we don't need disabledString as setting disabled to a boolean value and passing it to an input helper will add/remove the attribute on the input.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/929)

**Comment by azizpunjani** [comment]
<sup>**[addon/components/sl-checkbox.js, line 20 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/929#-K1AXn62nN6Yu8pcc54O)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/3a8651e1193fe4d4e5d664690bfce085f77cb31a/addon/components/sl-checkbox.js#L20)):</sup>
I created an issue to remove `disabledString` https://github.com/softlayer/sl-ember-components/issues/970


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/929)

**Comment by notmessenger** [comment]
There are merge conflicts


---

Reviewed 12 of 20 files at r1, 1 of 1 files at r2, 9 of 9 files at r3.
Review status: 17 of 24 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/929)

**Comment by alxyuu** [comment]
the conflict was due to changes to the "The readonly state applies to sl-radio children" in #941. That test was removed in this pr due to readonly not being applicable to radio input types.


---

Review status: 15 of 23 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/929)

**Comment by notmessenger** [comment]
There are merge conflicts


---

Review status: 15 of 23 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/929)

**Comment by alxyuu** [comment]
conflicts were from #970. Fixed now.


---

Review status: 8 of 23 files reviewed at latest revision, 3 unresolved discussions.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/929)

**Comment by notmessenger** [comment]
Can you take a look at this PR as well @azizpunjani?  Thanks


---

Review status: 8 of 23 files reviewed at latest revision, 3 unresolved discussions.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/929)

**Comment by notmessenger** [comment]
@alxyuu Merge conflicts


---

Review status: 8 of 23 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/929)

**Comment by azizpunjani** [comment]
Reviewed 4 of 7 files at r4, 3 of 4 files at r5, 7 of 8 files at r6, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/929)

**Comment by notmessenger** [comment]
Reviewed 4 of 7 files at r4, 3 of 4 files at r5, 7 of 8 files at r6, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/929)

**Pull request merged**
