### PR TITLE
Closes softlayer/sl-ember-components#1067

### PR DESCRIPTION
**Pull request by SpikedKira**
[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1075)

### CODE REVIEW

**Comment by notmessenger** [comment]
This PR should also address that content is not yielded when the `label` property is populated.  Maybe the default state test should see that the content is yielded?  Then test that sets label shows that it doesn't?  Then the test that was added is not needed?  However you want to approach it but there should be a little more addressed in this issue's work.


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1075)

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1075)

**Comment by SpikedKira** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[tests/integration/components/sl-button-test.js, line 78 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1075#-K2hE79KfP7CIsMyBukR)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/4c153fe1ac350d3d4508501fbe471e74540392ea/tests/integration/components/sl-button-test.js#L78)):</sup>
This test's primary goal is to check that label works, but in doing so also tests that content is not yielded.


---

<sup>**[tests/integration/components/sl-button-test.js, line 115 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1075#-K2hEIDuzoLVNM6DWWGO)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/4c153fe1ac350d3d4508501fbe471e74540392ea/tests/integration/components/sl-button-test.js#L115)):</sup>
I can move this assert into the default state test if you want


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1075)

**Comment by notmessenger** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[tests/integration/components/sl-button-test.js, line 78 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1075#-K2hE79KfP7CIsMyBukR)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/4c153fe1ac350d3d4508501fbe471e74540392ea/tests/integration/components/sl-button-test.js#L78)):</sup>
Though there's not any test that actually checks this.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1075)

**Pull request merged**
