### PR TITLE
use broccoli-unwatched-tree to generate less path tree for funnel

### PR DESCRIPTION
**Pull request by SpikedKira**
[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1225)

### CODE REVIEW

**Comment by notmessenger** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[index.js, line 89 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1225#-K4XvUM6LGpMngTZF5xZ:-K4XvUM6LGpMngTZF5x_:581310861) ([raw file](https://github.com/softlayer/sl-ember-components/blob/6a4c32b6a8f38cf2e9c812b3cde9416a51ce60c8/index.js#L89)):*
Delete this line rather than commenting it out

---

*[index.js, line 226 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1225#-K4Xvkd001JTrQUQE9Xb:-K4Xvkd001JTrQUQE9Xc:-572809994) ([raw file](https://github.com/softlayer/sl-ember-components/blob/6a4c32b6a8f38cf2e9c812b3cde9416a51ce60c8/index.js#L226)):*
Does cleaning up after ourselves cause a problem, because if not we should do so.  If it does then `postBuild()`, `removeTempPath()`, and any other related/called methods should be removed from the file, as they have then become dead code.

---

*[package.json, line 60 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1225#-K4XwayEDzFWZCJ2NujV:-K4XwayEDzFWZCJ2NujW:-1379064982) ([raw file](https://github.com/softlayer/sl-ember-components/blob/6a4c32b6a8f38cf2e9c812b3cde9416a51ce60c8/package.json#L60)):*
Given how "in the weeds" some of the functionality is across underlying dependencies do we want to have different versions installed automatically for us versus remaining tightly version locked?

This will likely need to be a dependency versus a dev dependency.  Have you tested consuming the changes you've made to this addon in an app (to see)?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1225)*

**Comment by notmessenger** [comment]
*[index.js, line 128 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1225#-K4YFKo-9roO_NnHZ99I:-K4YFKo-9roO_NnHZ99J:8007275) ([raw file](https://github.com/softlayer/sl-ember-components/blob/6a4c32b6a8f38cf2e9c812b3cde9416a51ce60c8/index.js#L128)):*
The README at https://github.com/rwjblue/broccoli-unwatched-tree says to use `new UnwatchedTree()`.  Is this not correct?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1225)*

**Comment by notmessenger** [comment]
*[index.js, line 128 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1225#-K4YFKo-9roO_NnHZ99I:-K4YGT4R2G6tmTqKcFIY:1405869181) ([raw file](https://github.com/softlayer/sl-ember-components/blob/6a4c32b6a8f38cf2e9c812b3cde9416a51ce60c8/index.js#L128)):*
`unwatched()` seems to be part of https://github.com/sebastianseilund/broccoli-duplicate-watched-tree-finder

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1225)*

**Comment by notmessenger** [comment]
*[index.js, line 128 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1225#-K4YFKo-9roO_NnHZ99I:-K4YGzOSRuFp9YJ5VeD-:-1049670383) ([raw file](https://github.com/softlayer/sl-ember-components/blob/6a4c32b6a8f38cf2e9c812b3cde9416a51ce60c8/index.js#L128)):*
Rather meant the example may have come from there?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1225)*

**Comment by SpikedKira** [comment]
*[index.js, line 128 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1225#-K4YFKo-9roO_NnHZ99I:-K4YL9PoaVONpJKFjQ4q:-250785547) ([raw file](https://github.com/softlayer/sl-ember-components/blob/6a4c32b6a8f38cf2e9c812b3cde9416a51ce60c8/index.js#L128)):*
unwatched is defined by us at the top during require.  The example only applies to brocfile.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1225)*

**Comment by notmessenger** [comment]
Reviewed 1 of 2 files at r2.
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[index.js, line 11 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1225#-K4YK8yWn_LDRzZbBp41:-K4YK8yWn_LDRzZbBp42:571062700) ([raw file](https://github.com/softlayer/sl-ember-components/blob/607ae11e4a7257e6766ed5326417cd8c2e886f14/index.js#L11)):*
https://github.com/softlayer/ember-style-guide/blob/master/javascript.md#block-statements

---

*[index.js, line 218 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1225#-K4YTVFLxbZyxOK9pZko:-K4YTVFLxbZyxOK9pZkp:176204121) ([raw file](https://github.com/softlayer/sl-ember-components/blob/607ae11e4a7257e6766ed5326417cd8c2e886f14/index.js#L218)):*
If the file does not exist the folder will never be removed which is likely not what we desire and what was not in the original code in place.

---

*[index.js, line 220 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1225#-K4YRC0D1d1cBT0wyS1k:-K4YRC0D1d1cBT0wyS1l:571062700) ([raw file](https://github.com/softlayer/sl-ember-components/blob/607ae11e4a7257e6766ed5326417cd8c2e886f14/index.js#L220)):*
https://github.com/softlayer/ember-style-guide/blob/master/javascript.md#block-statements

---

*[package.json, line 79 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1225#-K4YKVoPJKxa9GNxIs0p:-K4YKVoPJKxa9GNxIs0q:1799499018) ([raw file](https://github.com/softlayer/sl-ember-components/blob/607ae11e4a7257e6766ed5326417cd8c2e886f14/package.json#L79)):*
Depending on whether the `^` is removed for `broccoli-unwatched-tree` consider the same for this entry.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1225)*

**Comment by notmessenger** [comment]
*[index.js, line 10 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1225#-K4YhJYt4MiqZeybkvA1:-K4YhJYt4MiqZeybkvA2:686680312) ([raw file](https://github.com/softlayer/sl-ember-components/blob/4865cfa4ec41e52251c17e9972f48988196d8230/index.js#L10)):*
Let's change this to `unwatchedTree` to be more explicit about what it is.  Brings inline with use of `mergeTrees`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1225)*

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r3.
Review status: 1 of 2 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1225)*

**Comment by SpikedKira** [comment]
*[package.json, line 79 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1225#-K4YKVoPJKxa9GNxIs0p:-K4ZKCQNjeopuhnUhv36:-1223593799) ([raw file](https://github.com/softlayer/sl-ember-components/blob/607ae11e4a7257e6766ed5326417cd8c2e886f14/package.json#L79)):*
I think it is okay for these to update

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1225)*

**Comment by azizpunjani** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[index.js, line 246 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1225#-K4cNCsN6H2rgKFq0tAT:-K4cNCsN6H2rgKFq0tAU:1969045519) ([raw file](https://github.com/softlayer/sl-ember-components/blob/b31cdc00f7798752a97411b2d9bcc66dba357472/index.js#L246)):*
superflous comment?

---

*[index.js, line 247 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1225#-K4cNEhRdlRGO4kCFCoi:-K4cNEhRdlRGO4kCFCoj:315284308) ([raw file](https://github.com/softlayer/sl-ember-components/blob/b31cdc00f7798752a97411b2d9bcc66dba357472/index.js#L247)):*
Reject with error, for easier debugging and friendly message.

`reject( error );`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1225)*

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[index.js, line 51 \[r5\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1225#-K4cxBie1ojlF2ddo4Df:-K4cxBie1ojlF2ddo4Dg:-154334740) ([raw file](https://github.com/softlayer/sl-ember-components/blob/7a660be35e4f106ee06aa21fac6504b3932316a4/index.js#L51)):*
Update type

---

*[index.js, line 69 \[r5\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1225#-K4cy7d7Z0J_tCKUPi0_:-K4cy7d7Z0J_tCKUPi0a:-881631835) ([raw file](https://github.com/softlayer/sl-ember-components/blob/7a660be35e4f106ee06aa21fac6504b3932316a4/index.js#L69)):*
Would like to see this same logic that's contained in `getTempPath()` to be extracted out for re-use by both locations but only definition in one.

---

*[index.js, line 82 \[r5\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1225#-K4cwmlvbCJECg0o1HRd:-K4cwmlvbCJECg0o1HRe:1589232121) ([raw file](https://github.com/softlayer/sl-ember-components/blob/7a660be35e4f106ee06aa21fac6504b3932316a4/index.js#L82)):*
Remove the comment

---

*[index.js, line 95 \[r5\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1225#-K4cyUWZQ9B-Y-X-ypt8:-K4cyUWZQ9B-Y-X-ypt9:1270500793) ([raw file](https://github.com/softlayer/sl-ember-components/blob/7a660be35e4f106ee06aa21fac6504b3932316a4/index.js#L95)):*
Where's the logic catching any error that occurs with the `fs.mkdir()` call?

---

*[index.js, line 220 \[r5\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1225#-K4cx8kSwWfPW0Otryvx:-K4cx8kSwWfPW0Otryvy:-154334740) ([raw file](https://github.com/softlayer/sl-ember-components/blob/7a660be35e4f106ee06aa21fac6504b3932316a4/index.js#L220)):*
Update type

---

*[index.js, line 225 \[r5\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1225#-K4cx5Bl1SMmA7k2qscE:-K4cx5Bl1SMmA7k2qscF:1382504424) ([raw file](https://github.com/softlayer/sl-ember-components/blob/7a660be35e4f106ee06aa21fac6504b3932316a4/index.js#L225)):*
Add a blank line before this one

---

*[index.js, line 231 \[r5\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1225#-K4cyxxK5t11J-1VGT5v:-K4cyxxK5t11J-1VGT5w:-1844098346) ([raw file](https://github.com/softlayer/sl-ember-components/blob/7a660be35e4f106ee06aa21fac6504b3932316a4/index.js#L231)):*
Where's the logic catching any error that occurs with the `fs.rmdir()` call?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1225)*

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1225)*

**Pull request merged**
