### PR TITLE
Create Unit test to assert properties observed by Ember.observer()

### PR DESCRIPTION
**Pull request by erangeles**
[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1117)

### CODE REVIEW

**Comment by juwara0** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[tests/unit/mixins/sl-tooltip-enabled-test.js, line 274 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1117#-K2wTPypi-8_aMdrO40v)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/bbfd2df4e38e9eab06a0b9aef1a3f7fb4671c9b3/tests/unit/mixins/sl-tooltip-enabled-test.js#L274)):</sup>
A blank line needs to be added to the end of this file to pass linting.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1117)

**Comment by erangeles** [comment]
@juwara0 github doesnt show the empty line by default, it is present and has passed linting in the build. ready to merge.

**Comment by juwara0** [comment]
@notmessenger: this is ready to merge


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1117)

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1117)

**Pull request merged**
