### PR TITLE
Refactored events. Closes #1287

### LINKED ISSUE #1287: Refactor to align with updated style guide
https://github.com/softlayer/ember-style-guide#defining-functions-to-be-called-when-events-are-triggered 

* `init()` - https://github.com/softlayer/sl-ember-components/blob/v0.11.0/addon/components/sl-chart.js#L83
* `didInsertElement()` - https://github.com/softlayer/sl-ember-components/blob/v0.11.0/addon/components/sl-chart.js#L124

### PR DESCRIPTION
**Pull request by azizpunjani**
Closes https://github.com/softlayer/sl-ember-components/issues/1440

[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1390)

### CODE REVIEW

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[addon/components/sl-chart.js, line 114 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1390#-K7wcM_Nt2x5J5AuBltm:-K7wcM_Nt2x5J5AuBltn:2073413921) ([raw file](https://github.com/softlayer/sl-ember-components/blob/760b7e05272e1a2561519d6552f8c4507120b0a6/addon/components/sl-chart.js#L114)):*
This is in the wrong section

---

*[addon/components/sl-chart.js, line 175 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1390#-K7wcUg5iT42fsU-Tk2-:-K7wcUg5iT42fsU-Tk20:-1452854149) ([raw file](https://github.com/softlayer/sl-ember-components/blob/760b7e05272e1a2561519d6552f8c4507120b0a6/addon/components/sl-chart.js#L175)):*
This is not in alphabetical order

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1390)*

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[addon/components/sl-chart.js, line 101 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1390#-K8KHnORUyxHpVti-Zhp:-K8KHnORUyxHpVti-Zhq:558866305) ([raw file](https://github.com/softlayer/sl-ember-components/blob/6afdfcce9a505484199976d34ffaa97050baa4e3/addon/components/sl-chart.js#L101)):*
* Is in the wrong section of the document.
* What is gained by this being computed? Can't is just be a normal function?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1390)*

**Comment by notmessenger** [comment]
Tests are failing

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1390#-:-K8_JO9tOVEWlWvAdhS_:-2087875532)*

**Comment by azizpunjani** [comment]
Created https://github.com/softlayer/sl-ember-components/issues/1440

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1390)*

**Comment by azizpunjani** [comment]
@notmessenger this is ready for review. I added back the test that was giving issues. Also did a code cleanup.

**Comment by notmessenger** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[addon/components/sl-chart.js, line 232 \[r5\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1390#-K9Z4vv6JsP8r4pVClEh:-K9Z4vv6JsP8r4pVClEi:-1452854149) ([raw file](https://github.com/softlayer/sl-ember-components/blob/7c4c6a75dbc26fa9debe68a0815ac39b14970aae/addon/components/sl-chart.js#L232)):*
This is not in alphabetical order

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1390)*

**Comment by azizpunjani** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[addon/components/sl-chart.js, line 175 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1390#-K7wcUg5iT42fsU-Tk2-:-K9cRI7vqvxfplT4pAXE:-1929118193) ([raw file](https://github.com/softlayer/sl-ember-components/blob/760b7e05272e1a2561519d6552f8c4507120b0a6/addon/components/sl-chart.js#L175)):*
@notmessenger should this comment be on another line?

---

*[addon/components/sl-chart.js, line 232 \[r5\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1390#-K9Z4vv6JsP8r4pVClEh:-K9cRAecWYpirZRgDIgo:-1929118193) ([raw file](https://github.com/softlayer/sl-ember-components/blob/7c4c6a75dbc26fa9debe68a0815ac39b14970aae/addon/components/sl-chart.js#L232)):*
@notmessenger should this comment be on another line?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1390)*

**Pull request merged**
