### PR TITLE
validate timezone value in sl-date-time.js

### PR DESCRIPTION
**Pull request by erangeles**
[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1224)

### CODE REVIEW

**Comment by azizpunjani** [comment]
*[addon/components/sl-date-time.js, line 112 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1224#-K4U2cLQVaW2GsxmAVRr:-K4U2cLQVaW2GsxmAVRs:-1356787943) ([raw file](https://github.com/softlayer/sl-ember-components/blob/1dda3fae5ee17dae28df6f53c3fb9cb744fa2652/addon/components/sl-date-time.js#L112)):*
Code can be simplified quite a bit with ES6 `Array.prototype.includes()` method.

```
if ( !validTimeZonesArray.includes( this.get( 'timezone' ) ) {
    throw new Ember.Error( 'timezone property provided is not valid' );
}
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1224)*

**Comment by azizpunjani** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[tests/unit/components/sl-date-time-test.js, line 298 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1224#-K4U4qeu8Bu9VYJzApzg:-K4U4qevbFxx33VHAz-h:876791673) ([raw file](https://github.com/softlayer/sl-ember-components/blob/1dda3fae5ee17dae28df6f53c3fb9cb744fa2652/tests/unit/components/sl-date-time-test.js#L298)):*
Remove newline from here so comment goes with code below it.

---

*[tests/unit/components/sl-date-time-test.js, line 307 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1224#-K4U4zYwl4ga8kaVl2w8:-K4U4zYwl4ga8kaVl2w9:876791673) ([raw file](https://github.com/softlayer/sl-ember-components/blob/1dda3fae5ee17dae28df6f53c3fb9cb744fa2652/tests/unit/components/sl-date-time-test.js#L307)):*
Remove newline from here so comment goes with code below it.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1224)*

**Comment by erangeles** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[addon/components/sl-date-time.js, line 112 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1224#-K4U2cLQVaW2GsxmAVRr:-K4UE4F5RpBgNGh0Vfal:-804378102) ([raw file](https://github.com/softlayer/sl-ember-components/blob/1dda3fae5ee17dae28df6f53c3fb9cb744fa2652/addon/components/sl-date-time.js#L112)):*
thanks for the input aziz. 

---

*[tests/unit/components/sl-date-time-test.js, line 298 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1224#-K4U4qeu8Bu9VYJzApzg:-K4UE8vWFC3_KQOzlEf4:-499146009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/1dda3fae5ee17dae28df6f53c3fb9cb744fa2652/tests/unit/components/sl-date-time-test.js#L298)):*
Done.

---

*[tests/unit/components/sl-date-time-test.js, line 307 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1224#-K4U4zYwl4ga8kaVl2w8:-K4UE9J-gURTGuOIOHdu:-499146009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/1dda3fae5ee17dae28df6f53c3fb9cb744fa2652/tests/unit/components/sl-date-time-test.js#L307)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1224)*

**Comment by azizpunjani** [comment]
Reviewed 2 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1224)*

**Comment by notmessenger** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[addon/components/sl-date-time.js, line 113 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1224#-K4ZWNgA2qQE1R_A6Aal:-K4ZWNgA2qQE1R_A6Aam:-771558369) ([raw file](https://github.com/softlayer/sl-ember-components/blob/4c6329f8626ad7f92b7f47f7421a8b1fc86b2c46/addon/components/sl-date-time.js#L113)):*
The use of `includes()` does not align with our support of current browser versions and one prior

* http://softlayer.github.io/sl-ember-components/#/browsers
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes#Browser_compatibility )

Does it get transpiled correctly into something that is?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1224)*

**Comment by erangeles** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[addon/components/sl-date-time.js, line 113 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1224#-K4ZWNgA2qQE1R_A6Aal:-K4ZZYMEO0AHpHagQkrH:-620560598) ([raw file](https://github.com/softlayer/sl-ember-components/blob/4c6329f8626ad7f92b7f47f7421a8b1fc86b2c46/addon/components/sl-date-time.js#L113)):*
from my testing it worked in windows 7, chrome Version 46.0.2490.86. I can revert it to my previous usage though to ensure full browser compatibility. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1224)*

**Comment by azizpunjani** [comment]
*[addon/components/sl-date-time.js, line 113 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1224#-K4ZWNgA2qQE1R_A6Aal:-K4ZZOLcK23TQA1JQo3C:-1835292634) ([raw file](https://github.com/softlayer/sl-ember-components/blob/4c6329f8626ad7f92b7f47f7421a8b1fc86b2c46/addon/components/sl-date-time.js#L113)):*
It is polyfilled https://github.com/softlayer/sl-ember-components/blob/EmberCli-1.13.8/ember-cli-build.js#L10 by balbel.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1224)*

**Comment by azizpunjani** [comment]
*[addon/components/sl-date-time.js, line 113 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1224#-K4ZWNgA2qQE1R_A6Aal:-K4Z_G57m6wdFraKNnnr:949590853) ([raw file](https://github.com/softlayer/sl-ember-components/blob/4c6329f8626ad7f92b7f47f7421a8b1fc86b2c46/addon/components/sl-date-time.js#L113)):*
*babel

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1224)*

**Comment by erangeles** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[addon/components/sl-date-time.js, line 113 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1224#-K4ZWNgA2qQE1R_A6Aal:-K4Za4IAM4d00ODFuhYE:-1124732057) ([raw file](https://github.com/softlayer/sl-ember-components/blob/4c6329f8626ad7f92b7f47f7421a8b1fc86b2c46/addon/components/sl-date-time.js#L113)):*
since it provides facilities that are not built into a web browser that means we can use es6 methods right? @notmessenger

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1224)*

**Comment by juwara0** [comment]
We need to also add a note in the demo app properties section for timezone saying that "only timezones supported/returned by moment.tz.names() are supported"

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1224#-:-K4Zl-638qHZs5t4II2h:-804586773)*

**Comment by erangeles** [comment]
changing it to...

"The string value for the current moment timezone name (i.e., "America/Chicago")."  

moment timezone implies that it should be valid. and follows the desc for locale

"The locale string to use for moment date formats."

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1224#-:-K4ZlztbiDG-e6y4uhRG:-1227069561)*

**Comment by juwara0** [comment]
*[addon/components/sl-date-time.js, line 113 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1224#-K4ZWNgA2qQE1R_A6Aal:-K4cEOCC986-UuFH4txG:-767763160) ([raw file](https://github.com/softlayer/sl-ember-components/blob/4c6329f8626ad7f92b7f47f7421a8b1fc86b2c46/addon/components/sl-date-time.js#L113)):*
We tested on IE yesterday to verify and it worked correctly with the includes() so this should be alright.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1224)*

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tests/dummy/app/templates/demos/sl-date-time.hbs, line 73 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1224#-K4cuBmcSdHFHRjGGEKK:-K4cuBmcSdHFHRjGGEKL:-1604804009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/303a3821ec63b52e8d750e826fba900d79c8bb0b/tests/dummy/app/templates/demos/sl-date-time.hbs#L73)):*
Change to "moment.js", like the `value` property

---

*[tests/dummy/app/templates/demos/sl-date-time.hbs, line 81 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1224#-K4cuEtHdN3DaxbbH2lv:-K4cuEtHdN3DaxbbH2lw:-1604804009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/303a3821ec63b52e8d750e826fba900d79c8bb0b/tests/dummy/app/templates/demos/sl-date-time.hbs#L81)):*
Change to "moment.js", like the `value` property

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1224)*

**Comment by erangeles** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[tests/dummy/app/templates/demos/sl-date-time.hbs, line 73 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1224#-K4cuBmcSdHFHRjGGEKK:-K4hbovqRVr_IHbhJ6ne:-499146009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/303a3821ec63b52e8d750e826fba900d79c8bb0b/tests/dummy/app/templates/demos/sl-date-time.hbs#L73)):*
Done.

---

*[tests/dummy/app/templates/demos/sl-date-time.hbs, line 81 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1224#-K4cuEtHdN3DaxbbH2lv:-K4hbqWsecjhw__yetqT:-499146009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/303a3821ec63b52e8d750e826fba900d79c8bb0b/tests/dummy/app/templates/demos/sl-date-time.hbs#L81)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1224)*

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1224)*

**Pull request merged**
