### PR TITLE
sl-date-range-picker: "startDateValue", "minDate", "maxdate", "endDateValue" must be within proper values

### LINKED ISSUE #870: sl-date-range-picker: "startDateValue" should not be able to be set when it is less than "minDate"

### PR DESCRIPTION
**Pull request by Yogeswar**
Close 
* softlayer/sl-ember-components#870
* softlayer/sl-ember-components#871
* softlayer/sl-ember-components#874
* softlayer/sl-ember-components#875

ensure that startDateValue, minDate, maxDate and endDateValue params
given to sl-date-range-picker are valid

[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1144)

### CODE REVIEW

**Comment by Yogeswar** [comment]
Had to use window.moment( new Date(value) ) due to a deprecation warning - https://github.com/moment/moment/issues/1407

**Comment by Yogeswar** [comment]
This pull request also addresses #871, #874, #875

**Comment by Yogeswar** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[addon/components/sl-date-range-picker.js, line 90 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1144#-K2ndpEmpjsa06ftwa24)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/2706588e229361ba4df8486529bb93215b6812c3/addon/components/sl-date-range-picker.js#L90)):</sup>
Had to use window.moment( new Date(value) ) due to a deprecation warning - https://github.com/moment/moment/issues/1407


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1144)

**Comment by juwara0** [comment]
I am reviewing this.


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1144)

**Comment by notmessenger** [comment]
Closing this PR as this component is going to be refactored in milestone v0.12.0

**Pull request closed without merging**
