### PR TITLE
Closes softlayer/sl-ember-components#783

### PR DESCRIPTION
**Pull request by SpikedKira**
[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1071)

### CODE REVIEW

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

<sup>**[tests/integration/components/sl-calendar-test.js, line 51 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1071#-K28dqa4targrH-6kyNA)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/1017bc2dd61ec84a08f7dd98c80636cd41c97a22/tests/integration/components/sl-calendar-test.js#L51)):</sup>
* What about the classes from https://github.com/softlayer/sl-ember-components/blob/EmberCli-1.13.8/addon/templates/components/sl-calendar.hbs#L1?
* There are test cases to ensure that both months and year values are displayed in the correct order when in either of these modes - there should be an assertion for the default rendering of the days
* The content in the rendered calendar table should be asserted as well


---

<sup>**[tests/integration/components/sl-calendar-test.js, line 54 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1071#-K28eRBigX3ogjGJer8y)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/1017bc2dd61ec84a08f7dd98c80636cd41c97a22/tests/integration/components/sl-calendar-test.js#L54)):</sup>
This value is not being used


---

<sup>**[tests/integration/components/sl-calendar-test.js, line 56 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1071#-K28eXr79jeUdXs3CRrl)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/1017bc2dd61ec84a08f7dd98c80636cd41c97a22/tests/integration/components/sl-calendar-test.js#L56)):</sup>
This value is not being used


---

<sup>**[tests/integration/components/sl-calendar-test.js, line 67 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1071#-K28eiILmxoameueOQ5-)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/1017bc2dd61ec84a08f7dd98c80636cd41c97a22/tests/integration/components/sl-calendar-test.js#L67)):</sup>
Wouldn't a better selector be for https://github.com/softlayer/sl-ember-components/blob/EmberCli-1.13.8/addon/components/sl-calendar-day.js#L25?


---

<sup>**[tests/integration/components/sl-calendar-test.js, line 70 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1071#-K28eoTJ5AMQJQGb5QRv)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/1017bc2dd61ec84a08f7dd98c80636cd41c97a22/tests/integration/components/sl-calendar-test.js#L70)):</sup>
Can we put the `let`s together instead of splitting them with the `const`?


---

<sup>**[tests/integration/components/sl-calendar-test.js, line 75 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1071#-K28evALDQTY7NT3B0qy)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/1017bc2dd61ec84a08f7dd98c80636cd41c97a22/tests/integration/components/sl-calendar-test.js#L75)):</sup>
styleguide


---

<sup>**[tests/integration/components/sl-calendar-test.js, line 78 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1071#-K28exbAWTDOXwbxbI1z)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/1017bc2dd61ec84a08f7dd98c80636cd41c97a22/tests/integration/components/sl-calendar-test.js#L78)):</sup>
styleguide


---

<sup>**[tests/integration/components/sl-calendar-test.js, line 82 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1071#-K28f20qv_-x_0RS2zKg)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/1017bc2dd61ec84a08f7dd98c80636cd41c97a22/tests/integration/components/sl-calendar-test.js#L82)):</sup>
styleguide


---

<sup>**[tests/integration/components/sl-calendar-test.js, line 83 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1071#-K28f2PcpYe2wozg6C5E)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/1017bc2dd61ec84a08f7dd98c80636cd41c97a22/tests/integration/components/sl-calendar-test.js#L83)):</sup>
styleguide


---

<sup>**[tests/integration/components/sl-calendar-test.js, line 88 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1071#-K28f3XtSBHNhIdbbc3n)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/1017bc2dd61ec84a08f7dd98c80636cd41c97a22/tests/integration/components/sl-calendar-test.js#L88)):</sup>
styleguide


---

<sup>**[tests/integration/components/sl-calendar-test.js, line 119 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1071#-K28fQZjLHo8sksbBxtv)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/1017bc2dd61ec84a08f7dd98c80636cd41c97a22/tests/integration/components/sl-calendar-test.js#L119)):</sup>
styleguide


---

<sup>**[tests/integration/components/sl-calendar-test.js, line 125 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1071#-K28fRG3WHxDvNIOr23o)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/1017bc2dd61ec84a08f7dd98c80636cd41c97a22/tests/integration/components/sl-calendar-test.js#L125)):</sup>
styleguide


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1071)

**Comment by SpikedKira** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

<sup>**[tests/integration/components/sl-calendar-test.js, line 51 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1071#-K28dqa4targrH-6kyNA)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/1017bc2dd61ec84a08f7dd98c80636cd41c97a22/tests/integration/components/sl-calendar-test.js#L51)):</sup>
1) those are passed through, not applied to generated.
2) roger that
3) i think this is the same as your 2nd bullet point?


---

<sup>**[tests/integration/components/sl-calendar-test.js, line 67 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1071#-K28eiILmxoameueOQ5-)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/1017bc2dd61ec84a08f7dd98c80636cd41c97a22/tests/integration/components/sl-calendar-test.js#L67)):</sup>
yes, I suppose so.  I was trying to prevent grabbing an element inside of a td that happened to have the same class.  I suppose we control that in the test environment though, so it's moot.


---

<sup>**[tests/integration/components/sl-calendar-test.js, line 70 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1071#-K28eoTJ5AMQJQGb5QRv)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/1017bc2dd61ec84a08f7dd98c80636cd41c97a22/tests/integration/components/sl-calendar-test.js#L70)):</sup>
Those two are reused by the 2nd piece of logic, both pieces of logic have a comment that starts them.  These two lets are outside of both b/c they are used in both.  Still feel like they should be moved?


---

<sup>**[tests/integration/components/sl-calendar-test.js, line 75 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1071#-K28evALDQTY7NT3B0qy)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/1017bc2dd61ec84a08f7dd98c80636cd41c97a22/tests/integration/components/sl-calendar-test.js#L75)):</sup>
whoops; expected lint to catch this


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1071)

**Comment by notmessenger** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[tests/integration/components/sl-calendar-test.js, line 51 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1071#-K28dqa4targrH-6kyNA)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/1017bc2dd61ec84a08f7dd98c80636cd41c97a22/tests/integration/components/sl-calendar-test.js#L51)):</sup>
1) per conversation, assert these two classes
3) sort of - don't know how much of the extra structure we need/want to care about


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1071)

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1071)

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1071)

**Pull request merged**
