### PR TITLE
Issue 1196

### PR DESCRIPTION
**Pull request by SpikedKira**
[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1222)

### CODE REVIEW

**Comment by SpikedKira** [comment]
not ready >.>

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1222#-:-K4PBTmZ-wWbLPlFRFLK:753625247)*

**Comment by SpikedKira** [comment]
still not ready; waiting to merge #1221 

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1222#-:-K4PDPPq654dHRLNCYo0:1084103577)*

**Comment by erangeles** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/integration/components/sl-span-test.js, line 51 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1222#-K4TTm3HeGK8woBrk44m:-K4TTm3HeGK8woBrk44n:-326148651) ([raw file](https://github.com/softlayer/sl-ember-components/blob/d8aac0b6212bff598b084cf7359d218877a6b8b9/tests/integration/components/sl-span-test.js#L51)):*
remove this, currently we are only doing "positive assertions".  meaning set the prop to true and test if the class is there.

---

*[tests/integration/components/sl-span-test.js, line 71 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1222#-K4TToQCA5rz87IhLVqy:-K4TToQCA5rz87IhLVqz:-326148651) ([raw file](https://github.com/softlayer/sl-ember-components/blob/d8aac0b6212bff598b084cf7359d218877a6b8b9/tests/integration/components/sl-span-test.js#L71)):*
remove this, currently we are only doing "positive assertions".  meaning set the prop to true and test if the class is there.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1222)*

**Comment by notmessenger** [comment]
https://github.com/softlayer/sl-ember-components/pull/1221 has been merged

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1222#-:-K4dPlgHLqbigF72-rQ8:-849350888)*

**Comment by SpikedKira** [comment]
should be ready

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1222#-:-K4dWJlwa51JOAmn3SSd:327851950)*

**Comment by notmessenger** [comment]
tests/integration/components/sl-span-test.js needs an assertion that "value" takes precedence over yielded content when both are specified.  Should we make mention of this in the docs so a user knows and doesn't have to go digging in the code to answer this question for themselves?

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1222#-:-K4hX3wwLmZHFnR6nlre:645649033)*

**Comment by SpikedKira** [comment]
pending a change to the tests

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1222#-:-K5CnbosTb7x3bpbHfp8:-1969172016)*

**Comment by notmessenger** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/integration/components/sl-span-test.js, line 36 \[r3\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1222#-K5GskZjPU2dojFprCok:-K5GskZjPU2dojFprCol:87270820) ([raw file](https://github.com/softlayer/sl-ember-components/blob/d432d52e225d7593af9e14c03846f9e72d0b3305/tests/integration/components/sl-span-test.js#L36)):*
I'd rather see this in its own test case or assertion, so that value is tested, yield is tested, and that value overrides yield is tested.  Without knowing this functionality specifically it is not obvious that this template setup is testing both scenarios and the removal of value by someone believing they are cleaning things up will still allow the test to pass, which will confirm their misinformed intentions.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1222)*

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1222)*

**Pull request merged**
