### PR TITLE
Global libraries tests

### LINKED ISSUE #728: Test multiple rendered instances

### LINKED ISSUE #729: Test multiple rendered instances

### LINKED ISSUE #732: Test multiple rendered instances

### LINKED ISSUE #733: Test multiple rendered instances

### LINKED ISSUE #734: Test multiple rendered instances

### LINKED ISSUE #988: Test multiple rendered instances
Depends on https://github.com/softlayer/sl-ember-test-helpers/issues/156

### LINKED ISSUE #989: Test multiple rendered instances
Depends on https://github.com/softlayer/sl-ember-test-helpers/issues/156

### LINKED ISSUE #990: Test multiple rendered instances
Depends on https://github.com/softlayer/sl-ember-test-helpers/issues/156

### LINKED ISSUE #991: Test multiple rendered instances
Depends on https://github.com/softlayer/sl-ember-test-helpers/issues/156

### LINKED ISSUE #992: Test multiple rendered instances
Depends on https://github.com/softlayer/sl-ember-test-helpers/issues/156

### LINKED ISSUE #993: Test multiple rendered instances
Depends on https://github.com/softlayer/sl-ember-test-helpers/issues/156

The integration test suite also has a skipped test for this that should be removed

### LINKED ISSUE #994: Test multiple rendered instances
Depends on https://github.com/softlayer/sl-ember-test-helpers/issues/156

### LINKED ISSUE #995: Test multiple rendered instances
Depends on https://github.com/softlayer/sl-ember-test-helpers/issues/156

### LINKED ISSUE #996: Test multiple rendered instances
Depends on https://github.com/softlayer/sl-ember-test-helpers/issues/156

### LINKED ISSUE #997: Test multiple rendered instances
Depends on https://github.com/softlayer/sl-ember-test-helpers/issues/156

### LINKED ISSUE #998: Test multiple rendered instances
Depends on https://github.com/softlayer/sl-ember-test-helpers/issues/156

### LINKED ISSUE #999: Test multiple rendered instances
Depends on https://github.com/softlayer/sl-ember-test-helpers/issues/156

### LINKED ISSUE #1000: Test multiple rendered instances
Depends on https://github.com/softlayer/sl-ember-test-helpers/issues/156

### LINKED ISSUE #1001: Test multiple rendered instances
Depends on https://github.com/softlayer/sl-ember-test-helpers/issues/156

### LINKED ISSUE #1002: Test multiple rendered instances
Depends on https://github.com/softlayer/sl-ember-test-helpers/issues/156

### LINKED ISSUE #1003: Test multiple rendered instances
Depends on https://github.com/softlayer/sl-ember-test-helpers/issues/156

### LINKED ISSUE #1004: Test multiple rendered instances
Depends on https://github.com/softlayer/sl-ember-test-helpers/issues/156

### LINKED ISSUE #1006: Test multiple rendered instances
Depends on https://github.com/softlayer/sl-ember-test-helpers/issues/156

### LINKED ISSUE #1007: Test multiple rendered instances
Depends on https://github.com/softlayer/sl-ember-test-helpers/issues/156

### LINKED ISSUE #1008: Test multiple rendered instances
Depends on https://github.com/softlayer/sl-ember-test-helpers/issues/156

### LINKED ISSUE #1009: Test multiple rendered instances
Depends on https://github.com/softlayer/sl-ember-test-helpers/issues/156

### PR DESCRIPTION
**Pull request by azizpunjani**
Closes #1009
Closes #1008
Closes #1007
Closes #1006
Closes #1003
Closes #1002
Closes #1004 
Closes #1001
Closes #1000
Closes #999
Closes #998
Closes #997
Closes #996
Closes #995
Closes #994
Closes #993
Closes #992
Closes #991
Closes #990
Closes #989
Closes #988
Closes #734
Closes #733
Closes #732
Closes #729
Closes #728

[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1459)

### CODE REVIEW

**Comment by notmessenger** [comment]
* https://github.com/softlayer/sl-ember-components/issues/1004 does not seem to be address in this PR
* I know that there were not issues for these, and that they are not components intended to be directly used, and that they don't do anything DOM related, but we should we also test these components the same way, precisely to make sure they don't start doing DOM things in a bad way?
 * `sl-menu-item-show-all`
 * `sl-modal-body`
 * `/sl-modal-footer`
 * `sl-modal-header`

---

Reviewed 34 of 34 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/.jshintrc, line 5 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1459#-K9nc-Mh52IrXzvWqxAd:-K9nc-Mh52IrXzvWqxAe:-1735785307) ([raw file](https://github.com/softlayer/sl-ember-components/blob/516340bcb208f2bcce356db0afa181f55e580551/tests/.jshintrc#L5)):*
This is a duplicate entry

---

*[tests/unit/components/sl-date-time-test.js, line 307 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1459#-K9nfcKw_0xVgMIE-35P:-K9nfcKw_0xVgMIE-35Q:1142582354) ([raw file](https://github.com/softlayer/sl-ember-components/blob/516340bcb208f2bcce356db0afa181f55e580551/tests/unit/components/sl-date-time-test.js#L307)):*
Remove this added empty line

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1459#-:-K9nhoJScYlkFjUx8SyA:-973211698)*

**Comment by juwara0** [comment]
There is no message included in the assert for these tests.

```
 assert.notOk(
        globalLibraries.called()
    );
```

Please add a message:

```
 assert.notOk(
        globalLibraries.called(),
       'Need a message here'
    );
```

---

Reviewed 19 of 34 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1459#-:-KA0Fbkz-Xw_RgBN0EKv:1528676411)*

**Comment by azizpunjani** [comment]
I don't think a message is needed because that is the only assert in the test, @notmessenger can probably weight in on this?

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1459#-:-KA0HSLvC92Zfjv5TkRv:1531023011)*

**Comment by juwara0** [comment]
https://github.com/softlayer/ember-style-guide/issues/79

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1459#-:-KA0HrHODZt2b5KplzHW:-2035489195)*

**Comment by azizpunjani** [comment]
Created https://github.com/softlayer/sl-ember-components/issues/1463 based off https://github.com/softlayer/sl-ember-components/pull/1459#issuecomment-181396318 comment.

**Comment by azizpunjani** [comment]
Review status: 3 of 38 files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/.jshintrc, line 5 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1459#-K9nc-Mh52IrXzvWqxAd:-KA5BZuNdzRhsA_4yEiK:393131782) ([raw file](https://github.com/softlayer/sl-ember-components/blob/516340bcb208f2bcce356db0afa181f55e580551/tests/.jshintrc#L5)):*
Removed duplicate. Sorted alphabetically to avoid duplicates.

---

*[tests/unit/components/sl-date-time-test.js, line 307 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1459#-K9nfcKw_0xVgMIE-35P:-KA5BULsK_v-0LnyDy1e:-499146009) ([raw file](https://github.com/softlayer/sl-ember-components/blob/516340bcb208f2bcce356db0afa181f55e580551/tests/unit/components/sl-date-time-test.js#L307)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1459)*

**Comment by juwara0** [comment]
Reviewed 1 of 34 files at r1, 22 of 34 files at r2, 2 of 2 files at r3.
Review status: 27 of 38 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1459)*

**Comment by notmessenger** [comment]
* https://github.com/softlayer/sl-ember-components/issues/1004 does not seem to be address in this PR

---

Reviewed 33 of 34 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1459#-:-KA75yY85hUx23eJBYfw:478017757)*

**Comment by azizpunjani** [comment]
@notmessenger 1004 has now been addressed.

**Comment by notmessenger** [comment]
Reviewed 7 of 7 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/unit/components/sl-alert-test.js, line 95 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1459#-KACWuGfXz3ZcgnQYyDI:-KACWuGfXz3ZcgnQYyDJ:533391387) ([raw file](https://github.com/softlayer/sl-ember-components/blob/8008e929a83c8c41e756bc646315b2ccafa73b46/tests/unit/components/sl-alert-test.js#L95)):*
Haven't we, if only by convention, been placing these tests cases at/near the end of the file?

---

*[tests/unit/components/sl-grid-test.js, line 901 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1459#-KACXzENzNud4yEUO_Pb:-KACXzENzNud4yEUO_Pc:-1961755923) ([raw file](https://github.com/softlayer/sl-ember-components/blob/8008e929a83c8c41e756bc646315b2ccafa73b46/tests/unit/components/sl-grid-test.js#L901)):*
The 3 assert calls are necessary vs the pattern in most of the other ones?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1459)*

**Comment by azizpunjani** [comment]
Review status: 38 of 39 files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/unit/components/sl-alert-test.js, line 95 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1459#-KACWuGfXz3ZcgnQYyDI:-KAFN_BdyOrx1zwNrps1:1793463767) ([raw file](https://github.com/softlayer/sl-ember-components/blob/8008e929a83c8c41e756bc646315b2ccafa73b46/tests/unit/components/sl-alert-test.js#L95)):*
Yes, moved the test to the end of the file.

---

*[tests/unit/components/sl-grid-test.js, line 901 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1459#-KACXzENzNud4yEUO_Pb:-KAFNcKS-IZm8A52pS_A:-1928899161) ([raw file](https://github.com/softlayer/sl-ember-components/blob/8008e929a83c8c41e756bc646315b2ccafa73b46/tests/unit/components/sl-grid-test.js#L901)):*
They are necessary because the grid *does* reference `Ember.$` but not `jQuery` or `$`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1459)*

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1459)*

**Pull request merged**
