### PR TITLE
Unit | Component | sl grid: handleListContentScroll() requests data as expected #1642

### PR DESCRIPTION
**Pull request by erangeles**
This change is [Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1650)

### CODE REVIEW

**Comment by erangeles** [comment]
adding doc changes as `.list-pane` no longer exists.

**Comment by notmessenger** [comment]
@erangeles Does your comment of "adding doc changes as .list-pane no longer exists." mean there are more commits to come against this PR?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1650#-:-KCXbvUEZ43h0s5SlOUe:1381872513)*

**Comment by erangeles** [comment]
https://github.com/softlayer/sl-ember-components/commit/e00b5b8adf752cf88e860fd1123f3b3b9b569168#diff-ab79330a94d580c0b784c829a359a02b the changeset that removed list-pane.

**Comment by notmessenger** [comment]
Can you merge the latest branch changes?

Tentatively it looks like the failing test is now passing, but nothing about this PR would have caused that.  This test is failing in your other PR, for example - https://github.com/softlayer/sl-ember-components/pull/1639

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1650#-:-KD5WvDAJT6QhnJtjQ0B:-1738496159)*

**Comment by erangeles** [comment]
ready to merge.

**Pull request merged**
