### PR TITLE
Create Unit test suite

### PR DESCRIPTION
**Pull request by erangeles**
@notmessenger The 3 failing tests are in conjunction to Michael's changes, his PR should be merged in first. approaches and tests vetted by Micheal. 

(4:15:25 PM) Michael Carroll: Hey man, I added three more properties to the component file that you will want assert their default values...
(4:15:36 PM) Michael Carroll: optional: false
required: false
label: null
(4:15:43 PM) erangeles: okay will add those in my test now
(4:15:46 PM) Michael Carroll: They should have been in there but were missed

[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1084)

### CODE REVIEW

**Comment by erangeles** [comment]
@notmessenger discussion around refactoring sl-radio-group is in discussion. this pr is subject to change.

**Comment by juwara0** [comment]
<sup>**[tests/unit/components/sl-radio-group-test.js, line 59 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1084#-K2wW4bQpWGUvCJGdMJ7)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/5bf3d5d2c947bc9951956313a68cb4db2f40b8b7/tests/unit/components/sl-radio-group-test.js#L59)):</sup>
We need to add a test for: https://github.com/softlayer/sl-ember-components/blob/EmberCli-1.13.8/addon/components/sl-radio-group.js#L80-L83 you can follow the example here to do this: https://github.com/softlayer/sl-ember-components/blob/EmberCli-1.13.8/tests/unit/components/sl-tooltip-test.js#L25-L36


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1084)

**Comment by notmessenger** [comment]
Which PR should be merged first?


---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1084)

**Comment by juwara0** [comment]
@notmessenger: https://github.com/softlayer/sl-ember-components/pull/1083


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1084)

**Comment by notmessenger** [comment]
@erangeles https://github.com/softlayer/sl-ember-components/pull/1083 has been merged.  Please pull the latest changes into this branch.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1084#-:-K3KyzPHU9hUzDg_mGD4:-1291563760)_

**Pull request closed without merging**
