### PR TITLE
Implemented fix for CSP warning

### PR DESCRIPTION
**Pull request by juwara0**
Closes softlayer/sl-ember-components#852

[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/1152)

### CODE REVIEW

**Comment by juwara0** [comment]
@notmessenger: This is ready for review

**Comment by azizpunjani** [comment]
Personally I think we could have avoided the CSP mixin and creating another component.  

Here's how I think we could have avoided the mixin and the extra component https://gist.github.com/azizpunjani/224920f343747befaaaf. This is just from my initial investigation and 10minutes of tinkering with CSP warnings. There might be a valid use case for using the CSP mixin. If this is the way that was agreed upon I am OK with it.


---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1152)

**Comment by azizpunjani** [comment]
Reviewed 8 of 9 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1152)

**Comment by notmessenger** [comment]
@juwara0 This does seem like a simpler approach but I may be missing something


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/1152)

**Pull request closed without merging**
