### PR TITLE
Sl date picker tests

### PR DESCRIPTION
**Pull request by azizpunjani**
[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-components/927)

### CODE REVIEW

**Comment by juwara0** [comment]
@azizpunjani - What issue is this work against?

**Comment by azizpunjani** [comment]
@juwara0 This issue closes https://github.com/softlayer/sl-ember-components/issues/581

**Comment by juwara0** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions, all commit checks successful.

---

<sup>**[addon/components/sl-date-picker.js, line 316 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927#-K0glFGzMPGfORTTyyU_)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/301e1278d9925d3ea742a959f609bd5b2e9d0b73/addon/components/sl-date-picker.js#L316)):</sup>
Nice catch!


---

<sup>**[tests/integration/components/sl-date-picker-test.js, line 44 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927#-K0lSXwWLVU34fn4dQO4)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/301e1278d9925d3ea742a959f609bd5b2e9d0b73/tests/integration/components/sl-date-picker-test.js#L44)):</sup>
Instead of doing this assertion here, instead move it to the test where you verify that disabled is wired up correctly. Verify that without passing it in is is not set and then go into the part of the test where you pass it in and verify that it is set.


---

<sup>**[tests/integration/components/sl-date-picker-test.js, line 61 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927#-K0lSsx3oZ3wGg4gNzW0)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/301e1278d9925d3ea742a959f609bd5b2e9d0b73/tests/integration/components/sl-date-picker-test.js#L61)):</sup>
Instead of doing this assertion here, instead move it to the test where you verify that placeholder is wired up correctly. Verify that without passing it in is is not set and then go into the part of the test where you pass it in and verify that it is set.


---

<sup>**[tests/integration/components/sl-date-picker-test.js, line 66 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927#-K0lSxBIr3Vci3LLyATk)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/301e1278d9925d3ea742a959f609bd5b2e9d0b73/tests/integration/components/sl-date-picker-test.js#L66)):</sup>
Let's remove this assertion.


---

<sup>**[tests/integration/components/sl-date-picker-test.js, line 72 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927#-K0lfTLxeF1flDH_o7BK)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/301e1278d9925d3ea742a959f609bd5b2e9d0b73/tests/integration/components/sl-date-picker-test.js#L72)):</sup>
I did not see integration tests to verify that things are wired up correctly for:
autoclose
calendarWeeks
clearBtn
daysOfWeekDisabled
endDate
forceParse
format
inputs
keyboardNavigation
language
minViewMode
multidate
orientation
startDate
startView
todayBtn
todayHighlight
weekStart


---

<sup>**[tests/integration/components/sl-date-picker-test.js, line 185 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927#-K0lXOJYw6vzutniZPIV)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/301e1278d9925d3ea742a959f609bd5b2e9d0b73/tests/integration/components/sl-date-picker-test.js#L185)):</sup>
Lets remove this test and restore the unit test that covers this functionality. For the integration test, what I would like to see is the behavior tested when startDate is passed in and the user types a value into the input field that is before the startDate value.


---

<sup>**[tests/integration/components/sl-date-picker-test.js, line 213 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927#-K0l_F7y6p2duSoiRO_1)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/301e1278d9925d3ea742a959f609bd5b2e9d0b73/tests/integration/components/sl-date-picker-test.js#L213)):</sup>
Lets remove this test and restore the unit test that covers this functionality. For the integration test, what I would like to see is the behavior tested when endDate is passed in and the user types a value into the input field that is after the endDate value.


---

<sup>**[tests/integration/components/sl-date-picker-test.js, line 243 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927#-K0l_KdMABDz2yzuoWki)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/301e1278d9925d3ea742a959f609bd5b2e9d0b73/tests/integration/components/sl-date-picker-test.js#L243)):</sup>
Lets remove this test and restore the unit test that covers this functionality. For the integration test, what I would like to see is the behavior tested when startDate is passed in and the user types a value into the input field that is before the startDate value and the supplied placeholder text is displayed.


---

<sup>**[tests/integration/components/sl-date-picker-test.js, line 272 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927#-K0l_ctsdGWt5v8Uk9Zl)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/301e1278d9925d3ea742a959f609bd5b2e9d0b73/tests/integration/components/sl-date-picker-test.js#L272)):</sup>
Lets remove this test and restore the unit test that covers this functionality. For the integration test, what I would like to see is the behavior tested when endDate is passed in and the user types a value into the input field that is before the endDate value and the supplied placeholder text is displayed.


---

<sup>**[tests/integration/components/sl-date-picker-test.js, line 314 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927#-K0lcnwpY-Si2392b3Vd)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/301e1278d9925d3ea742a959f609bd5b2e9d0b73/tests/integration/components/sl-date-picker-test.js#L314)):</sup>
I had to do something similar for the sl-date-range-picker integration tests but I approached this test differently. I want to talk with you and Jeremy and decide which approach we like better. My thought about the test was to test the behavior from a user interacting with the component instead of setting the values programmatically. So, for instance, to set the date, I would set the monthView/yearView to freeze the calendar so I could use jQuery to select a date, then I would do a click() on that to set that value for the input.


---

<sup>**[tests/integration/components/sl-date-picker-test.js, line 324 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927#-K0lerSzSryK4HC8Q7Ac)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/301e1278d9925d3ea742a959f609bd5b2e9d0b73/tests/integration/components/sl-date-picker-test.js#L324)):</sup>
I had to do something similar for the sl-date-range-picker integration tests but I approached this test differently. I want to talk with you and Jeremy and decide which approach we like better. My thought about the test was to test the behavior from a user interacting with the component instead of setting the values programmatically. So, for instance, to set the date, I would set the monthView/yearView to freeze the calendar so I could use jQuery to select a date, then I would do a click() on that to set that value for the input.


---

<sup>**[tests/unit/components/sl-date-picker-test.js, line 167 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927#-K0gohyqCaGlFk00mopL)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/301e1278d9925d3ea742a959f609bd5b2e9d0b73/tests/unit/components/sl-date-picker-test.js#L167)):</sup>
Are you sure that a this.render() is not needed here and also wrapping the component.trigger( 'willClearRender' ) in an Ember.run() loop? In other tests where we are verifying setting and removing event handlers we do: https://github.com/softlayer/sl-ember-components/blob/EmberCli-1.13.8/tests/unit/components/sl-input-test.js#L42-L60 and https://github.com/softlayer/sl-ember-components/blob/EmberCli-1.13.8/tests/unit/components/sl-date-range-picker-test.js#L101-L116


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927)

**Comment by azizpunjani** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

<sup>**[tests/integration/components/sl-date-picker-test.js, line 72 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927#-K0lfTLxeF1flDH_o7BK)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/301e1278d9925d3ea742a959f609bd5b2e9d0b73/tests/integration/components/sl-date-picker-test.js#L72)):</sup>
The reason for no integration tests for those is that we would affectively be testing bootstrap functionality.


---

<sup>**[tests/unit/components/sl-date-picker-test.js, line 167 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927#-K0gohyqCaGlFk00mopL)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/301e1278d9925d3ea742a959f609bd5b2e9d0b73/tests/unit/components/sl-date-picker-test.js#L167)):</sup>
`this.render()` is not needed because `this.$(  'input.date-picker' ).get( 0 )` will call render. Basically any call to `this.$()` will cause a render. https://github.com/switchfly/ember-test-helpers/blob/ae46af8788122b62b11bf0aaaceab58cfe16a5e8/lib/ember-test-helpers/test-module-for-component.js#L115


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927)

**Comment by notmessenger** [comment]
* We don't need integration test cases to assert Start and End dates are correctly set on the date picker?
* Do not see any unit test case assertions for dependent keys of computed properties


---

Reviewed 1 of 3 files at r2.
Review status: 1 of 3 files reviewed at latest revision, 29 unresolved discussions, some commit checks pending.

---

<sup>**[tests/integration/components/sl-date-picker-test.js, line 45 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927#-K19pCiRX-lclenHC1kk)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/35845d5b42479a8ee4815f4c4e56cb2266a520b7/tests/integration/components/sl-date-picker-test.js#L45)):</sup>
Testing for the non-presence of something is a never-ending possibility.  Why only look for label?  Why not buttons?  H1s?  The point is if we are testing the default rendering then I would only expect to see assertions for things we expect to see.  Other test cases will exercise the functionality that causes additional, optional items/functionality.   As an aside, the help block was not asserted - only the label.


---

<sup>**[tests/integration/components/sl-date-picker-test.js, line 201 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927#-K19vWfYuRsTHPhUGbNb)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/35845d5b42479a8ee4815f4c4e56cb2266a520b7/tests/integration/components/sl-date-picker-test.js#L201)):</sup>
Support for `action` is not listed in the documentation.  Please create an issue regarding this.


---

<sup>**[tests/integration/components/sl-date-picker-test.js, line 301 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927#-K19y44i6yfWF48NALFy)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/35845d5b42479a8ee4815f4c4e56cb2266a520b7/tests/integration/components/sl-date-picker-test.js#L301)):</sup>
I spoke with Jeff about this approach and it seems it may be missing the mark.  Please reach out to him.


---

<sup>**[tests/integration/components/sl-date-picker-test.js, line 337 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927#-K19ymivilr1jpxrf-BI)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/35845d5b42479a8ee4815f4c4e56cb2266a520b7/tests/integration/components/sl-date-picker-test.js#L337)):</sup>
Jeff may be able to provide some guidance on the approach of this test case as well.


---

<sup>**[tests/unit/components/sl-date-picker-test.js, line 25 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927#-K19zJckloGHTHQBMKGX)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/35845d5b42479a8ee4815f4c4e56cb2266a520b7/tests/unit/components/sl-date-picker-test.js#L25)):</sup>
https://github.com/softlayer/ember-style-guide/blob/master/ember-testing.md#specificity


---

<sup>**[tests/unit/components/sl-date-picker-test.js, line 31 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927#-K19zK530E8JOYY2pfbm)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/35845d5b42479a8ee4815f4c4e56cb2266a520b7/tests/unit/components/sl-date-picker-test.js#L31)):</sup>
https://github.com/softlayer/ember-style-guide/blob/master/ember-testing.md#specificity


---

<sup>**[tests/unit/components/sl-date-picker-test.js, line 37 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927#-K19zKW6oM0Aic36fqD6)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/35845d5b42479a8ee4815f4c4e56cb2266a520b7/tests/unit/components/sl-date-picker-test.js#L37)):</sup>
https://github.com/softlayer/ember-style-guide/blob/master/ember-testing.md#specificity


---

<sup>**[tests/unit/components/sl-date-picker-test.js, line 49 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927#-K19zMxL1VVUTvlpgdar)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/35845d5b42479a8ee4815f4c4e56cb2266a520b7/tests/unit/components/sl-date-picker-test.js#L49)):</sup>
https://github.com/softlayer/ember-style-guide/blob/master/ember-testing.md#specificity


---

<sup>**[tests/unit/components/sl-date-picker-test.js, line 61 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927#-K19zQM-ThiPX7oCdUP5)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/35845d5b42479a8ee4815f4c4e56cb2266a520b7/tests/unit/components/sl-date-picker-test.js#L61)):</sup>
https://github.com/softlayer/ember-style-guide/blob/master/ember-testing.md#specificity


---

<sup>**[tests/unit/components/sl-date-picker-test.js, line 67 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927#-K19zTM_hdW8QuZn9zQE)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/35845d5b42479a8ee4815f4c4e56cb2266a520b7/tests/unit/components/sl-date-picker-test.js#L67)):</sup>
https://github.com/softlayer/ember-style-guide/blob/master/ember-testing.md#specificity


---

<sup>**[tests/unit/components/sl-date-picker-test.js, line 73 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927#-K19zTytogHeD1OhlCUU)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/35845d5b42479a8ee4815f4c4e56cb2266a520b7/tests/unit/components/sl-date-picker-test.js#L73)):</sup>
https://github.com/softlayer/ember-style-guide/blob/master/ember-testing.md#specificity


---

<sup>**[tests/unit/components/sl-date-picker-test.js, line 79 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927#-K19zUR5q9bmpu8zVfOT)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/35845d5b42479a8ee4815f4c4e56cb2266a520b7/tests/unit/components/sl-date-picker-test.js#L79)):</sup>
https://github.com/softlayer/ember-style-guide/blob/master/ember-testing.md#specificity


---

<sup>**[tests/unit/components/sl-date-picker-test.js, line 85 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927#-K19zYeRJSd952Fq_J31)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/35845d5b42479a8ee4815f4c4e56cb2266a520b7/tests/unit/components/sl-date-picker-test.js#L85)):</sup>
https://github.com/softlayer/ember-style-guide/blob/master/ember-testing.md#specificity


---

<sup>**[tests/unit/components/sl-date-picker-test.js, line 91 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927#-K19zZY2rWVlKYA7Ej82)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/35845d5b42479a8ee4815f4c4e56cb2266a520b7/tests/unit/components/sl-date-picker-test.js#L91)):</sup>
https://github.com/softlayer/ember-style-guide/blob/master/ember-testing.md#specificity


---

<sup>**[tests/unit/components/sl-date-picker-test.js, line 97 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927#-K19zafmLtWDtlRvi-Q8)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/35845d5b42479a8ee4815f4c4e56cb2266a520b7/tests/unit/components/sl-date-picker-test.js#L97)):</sup>
https://github.com/softlayer/ember-style-guide/blob/master/ember-testing.md#specificity


---

<sup>**[tests/unit/components/sl-date-picker-test.js, line 103 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927#-K19zbBt1qSJExuayFn5)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/35845d5b42479a8ee4815f4c4e56cb2266a520b7/tests/unit/components/sl-date-picker-test.js#L103)):</sup>
https://github.com/softlayer/ember-style-guide/blob/master/ember-testing.md#specificity


---

<sup>**[tests/unit/components/sl-date-picker-test.js, line 109 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927#-K19zdIE8o1qlIEKo5UL)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/35845d5b42479a8ee4815f4c4e56cb2266a520b7/tests/unit/components/sl-date-picker-test.js#L109)):</sup>
https://github.com/softlayer/ember-style-guide/blob/master/ember-testing.md#specificity


---

<sup>**[tests/unit/components/sl-date-picker-test.js, line 115 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927#-K19zdsRYF9993dCy0Mg)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/35845d5b42479a8ee4815f4c4e56cb2266a520b7/tests/unit/components/sl-date-picker-test.js#L115)):</sup>
https://github.com/softlayer/ember-style-guide/blob/master/ember-testing.md#specificity


---

<sup>**[tests/unit/components/sl-date-picker-test.js, line 121 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927#-K19zfyMVJEaX96TlbIG)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/35845d5b42479a8ee4815f4c4e56cb2266a520b7/tests/unit/components/sl-date-picker-test.js#L121)):</sup>
https://github.com/softlayer/ember-style-guide/blob/master/ember-testing.md#specificity


---

<sup>**[tests/unit/components/sl-date-picker-test.js, line 127 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927#-K19zgRogyaLL6Lgpf7Z)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/35845d5b42479a8ee4815f4c4e56cb2266a520b7/tests/unit/components/sl-date-picker-test.js#L127)):</sup>
https://github.com/softlayer/ember-style-guide/blob/master/ember-testing.md#specificity


---

<sup>**[tests/unit/components/sl-date-picker-test.js, line 133 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927#-K19zk3C7JAV0V6QLNk_)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/35845d5b42479a8ee4815f4c4e56cb2266a520b7/tests/unit/components/sl-date-picker-test.js#L133)):</sup>
https://github.com/softlayer/ember-style-guide/blob/master/ember-testing.md#specificity


---

<sup>**[tests/unit/components/sl-date-picker-test.js, line 139 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927#-K19zkaJoq854Zy7WKU0)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/35845d5b42479a8ee4815f4c4e56cb2266a520b7/tests/unit/components/sl-date-picker-test.js#L139)):</sup>
https://github.com/softlayer/ember-style-guide/blob/master/ember-testing.md#specificity


---

<sup>**[tests/unit/components/sl-date-picker-test.js, line 145 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927#-K19zoNtNmKPQ__ABb8Y)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/35845d5b42479a8ee4815f4c4e56cb2266a520b7/tests/unit/components/sl-date-picker-test.js#L145)):</sup>
https://github.com/softlayer/ember-style-guide/blob/master/ember-testing.md#specificity


---

<sup>**[tests/unit/components/sl-date-picker-test.js, line 151 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927#-K19znwEaP7lUlBGSMiC)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/35845d5b42479a8ee4815f4c4e56cb2266a520b7/tests/unit/components/sl-date-picker-test.js#L151)):</sup>
https://github.com/softlayer/ember-style-guide/blob/master/ember-testing.md#specificity


---

<sup>**[tests/unit/components/sl-date-picker-test.js, line 157 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927#-K19znXhJ9jJ2xmSaOdg)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/35845d5b42479a8ee4815f4c4e56cb2266a520b7/tests/unit/components/sl-date-picker-test.js#L157)):</sup>
https://github.com/softlayer/ember-style-guide/blob/master/ember-testing.md#specificity


---

<sup>**[tests/unit/components/sl-date-picker-test.js, line 164 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927#-K1A1Bm5PYRkwAqflYMu)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/35845d5b42479a8ee4815f4c4e56cb2266a520b7/tests/unit/components/sl-date-picker-test.js#L164)):</sup>
Shouldn't this test case go further and spy that `sendAction()` is what is called on the `changeDate` event?


---

<sup>**[tests/unit/components/sl-date-picker-test.js, line 184 \[r2\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927#-K1A253UljA6Bn_eRPbz)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/35845d5b42479a8ee4815f4c4e56cb2266a520b7/tests/unit/components/sl-date-picker-test.js#L184)):</sup>
Between the assertions against default property values and passing any of the option properties into the component, is this test needed?  Seems the combination of these other two groups of tests cover this scenario.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927)

**Comment by notmessenger** [comment]
Reviewed 1 of 3 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 29 unresolved discussions, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927)

**Comment by notmessenger** [comment]
Review status: 2 of 3 files reviewed at latest revision, 29 unresolved discussions, some commit checks failed.

---

<sup>**[tests/unit/components/sl-date-picker-test.js, line 167 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927#-K0gohyqCaGlFk00mopL)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/301e1278d9925d3ea742a959f609bd5b2e9d0b73/tests/unit/components/sl-date-picker-test.js#L167)):</sup>
The render in https://github.com/softlayer/sl-ember-components/blob/EmberCli-1.13.8/tests/unit/components/sl-date-range-picker-test.js#L101-L116 is not needed because of the use `this.$()' while it is needed in https://github.com/softlayer/sl-ember-components/blob/EmberCli-1.13.8/tests/unit/components/sl-input-test.js#L42-L60 because of the lack of it.  Should we standardize this approach, at least between the 3 of these examples?  As it stands right now don't know which one the first one should be changed to as the other 2 references are difference patterns.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927)

**Comment by notmessenger** [comment]
Reviewed 1 of 3 files at r2.
Review status: all files reviewed at latest revision, 29 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927)

**Comment by notmessenger** [comment]
Linting is failing


---

Review status: all files reviewed at latest revision, 29 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927)

**Comment by azizpunjani** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

<sup>**[tests/unit/components/sl-date-picker-test.js, line 167 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927#-K0gohyqCaGlFk00mopL)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/301e1278d9925d3ea742a959f609bd5b2e9d0b73/tests/unit/components/sl-date-picker-test.js#L167)):</sup>
To standardize a pattern, `this.render()` should only be called when we do not use `this.$()`. So the first example, we should remove the superfluous `this.render` call.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927)

**Comment by notmessenger** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[tests/unit/components/sl-date-picker-test.js, line 167 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927#-K0gohyqCaGlFk00mopL)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/301e1278d9925d3ea742a959f609bd5b2e9d0b73/tests/unit/components/sl-date-picker-test.js#L167)):</sup>
I understand when we do and do not need `this.render()`.  What I'm saying is that do we always want to force use of `this.$()` instead of `component.getInput().get( 0 )` for example.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927)

**Comment by azizpunjani** [comment]
<sup>**[tests/unit/components/sl-date-picker-test.js, line 167 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927#-K0gohyqCaGlFk00mopL)** ([raw file](https://github.com/softlayer/sl-ember-components/blob/301e1278d9925d3ea742a959f609bd5b2e9d0b73/tests/unit/components/sl-date-picker-test.js#L167)):</sup>
Ah ok. Looks like we have a mix of `.getInput()` and `this.$( 'input' )` in that test. I think we should be consistent and always use `this.$( )`.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-components/927)

**Pull request merged**
